/* Pashto string table. Phase 1: shell and shared components. AI-generated; to be checked by native readers. */
window.CVH_STRINGS = window.CVH_STRINGS || {};
window.CVH_STRINGS.ps = {
 meta: { code: 'ps', name: 'پښتو', aiNote: 'د دې نمونې ټول متن د مصنوعي ځیرکتیا په مرسته جوړ شوی دی. د CVH له پیل مخکې خلک یې کتنه کوي.' },
 time: { justNow: 'همدا اوس', ago: '{t} مخکې', join: ' او ', second: '1 ثانیه', seconds: '{n} ثانیې', minute: '1 دقیقه', minutes: '{n} دقیقې', hour: '1 ساعت', hours: '{n} ساعته', day: '1 ورځ', days: '{n} ورځې', today: 'نن', tomorrow: 'سبا', until: 'تر {t} پورې', closed: 'تړلی',
   days7: { mon: 'دوشنبه', tue: 'سه‌شنبه', wed: 'چهارشنبه', thu: 'پنجشنبه', fri: 'جمعه', sat: 'شنبه', sun: 'یکشنبه' } },
 shell: { cvhName: 'ټولنیز مجازي مرکز', prototype: 'آزمایښتي نمونه', prototypeNote: 'دا ریښتینی خدمت نه دی. ټوله منځپانګه د مصنوعي ځیرکتیا ده.',
   language: 'ژبه', changeLanguage: 'ژبه بدله کړئ', languageTitle: 'خپله ژبه وټاکئ', languageCurrent: 'اوس ښودل کېږي', languageReturn: 'پاڼه به همغلته پاتې شي چې تاسو وئ.',
   choices: 'ما CVH ته څه ویلي', choicesShort: 'زما انتخابونه', nav: { now: 'خبرتیاوې', help: 'مرسته ومومئ', map: 'نقشه', ready: 'چمتو اوسئ' }, navLabel: 'اصلي',
   close: 'بندول', back: 'شاته', next: 'دوام', skip: 'پرېښودل', done: 'وشو', cancel: 'لغوه', more: 'نور',
   notInPrototype: 'په دې نمونه کې نشته', notInPrototypeBody: 'دا برخه په نمونه کې نه ده جوړه شوې. هیڅ بدلون نه دی راغلی.', ok: 'سمه ده',
   about: 'د CVH په اړه', aboutBody: 'ټولنیز مجازي مرکز Thorncliffe Park Community Hub د تورنکلیف پارک او فلیمینګډن پارک لپاره چلوي.', builtBy: 'د Sprout Climate سره جوړ شوی',
   rules: 'د دې ځای قواعد', ambassador: 'سفیر', offline: 'تاسو آفلاین یاست. هغه څه ښودل کېږي چې {t} پورته شوي وو.', aiLabel: 'د نمونې لپاره د مصنوعي ځیرکتیا جوړ شوی', illustrative: 'بېلګه' },
 x01: { text: 'CVH بیړني خدمت نه دی.', call: 'که څوک په خطر کې وي، 911 ته زنګ ووهئ.', short: 'بیړني خدمت نه دی. په خطر کې؟ 911 ته زنګ ووهئ.',
   sms: 'مرکز بیړني خدمت نه دی. که څوک په خطر کې وي، 911 ته زنګ ووهئ.', print: 'دا بیړني خدمت نه دی. که څوک په خطر کې وي، 911 ته زنګ ووهئ.' },
 x02: { official: 'له {source} څخه رسمي خبرتیا', community: 'له {author} څخه ټولنیزه خبرتیا', verifiedBy: '{org} تایید کړې', notYetVerified: 'لا تایید شوې نه ده',
   corrected: '{t} سمه شوه', whatMeans: 'مانا یې څه ده', hub: 'مرکز', theHub: 'مرکز', ambassador: 'د ودانۍ سفیر، {building}', postedBy: '{author} خپره کړه',
   levelOfficial: 'رسمي خبرتیا', levelCommunity: 'ټولنیزه خبرتیا', sources: { ECCC: 'د کاناډا د چاپېریال او اقلیم بدلون اداره', CITY: 'د ټورنټو ښاروالي', ALERTREADY: 'الرټ ریډي' } },
 x03: { title: 'د دې ځای قواعد', intro: 'CVH د ګاونډیانو لپاره دی چې یو بل سره مرسته وکړي. د څه اضافه کولو مخکې دا ولولئ.',
   rules: ['هغه ځایونه او مرستې شریکې کړئ چې وړیا یا ارزانه وي او ټولو ته پرانیستې وي.', 'د یوه ځای په اړه ولیکئ، نه د یو کس. د چا نوم، د اپارتمان شمېره یا تلیفون مه شریکوئ.',
     'مهربانه اوسئ. د هېڅ ډلې سپکاوی یا په نښه کول نه دي منل شوي.', 'یوازې هغه څه شریک کړئ چې پوهېږئ رښتیا دي. که ډاډه نه یاست، «ډاډه نه یم» وټاکئ.'],
   market: 'CVH بازار نه دی. نه پلور، نه اعلانونه.', review: 'نقشې ته له تللو مخکې د مرکز یو کس هر څه لولي.', agree: 'پوه شوم', readMore: 'قواعد ولولئ' },
 x04: { label: 'د ماشین ژباړه', from: 'له {lang} څخه', report: 'د ژباړې ستونزه راپور کړئ', reportTitle: 'په دې ژباړه کې څه غلط دي؟',
   reasons: { meaning: 'مانا غلطه ده', words: 'ځینې کلمې غلطې دي', unclear: 'پوهېدل یې سخت دي' }, send: 'ولېږئ', reported: 'مننه. د مرکز یو کس به دا ژباړه وګوري.',
   unavailable: 'په دې ژبه لا نشته', unavailableBody: 'دا لا {lang} ته نه ده ژباړل شوې.', showSource: 'په {lang} یې ولولئ', original: 'اصلي ({lang})' },
 x07: { label: 'لوی متن، لږ شیان', on: 'روښانه', off: 'بند', setByHelper: 'هغه چا روښانه کړ چې ستاسو مرسته کوي', remembered: 'په دې وسیله کې ساتل شوی', turnOn: 'روښانه کړئ', turnOff: 'بند کړئ' },
 x08: { idle: 'واورئ · {t}', loading: 'غږ پورته کېږي', playing: 'غږېږي', paused: 'درېدلی', left: '{t} پاتې',
   failed: 'په دې اتصال غږ پورته نه شو. هر څه چې وایي دلته لیکل شوي.', retry: 'بیا هڅه وکړئ', play: 'غږول', pause: 'درول', section: 'دا برخه واورئ · {t}' },
 x09: { open: 'پرانیستی', full: 'ډک', closed: 'تړلی', unconfirmed: 'نه دی تایید شوی',
   purpose: { cooling: 'د یخېدو لپاره', cleanAir: 'د پاکې هوا لپاره', warming: 'د تودېدو لپاره', charging: 'د وسیلو چارج لپاره' },
   confirmed: '{t} تایید شو', unconfirmedNote: '{t} راهیسې نه دی تایید شوی. کېدای شي پرانیستی نه وي. له تګ مخکې زنګ ووهئ.', hoursToday: 'نن له {from} تر {to}', closedToday: 'نن تړلی دی',
   water: 'د څښلو اوبه', seating: 'د کېناستو ځای', charging: 'د تلیفون چارج', washrooms: 'تشناب', stepFree: 'بې زینو', notStepFree: 'زینې لري', noId: 'پېژند پاڼه نه غواړي', idAsked: 'پېژند پاڼه غواړي',
   runBy: '{org} یې چلوي', yes: 'هو', no: 'نه', unknown: 'نامعلوم' },
 x10: { word: 'تمرین', running: 'تمرین. دا یوازې تمرین دی.', runningSub: 'له دې ځایه اوسېدونکو ته هیڅ نه لېږل کېږي.', ended: 'تمرین پای ته ورسېد', sms: 'تمرین. یوازې تمرین.' },
 x11: { title: 'فلټرونه فعال دي', remove: 'فلټر لرې کړئ: {f}', hiding: 'د دې فلټرونو له امله {n} ځایونه پټ دي', hidingOne: 'د دې فلټرونو له امله 1 ځای پټ دی',
   fromChoices: 'ځینې فلټرونه ستاسو له انتخابونو دي', clear: 'ټول فلټرونه لرې کړئ', none: 'فلټر نشته' },
 x12: { title: 'دا ستاسو لپاره څه مانا لري', fromHub: 'د مرکز مشوره', tailoredLink: 'ستاسو د انتخابونو سره سم', standard: 'هغه نسخه وښیه چې ټول یې ترلاسه کوي',
   standardShown: 'تاسو هغه نسخه ګورئ چې ټول یې ترلاسه کوي.', showMine: 'وښیه چې زما لپاره څه مانا لري', checkin: 'ستاسو د پوړ سفیر به نن ستاسو پوښتنه وکړي.',
   noCheckin: 'ستاسو په پوړ کې لا سفیر نشته، نو ستاسو پوښتنه نه شو کولی. مرکز ته په {phone} زنګ ووهئ. موږ {hours} پرانیستي یو.',
   hubHours: 'له دوشنبې تر پنجشنبې سهار 9 نه شپې 8 بجو پورې، جمعه سهار 9 نه ماښام 5 بجو پورې، شنبه سهار 10 نه غرمې 2 بجو پورې', listen: 'واورئ · {t}' },
 x13: { fire: 'اور', power: 'برېښنا', water: 'اوبه', elevator: 'لفټ', flood: 'سیلاب یا څڅېدنه', heat: 'ګرمي', smoke: 'لوګی', winter: 'د واورې طوفان', other: 'نور', fireAlarm: 'د اور زنګ یا وتل', waterPlumbing: 'اوبه یا نلونه' },
 x14: { label: 'څنګه مرسته کولی شي' },
 status: { active: 'فعاله ستونزه', progress: 'کار روان دی', resolved: 'حل شوه', unknown: 'نامعلوم' },
 filters: { short: { openNow: 'اوس پرانیستی', free: 'وړیا', lowCost: 'وړیا یا ارزانه', noId: 'پېژند پاڼه نه غواړي', stepFree: 'بې زینو', noAppointment: 'وخت اخیستلو ته اړتیا نشته', nbhdTP: 'تورنکلیف پارک', nbhdFP: 'فلیمینګډن پارک', language: '{lang} خبرې کوي' } },
 R02: { title: 'خپله ژبه وټاکئ', changed: 'اوس په {lang} ښودل کېږي.' }
};
