/* Punjabi (Gurmukhi) string table. Phase 1: shell and shared components. Script choice open (brief O3). AI-generated; to be checked by native readers. */
window.CVH_STRINGS = window.CVH_STRINGS || {};
window.CVH_STRINGS.pa = {
 meta: { code: 'pa', name: 'ਪੰਜਾਬੀ', aiNote: 'ਇਸ ਪ੍ਰੋਟੋਟਾਈਪ ਦਾ ਸਾਰਾ ਲਿਖਤ AI ਨਾਲ ਬਣਿਆ ਹੈ। CVH ਸ਼ੁਰੂ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ ਲੋਕ ਇਸਦੀ ਜਾਂਚ ਕਰਨਗੇ।' },
 time: { justNow: 'ਹੁਣੇ', ago: '{t} ਪਹਿਲਾਂ', join: ' ', second: '1 ਸਕਿੰਟ', seconds: '{n} ਸਕਿੰਟ', minute: '1 ਮਿੰਟ', minutes: '{n} ਮਿੰਟ', hour: '1 ਘੰਟਾ', hours: '{n} ਘੰਟੇ', day: '1 ਦਿਨ', days: '{n} ਦਿਨ', today: 'ਅੱਜ', tomorrow: 'ਕੱਲ੍ਹ', until: '{t} ਤੱਕ', closed: 'ਬੰਦ',
   days7: { mon: 'ਸੋਮਵਾਰ', tue: 'ਮੰਗਲਵਾਰ', wed: 'ਬੁੱਧਵਾਰ', thu: 'ਵੀਰਵਾਰ', fri: 'ਸ਼ੁੱਕਰਵਾਰ', sat: 'ਸ਼ਨਿੱਚਰਵਾਰ', sun: 'ਐਤਵਾਰ' } },
 shell: { cvhName: 'ਕਮਿਊਨਿਟੀ ਵਰਚੁਅਲ ਹੱਬ', prototype: 'ਪ੍ਰੋਟੋਟਾਈਪ', prototypeNote: 'ਇਹ ਅਸਲੀ ਸੇਵਾ ਨਹੀਂ ਹੈ। ਸਾਰੀ ਸਮੱਗਰੀ AI ਨਾਲ ਬਣੀ ਹੈ।',
   language: 'ਭਾਸ਼ਾ', changeLanguage: 'ਭਾਸ਼ਾ ਬਦਲੋ', languageTitle: 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ', languageCurrent: 'ਹੁਣ ਦਿਖਾਈ ਜਾ ਰਹੀ ਹੈ', languageReturn: 'ਸਕ੍ਰੀਨ ਉੱਥੇ ਹੀ ਰਹੇਗੀ ਜਿੱਥੇ ਤੁਸੀਂ ਸੀ।',
   choices: 'ਮੈਂ CVH ਨੂੰ ਕੀ ਦੱਸਿਆ ਹੈ', choicesShort: 'ਮੇਰੀਆਂ ਚੋਣਾਂ', nav: { now: 'ਹੁਣ', help: 'ਮਦਦ ਲੱਭੋ', map: 'ਨਕਸ਼ਾ', ready: 'ਤਿਆਰ ਰਹੋ' }, navLabel: 'ਮੁੱਖ',
   close: 'ਬੰਦ ਕਰੋ', back: 'ਪਿੱਛੇ', next: 'ਜਾਰੀ ਰੱਖੋ', skip: 'ਛੱਡੋ', done: 'ਹੋ ਗਿਆ', cancel: 'ਰੱਦ ਕਰੋ', more: 'ਹੋਰ',
   notInPrototype: 'ਇਸ ਪ੍ਰੋਟੋਟਾਈਪ ਵਿੱਚ ਨਹੀਂ', notInPrototypeBody: 'ਇਹ ਹਿੱਸਾ ਪ੍ਰੋਟੋਟਾਈਪ ਵਿੱਚ ਨਹੀਂ ਬਣਿਆ। ਕੁਝ ਨਹੀਂ ਬਦਲਿਆ।', ok: 'ਠੀਕ ਹੈ',
   about: 'CVH ਬਾਰੇ', aboutBody: 'ਕਮਿਊਨਿਟੀ ਵਰਚੁਅਲ ਹੱਬ ਨੂੰ Thorncliffe Park Community Hub, ਥੋਰਨਕਲਿਫ਼ ਪਾਰਕ ਅਤੇ ਫਲੇਮਿੰਗਡਨ ਪਾਰਕ ਲਈ ਚਲਾਉਂਦਾ ਹੈ।', builtBy: 'Sprout Climate ਨਾਲ ਬਣਾਇਆ',
   rules: 'ਇਸ ਥਾਂ ਦੇ ਨਿਯਮ', ambassador: 'ਐਂਬੈਸਡਰ', offline: 'ਤੁਸੀਂ ਆਫ਼ਲਾਈਨ ਹੋ। {t} ਲੋਡ ਹੋਈ ਸਮੱਗਰੀ ਦਿਖਾਈ ਜਾ ਰਹੀ ਹੈ।', aiLabel: 'ਪ੍ਰੋਟੋਟਾਈਪ ਲਈ AI ਨਾਲ ਬਣਿਆ', illustrative: 'ਸਿਰਫ਼ ਉਦਾਹਰਨ' },
 x01: { text: 'CVH ਐਮਰਜੈਂਸੀ ਸੇਵਾ ਨਹੀਂ ਹੈ।', call: 'ਜੇ ਕੋਈ ਖ਼ਤਰੇ ਵਿੱਚ ਹੈ, ਤਾਂ 911 ਤੇ ਕਾਲ ਕਰੋ।', short: 'ਐਮਰਜੈਂਸੀ ਸੇਵਾ ਨਹੀਂ। ਖ਼ਤਰਾ? 911 ਤੇ ਕਾਲ ਕਰੋ।',
   sms: 'ਹੱਬ ਐਮਰਜੈਂਸੀ ਸੇਵਾ ਨਹੀਂ ਹੈ। ਜੇ ਕੋਈ ਖ਼ਤਰੇ ਵਿੱਚ ਹੈ, ਤਾਂ 911 ਤੇ ਕਾਲ ਕਰੋ।', print: 'ਇਹ ਐਮਰਜੈਂਸੀ ਸੇਵਾ ਨਹੀਂ ਹੈ। ਜੇ ਕੋਈ ਖ਼ਤਰੇ ਵਿੱਚ ਹੈ, ਤਾਂ 911 ਤੇ ਕਾਲ ਕਰੋ।' },
 x02: { official: '{source} ਵੱਲੋਂ ਅਧਿਕਾਰਤ ਚੇਤਾਵਨੀ', community: '{author} ਵੱਲੋਂ ਭਾਈਚਾਰਕ ਚੇਤਾਵਨੀ', verifiedBy: '{org} ਨੇ ਪੁਸ਼ਟੀ ਕੀਤੀ', notYetVerified: 'ਅਜੇ ਪੁਸ਼ਟੀ ਨਹੀਂ ਹੋਈ',
   corrected: '{t} ਸੋਧਿਆ ਗਿਆ', whatMeans: 'ਇਸਦਾ ਮਤਲਬ', hub: 'ਹੱਬ', theHub: 'ਹੱਬ', ambassador: 'ਬਿਲਡਿੰਗ ਐਂਬੈਸਡਰ, {building}', postedBy: '{author} ਨੇ ਪੋਸਟ ਕੀਤਾ',
   levelOfficial: 'ਅਧਿਕਾਰਤ ਚੇਤਾਵਨੀ', levelCommunity: 'ਭਾਈਚਾਰਕ ਚੇਤਾਵਨੀ', sources: { ECCC: 'ਇਨਵਾਇਰਨਮੈਂਟ ਐਂਡ ਕਲਾਈਮੇਟ ਚੇਂਜ ਕੈਨੇਡਾ', CITY: 'ਟੋਰਾਂਟੋ ਸ਼ਹਿਰ', ALERTREADY: 'ਅਲਰਟ ਰੈਡੀ' } },
 x03: { title: 'ਇਸ ਥਾਂ ਦੇ ਨਿਯਮ', intro: 'CVH ਗੁਆਂਢੀਆਂ ਦੀ ਇੱਕ-ਦੂਜੇ ਦੀ ਮਦਦ ਲਈ ਹੈ। ਕੁਝ ਜੋੜਨ ਤੋਂ ਪਹਿਲਾਂ ਇਹ ਪੜ੍ਹੋ।',
   rules: ['ਮੁਫ਼ਤ ਜਾਂ ਘੱਟ ਕੀਮਤ ਵਾਲੀਆਂ ਅਤੇ ਸਭ ਲਈ ਖੁੱਲ੍ਹੀਆਂ ਥਾਵਾਂ ਅਤੇ ਮਦਦ ਸਾਂਝੀ ਕਰੋ।', 'ਕਿਸੇ ਥਾਂ ਬਾਰੇ ਲਿਖੋ, ਕਿਸੇ ਵਿਅਕਤੀ ਬਾਰੇ ਨਹੀਂ। ਕਿਸੇ ਦਾ ਨਾਮ, ਯੂਨਿਟ ਨੰਬਰ ਜਾਂ ਫ਼ੋਨ ਨੰਬਰ ਨਾ ਦਿਓ।',
     'ਦਿਆਲੂ ਰਹੋ। ਕਿਸੇ ਸਮੂਹ ਦਾ ਅਪਮਾਨ ਜਾਂ ਨਿਸ਼ਾਨਾ ਨਹੀਂ।', 'ਸਿਰਫ਼ ਉਹੀ ਸਾਂਝਾ ਕਰੋ ਜੋ ਤੁਸੀਂ ਜਾਣਦੇ ਹੋ ਕਿ ਸੱਚ ਹੈ। ਯਕੀਨ ਨਾ ਹੋਵੇ ਤਾਂ "ਯਕੀਨ ਨਹੀਂ" ਚੁਣੋ।'],
   market: 'CVH ਬਾਜ਼ਾਰ ਨਹੀਂ ਹੈ। ਨਾ ਵਿਕਰੀ, ਨਾ ਇਸ਼ਤਿਹਾਰ।', review: 'ਨਕਸ਼ੇ ਤੇ ਆਉਣ ਤੋਂ ਪਹਿਲਾਂ ਹੱਬ ਦਾ ਕੋਈ ਵਿਅਕਤੀ ਸਭ ਕੁਝ ਪੜ੍ਹਦਾ ਹੈ।', agree: 'ਮੈਂ ਸਮਝ ਗਿਆ', readMore: 'ਨਿਯਮ ਪੜ੍ਹੋ' },
 x04: { label: 'ਮਸ਼ੀਨ ਅਨੁਵਾਦ', from: '{lang} ਤੋਂ', report: 'ਅਨੁਵਾਦ ਦੀ ਸਮੱਸਿਆ ਦੱਸੋ', reportTitle: 'ਇਸ ਅਨੁਵਾਦ ਵਿੱਚ ਕੀ ਗਲਤ ਹੈ?',
   reasons: { meaning: 'ਮਤਲਬ ਗਲਤ ਹੈ', words: 'ਕੁਝ ਸ਼ਬਦ ਗਲਤ ਹਨ', unclear: 'ਸਮਝਣਾ ਔਖਾ ਹੈ' }, send: 'ਭੇਜੋ', reported: 'ਧੰਨਵਾਦ। ਹੱਬ ਦਾ ਕੋਈ ਵਿਅਕਤੀ ਇਹ ਅਨੁਵਾਦ ਦੇਖੇਗਾ।',
   unavailable: 'ਇਸ ਭਾਸ਼ਾ ਵਿੱਚ ਅਜੇ ਉਪਲਬਧ ਨਹੀਂ', unavailableBody: 'ਇਸਦਾ ਅਜੇ {lang} ਵਿੱਚ ਅਨੁਵਾਦ ਨਹੀਂ ਹੋਇਆ।', showSource: '{lang} ਵਿੱਚ ਪੜ੍ਹੋ', original: 'ਮੂਲ ({lang})' },
 x07: { label: 'ਵੱਡੇ ਅੱਖਰ, ਘੱਟ ਚੀਜ਼ਾਂ', on: 'ਚਾਲੂ', off: 'ਬੰਦ', setByHelper: 'ਤੁਹਾਡੀ ਮਦਦ ਕਰਨ ਵਾਲੇ ਨੇ ਚਾਲੂ ਕੀਤਾ', remembered: 'ਇਸ ਡਿਵਾਈਸ ਤੇ ਯਾਦ ਰੱਖਿਆ', turnOn: 'ਚਾਲੂ ਕਰੋ', turnOff: 'ਬੰਦ ਕਰੋ' },
 x08: { idle: 'ਸੁਣੋ · {t}', loading: 'ਆਡੀਓ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ', playing: 'ਚੱਲ ਰਿਹਾ ਹੈ', paused: 'ਰੁਕਿਆ', left: '{t} ਬਾਕੀ',
   failed: 'ਇਸ ਕਨੈਕਸ਼ਨ ਤੇ ਆਡੀਓ ਲੋਡ ਨਹੀਂ ਹੋਇਆ। ਇਸ ਵਿੱਚ ਜੋ ਹੈ ਉਹ ਸਭ ਇੱਥੇ ਲਿਖਿਆ ਹੈ।', retry: 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ', play: 'ਚਲਾਓ', pause: 'ਰੋਕੋ', section: 'ਇਹ ਹਿੱਸਾ ਸੁਣੋ · {t}' },
 x09: { open: 'ਖੁੱਲ੍ਹਾ', full: 'ਭਰਿਆ', closed: 'ਬੰਦ', unconfirmed: 'ਪੁਸ਼ਟੀ ਨਹੀਂ',
   purpose: { cooling: 'ਠੰਢਕ ਲਈ', cleanAir: 'ਸਾਫ਼ ਹਵਾ ਲਈ', warming: 'ਨਿੱਘ ਲਈ', charging: 'ਫ਼ੋਨ ਚਾਰਜ ਕਰਨ ਲਈ' },
   confirmed: '{t} ਪੁਸ਼ਟੀ ਹੋਈ', unconfirmedNote: '{t} ਤੋਂ ਪੁਸ਼ਟੀ ਨਹੀਂ। ਸ਼ਾਇਦ ਖੁੱਲ੍ਹਾ ਨਾ ਹੋਵੇ। ਜਾਣ ਤੋਂ ਪਹਿਲਾਂ ਫ਼ੋਨ ਕਰੋ।', hoursToday: 'ਅੱਜ {from} ਤੋਂ {to}', closedToday: 'ਅੱਜ ਬੰਦ',
   water: 'ਪੀਣ ਵਾਲਾ ਪਾਣੀ', seating: 'ਬੈਠਣ ਦੀ ਥਾਂ', charging: 'ਫ਼ੋਨ ਚਾਰਜਿੰਗ', washrooms: 'ਪਖਾਨੇ', stepFree: 'ਬਿਨਾਂ ਪੌੜੀਆਂ', notStepFree: 'ਪੌੜੀਆਂ ਹਨ', noId: 'ਪਛਾਣ ਪੱਤਰ ਨਹੀਂ ਮੰਗਦੇ', idAsked: 'ਪਛਾਣ ਪੱਤਰ ਮੰਗਦੇ ਹਨ',
   runBy: '{org} ਚਲਾਉਂਦਾ ਹੈ', yes: 'ਹਾਂ', no: 'ਨਹੀਂ', unknown: 'ਪਤਾ ਨਹੀਂ' },
 x10: { word: 'ਅਭਿਆਸ', running: 'ਅਭਿਆਸ। ਇਹ ਸਿਰਫ਼ ਪ੍ਰੈਕਟਿਸ ਹੈ।', runningSub: 'ਇੱਥੋਂ ਵਸਨੀਕਾਂ ਨੂੰ ਕੁਝ ਨਹੀਂ ਭੇਜਿਆ ਜਾਂਦਾ।', ended: 'ਅਭਿਆਸ ਖ਼ਤਮ', sms: 'ਅਭਿਆਸ। ਸਿਰਫ਼ ਪ੍ਰੈਕਟਿਸ।' },
 x11: { title: 'ਫਿਲਟਰ ਲੱਗੇ ਹਨ', remove: 'ਫਿਲਟਰ ਹਟਾਓ: {f}', hiding: 'ਇਨ੍ਹਾਂ ਫਿਲਟਰਾਂ ਕਾਰਨ {n} ਥਾਵਾਂ ਲੁਕੀਆਂ ਹਨ', hidingOne: 'ਇਨ੍ਹਾਂ ਫਿਲਟਰਾਂ ਕਾਰਨ 1 ਥਾਂ ਲੁਕੀ ਹੈ',
   fromChoices: 'ਕੁਝ ਫਿਲਟਰ ਤੁਹਾਡੀਆਂ ਚੋਣਾਂ ਤੋਂ ਹਨ', clear: 'ਸਾਰੇ ਫਿਲਟਰ ਹਟਾਓ', none: 'ਕੋਈ ਫਿਲਟਰ ਨਹੀਂ' },
 x12: { title: 'ਤੁਹਾਡੇ ਲਈ ਇਸਦਾ ਮਤਲਬ', fromHub: 'ਹੱਬ ਦੀ ਸਲਾਹ', tailoredLink: 'ਤੁਹਾਡੀਆਂ ਚੋਣਾਂ ਅਨੁਸਾਰ', standard: 'ਉਹ ਸੰਸਕਰਣ ਦਿਖਾਓ ਜੋ ਸਭ ਨੂੰ ਮਿਲਦਾ ਹੈ',
   standardShown: 'ਤੁਸੀਂ ਉਹ ਸੰਸਕਰਣ ਦੇਖ ਰਹੇ ਹੋ ਜੋ ਸਭ ਨੂੰ ਮਿਲਦਾ ਹੈ।', showMine: 'ਮੇਰੇ ਲਈ ਮਤਲਬ ਦਿਖਾਓ', checkin: 'ਤੁਹਾਡੀ ਮੰਜ਼ਿਲ ਦਾ ਐਂਬੈਸਡਰ ਅੱਜ ਤੁਹਾਡਾ ਹਾਲ ਪੁੱਛੇਗਾ।',
   noCheckin: 'ਤੁਹਾਡੀ ਮੰਜ਼ਿਲ ਤੇ ਅਜੇ ਕੋਈ ਐਂਬੈਸਡਰ ਨਹੀਂ, ਇਸ ਲਈ ਅਸੀਂ ਹਾਲ ਨਹੀਂ ਪੁੱਛ ਸਕਦੇ। ਹੱਬ ਨੂੰ {phone} ਤੇ ਕਾਲ ਕਰੋ। ਅਸੀਂ {hours} ਖੁੱਲ੍ਹੇ ਹਾਂ।',
   hubHours: 'ਸੋਮਵਾਰ ਤੋਂ ਵੀਰਵਾਰ ਸਵੇਰੇ 9 ਤੋਂ ਰਾਤ 8, ਸ਼ੁੱਕਰਵਾਰ ਸਵੇਰੇ 9 ਤੋਂ ਸ਼ਾਮ 5, ਸ਼ਨੀਵਾਰ ਸਵੇਰੇ 10 ਤੋਂ ਦੁਪਹਿਰ 2', listen: 'ਸੁਣੋ · {t}' },
 x13: { fire: 'ਅੱਗ', power: 'ਬਿਜਲੀ', water: 'ਪਾਣੀ', elevator: 'ਲਿਫ਼ਟ', flood: 'ਹੜ੍ਹ ਜਾਂ ਲੀਕ', heat: 'ਗਰਮੀ', smoke: 'ਧੂੰਆਂ', winter: 'ਬਰਫ਼ੀਲਾ ਤੂਫ਼ਾਨ', other: 'ਹੋਰ', fireAlarm: 'ਫਾਇਰ ਅਲਾਰਮ ਜਾਂ ਨਿਕਾਸੀ', waterPlumbing: 'ਪਾਣੀ ਜਾਂ ਪਲੰਬਿੰਗ' },
 x14: { label: 'ਉਹ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦੇ ਹਨ' },
 status: { active: 'ਸਰਗਰਮ ਸਮੱਸਿਆ', progress: 'ਕੰਮ ਚੱਲ ਰਿਹਾ ਹੈ', resolved: 'ਹੱਲ ਹੋ ਗਿਆ', unknown: 'ਪਤਾ ਨਹੀਂ' },
 R02: { title: 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ', changed: 'ਹੁਣ {lang} ਵਿੱਚ ਦਿਖਾਇਆ ਜਾ ਰਿਹਾ ਹੈ।' }
};
