/* English string table. Keys are grouped by screen or component ID.
   AI-generated for the prototype (brief O16); checked by people before production.
   House style (design system): sentence case, plain words, no em dashes, no exclamation marks. */
window.CVH_STRINGS = window.CVH_STRINGS || {};
window.CVH_STRINGS.en = {
 meta: { code: 'en', name: 'English', aiNote: 'All text in this prototype is AI-generated and will be checked by people before the CVH goes live.' },

 time: { justNow: 'just now', ago: '{t} ago', join: ' ', second: '1 second', seconds: '{n} seconds', minute: '1 minute', minutes: '{n} minutes',
   hour: '1 hour', hours: '{n} hours', day: '1 day', days: '{n} days', today: 'Today', tomorrow: 'Tomorrow', until: 'until {t}', closed: 'Closed',
   days7: { mon: 'Monday', tue: 'Tuesday', wed: 'Wednesday', thu: 'Thursday', fri: 'Friday', sat: 'Saturday', sun: 'Sunday' } },

 /* ------------------------------------------------ Terms and privacy page, /{lang}/terms (S07.01). The terms text itself is
    not here: it comes from data/catalogue/terms.json and its reviewed translations. */
 terms: {
  version: 'Version', owner: 'Owner', updated: 'Last updated', privacyContact: 'Privacy contact',
  draftTitle: 'Draft: not yet published',
  draftBody: 'This text has not been approved yet. It is not the final terms. Do not sign up on the strength of it.',
  draftWhy: 'Not published because:',
  translationNote: 'Some of this page has not been translated into {lang} yet. Those parts show in English.'
 },

 /* ------------------------------------------------ Shell (resident and ambassador app) */
 shell: {
  cvhName: 'Community Virtual Hub', hubName: 'Thorncliffe Park Community Hub', hubLogoAlt: 'Thorncliffe Park Community Hub',
  prototype: 'Prototype', prototypeNote: 'Not a live service. All content is AI-generated.',
  language: 'Language', changeLanguage: 'Change language', languageTitle: 'Choose your language', languageCurrent: 'Now showing',
  languageReturn: 'The screen stays where you were.',
  choices: 'What I have told the CVH', choicesShort: 'My choices',
  nav: { now: 'Now', help: 'Find help', map: 'Map', ready: 'Be ready' },
  navLabel: 'Main', close: 'Close', back: 'Back', next: 'Continue', skip: 'Skip', done: 'Done', cancel: 'Cancel', more: 'More',
  notInPrototype: 'Not in this prototype', notInPrototypeBody: 'This part is not built in the prototype. Nothing has changed.',
  pageNotFound: 'This page could not be found.', pageNotFoundBody: 'The link may be old or mistyped. Use the menu below to go on.',
  ok: 'OK', about: 'About the CVH', aboutBody: 'The Community Virtual Hub is run by Thorncliffe Park Community Hub for Thorncliffe Park and Flemingdon Park.',
  builtBy: 'Built with Sprout Climate', rules: 'The rules of this space', ambassador: 'Ambassador',
  offline: 'You are offline. Showing what was last loaded {t}.', aiLabel: 'AI-generated for the prototype', illustrative: 'Illustrative'
 },

 /* ------------------------------------------------ Shared components */
 x01: { text: 'The CVH is not an emergency service.', call: 'If someone is in danger, call 911.',
   short: 'Not an emergency service. In danger? Call 911.',
   sms: 'The Hub is not an emergency service. If someone is in danger, call 911.',
   partner: 'This space does not call 911 for anyone. If someone is in danger, call 911 yourself. Do not assume another organisation has.',
   print: 'This is not an emergency service. If someone is in danger, call 911.' },

 x02: { official: 'Official alert from {source}', community: 'Community alert from {author}',
   verifiedBy: 'Verified by {org}', notYetVerified: 'Not yet verified', corrected: 'Corrected {t}',
   whatMeans: 'What this means', hub: 'the Hub', theHub: 'The Hub', ambassador: 'Building ambassador, {building}',
   postedBy: 'Posted by {author}', levelOfficial: 'Official alert', levelCommunity: 'Community alert',
   sources: { ECCC: 'Environment and Climate Change Canada', CITY: 'City of Toronto', ALERTREADY: 'Alert Ready' } },

 x03: { title: 'The rules of this space', intro: 'The CVH is for neighbours helping neighbours. Before you add something, please read this.',
   rules: ['Share places and help that are free or low cost and open to the community.', 'Write about a place, not a person. Do not share anyone\'s name, unit number or phone number.',
     'Be kind. Nothing that insults or targets any group of people.', 'Only share what you know is true. If you are not sure, choose "Not sure".'],
   market: 'The CVH is not a marketplace. No selling, and no advertising.',
   review: 'Someone at the Hub reads everything before it goes on the map.', agree: 'I understand', readMore: 'Read the rules' },

 x04: { label: 'Translated by machine', from: 'from {lang}', report: 'Report a translation problem', reportTitle: 'What is wrong with this translation?',
   reasons: { meaning: 'The meaning is wrong', words: 'Some words are wrong', unclear: 'It is hard to understand' },
   send: 'Send', reported: 'Thank you. Someone at the Hub will check this translation.',
   unavailable: 'Not yet available in this language', unavailableBody: 'This has not been translated into {lang} yet.',
   showSource: 'Read it in {lang}', original: 'Original ({lang})' },

 x05: { title: 'Get alerts and help in your language', lead: 'The Community Virtual Hub tells you when something happens in your building, and helps you find services near you.',
   steps: ['Open the link or scan the code with your phone.', 'Choose your language.', 'You do not need an account or an app.'],
   link: 'Short link', scan: 'Scan with your phone camera', building: 'Building', floor: 'Floor', writeIn: 'Written in by your ambassador',
   text: 'No smartphone? Ask your floor ambassador to help you get text alerts.', from: 'From Thorncliffe Park Community Hub', sampleLink: 'Sample link, not live' },

 x06: { doing: 'We are doing this', canTake: 'We can take this on', cannotCover: 'We cannot cover this', need: 'We need this',
   claimed: 'Taken on by {org}', supply: 'Supply: {item}', recordDecision: 'Record as a decision' },

 x07: { label: 'Bigger text, fewer things', on: 'On', off: 'Off', setByHelper: 'Turned on by someone helping you', remembered: 'Remembered on this device',
   turnOn: 'Turn on bigger text, fewer things', turnOff: 'Turn off bigger text, fewer things' },

 x08: { idle: 'Listen · {t}', loading: 'Loading the audio', playing: 'Playing', paused: 'Paused', left: '{t} left',
   failed: 'The audio could not load on this connection. Everything it says is written here.', retry: 'Try again',
   play: 'Play', pause: 'Pause', section: 'Listen to this section · {t}' },

 x09: { open: 'Open', full: 'Full', closed: 'Closed', unconfirmed: 'Not confirmed',
   purpose: { cooling: 'for cooling', cleanAir: 'for clean air', warming: 'for warming', charging: 'for device charging' },
   confirmed: 'Confirmed {t}', unconfirmedNote: 'Not confirmed for {t}. It may not be open. Call before you go.',
   hoursToday: 'Today {from} to {to}', closedToday: 'Closed today', water: 'Drinking water', seating: 'Seating', charging: 'Phone charging',
   washrooms: 'Washrooms', stepFree: 'Step-free', notStepFree: 'Has steps', noId: 'Does not ask for ID', idAsked: 'Asks for ID', runBy: 'Run by {org}',
   yes: 'Yes', no: 'No', unknown: 'Not known' },

 x10: { word: 'Exercise', running: 'Exercise. This is practice.', runningSub: 'Nothing here is sent to residents.',
   ended: 'Exercise ended', sms: 'Exercise. Practice only.' },

 x11: { title: 'Filters on', remove: 'Remove filter: {f}', hiding: '{n} places are hidden by these filters', hidingOne: '1 place is hidden by these filters',
   fromChoices: 'Some filters come from your choices', clear: 'Remove all filters', none: 'No filters' },

 x12: { title: 'What this means for you', fromHub: 'Advice from the Hub', tailoredLink: 'Tailored to your choices',
   standard: 'Show the version everyone gets', standardShown: 'You are seeing the version everyone gets.', showMine: 'Show what this means for you',
   checkin: 'Your floor ambassador will check on you today.',
   noCheckin: 'There is no floor ambassador on your floor yet, so we cannot check on you. Call the Hub at {phone}. We are open {hours}.',
   hubHours: 'Monday to Thursday 9 am to 8 pm, Friday 9 am to 5 pm, Saturday 10 am to 2 pm', listen: 'Listen · {t}' },

 // X-12 (S04.09): the advice lines of the tailored block, by disruption type and then group; the phone adds one of them to an alert that is for it. Copied from the tailored table of data.js.
 tailored: {
  power: {
   seniors: ['If you use a medical device that needs power, go to a place with charging now.',
    'Take the stairs only if you feel able. Your floor ambassador can bring things to you.'],
   newcomers: ['Charging spaces do not ask for ID or immigration status.',
    'Toronto Hydro and the City will never ask you for money or papers by phone during an outage.'],
   families: ['Keep baby formula and milk in a cooler with ice if the fridge is warm.',
    'Use flashlights, not candles, around children.'],
  },
  flood: {
   seniors: ['Move medicines and papers to a high shelf now.',
    'Ask a neighbour or your floor ambassador for help if you need to leave.'],
   newcomers: ['You can report a leak to your landlord without it affecting your immigration status.',
    'Free legal help can explain repairs and rent after a flood, in your language.'],
   families: ['Keep children out of wet areas and away from outlets.',
    'Throw away toys and food that touched flood water.'],
  },
  elevator: {
   seniors: ['Your floor ambassador can arrange for groceries or medicines to be brought up.',
    'Rides to medical appointments can be arranged while the elevator is out.'],
   newcomers: ['Help with groceries and transport does not ask for ID or status.',
    'You have the right to ask your landlord when the elevator will be fixed.'],
   families: ['Neighbours can help carry strollers and groceries up the stairs.',
    'If a child has a medical appointment, ask about transport help.'],
  },
  heat: {
   seniors: ['Some medicines make heat harder on the body. Check with your pharmacist.',
    'Go to a cooling space in the early afternoon, before the hottest part of the day.'],
   newcomers: ['Cooling spaces are free and do not ask for ID or immigration status.',
    'Help with electricity bills is free. Ask at the Hub.'],
   families: ['Babies and small children get hot faster than adults. Give them water often.',
    'Never leave a child in a parked car, even for a minute.'],
  },
  smoke: {
   seniors: ['If you have asthma or a heart condition, keep your medicines close.',
    'Spaces with filtered air are open. Ask a neighbour to go with you.'],
   newcomers: ['Spaces with filtered air are free and do not ask for ID or immigration status.',
    'Masks are free at the Hub while supplies last.'],
   families: ['Keep children indoors and limit running and play.',
    'A box-fan filter in the children\'s room helps them sleep.'],
  },
  fire: {
   seniors: ['If you cannot use the stairs, stay in your unit with the door closed and call 911.',
    'Your floor ambassador knows which residents may need help leaving.'],
   newcomers: ['Reception points and support after a fire do not ask for immigration status.',
    'Settlement workers can help replace lost documents.'],
   families: ['Practise with your children: how to get to the stairwell, and where to meet outside.',
    'Keep a bag with children\'s medicines and papers by the door.'],
  },
  winter: {
   seniors: ['Charge your phone and keep blankets close in case the power goes out.'],
   newcomers: ['Warming spaces are free and do not ask for ID or status.'],
   families: ['Dress children in layers indoors if the heating goes off.'],
  },
 },

 x13: { fire: 'Fire', power: 'Power', water: 'Water', elevator: 'Elevator', flood: 'Flood or leak', heat: 'Heat', smoke: 'Smoke', winter: 'Winter storm', other: 'Other',
   fireAlarm: 'Fire alarm or evacuation', waterPlumbing: 'Water or plumbing' },

 x14: { label: 'How they can help' },

 status: { active: 'Active problem', progress: 'Work in progress', resolved: 'Resolved', unknown: 'Not known' },

 /* ------------------------------------------------ Shared vocabulary */
 groups: {
  seniors: { label: 'Seniors', line: 'Heat warnings and services for older residents, and advice for you in every alert.' },
  newcomers: { label: 'Newcomers', line: 'Services that do not ask for status, and advice for you in every alert.' },
  families: { label: 'Families with young children', line: 'Alerts and advice about babies and young children, and services for families.' },
  checkin: { label: 'I would like a check-in during heat and outages', line: 'Your floor ambassador checks on you when there is a heat warning or a power outage.' }
 },
 categories: { food: 'Food', housing: 'Housing and rent', health: 'Health', money: 'Money and benefits', settlement: 'Immigration and settlement',
   jobs: 'Jobs and training', children: 'Children and youth', seniors: 'Seniors', legal: 'Legal help', mentalHealth: 'Mental health' },
 filters: { openNow: 'Is it open right now?', nbhd: 'Which neighbourhood?', language: 'Do they speak my language?', cost: 'What does it cost?',
   noId: 'Will they ask for ID or status?', stepFree: 'Can I get in without steps?', noAppointment: 'Do I need an appointment?',
   short: { openNow: 'Open now', nbhdTP: 'Thorncliffe Park', nbhdFP: 'Flemingdon Park', language: 'Speaks {lang}', free: 'Free', lowCost: 'Free or low cost',
     noId: 'Does not ask for ID', stepFree: 'Step-free', noAppointment: 'No appointment needed' },
   answers: { yes: 'Yes', no: 'No', any: 'Any', free: 'Free only', lowCost: 'Free or low cost', noIdOnly: 'Only places that do not ask', stepFreeOnly: 'Only step-free places', walkIn: 'Only walk-in' } },
 utilities: { ac: 'Air conditioning', wifi: 'Wi-Fi', charging: 'Charging', washrooms: 'Washrooms', water: 'Drinking water', food: 'Food', kit: 'Preparedness kits here', space: 'Open as a space now' },
 orgKinds: { grassroots: 'Grassroots group', nonprofit: 'Non-profit', faith: 'Faith organisation', public: 'Public service', business: 'Business', communityOffer: 'Community offer' },
 neighbourhoods: { TP: 'Thorncliffe Park', FP: 'Flemingdon Park' },
 /* Map subcategory filter labels, keyed by the CSV Subcategory value */
 subcats: { 'Police Station': 'Police station', 'Fire Station': 'Fire station', 'Food Collaboratives': 'Food banks and food programs', 'Shelter': 'Shelters',
   'Faith-Based Organizations': 'Faith communities', 'Legal Services': 'Legal services', 'Government Documentation': 'Government documents', 'Schools': 'Schools',
   'Childminding & EarlyON': 'Child care and EarlyON', 'Dental Clinics': 'Dental clinics', 'Midwives Clinic': 'Midwives', 'Health Clinics': 'Health clinics',
   'Non-Profits': 'Community organisations', 'Community Centres': 'Community centres', 'Public Washrooms': 'Public washrooms', 'Libraries': 'Libraries',
   'Water Fountains': 'Drinking water', 'Museums': 'Museums', 'Cooling Spaces': 'Cooling spaces', 'Multi-Service Agencies': 'Multi-service agencies',
   'Food Security & Climate Resilience': 'Food and climate groups', 'Employment & Skills Training': 'Jobs and skills', 'Family & Parenting Support': 'Family and parenting',
   'Social & Cultural Organizations': 'Social and cultural groups', 'Newcomer Supports': 'Newcomer support', 'Housing & Tenant Supports': 'Housing and tenants',
   'Neighbourhood & Individual Empowerment': 'Neighbourhood groups' },
 hazards: { power: 'Power outage', flood: 'Flood or plumbing failure', elevator: 'Elevator failure', heat: 'Extreme heat', smoke: 'Wildfire smoke', fire: 'Fire and evacuation' },
 stages: { before: 'Before', during: 'During', after: 'After' },

 /* ------------------------------------------------ Resident screens */
 R01: { title: 'Choose your language', preselected: 'Chosen from your notice', selected: 'Selected', continue: 'Continue',
   helperBasic: 'Helping someone? Turn on bigger text, fewer things for them.', forwardedNote: 'Someone shared an alert with you. Choose your language first.' },
 R02: { title: 'Choose your language', current: 'Now showing', changed: 'Now showing {lang}.', unavailable: 'Not yet available in this language',
   unavailableBody: 'Some things on this screen have not been translated into {lang} yet. We will say so wherever that happens.' },
 R03: {
   getTextAlerts: 'Get text alerts', getTextAlertsLine: 'Alerts for your building by text message. No app, no account.',
   signedUp: 'Text alerts on', sent: 'Reply YES on your phone to start text alerts',
   alertsNow: 'Alerts now', myBuilding: 'Your building', myFloor: 'Your floor', myNeighbourhood: '{nbhd}',
   nothingActive: 'Nothing is happening right now.', nothingActiveBody: 'When something affects your building or your neighbourhood, it will show here first.',
   noBuildingChosen: 'Choose your building to see its alerts first', ongoing: 'Ongoing', updated: 'Updated {t}', posted: 'Posted {t}',
   everyday: 'Every day', findHelp: 'Find help', map: 'Map', beReady: 'Be ready',
   findHelpLine: 'Services and support near you', mapLine: 'Places near you, and what is open now', beReadyLine: 'Guides, numbers and check-ins',
   archive: 'Alerts that have ended', basicTurnOn: 'Bigger text, fewer things',
   headsUpTitle: 'Before the hot weather', headsUpFrom: 'A heads-up you chose', headsUpGuide: 'Read the heat guide', headsUpEvent: 'Workshop near you'
 },
 R04: {
   deviceLabel: 'Text message on a basic phone', from: 'Thorncliffe Hub', fromNumber: 'CVH alerts', lockScreen: 'Lock screen', now: 'now',
   levelOfficial: 'Official alert from {source}.', levelCommunity: 'Community alert from the Hub. Verified by the Hub.',
   fromHub: 'Community alert from the Hub',
   levelAmbassador: 'Community alert from a building ambassador. Not yet verified.',
   stop: 'To stop all messages from the Hub, reply STOP.', verifiedKeyword: 'To learn what verified means, reply INFO.',
   ackMore: 'More information to come.', update: 'Update to the alert "{headline}":', correction: 'Correction to the alert "{headline}": {changed}',
   resolved: 'Resolved: "{headline}". {final}', nearestSpace: 'Nearest open space: {space}, {hours}.',
   confirmRequest: 'Thorncliffe Park Community Hub: someone asked for text alerts for this phone, in {lang}, for {where}. To agree, reply YES. To stop all messages from the Hub, reply STOP.',
   keywordChange: 'Reply GROUPS to change the groups you chose.', checkinWithdraw: 'Reply NOCHECK to stop check-ins.', link: 'More: {url}',
   sampleLabel: 'Sample message. Nothing is sent.'
 },
 R05: {
   title: 'Get text alerts', lead: 'We send a text message when something happens in your building or neighbourhood. No app, no account, no email.',
   required: 'Required', optional: 'Optional', phone: 'Phone number', phoneHelp: 'Any way you write it is fine.', phoneShown: 'We will text {phone}',
   phoneError: 'This number needs 10 digits, like 416 555 0123.', nbhd: 'Neighbourhood', building: 'Building', floor: 'Floor',
   buildingSearch: 'Search for your building', notListed: 'My building isn\'t listed',
   notListedResult: 'You will get every alert for {nbhd}. We have told the Hub your building is missing from the list.',
   language: 'Language', languageFrom: 'From your first choice', groupsTitle: 'Which groups do you belong to?', groupsSkip: 'Skip this',
   send: 'Send me a text to confirm', formError: 'We could not send this yet. Please add: {missing}.',
   whatYouGet: 'Text messages are only for alerts. We never send everyday news or ads by text.',
   sentTitle: 'Check your phone', sentBody: 'We\'ve sent a message to {phone}. Reply YES to start getting alerts.',
   resend: 'Send it again', fix: 'Fix the number', signedUpTitle: 'Signed up', signedUpBody: '{phone} will get alerts in {lang}.', noAccount: 'You do not need an account.'
 },
 R06: {
   thanks: 'Thank you. You will get alerts from the Hub for {where}, in {lang}.', howStop: 'To stop all messages, reply STOP.',
   howChange: 'To change your groups, reply GROUPS.', groupsChanged: 'Done. You will no longer get alerts for: {group}.',
   checkinWithdrawn: 'Done. Your check-in request is withdrawn. You will still get alerts.', stopped: 'You will not get any more messages from the Hub. To start again, reply START.'
 },
 R07: {
   moreComing: 'More information to come', moreComingLine: 'We will update this as soon as we know more.',
   notYetKnown: 'Not known yet', where: 'Where', whatToDo: 'What to do', validUntil: 'Valid {until}', untilResolved: 'until resolved',
   posted: 'Posted {t}', updated: 'Updated {t}', latest: 'Latest', thread: 'Updates, newest first', earlier: 'Earlier updates',
   update: 'Update', correction: 'Correction', corrected: 'Corrected {t}', whatChanged: 'What changed: {changed}', earlierWording: 'Earlier wording',
   final: 'Final update', resolvedTitle: 'Resolved {t}', expiredTitle: 'Expired {t}', expiredNote: 'This alert reached its end time without a final update.',
   fromArchive: 'This alert has ended. It stays here so you can read it.', ongoingDays: 'Ongoing: day {n} of {total}',
   supportOffer: 'Help with this', openNear: 'Open near you', openNearAll: 'See all open spaces', officialLink: 'Official alert on the same event',
   officialFrom: 'From {source}', adds: 'This message adds what is happening in your building.', officialText: 'Official wording', officialTemplate: 'Translated from a checked template',
   guide: 'What to do: the {hazard} guide', services: 'Services that can help with this', share: 'Share', amberNote: 'Fictional placeholder. This shows the layout only.',
   ambLine: 'Message from the ambassador', readingOrder: 'Screen reader order: origin and verification, time posted, the alert, the not-911 statement, then actions.'
 },
 R08: { title: 'Alerts that have ended', resolved: 'Resolved {t}', expired: 'Expired {t}', empty: 'No alerts have ended yet.', emptyBody: 'When an alert ends, it moves here and stays readable.' },
 R09: { title: 'Find help', prompt: 'For example: my landlord wants me to move out', promptAlt: ['For example: I need food for my family this week', 'For example: someone to talk to about stress'],
   searchLabel: 'Tell us what you need, in your own words', search: 'Search', orChoose: 'Or choose a topic', within: 'Search within {cat}', clearCat: 'All topics' },
 R10: { title: 'Results', resultsFor: '{n} results for "{q}"', matched: 'Matched: {reason}', crossLanguage: 'Written in {lang}, shown translated',
   contributed: 'Added by a neighbour', filters: 'Filters', helpListTitle: 'Services that can help with: {hazard}',
   helpListNote: 'Only services that say how they can help with this are shown. Ranked by how well they fit, whether they are open now, distance and how recently confirmed.',
   noMatch: 'Nothing is open right now that is free and does not ask for ID.', noMatchSuggest: 'If you remove "{f}", {n} places match. The nearest opens {when}.',
   applySuggestion: 'Remove "{f}"', emergency: 'If someone is hurt right now, call 911.', openNow: 'Open now', closedNow: 'Closed now', opensAt: 'Opens {t}', distance: '{d} km' },
 R11: { title: 'We could not find that yet', body: 'A person at the Hub can help you find the right service.', person: 'Talk to the Hub\'s community navigator',
   call: 'Call {phone}', hours: 'Open {hours}', visit: 'Or visit 45 Overlea Boulevard', tryAgain: 'Try different words', categories: 'Choose a topic instead' },
 R12: { status: 'Right now', openNow: 'Open now, until {t}', closed: 'Closed now', opens: 'Opens {t}', address: 'Address and how to get there', directions: 'Directions',
   hours: 'Hours', languages: 'Languages spoken', cost: 'Cost', bring: 'What to bring', id: 'Will they ask for ID or status?', access: 'Accessibility', contact: 'Contact',
   call: 'Call', email: 'Email', website: 'Website', unknown: 'Not known', languagesUnknown: 'Not known. The Hub does not know which languages are spoken here.',
   noAddress: 'No street address', whereToFind: 'Where to find it',
   confirmedBy: 'Confirmed by {org} on {date}', publicSource: 'From public sources. Not yet confirmed by the organisation.', contributedBy: 'Added by a neighbour on {date}, checked by the Hub',
   kind: 'Kind of organisation', services: 'Services', org: 'Who runs it', otherServices: 'See what else {org} offers', onMap: 'See on the map',
   correct: 'Something wrong? Correct it', communityOffer: 'Community offer', communityOfferLine: 'Offered by neighbours, not an official service.',
   callConfirm: 'In the real CVH, this would call {phone}.', directionsConfirm: 'In the real CVH, this would open directions to {place}.', illustrative: 'Sample details for the prototype' },
 R13: { title: '{org}', services: 'Services', about: 'About' },
 R14: { title: 'Map', list: 'List', mapView: 'Map', loading: 'Loading the map', unavailable: 'The map could not load. The list has everything.', showList: 'Show the list',
   noneInView: 'Nothing here. Try zooming out.', places: '{n} places', place: '1 place', add: 'Add a place', rules: 'The rules of this space', filters: 'What do you need?',
   disruptionView: 'Showing places that can help with: {hazard}', legend: 'Kinds of place', newlyAdded: 'New', tapForHours: 'Tap a place for its hours' },
 R15: { title: 'Places near you', byDistance: 'Nearest first', empty: 'No places match these filters.', emptyBody: 'Remove a filter to see more.', add: 'Add a place' },
 R16: { open: 'See details', hoursToday: 'Today: {hours}', close: 'Close' },
 R17: { title: 'Add or correct a place', add: 'Add a place that is missing', correct: 'Correct a place that looks wrong', fromEntry: 'Correct this place' },
 R18: { title: 'Before you add a place', continue: 'I understand, continue' },
 R19: { title: 'Add a place', name: 'What is it called?', what: 'What happens there, in one sentence', whatHint: 'Up to 140 characters', category: 'What kind of help is it?',
   type: 'Is it an official service or a community offer?', official: 'An official service', offer: 'A community offer from neighbours',
   hours: 'When is it open?', sameWeekdays: 'Same every weekday', notSure: 'Not sure', from: 'From', to: 'To', closedDay: 'Closed',
   cost: 'What does it cost?', idQ: 'Will they ask for ID or status?', stepFreeQ: 'Can you get in without steps?', languagesQ: 'Which languages are spoken?',
   location: 'Where is it?', submit: 'Send to the Hub', optional: 'Optional', ready: 'Ready to send', saved: 'Saved on this phone' },
 R20: { title: 'Where is it?', pin: 'Drop a pin on the map', building: 'In a building', described: 'Describe where in the building', describedHint: 'For example: the community room behind the mosque',
   landmark: 'Near a landmark', landmarkHint: 'For example: by the splash pad in R.V. Burgess Park', address: 'Street address', noAddress: 'You do not need a street address.' },
 R21: { title: 'Sent to the Hub', general: 'Someone at the Hub will read it within about a week. We will tell you when it is on the map.',
   ambassador: 'You are an ambassador, so this is checked first. It is usually on the map within a day.', lane: 'Review path: {lane}', laneGeneral: 'Community review', laneAmbassador: 'Ambassador review, faster' },
 R22: { title: 'Correct this place', changeOne: 'Change what is wrong. Everything else stays as it is.', submit: 'Send the correction', sent: 'Thank you. The Hub will check the change.' },
 R23: { title: 'Your place was not added yet', reason: 'Why', whatToChange: 'What to change', resubmit: 'Change it and send again', kept: 'Everything you wrote is kept.' },
 R24: { title: 'Be ready', lead: 'What to do before, during and after the six disruptions that happen here.', numbers: 'Numbers I might need', headsUp: 'A heads-up before each season',
   checkin: 'Ask for a check-in during heat and outages', readTime: '{n} minute read' },
 R25: { stagesNav: 'Jump to', aiLabel: 'Written by AI for the prototype. People will check it before the CVH goes live.', kit: 'This guide matches the printed Local Preparedness Kit.',
   numbers: 'Numbers I might need', services: 'Services that can help', spaces: 'Spaces open for {purpose}', forYou: 'For you first', fullGuide: 'The full guide',
   next: 'Next: {stage}', stageNow: 'You are reading: {stage}', unavailable: 'This guide is not yet available in {lang}.' },
 R26: { title: 'Which groups do you belong to?', lead: 'Choose any that fit you. This shapes the alerts you get and the advice you see. We never ask why.',
   skipLine: 'Skipping changes nothing about the alerts you get.', helperConfirm: 'I am helping someone. They agreed to these choices.', helperNote: 'Please ask them first.' },
 R27: { title: 'Filters', apply: 'Show {n} results', clear: 'Clear all' },
 R28: { title: 'What "verified" means', body: 'Verified means someone at the Hub, or at a partner organisation the Hub works with, checked this alert with the people on the ground before it went out.',
   who: '{org} verified this alert {t}.', notYet: 'Not yet verified means the alert came from a building ambassador, who is often the first to know. The Hub checks it as soon as it can.',
   official: 'Official alerts come from {source} and are passed on without changing their words.', notFalse: 'Not yet verified does not mean it is wrong.' },
 R29: { title: 'Share this alert', preview: 'This is what your neighbours will get', everyone: 'Everyone gets this version. Nothing tailored to you is shared.',
   notRecorded: 'The CVH does not record who shares alerts or who you send them to.', send: 'Share', handed: 'Your phone\'s share options would open here.' },
 R30: { deviceLabel: 'The alert in a WhatsApp group', group: 'Floor 4 neighbours', openedLater: 'Opened later: it shows the newest update and a correction.' },
 R31: { title: 'Numbers I might need', emergency: 'Emergency', emergencyWhen: 'Call 911 if someone\'s life or safety is in danger right now: fire, a medical emergency, or a crime happening now.',
   p211: 'Help finding community, social and government services', p311: 'City of Toronto services and non-emergency problems',
   hydro: 'Report a power outage to Toronto Hydro', hub: 'Talk to someone at the Hub', building: 'Your building\'s {role}',
   noBuilding: 'We don\'t have a contact for your building yet. Your floor ambassador can help.', call: 'Call', callConfirm: 'In the real CVH, this would call {number}.' },
 R32: { title: 'A heads-up before each season', lead: 'A short reminder in the CVH before heat, smoke and winter outages, with one or two things to do.',
   never: 'Heads-ups appear in the CVH only. They never arrive as a text message.', on: 'Heads-ups on', off: 'Heads-ups off', season: 'When: {season}' },
 R33: { title: 'Ask for a check-in', what: 'When there is a heat warning or a power outage in your building, your floor ambassador will check on you, and can help you reach services you need.',
   notEmergency: 'A check-in is not an emergency service.', how: 'How would you like to be checked on?', call: 'A phone call', text: 'A text message', knock: 'A knock on the door',
   unit: 'Unit number', unitWhy: 'We only ask for your unit number so your ambassador knows which door to knock on.',
   building: 'Your building and floor', noAmbassador: 'There is no floor ambassador on floor {floor} yet, so we cannot promise a check-in.',
   hubInstead: 'Call the Hub at {phone} instead. We are open {hours}.', request: 'Ask for check-ins', requested: 'Check-ins asked for',
   requestedBody: 'When there is a heat warning or a power outage in {building}, your floor ambassador will check on you by {method}.', withdraw: 'Stop check-ins',
   withdrawn: 'Check-ins stopped. You will still get alerts.', helper: 'I am helping someone. They agreed to ask for check-ins.' },
 R34: { title: 'What I have told the CVH', lead: 'Only what you chose. Change or remove anything here. Changes happen straight away.',
   language: 'Language', building: 'Building and floor', basic: 'Bigger text, fewer things', groups: 'Groups', checkin: 'Check-ins', headsUp: 'Seasonal heads-ups',
   change: 'Change', remove: 'Remove', removed: 'Removed. This takes effect now.', nothing: 'You have not told the CVH anything yet.',
   onDevice: 'These choices are kept on this device only.', invite: 'To get alerts for your building and groups on your phone, set up text alerts. It takes a minute and needs no account.',
   inviteYes: 'Set up text alerts', inviteNo: 'Not now' },
 R35: { title: 'Get alerts for your building', lead: 'Choose where you live to see your building\'s alerts first. Every step is optional.',
   nbhd: 'Neighbourhood', building: 'Building', floor: 'Floor', nbhdOnly: 'The whole neighbourhood only', floorLine: 'Choosing a floor also gets you alerts for just your floor, like an elevator or water shut-off.',
   noUnit: 'We never ask for your unit number here.', preselected: 'From your notice', skipLine: 'If you skip, you still see every alert for your neighbourhood.',
   finishedTitle: 'You chose', finishedSummary: '{summary}', invite: 'To get alerts for your building, your floor and your groups on your phone, set up text alerts. It takes a minute and needs no account.',
   inviteYes: 'Set up text alerts', inviteNo: 'Not now', helper: 'I am helping someone. They agreed to this choice.' },

 /* ------------------------------------------------ Hub and partner shell (English only, brief Section 8) */
 hub: { appName: 'Hub and partner space', signedInAs: 'Signed in as {name}, {org}', signOut: 'Sign out',
   nav: { incidents: 'Incidents', log: 'Log a disruption', compose: 'Compose an alert', moderation: 'Moderation', rounds: 'Check-in rounds',
     readiness: 'Readiness', commitments: 'Standing commitments', playbooks: 'Playbooks', teams: 'Teams and triggers', exercise: 'Exercises',
     indicators: 'Indicators', lookBack: 'Look back', space: 'Shared space', coverage: 'Coverage', ourSpaces: 'Our spaces', supplies: 'Supplies',
     decisions: 'Decision log', capacity: 'Our capacity' },
   sections: { disruption: 'In a disruption', between: 'Between disruptions', thisDisruption: 'This disruption' },
   partnerBand: 'Partner space', partnerBandLine: 'Only Hub and partner staff can see this. Residents and ambassadors cannot.',
   readinessBand: 'Readiness area', readinessBandLine: 'Hub and partner staff only. Used between disruptions.',
   menu: 'Menu', exerciseToggle: 'Exercise running', noResidentRoute: 'This is a separate application. There is no link to it from the resident app.' },

 /* ------------------------------------------------ Ambassador screens */
 A01: { title: 'My building', assigned: 'You are the ambassador for {building}, floors {floors}.', canPost: 'You can post updates for any floor of {building}.',
   post: 'Post a building update', active: 'Happening in your building', nothing: 'Nothing active in your building.', round: 'Check-in round: {n} on your floors', openRound: 'Open my round' },
 A02: { title: 'Post a building update', types: 'What is happening? Choose all that apply', floors: 'Which floors?', wholeBuilding: 'Whole building', range: 'From floor {a} to {b}',
   pick: 'Choose floors', photo: 'Add a photo', line: 'Add one line', lineRequired: 'Say what is happening, in one line', optional: 'Optional',
   other911: 'If anyone is in danger, call 911 first.', appearsAs: 'This will appear as: Building ambassador, {building}', goesNow: 'This will go out now.',
   waits: 'The Hub will check this before it goes out.', post: 'Post update', notOffered: 'Heat and smoke come from the Hub for the whole neighbourhood.' },
 A03: { liveTitle: 'Posted', live: 'Live now on every channel, including text messages. It shows as "Not yet verified" until the Hub checks it.',
   waitingTitle: 'Waiting for the Hub', waiting: 'The Hub is checking this now. It goes out as soon as it is approved.', approved: 'Approved and sent {t}.',
   declined: 'The Hub did not send this. Reason: {reason}', verified: 'The Hub verified your update {t}.', corrected: 'The Hub corrected your update. Reason: {reason}',
   withdrawn: 'The Hub withdrew your update. Reason: {reason}', slow: 'Still sending. Weak signal here. It will finish when your signal is better.',
   where: 'Sent to: {channels}', when: 'Posted {t}' },
 A04: { title: 'My round', checkins: 'Check-ins asked for on your floors', unreachable: 'Households on your floors not reachable by phone or app',
   carry: 'Alert to tell them', floorDoor: 'Floor {floor}, door {door}', floorPhone: 'Floor {floor}, {method} {phone}', method: { call: 'call', text: 'text', knock: 'knock' },
   done: 'Done', notReached: 'Not reached', needsHelp: 'Needs help', connected: 'Connected to a service', passed: 'Passed to the Hub',
   offline: 'No signal. Your taps are saved and will send when you have signal.', deleted: 'When this disruption closes, these records are deleted. Only the counts are kept.',
   addDoor: 'Add a door at a resident\'s request', addConfirm: 'The resident agreed to be added, here on my screen.', addedByRequest: 'Added at the resident\'s request',
   addNote: 'This door is deleted when the disruption closes. To be checked on every time, they can choose it in the CVH.', exercise: 'This is a practice round.' },
 A05: { title: 'Connect to a service', urgent: 'Anything urgent or dangerous: call 911 now.', list: 'Open now, in the resident\'s language',
   choose: 'Tell them about this', chosen: 'Tell the resident how to reach {service}, or write it down for them.', neverText: 'We do not send this by text message.',
   recorded: 'Recorded as: {category}. Nothing else is saved.' }
};
