/* Tagalog strings for the resident and ambassador screens, merged into the Tagalog table by
   screen ID. AI-generated (Claude), not yet checked by native readers. Staff screens stay in English. */
(function () {
  var t = window.CVH_STRINGS.tl;
  function m(t, s) { for (var k in s) { if (!Object.prototype.hasOwnProperty.call(s, k) || k === "__proto__" || k === "constructor" || k === "prototype") continue; if (s[k] && typeof s[k] === "object" && !Array.isArray(s[k]) && t[k] && typeof t[k] === "object" && !Array.isArray(t[k])) m(t[k], s[k]); else t[k] = s[k]; } }
  /* Production UAT (2026-10-08): the display settings (Aa), the alert-state words (an alert or entry the Hub withdrew, the note on
     an alert read from a kept copy whose time has passed, the archive's older alerts), the share screen's copy and WhatsApp words, and
     the footer's two links. AI-generated (Claude), not yet checked by native readers. The alert-state words (R07, R08) tell a resident
     not to act on an alert: they wait for native review on the launch checklist (Launch Readiness). */
  m(t, {
    "display": {"title": "Mga setting ng display", "close": "Tapos na", "textSize": "Laki ng teksto", "standard": "Karaniwan", "large": "Malaki", "simpler": "Mas simpleng view", "help": "Magpakita ng mas kaunting detalye at gumamit ng mga listahan sa halip na mapa. Hindi nagbabago ang laki ng teksto.", "saved": "Naka-save sa device na ito.", "sessionOnly": "Hindi kayang i-save ng iyong browser ang setting na ito. Para lang ito sa pagbisitang ito."},
    "R07": {"withdrawn": "Binawi", "mayHaveEnded": "Maaaring tapos na ang alertong ito. Tingnan ulit kapag may signal ka na"},
    "R08": {"withdrawn": "Binawi {t}", "more": "Ipakita ang mas lumang mga alerto", "moreFailed": "Hindi namin ma-load ang mas lumang mga alerto. Tiyaking may signal ka at subukan ulit."},
    "R29": {"copy": "Kopyahin ang mensahe", "copied": "Nakopya na. Maaari mo itong i-paste sa kahit anong app.", "copyFailed": "Hindi ito kinopya ng iyong telepono. Pindutin nang matagal ang mensahe sa itaas para kopyahin ito.", "whatsapp": "Ipadala sa WhatsApp", "noSheet": "Walang mga opsyon sa pagbabahagi ang iyong telepono dito. Kopyahin ang mensahe, o ipadala ito sa WhatsApp."},
    "shell": {"staffSignIn": "Pag-sign in ng staff", "termsLink": "Mga tuntunin at privacy"}
  });
  m(t, {
  "terms": {
   "version": "Bersyon",
   "owner": "May-ari",
   "updated": "Huling na-update",
   "privacyContact": "Contact para sa privacy",
   "draftTitle": "Draft: hindi pa nailalathala",
   "draftBody": "Hindi pa naaaprubahan ang tekstong ito. Hindi pa ito ang huling mga tuntunin. Huwag mag-sign up dahil lang dito.",
   "draftWhy": "Hindi nailathala dahil:",
   "translationNote": "May ilang bahagi ng pahinang ito na hindi pa naisasalin sa {lang}. Sa English lumalabas ang mga bahaging iyon.",
   /* S09.08: the day the pilot's resident data was deleted, shown once the end-of-pilot purge has completed. AI-generated (Claude), not yet checked by native readers. */
   "dataDeleted": "Binura ang datos ng mga residente",
   "dataDeletedNote": "Tapos na ang pilot ng CVH. Sa petsang iyon, binura namin ang numero ng telepono at mga pinili ng lahat ng hindi nag-reply ng YES para patuloy na makatanggap ng alerto."
  },
  "shell": {
   "hubName": "Thorncliffe Park Community Hub",
   "hubLogoAlt": "Thorncliffe Park Community Hub",
   "pageNotFound": "Hindi mahanap ang pahinang ito.",
   "pageNotFoundBody": "Maaaring luma o mali ang pagkaka-type ng link. Gamitin ang menu sa ibaba para magpatuloy."
  },
  "x01": {
   "partner": "Hindi tumatawag sa 911 ang espasyong ito para kaninuman. Kung may nasa panganib, ikaw mismo ang tumawag sa 911. Huwag ipagpalagay na may ibang organisasyong tumawag na."
  },
  "x05": {
   "title": "Kumuha ng mga alerto at tulong sa iyong wika",
   "lead": "Sinasabi sa iyo ng Community Virtual Hub kapag may nangyari sa iyong gusali, at tinutulungan kang humanap ng mga serbisyong malapit sa iyo.",
   "steps": ["Buksan ang link o i-scan ang code gamit ang iyong telepono.", "Piliin ang iyong wika.", "Hindi mo kailangan ng account o app."],
   "link": "Maikling link",
   "scan": "I-scan gamit ang camera ng iyong telepono",
   "building": "Gusali",
   "floor": "Palapag",
   "writeIn": "Isinulat ng iyong ambassador",
   "text": "Walang smartphone? Hilingin sa ambassador ng palapag mo na tulungan kang makakuha ng text alert.",
   "from": "Mula sa Thorncliffe Park Community Hub",
   "sampleLink": "Halimbawang link, hindi gumagana"
  },
  "x06": {
   "doing": "Ginagawa namin ito",
   "canTake": "Kaya naming akuin ito",
   "cannotCover": "Hindi namin ito kaya",
   "need": "Kailangan namin ito",
   "claimed": "Inako ng {org}",
   "supply": "Suplay: {item}",
   "recordDecision": "Itala bilang desisyon"
  },
  "groups": {
   "seniors": {
    "label": "Mga nakatatanda",
    "line": "Mga babala sa init at serbisyo para sa matatandang residente, at payo para sa iyo sa bawat alerto."
   },
   "newcomers": {
    "label": "Mga bagong dating",
    "line": "Mga serbisyong hindi nagtatanong ng status, at payo para sa iyo sa bawat alerto."
   },
   "families": {
    "label": "Mga pamilyang may maliliit na anak",
    "line": "Mga alerto at payo tungkol sa mga sanggol at maliliit na bata, at mga serbisyo para sa mga pamilya."
   },
   "checkin": {
    "label": "Gusto ko ng pangungumusta tuwing may matinding init at pagkawala ng kuryente",
    "line": "Kukumustahin ka ng ambassador ng palapag mo kapag may babala ng matinding init o pagkawala ng kuryente."
   }
  },
  "categories": {
   "food": "Pagkain",
   "housing": "Pabahay at upa",
   "health": "Kalusugan",
   "money": "Pera at benepisyo",
   "settlement": "Imigrasyon at tulong sa mga bagong dating",
   "jobs": "Trabaho at pagsasanay",
   "children": "Mga bata at kabataan",
   "seniors": "Mga nakatatanda",
   "legal": "Tulong legal",
   "mentalHealth": "Kalusugan ng isip"
  },
  "filters": {
   "openNow": "Bukas ba ito ngayon?",
   "nbhd": "Aling kapitbahayan?",
   "language": "Nagsasalita ba sila ng wika ko?",
   "cost": "Magkano ang bayad?",
   "noId": "Hihingi ba sila ng ID o status?",
   "stepFree": "Makakapasok ba ako nang walang hagdan?",
   "noAppointment": "Kailangan ko ba ng appointment?",
   "answers": {
    "yes": "Oo",
    "no": "Hindi",
    "any": "Kahit ano",
    "free": "Libre lang",
    "lowCost": "Libre o mura",
    "noIdOnly": "Mga lugar lang na hindi nagtatanong",
    "stepFreeOnly": "Mga lugar lang na walang hagdan",
    "walkIn": "Walang appointment lang"
   }
  },
  "utilities": {
   "ac": "Aircon",
   "wifi": "Wi-Fi",
   "charging": "Pag-charge",
   "washrooms": "Banyo",
   "water": "Inuming tubig",
   "food": "Pagkain",
   "kit": "May preparedness kit dito",
   "space": "Bukas bilang espasyo ngayon"
  },
  "orgKinds": {
   "grassroots": "Grupo ng mga residente",
   "nonprofit": "Non-profit na organisasyon",
   "faith": "Organisasyon ng pananampalataya",
   "public": "Pampublikong serbisyo",
   "business": "Negosyo",
   "communityOffer": "Alok ng komunidad"
  },
  "neighbourhoods": {
   "TP": "Thorncliffe Park",
   "FP": "Flemingdon Park"
  },
  "subcats": {
   "Police Station": "Istasyon ng pulisya",
   "Fire Station": "Istasyon ng bumbero",
   "Food Collaboratives": "Mga food bank at programa sa pagkain",
   "Shelter": "Mga silungan",
   "Faith-Based Organizations": "Mga komunidad ng pananampalataya",
   "Legal Services": "Mga serbisyo sa legal",
   "Government Documentation": "Mga dokumento ng gobyerno",
   "Schools": "Mga paaralan",
   "Childminding & EarlyON": "Pag-aalaga sa bata at EarlyON",
   "Dental Clinics": "Mga dental clinic",
   "Midwives Clinic": "Mga komadrona",
   "Health Clinics": "Mga klinika ng kalusugan",
   "Non-Profits": "Mga organisasyon ng komunidad",
   "Community Centres": "Mga sentro ng komunidad",
   "Public Washrooms": "Mga pampublikong palikuran",
   "Libraries": "Mga aklatan",
   "Water Fountains": "Inuming tubig",
   "Museums": "Mga museo",
   "Cooling Spaces": "Mga lugar na pampalamig",
   "Multi-Service Agencies": "Mga ahensyang may iba't ibang serbisyo",
   "Food Security & Climate Resilience": "Mga grupo para sa pagkain at klima",
   "Employment & Skills Training": "Trabaho at kasanayan",
   "Family & Parenting Support": "Pamilya at pagpapalaki ng anak",
   "Social & Cultural Organizations": "Mga grupong panlipunan at pangkultura",
   "Newcomer Supports": "Suporta para sa mga bagong dating",
   "Housing & Tenant Supports": "Pabahay at mga nangungupahan",
   "Neighbourhood & Individual Empowerment": "Mga grupo sa kapitbahayan"
  },
  "hazards": {
   "power": "Pagkawala ng kuryente",
   "flood": "Baha o sira sa tubo",
   "elevator": "Sirang elevator",
   "heat": "Matinding init",
   "smoke": "Usok mula sa wildfire",
   "fire": "Sunog at paglikas"
  },
  "stages": {
   "before": "Bago",
   "during": "Habang",
   "after": "Pagkatapos"
  },
  "R01": {
   "title": "Piliin ang iyong wika",
   "preselected": "Pinili mula sa iyong abiso",
   "selected": "Napili",
   "continue": "Magpatuloy",
   "helperBasic": "Tumutulong sa iba? Buksan ang mas malaking teksto, mas kaunting bagay para sa kanila.",
   "forwardedNote": "May nagbahagi sa iyo ng alerto. Piliin muna ang iyong wika.",
   "fromPhone": "Mula sa wika ng iyong telepono",
   "chooseFirst": "Pumili ng wika para magpatuloy.",
   "youChose": "Ang iyong wika:",
   "helperOn": "Nakabukas ang mas malaking teksto, mas kaunting bagay. Mananatili itong bukas para sa kanila."
  },
  "R02": {
   "current": "Ipinapakita ngayon",
   "unavailable": "Wala pa sa wikang ito",
   "unavailableBody": "May ilang bagay sa screen na ito na hindi pa naisasalin sa {lang}. Sasabihin namin ito saanman ito mangyari.",
   "continueIn": "Magpatuloy sa {lang}",
   "chooseOther": "Pumili ng ibang wika"
  },
  "R03": {
   "getTextAlerts": "Kumuha ng text alert",
   "getTextAlertsLine": "Mga alerto para sa iyong gusali sa pamamagitan ng text message. Walang app, walang account.",
   "signedUp": "Nakabukas ang text alert",
   "sent": "Sumagot ng YES sa iyong telepono para simulan ang text alert",
   "alertsNow": "Mga alerto ngayon",
   "myBuilding": "Ang iyong gusali",
   "myFloor": "Ang iyong palapag",
   "nothingActive": "Walang nangyayari ngayon.",
   "nothingActiveBody": "Kapag may nangyari na nakakaapekto sa iyong gusali o sa inyong lugar, dito ito unang lalabas.",
   "noBuildingChosen": "Piliin ang iyong gusali para unang makita ang mga alerto nito",
   "ongoing": "Patuloy pa",
   "updated": "Na-update {t}",
   "posted": "Ipinost {t}",
   "everyday": "Araw-araw",
   "findHelp": "Humanap ng tulong",
   "map": "Mapa",
   "beReady": "Maging handa",
   "findHelpLine": "Mga serbisyo at suporta na malapit sa iyo",
   "mapLine": "Mga lugar na malapit sa iyo, at kung ano ang bukas ngayon",
   "beReadyLine": "Mga gabay, numero at pangungumusta",
   "archive": "Mga alertong natapos na",
   "basicTurnOn": "Mas malaking teksto, mas kaunting bagay",
   "headsUpTitle": "Bago dumating ang mainit na panahon",
   "headsUpFrom": "Isang paalala na pinili mo",
   "headsUpGuide": "Basahin ang gabay sa init",
   "headsUpEvent": "Workshop na malapit sa iyo",
   "ongoingDay": "Patuloy pa: araw {n} ng {total}",
   "readAlert": "Basahin ang alerto",
   "neighbourhoods": "Thorncliffe Park at Flemingdon Park",
   "headsUpAction": "Isang bagay na gagawin ngayon",
   "ambassadorHome": "Ambassador: ang gusali ko",
   "ambassadorLine": "Mag-post ng update o gawin ang iyong pag-ikot para sa {building}",
   "noBuildingLine": "Dito lumalabas ang mga alerto para sa inyong lugar. Idagdag ang iyong gusali para unang makita ang mga alerto nito."
  },
  "R04": {
   "deviceLabel": "Text message sa simpleng telepono",
   "from": "Thorncliffe Hub",
   "fromNumber": "Mga alerto ng CVH",
   "lockScreen": "Naka-lock na screen",
   "now": "ngayon",
   "levelOfficial": "Opisyal na alerto mula sa {source}.",
   "levelCommunity": "Alerto ng komunidad mula sa Hub. Beripikado ng Hub.",
   "fromHub": "Alerto ng komunidad mula sa Hub",
   "levelAmbassador": "Alerto ng komunidad mula sa isang ambassador ng gusali. Hindi pa beripikado.",
   "stop": "Para itigil ang lahat ng mensahe mula sa Hub, sumagot ng STOP.",
   "verifiedKeyword": "Para malaman ang ibig sabihin ng beripikado, sumagot ng INFO.",
   "ackMore": "May darating pang impormasyon.",
   "update": "Update sa alertong \"{headline}\":",
   "correction": "Pagtatama sa alertong \"{headline}\": {changed}",
   "resolved": "Naayos na: \"{headline}\". {final}",
   "nearestSpace": "Pinakamalapit na bukas na lugar: {space}, {hours}.",
   "confirmRequest": "Thorncliffe Park Community Hub: may humiling ng text alert para sa teleponong ito, sa {lang}, para sa {where}. Para pumayag, sumagot ng YES. Para itigil ang lahat ng mensahe mula sa Hub, sumagot ng STOP.",
   "keywordChange": "Sumagot ng GROUPS para palitan ang mga grupong pinili mo.",
   "checkinWithdraw": "Sumagot ng NOCHECK para itigil ang pangungumusta.",
   "link": "Iba pa: {url}",
   "sampleLabel": "Halimbawang mensahe. Walang ipinapadala.",
   "tapOpen": "Pindutin ang mensahe para buksan ito",
   "back": "Bumalik sa app",
   "annotOn": "Aling mga linya ang isinalin",
   "annotOff": "Itago ang mga tala sa salin",
   "bigOn": "Pinakamalaking teksto",
   "bigOff": "Karaniwang teksto",
   "tagTemplate": "Sinuring template",
   "tagAlert": "Isinulat para sa alertong ito",
   "annotNote": "Nakaguhit sa English ang Phase 2. Ang mga linyang may markang \"Sinuring template\" ay nasa lahat ng labinlimang wika sa paglulunsad, at sinuri ng mga tao. Ang mga linyang may markang \"Isinulat para sa alertong ito\" ay isinasalin para sa bawat alerto. Wala pa sa prototype na ito ang bersyong Urdu at Greek.",
   "officialNote": "Ang mga opisyal na alerto ay ipinapadala mula sa template na sinuri ng tao sa bawat wika. Sinasabi ng kasunod na alerto ng komunidad kung ano ang idinadagdag nito rito.",
   "notKnownPrefix": "Hindi pa alam: {what}.",
   "you": "Ikaw",
   "exNote": "Pagsasanay. Ang mga taong naka-enroll lang sa drill ang makakatanggap ng text na ito. Walang matatanggap ang mga residente."
  },
  "R05": {
   "title": "Kumuha ng text alert",
   "lead": "Nagpapadala kami ng text message kapag may nangyari sa iyong gusali o sa inyong lugar. Walang app, walang account, walang email.",
   "required": "Kailangan",
   "optional": "Hindi kailangan",
   "phone": "Numero ng telepono",
   "phoneHelp": "Ayos lang kahit paano mo ito isulat.",
   "phoneShown": "Magte-text kami sa {phone}",
   "phoneError": "Kailangan ng numerong ito ng 10 digit, tulad ng 416 555 0123.",
   "nbhd": "Kapitbahayan",
   "building": "Gusali",
   "floor": "Palapag",
   "buildingSearch": "Hanapin ang iyong gusali",
   "notListed": "Wala sa listahan ang gusali ko",
   "notListedResult": "Makukuha mo ang bawat alerto para sa {nbhd}. Sinabihan na namin ang Hub na wala sa listahan ang iyong gusali.",
   "language": "Wika",
   "languageFrom": "Mula sa una mong pinili",
   "groupsTitle": "Saang mga grupo ka kabilang?",
   "groupsSkip": "Laktawan ito",
   "send": "Padalhan ako ng text para kumpirmahin",
   "formError": "Hindi pa namin ito maipadala. Pakidagdag ang: {missing}.",
   "whatYouGet": "Para lang sa mga alerto ang text message. Hindi kami nagpapadala ng pang-araw-araw na balita o ads sa text.",
   "sentTitle": "Tingnan ang iyong telepono",
   "sentBody": "Nagpadala kami ng mensahe sa {phone}. Sumagot ng YES para magsimulang makatanggap ng alerto.",
   "resend": "Ipadala muli",
   "fix": "Ayusin ang numero",
   "signedUpTitle": "Naka-sign up na",
   "signedUpBody": "Makakatanggap ang {phone} ng mga alerto sa {lang}.",
   "noAccount": "Hindi mo kailangan ng account.",
   "missingPhone": "numero ng telepono na may 10 digit",
   "missingNbhd": "ang inyong kapitbahayan",
   "and": " at ",
   "nbhdError": "Piliin ang inyong kapitbahayan.",
   "change": "Palitan",
   "noFloor": "Walang palapag, gusali lang",
   "floorN": "Palapag {n}",
   "step1": "Hakbang 1 ng 2",
   "step2": "Hakbang 2 ng 2",
   "continue": "Magpatuloy",
   "groupsLead": "Hindi ito kailangan. Kapag pumili ka ng grupo, makakatanggap ka ng mga alerto at payo para dito.",
   "consent": "Pumapayag ang may-ari ng teleponong ito kapag sumagot siya ng YES, kasama ang anumang grupong pinili rito.",
   "resent": "Ipinadala namin itong muli sa {phone}.",
   "protoSee": "Tingnan ang pagdating ng mensahe sa telepono",
   "protoTag": "Prototype",
   "howStop": "Para itigil ang lahat ng mensahe mula sa Hub, sumagot ng STOP sa anumang text.",
   "howChange": "Para palitan ang iyong mga grupo, sumagot ng GROUPS.",
   "toHome": "Pumunta sa Ngayon",
   "sample": "Halimbawang gusali",
   "moreBuildings": "{n} pa. I-type ang bahagi ng address."
  },
  "R06": {
   "thanks": "Salamat. Makakatanggap ka ng mga alerto mula sa Hub para sa {where}, sa {lang}.",
   "howStop": "Para itigil ang lahat ng mensahe, sumagot ng STOP.",
   "howChange": "Para palitan ang iyong mga grupo, sumagot ng GROUPS.",
   "groupsChanged": "Tapos na. Hindi ka na makakatanggap ng mga alerto para sa: {group}.",
   "checkinWithdrawn": "Tapos na. Binawi na ang iyong hiling na pangungumusta. Makakatanggap ka pa rin ng mga alerto.",
   "stopped": "Hindi ka na makakatanggap ng anumang mensahe mula sa Hub. Para magsimulang muli, sumagot ng START.",
   "deviceLabel": "Mga text message sa simpleng telepono",
   "back": "Bumalik sa app",
   "replyHint": "Pindutin ang isang sagot para ipadala ito",
   "you": "Ikaw",
   "groupsMenu": "Sumagot ng numero para itigil ang mga alerto para sa grupong iyon: {list}.",
   "noGroups": "Wala ka pang piniling grupo. Nakukuha mo ang bawat alerto para sa {where}.",
   "started": "Maligayang pagbabalik. Makakatanggap ka ng mga alerto mula sa Hub para sa {where}, sa {lang}.",
   "now": "ngayon",
   "exNote": "Pagsasanay. Praktis lang ang usapang ito, sa telepono ng taong naka-enroll sa drill. Walang residenteng na-sign up o binago."
  },
  "R07": {
   "moreComing": "May darating pang impormasyon",
   "moreComingLine": "Ia-update namin ito sa sandaling may malaman pa kami.",
   "notYetKnown": "Hindi pa alam",
   "where": "Saan",
   "whatToDo": "Ano ang gagawin",
   "validUntil": "May bisa {until}",
   "untilResolved": "hanggang maayos",
   "posted": "Ipinost {t}",
   "updated": "Na-update {t}",
   "latest": "Pinakabago",
   "thread": "Mga update, pinakabago muna",
   "earlier": "Mga naunang update",
   "update": "Update",
   "correction": "Pagtatama",
   "corrected": "Itinama {t}",
   "whatChanged": "Ano ang nagbago: {changed}",
   "earlierWording": "Naunang pagkakasulat",
   "final": "Huling update",
   "resolvedTitle": "Naayos {t}",
   "expiredTitle": "Nag-expire {t}",
   "expiredNote": "Umabot ang alertong ito sa oras ng pagtatapos nang walang huling update.",
   "fromArchive": "Natapos na ang alertong ito. Nananatili ito rito para mabasa mo.",
   "ongoingDays": "Patuloy pa: araw {n} ng {total}",
   "supportOffer": "Tulong para dito",
   "openNear": "Bukas malapit sa iyo",
   "openNearAll": "Tingnan ang lahat ng bukas na lugar",
   "officialLink": "Opisyal na alerto sa parehong pangyayari",
   "officialFrom": "Mula sa {source}",
   "adds": "Idinadagdag ng mensaheng ito kung ano ang nangyayari sa iyong gusali.",
   "officialText": "Opisyal na pagkakasulat",
   "officialTemplate": "Isinalin mula sa sinuring template",
   "guide": "Ano ang gagawin: ang gabay sa {hazard}",
   "services": "Mga serbisyong makakatulong dito",
   "share": "Ibahagi",
   "amberNote": "Kathang-isip na halimbawa. Ipinapakita lang nito ang layout.",
   "ambLine": "Mensahe mula sa ambassador",
   "readingOrder": "Pagkakasunod para sa screen reader: pinagmulan at beripikasyon, oras ng pag-post, ang alerto, ang paalala tungkol sa 911, at saka ang mga aksyon.",
   "kinds": {
    "ack": "Unang mensahe",
    "alert": "Alerto",
    "issued": "Inilabas",
    "update": "Update",
    "correction": "Pagtatama",
    "final": "Huling update",
    "ambassador": "Mensahe mula sa ambassador"
   },
   "whereLabel": "Saan",
   "actionLabel": "Ano ang gagawin ngayon",
   "notYetKnownLabel": "Hindi pa alam",
   "latestTag": "Pinakabago",
   "ambassadorOriginal": "Orihinal, sa {lang}",
   "officialCard": "Opisyal na alerto sa parehong pangyayari",
   "openOfficial": "Basahin ang opisyal na alerto",
   "fromCommunity": "Ipinapasa nito ang isang opisyal na alerto. Idinadagdag ng Hub kung ano ang nangyayari dito.",
   "spacesFiltered": "Ipinapakita ang mga lugar na hindi humihingi ng ID, batay sa mga pinili mo.",
   "supportSee": "Tingnan ang lugar",
   "amberBody": "Ang Amber Alert ay opisyal na alerto tungkol sa nawawalang bata. Laging galing sa Alert Ready ang totoong pagkakasulat.",
   "endedResolved": "Natapos na ang alertong ito. Naayos ito {t}.",
   "endedWithdrawn": "Binawi ng Hub ang alertong ito. {reason}",
   "endedExpired": "Natapos na ang alertong ito. Nag-expire ito {t} nang walang huling update.",
   "validLine": "May bisa {until}",
   "timeLine": "Ipinost {posted} · Na-update {updated}",
   "timeLineOne": "Ipinost {posted}",
   "basicMore": "Mga naunang update: {n}"
  },
  "R08": {
   "title": "Mga alertong natapos na",
   "resolved": "Naayos {t}",
   "expired": "Nag-expire {t}",
   "empty": "Wala pang alertong natatapos.",
   "emptyBody": "Kapag natapos ang isang alerto, lilipat ito rito at mababasa pa rin.",
   "lead": "Mababasa pa rin dito ang bawat alerto pagkatapos nito.",
   "endedOn": "Ipinost {posted}",
   "backHome": "Bumalik sa Ngayon"
  },
  "R09": {
   "title": "Humanap ng tulong",
   "prompt": "Halimbawa: gusto akong paalisin ng landlord ko",
   "promptAlt": ["Halimbawa: kailangan ko ng pagkain para sa pamilya ko ngayong linggo", "Halimbawa: may makakausap tungkol sa stress"],
   "searchLabel": "Sabihin sa amin ang kailangan mo, sa sarili mong salita",
   "search": "Hanapin",
   "orChoose": "O pumili ng paksa",
   "within": "Maghanap sa {cat}",
   "clearCat": "Lahat ng paksa",
   "lead": "Sabihin kung ano ang problema, gaya ng pagsasabi mo sa isang kaibigan. Hindi mo kailangang alamin ang pangalan ng serbisyo.",
   "focusHint": "Iba pang isinusulat ng mga tao",
   "topic": "Paksa: {cat}",
   "seeAll": "Tingnan ang lahat sa {cat}",
   "moreTopics": "Ipakita ang lahat ng {n} paksa",
   "clear": "Burahin ang isinulat ko",
   "testTitle": "Mga pansubok na paghahanap",
   "testNote": "Para sa mga facilitator: pindutin ang isa para patakbuhin ang nakahandang paghahanap mula sa brief. Hindi ito nakikita ng mga residente.",
   "testGloss": "(Dari: {gloss})"
  },
  "R10": {
   "title": "Mga resulta",
   "resultsFor": "{n} resulta para sa \"{q}\"",
   "matched": "Tugma: {reason}",
   "crossLanguage": "Nakasulat sa {lang}, ipinapakitang isinalin",
   "contributed": "Idinagdag ng isang kapitbahay",
   "filters": "Mga filter",
   "helpListTitle": "Mga serbisyong makakatulong sa: {hazard}",
   "helpListNote": "Ipinapakita lang ang mga serbisyong nagsasabi kung paano sila makakatulong dito. Nakaayos ayon sa kung gaano sila katugma, kung bukas sila ngayon, layo, at kung kailan huling nakumpirma.",
   "noMatch": "Walang bukas ngayon na libre at hindi humihingi ng ID.",
   "noMatchSuggest": "Kung aalisin mo ang \"{f}\", {n} lugar ang tugma. Ang pinakamalapit ay magbubukas {when}.",
   "applySuggestion": "Alisin ang \"{f}\"",
   "emergency": "Kung may nasaktan ngayon, tumawag sa 911.",
   "openNow": "Bukas ngayon",
   "closedNow": "Sarado ngayon",
   "opensAt": "Magbubukas {t}",
   "distance": "{d} km",
   "resultsForOne": "1 resulta para sa \"{q}\"",
   "catTitle": "{cat}: {n} serbisyo",
   "catTitleOne": "{cat}: 1 serbisyo",
   "changeSearch": "Palitan ang hinanap ko",
   "filtersCount": "Mga filter ({n})",
   "crossQuery": "Tugma kahit magkaiba ang wika. Sumulat ka sa {qlang}; nakasulat ito sa {lang}.",
   "noMatchAny": "Walang tugma sa lahat ng filter na ito.",
   "noMatchSuggestShort": "Kung aalisin mo ang \"{f}\", {n} lugar ang tugma.",
   "removeAll": "Alisin ang lahat ng filter",
   "noneTitle": "Hindi pa namin iyan mahanap",
   "noneBody": "Matutulungan ka ng isang tao sa Hub na hanapin ang tamang serbisyo.",
   "toPerson": "Makipag-usap sa isang tao sa Hub",
   "showMore": "Magpakita ng {n} pa",
   "hoursUnknown": "Hindi alam ang oras",
   "communityOffer": "Alok ng komunidad",
   "inCat": "Paksa: {cat}",
   "helpEmpty": "Walang serbisyong makakatulong dito na tugma sa mga filter na ito."
  },
  "R11": {
   "title": "Hindi pa namin iyan mahanap",
   "body": "Matutulungan ka ng isang tao sa Hub na hanapin ang tamang serbisyo.",
   "person": "Makipag-usap sa community navigator ng Hub",
   "call": "Tumawag sa {phone}",
   "hours": "Bukas {hours}",
   "visit": "O pumunta sa 45 Overlea Boulevard",
   "tryAgain": "Subukan ang ibang salita",
   "categories": "Pumili na lang ng paksa",
   "searched": "Nagtanong ka tungkol sa \"{q}\".",
   "navigatorName": "Samira",
   "navigatorRole": "Community navigator sa Hub",
   "navigatorLine": "Kilala niya ang mga serbisyo sa paligid at matutulungan ka niyang hanapin ang tama, sa telepono o nang personal.",
   "sampleName": "Halimbawang pangalan",
   "openNow": "Bukas ngayon, hanggang {t}",
   "closedNow": "Sarado ngayon. Magbubukas {t}",
   "callConfirm": "Sa totoong CVH, tatawag ito sa {phone}.",
   "directionsConfirm": "Sa totoong CVH, bubuksan nito ang direksyon papunta sa 45 Overlea Boulevard.",
   "directions": "Direksyon",
   "hoursFull": "Lunes hanggang Huwebes 9 am hanggang 8 pm, Biyernes 9 am hanggang 5 pm, Sabado 10 am hanggang 2 pm"
  },
  "R12": {
   "status": "Sa ngayon",
   "openNow": "Bukas ngayon, hanggang {t}",
   "closed": "Sarado ngayon",
   "opens": "Magbubukas {t}",
   "address": "Address at paano pumunta roon",
   "directions": "Direksyon",
   "hours": "Oras",
   "languages": "Mga wikang ginagamit",
   "cost": "Bayad",
   "bring": "Ano ang dapat dalhin",
   "id": "Hihingi ba sila ng ID o status?",
   "access": "Pagiging accessible",
   "contact": "Kontak",
   "call": "Tumawag",
   "email": "Mag-email",
   "website": "Website",
   "unknown": "Hindi alam",
   "languagesUnknown": "Hindi alam. Hindi alam ng Hub kung anong mga wika ang ginagamit dito.",
   "noAddress": "Walang address sa kalye",
   "whereToFind": "Saan ito makikita",
   "confirmedBy": "Kinumpirma ng {org} noong {date}",
   "publicSource": "Mula sa mga pampublikong source. Hindi pa kinukumpirma ng organisasyon.",
   "contributedBy": "Idinagdag ng isang kapitbahay noong {date}, sinuri ng Hub",
   "kind": "Uri ng organisasyon",
   "services": "Mga serbisyo",
   "org": "Sino ang nagpapatakbo",
   "otherServices": "Tingnan kung ano pa ang iniaalok ng {org}",
   "onMap": "Tingnan sa mapa",
   "correct": "May mali? Itama ito",
   "communityOffer": "Alok ng komunidad",
   "communityOfferLine": "Iniaalok ng mga kapitbahay, hindi opisyal na serbisyo.",
   "callConfirm": "Sa totoong CVH, tatawag ito sa {phone}.",
   "directionsConfirm": "Sa totoong CVH, bubuksan nito ang direksyon papunta sa {place}.",
   "illustrative": "Halimbawang detalye para sa prototype",
   "appointment": "Kailangan ko ba ng appointment?",
   "apptYes": "Oo. Tumawag muna para magpa-book.",
   "apptNo": "Hindi. Puwede kang pumunta nang walang appointment.",
   "apptSometimes": "Minsan. Tumawag para malaman.",
   "unknownCall": "Tumawag para magtanong bago pumunta.",
   "unknownAsk": "Magtanong sa Hub bago pumunta.",
   "stepFreeYes": "Walang hagdan.",
   "stepFreeNo": "May hagdan.",
   "idNo": "Hindi.",
   "idYes": "Oo.",
   "emailConfirm": "Sa totoong CVH, magsusulat ito ng email sa {email}.",
   "webConfirm": "Sa totoong CVH, bubuksan nito ang {web}.",
   "noContact": "Walang nakalistang telepono o email.",
   "todayTag": "Ngayon",
   "hoursUnknown": "Hindi alam ang oras",
   "seeAll": "Ipakita ang lahat ng detalye",
   "source": "Saan galing ang impormasyong ito",
   "derivedNote": "Sa ngayon, ang pangalan, lugar at uri lang ng entry na ito ang alam ng Hub.",
   "addedRecently": "kamakailan",
   "notFound": "Hindi mahanap ang lugar na ito.",
   "spaceHours": "Bukas bilang espasyo ngayong araw, {from} hanggang {to}. Hindi alam ang ibang oras.",
   "someUnknown": "May ilang detalyeng hindi pa alam. {ask}"
  },
  "R13": {
   "services": "Mga serbisyo",
   "about": "Tungkol dito",
   "servicesCount": "Mga serbisyo rito: {n}",
   "contact": "Kontak",
   "call": "Tumawag sa {phone}",
   "website": "Website",
   "illustrative": "Halimbawang paglalarawan para sa prototype",
   "webConfirm": "Sa totoong CVH, bubuksan nito ang {web}.",
   "callConfirm": "Sa totoong CVH, tatawag ito sa {phone}.",
   "showAll": "Ipakita ang lahat ng {n} serbisyo",
   "notFound": "Hindi mahanap ang organisasyong ito.",
   "aboutLines": {
    "TNO": "Isang ahensya ng komunidad sa Thorncliffe Park na may mga programa sa pagkain, tulong sa mga bagong dating, trabaho, kabataan at pamilya para sa kapitbahayan.",
    "HUB": "Ang community hub sa 45 Overlea Boulevard, kung saan magkakasama sa iisang gusali ang maraming lokal na serbisyo at grupo.",
    "TPL": "Ang pampublikong aklatan, na may libreng libro, computer, Wi-Fi at mga programa para sa lahat ng edad.",
    "CITY": "Mga community centre at programa ng City of Toronto sa Thorncliffe Park at Flemingdon Park."
   }
  },
  "R14": {
   "title": "Mapa",
   "list": "Listahan",
   "mapView": "Mapa",
   "loading": "Nilo-load ang mapa",
   "unavailable": "Hindi na-load ang mapa. Nasa listahan ang lahat.",
   "showList": "Ipakita ang listahan",
   "noneInView": "Walang nandito. Subukang mag-zoom out.",
   "places": "{n} lugar",
   "place": "1 lugar",
   "add": "Magdagdag ng lugar",
   "rules": "Ang mga patakaran ng espasyong ito",
   "filters": "Ano ang kailangan mo?",
   "disruptionView": "Ipinapakita ang mga lugar na makakatulong sa: {hazard}",
   "legend": "Mga uri ng lugar",
   "newlyAdded": "Bago",
   "tapForHours": "Pindutin ang isang lugar para makita ang oras nito",
   "legendFormal": "Isang serbisyo o pampublikong lugar",
   "legendInformal": "Isang grupo ng komunidad o komunidad ng pananampalataya",
   "legendOffer": "Alok ng komunidad mula sa mga kapitbahay",
   "legendSpace": "Bukas bilang espasyo ngayon",
   "legendCluster": "Magkakalapit na lugar. Pindutin para mag-zoom in.",
   "legendTitle": "Ano ang ibig sabihin ng mga hugis",
   "zoomIn": "Mag-zoom in",
   "zoomOut": "Mag-zoom out",
   "here": "{n} lugar dito",
   "mapLabel": "Mapa ng Thorncliffe Park at Flemingdon Park",
   "allPlaces": "Ipakita ang lahat ng lugar",
   "subAll": "Lahat ng uri ng lugar",
   "subLabel": "Anong uri ng lugar?",
   "spaceFor": "Bukas bilang espasyo ngayon {purpose}",
   "basicList": "Sa mas malaking teksto, ipinapakita ang mga lugar bilang listahan, pinakamalapit muna.",
   "noneMatch": "Walang lugar na tugma sa mga filter na ito.",
   "addShort": "Magdagdag ng lugar",
   "missing": "May kulang o mali?"
  },
  "R15": {
   "title": "Mga lugar na malapit sa iyo",
   "byDistance": "Pinakamalapit muna",
   "empty": "Walang lugar na tugma sa mga filter na ito.",
   "emptyBody": "Mag-alis ng filter para makakita ng higit pa.",
   "add": "Magdagdag ng lugar",
   "count": "{n} lugar",
   "countOne": "1 lugar",
   "more": "Magpakita ng {n} pa",
   "distanceHome": "{d} km",
   "clearAll": "Alisin ang lahat ng filter",
   "missing": "May kulang o mali rito?",
   "suggest": "Kung aalisin mo ang \"{f}\", {n} lugar ang tugma. {d} ang layo ng pinakamalapit.",
   "suggestOne": "Kung aalisin mo ang \"{f}\", 1 lugar ang tugma. {d} ang layo nito.",
   "suggestButton": "Alisin ang \"{f}\""
  },
  "R16": {
   "open": "Tingnan ang detalye",
   "hoursToday": "Ngayon: {hours}",
   "close": "Isara",
   "less": "Bawasan",
   "wrong": "May mali sa lugar na ito?",
   "distance": "{d} km mula sa lugar ng iyong tirahan",
   "contributed": "Idinagdag ng isang kapitbahay"
  },
  "R17": {
   "title": "Magdagdag o magtama ng lugar",
   "add": "Magdagdag ng lugar na kulang",
   "correct": "Itama ang lugar na mukhang mali",
   "fromEntry": "Itama ang lugar na ito",
   "addLine": "Isang bagay na nakakatulong sa mga kapitbahay at wala pa sa mapa. Dalawang maikling hakbang.",
   "correctLine": "Luma na ang oras, ang lugar o isang detalye.",
   "fromEntryLine": "Palitan lang ang mali. Mananatili ang lahat ng iba pa.",
   "lookingAt": "Ang tinitingnan mo",
   "pickTitle": "Aling lugar ang mukhang mali?",
   "pickHint": "Pinakamalapit sa iyo muna. May \"May mali? Itama ito\" din sa pahina ng bawat lugar.",
   "addDifferent": "Magdagdag ng ibang lugar na kulang"
  },
  "R18": {
   "title": "Bago ka magdagdag ng lugar",
   "continue": "Naiintindihan ko, magpatuloy",
   "step": "Hakbang 1 ng 2: ang mga patakaran",
   "readIn": "Basahin ang mga patakaran sa",
   "readInHint": "Nakasulat ang mga patakaran sa bawat wikang iniaalok ng CVH.",
   "after": "Susunod, sasabihin mo sa amin ang tungkol sa lugar. Halos pagpili lang ito, hindi pag-type."
  },
  "R19": {
   "title": "Magdagdag ng lugar",
   "name": "Ano ang pangalan nito?",
   "what": "Ano ang nangyayari doon, sa isang pangungusap",
   "whatHint": "Hanggang 140 character",
   "category": "Anong uri ng tulong ito?",
   "type": "Opisyal na serbisyo ba ito o alok ng komunidad?",
   "official": "Opisyal na serbisyo",
   "offer": "Alok ng komunidad mula sa mga kapitbahay",
   "hours": "Kailan ito bukas?",
   "sameWeekdays": "Pareho tuwing weekday",
   "notSure": "Hindi sigurado",
   "from": "Mula",
   "to": "Hanggang",
   "closedDay": "Sarado",
   "cost": "Magkano ang bayad?",
   "idQ": "Hihingi ba sila ng ID o status?",
   "stepFreeQ": "Makakapasok ka ba nang walang hagdan?",
   "languagesQ": "Anong mga wika ang ginagamit?",
   "location": "Nasaan ito?",
   "submit": "Ipadala sa Hub",
   "optional": "Hindi kailangan",
   "ready": "Handa nang ipadala",
   "saved": "Naka-save sa teleponong ito",
   "step": "Hakbang 2 ng 2: ang lugar",
   "choose": "Pumili ng isa",
   "catNotSure": "Hindi sigurado",
   "offerLine": "Iniaalok ng mga kapitbahay, hindi opisyal na serbisyo. Lumalabas ito sa mapa na may putol-putol na balangkas.",
   "officialLine": "Pinapatakbo ng isang organisasyon, ahensya o ng Lungsod.",
   "whereBtn": "Ipakita kung nasaan ito",
   "whereChange": "Palitan",
   "whereNone": "Hindi pa napipili",
   "costFree": "Libre",
   "costLow": "Mura",
   "costFee": "May bayad",
   "yes": "Oo",
   "no": "Hindi",
   "weekdays": "Lunes hanggang Biyernes",
   "langsHint": "Piliin ang lahat ng naaangkop.",
   "count": "{n} sa 140",
   "missingTitle": "Idagdag ang mga ito, saka ipadala:",
   "resubmitNote": "Ibinalik ito ng Hub. {change}",
   "closedOpt": "Sarado",
   "notSureOpt": "Hindi sigurado",
   "toOpt": "Hanggang",
   "fromOpt": "Nagbubukas",
   "hoursNotSureLine": "Ayos lang iyan. Tatanungin ng Hub ang lugar.",
   "whatPh": "Halimbawa: libreng grocery tuwing Huwebes ng gabi, para sa kahit sino",
   "namePh": "Halimbawa: Food bank tuwing Huwebes"
  },
  "R20": {
   "title": "Nasaan ito?",
   "pin": "Maglagay ng pin sa mapa",
   "building": "Sa loob ng gusali",
   "described": "Ilarawan kung saan sa gusali",
   "describedHint": "Halimbawa: ang community room sa likod ng mosque",
   "landmark": "Malapit sa isang palatandaan",
   "landmarkHint": "Halimbawa: sa tabi ng splash pad sa R.V. Burgess Park",
   "address": "Address sa kalye",
   "noAddress": "Hindi mo kailangan ng address sa kalye.",
   "howTitle": "Paano ito mahahanap ng mga tao?",
   "use": "Gamitin ang lugar na ito",
   "pinHint": "Igalaw ang mapa hanggang nasa lugar na ang pin.",
   "pinNear": "Isang pin sa mapa, malapit sa {place}",
   "nearLandmark": "Malapit sa {place}",
   "buildingChoose": "Pumili ng gusali",
   "landmarkChoose": "Pumili ng palatandaan",
   "landmarkMore": "Anumang iba pa na makakatulong sa mga tao na mahanap ito",
   "addressHint": "Kung alam mo lang.",
   "needOne": "Pumili ng isang paraan sa itaas.",
   "needBuilding": "Piliin muna ang gusali.",
   "needLandmark": "Piliin muna ang palatandaan.",
   "needAddress": "I-type muna ang address.",
   "pinWhere": "Malapit sa {place} ang pin.",
   "mapLabel": "Mapa para sa paglalagay ng pin"
  },
  "R21": {
   "title": "Naipadala sa Hub",
   "general": "Babasahin ito ng isang taga-Hub sa loob ng mga isang linggo. Sasabihin namin sa iyo kapag nasa mapa na ito.",
   "ambassador": "Ambassador ka, kaya ito ang unang susuriin. Kadalasan, nasa mapa na ito sa loob ng isang araw.",
   "lane": "Daan ng pagsusuri: {lane}",
   "laneGeneral": "Pagsusuri ng komunidad",
   "laneAmbassador": "Pagsusuri ng ambassador, mas mabilis",
   "youSent": "Ipinadala mo: {name}",
   "next": "Ano ang susunod na mangyayari",
   "n1": "Babasahin ito ng isang taga-Hub.",
   "n2": "Kung sumusunod ito sa mga patakaran, ilalagay ito sa mapa at sa paghahanap.",
   "n3": "Kung may kailangang baguhin, sasabihin namin kung ano, at puwede mo itong ipadala muli.",
   "n1Amb": "Babasahin ito ng isang taga-Hub nang mas maaga kaysa sa karaniwang pila.",
   "howLong": "Gaano katagal",
   "weekLine": "Mga isang linggo",
   "dayLine": "Kadalasan sa loob ng isang araw",
   "toMap": "Bumalik sa mapa",
   "another": "Magdagdag ng isa pang lugar",
   "protoLabel": "Para sa prototype lang",
   "protoDecline": "Tingnan ang lugar na ibinalik ng Hub",
   "protoAccepted": "Tingnan sa mapa ang lugar na idinagdag ng isang kapitbahay"
  },
  "R22": {
   "title": "Itama ang lugar na ito",
   "changeOne": "Palitan ang mali. Mananatili ang lahat ng iba pa.",
   "submit": "Ipadala ang pagtatama",
   "sent": "Salamat. Susuriin ng Hub ang pagbabago.",
   "change": "Palitan",
   "changedTag": "Binago",
   "was": "Dati: {v}",
   "undo": "Ibalik",
   "nothingYet": "Magpalit ng kahit isang bagay, saka ipadala.",
   "doneEditing": "Tapos na",
   "onlyThis": "Ang binago mo lang ang ipapadala. Susuriin ito ng Hub bago i-update ang lugar.",
   "toPlace": "Bumalik sa lugar",
   "toMap": "Bumalik sa mapa",
   "sentTitle": "Naipadala ang pagtatama",
   "whatChanged": "Ang binago mo",
   "whereLabel": "Nasaan ito",
   "namePlace": "Pangalan"
  },
  "R23": {
   "title": "Hindi pa naidagdag ang lugar mo",
   "reason": "Bakit",
   "whatToChange": "Ano ang babaguhin",
   "resubmit": "Baguhin ito at ipadala muli",
   "kept": "Naka-save ang lahat ng isinulat mo.",
   "sentAgo": "Ipinadala mo ito {t}.",
   "youWrote": "Ang isinulat mo",
   "whereNone": "Walang ibinigay na lugar",
   "toMap": "Bumalik sa mapa",
   "reasons": {
    "advert": {
     "why": "May ibinebenta ito o humihingi ng pera. Hindi palengke ang CVH.",
     "change": "Kung may libreng bahagi na puwedeng gamitin ng kahit sino, iyon lang ang ilarawan. Huwag isama ang presyo at bayad."
    },
    "noLocation": {
     "why": "Hindi namin malaman kung nasaan ito.",
     "change": "Magdagdag ng gusali, malapit na palatandaan o pin sa mapa. Hindi mo kailangan ng address sa kalye."
    },
    "duplicate": {
     "why": "Nasa mapa na ang lugar na ito.",
     "change": "Kung may mali tungkol dito, buksan ito at piliin ang \"Itama ito\"."
    },
    "unclear": {
     "why": "Hindi namin malaman kung anong lugar ito o ano ang nangyayari doon.",
     "change": "Ibigay ang pangalan nito at sabihin sa isang pangungusap kung ano ang makukuha ng mga tao doon."
    },
    "outOfArea": {
     "why": "Nasa labas ito ng Thorncliffe Park at Flemingdon Park.",
     "change": "Ang ipinapakita lang ng CVH ay mga lugar na nasa loob o malapit sa dalawang kapitbahayang ito."
    },
    "notCommunity": {
     "why": "Hindi ito bukas sa lahat ng tao sa kapitbahayan.",
     "change": "Ipadala ito muli kung puwede itong gamitin ng kahit sino mula sa kapitbahayan."
    }
   }
  },
  "R24": {
   "title": "Maging handa",
   "lead": "Ano ang gagawin bago, habang at pagkatapos ng anim na uri ng aberya na nangyayari dito.",
   "numbers": "Mga numerong maaaring kailanganin ko",
   "headsUp": "Paalala bago ang bawat season",
   "checkin": "Humiling ng pangungumusta tuwing may matinding init at pagkawala ng kuryente",
   "readTime": "{n} minutong babasahin",
   "guides": "Mga gabay: ano ang gagawin bago, habang at pagkatapos",
   "more": "Iba pang paraan para maging handa",
   "checkinLine": "Kukumustahin ka ng ambassador ng palapag mo. Hindi ito pang-emergency na serbisyo.",
   "numbersLine": "911, 211, 311, Toronto Hydro at ang Hub",
   "headsUpLine": "Sa CVH lang, hindi kailanman sa text message",
   "none": "Hindi ma-load ang mga gabay ngayon. Kung may nasa panganib, tumawag sa 911."
  },
  "R25": {
   "stagesNav": "Pumunta sa",
   "aiLabel": "Isinulat ng AI para sa prototype. Susuriin ito ng mga tao bago ilunsad ang CVH.",
   "kit": "Tugma ang gabay na ito sa naka-print na Local Preparedness Kit.",
   "numbers": "Mga numerong maaaring kailanganin ko",
   "services": "Mga serbisyong makakatulong",
   "spaces": "Mga lugar na bukas para sa {purpose}",
   "forYou": "Para sa iyo muna",
   "fullGuide": "Ang buong gabay",
   "next": "Susunod: {stage}",
   "stageNow": "Binabasa mo: {stage}",
   "unavailable": "Wala pa ang gabay na ito sa {lang}.",
   "guideWord": "Gabay",
   "readTime": "{n} minutong babasahin",
   "helpTitle": "Tulong para dito",
   "tailoredLink": "Iniangkop sa mga pinili mo",
   "allSteps": "Ipakita ang lahat ng {n} hakbang",
   "purposeWords": {
    "cooling": "pagpapalamig",
    "cleanAir": "malinis na hangin",
    "charging": "pag-charge"
   },
   "endLine": "Iyan na ang huling bahagi ng gabay na ito. Kung kailangan mo pa ng tulong:",
   "numbersLine": "911, 211, 311, Toronto Hydro at ang Hub",
   "openedDuring": "Binuksan sa \"Habang\" dahil nangyayari ito ngayon."
  },
  "R26": {
   "title": "Saang mga grupo ka kabilang?",
   "lead": "Piliin ang anumang angkop sa iyo. Dito nakabatay ang mga alertong makukuha mo at ang payong makikita mo. Hindi namin kailanman itatanong kung bakit.",
   "skipLine": "Walang mababago sa mga alertong makukuha mo kung lalaktawan mo ito.",
   "helperConfirm": "Tumutulong ako sa isang tao. Pumayag siya sa mga piniling ito.",
   "helperNote": "Pakitanong muna siya.",
   "step": "Hakbang 1 ng 2",
   "checkinNext": "Susunod, pipiliin mo ang iyong gusali at palapag, at kung paano mo gustong kumustahin ka.",
   "helperNeeded": "Pakitanong muna siya. Lagyan ng tsek ang kahon kapag pumayag na siya, o laktawan ang tanong na ito.",
   "save": "I-save",
   "saved": "Na-save. Epektibo na ito ngayon.",
   "choose": "Piliin ang anumang angkop sa iyo",
   "helping": "Tumutulong sa isang tao rito?"
  },
  "R27": {
   "title": "Mga filter",
   "apply": "Ipakita ang {n} resulta",
   "clear": "Alisin lahat",
   "lead": "Sagutin lang ang mga tanong na mahalaga sa iyo. Mananatiling bukas ang lahat ng iba pa.",
   "openNowOnly": "Mga lugar lang na bukas ngayon",
   "anyLang": "Anumang wika",
   "langHint": "Ipinapakita ang mga lugar kung saan may nagsasalita nito. Hindi kasama ang mga lugar na hindi pa nagsasabi sa amin.",
   "noIdHint": "Ipinapakita lang ang mga lugar na nagsabi sa Hub na hindi sila hihingi ng ID, papeles o immigration status para matulungan ka. Hindi kasama ang mga lugar na hindi pa nagsasabi sa amin, para hindi ka matanong pagpasok mo.",
   "private": "Nananatili sa teleponong ito ang mga sagot mo. Hindi ito sine-save o ipinapadala kaninuman.",
   "fromChoices": "Mula sa mga pinili mo",
   "cancel": "Bumalik nang walang binago",
   "applyOne": "Ipakita ang 1 resulta",
   "moreQuestions": "Iba pang tanong ({n})",
   "applyNone": "Ilapat (wala pang tugma)"
  },
  "R28": {
   "title": "Ano ang ibig sabihin ng \"beripikado\"",
   "body": "Ang ibig sabihin ng beripikado ay sinuri ng isang taga-Hub, o ng partner na organisasyon na katrabaho ng Hub, ang alertong ito kasama ang mga tao sa mismong lugar bago ito ipinadala.",
   "who": "Beripikado ng {org} ang alertong ito {t}.",
   "notYet": "Ang ibig sabihin ng hindi pa beripikado ay galing ang alerto sa isang ambassador ng gusali, na kadalasang unang nakakaalam. Susuriin ito ng Hub sa lalong madaling panahon.",
   "official": "Ang mga opisyal na alerto ay galing sa {source} at ipinapasa nang hindi binabago ang mga salita.",
   "notFalse": "Hindi ibig sabihin ng hindi pa beripikado na mali ito.",
   "thisAlert": "Ang alertong ito",
   "ambFirst": "Unang ipinost ito {t} ng isang ambassador ng gusali sa {building}.",
   "ambPosted": "Ipinost ito {t} ng isang ambassador ng gusali sa {building}.",
   "notYetAct": "Puwede ka nang kumilos ayon dito ngayon. Kapag nasuri na ito ng Hub, \"Beripikado ng Hub\" na ang makikita mo.",
   "correctedLine": "Itinama ito {t}. Ipinapakita ng alerto kung ano ang nagbago, at mababasa pa rin ang naunang pagkakasulat.",
   "officialAdds": "Hindi kailanman binabago ng Hub ang mga salita ng opisyal na alerto. Puwede nitong idagdag kung ano ang nangyayari sa iyong gusali sa sarili nitong alerto ng komunidad.",
   "legendTitle": "Ang mga salitang makikita mo sa mga alerto",
   "thisOne": "Ang alertong ito",
   "legendVerified": "Sinuri ito ng isang taga-Hub o ng partner bago ipinadala.",
   "legendUnverified": "Ipinost ng isang ambassador ng gusali. Hindi pa ito nasusuri ng Hub.",
   "legendOfficial": "Galing sa source ng gobyerno, ipinasa nang salita por salita.",
   "backToAlert": "Bumalik sa alerto"
  },
  "R29": {
   "title": "Ibahagi ang alertong ito",
   "preview": "Ito ang makukuha ng mga kapitbahay mo",
   "everyone": "Ito ang bersyong nakukuha ng lahat. Walang ibinabahaging iniangkop para sa iyo.",
   "notRecorded": "Hindi itinatala ng CVH kung sino ang nagbabahagi ng alerto o kung kanino mo ito ipinapadala.",
   "send": "Ibahagi",
   "handed": "Dito magbubukas ang mga opsyon sa pagbabahagi ng iyong telepono.",
   "lead": "Makukuha ng mga kapitbahay mo ang alerto gaya ng pagkakasulat ng Hub, kasama kung saan ito galing at link sa pinakabagong bersyon.",
   "postedAt": "Ipinost {t}",
   "updatedAt": "Na-update {t}",
   "todayAt": "ngayong araw nang {time}",
   "dayAt": "{day} nang {time}",
   "linkLine": "Pinakabagong update at anumang pagtatama: {url}",
   "sendLine": "Itatanong ng iyong telepono kung anong app ang gagamitin sa pagpapadala.",
   "placeMore": "at {n} pa"
  },
  "R30": {
   "deviceLabel": "Ang alerto sa isang WhatsApp group",
   "group": "Mga kapitbahay sa Palapag 4",
   "openedLater": "Binuksan pagkatapos: ipinapakita nito ang pinakabagong update at isang pagtatama.",
   "groupBuilding": "Mga kapitbahay sa {building}",
   "members": "{name}, Maria, ikaw at 9 pa",
   "membersOut": "Maria, Farhan at 10 pa",
   "today": "Ngayong araw",
   "forwarded": "Ipinasa",
   "you": "Ikaw",
   "askLine": "May iba pa bang nawalan ng kuryente?",
   "askLineOther": "May nakakaalam ba kung ano ang nangyayari sa elevator?",
   "proto": "Prototype",
   "backToApp": "Bumalik sa app",
   "removeLink": "Alisin ang link",
   "restoreLink": "Ibalik ang link",
   "openLater": "Buksan ang link, makalipas ang ilang oras",
   "senderLang": "Binabasa ni {name} ang CVH sa {lang}. Bubukas ang link sa wika ng nagbukas nito, hindi sa wika ng nagpadala.",
   "linkRemovedNote": "Inalis ang link. Sinasabi pa rin ng mensahe kung ano ang nangyari, saan, kanino galing, kung beripikado ito, kailan, at ano ang gagawin.",
   "sinceSent": "Mula nang ipadala ito ni {name}:",
   "showSince": "Ipakita ang nagbago",
   "noChange": "Binuksan pagkatapos: walang bagong ipinost mula nang ipadala ito.",
   "nowVerified": "Binuksan pagkatapos: nasuri na ng Hub ang post na ito, kaya \"Beripikado ng Hub\" na ang sinasabi ng alerto.",
   "exNote": "Pagsasanay. Kapag ipinasa ang isang mensaheng pampraktis, kasama nito ang salitang pagsasanay bilang unang linya, para walang mag-akalang totoong alerto ito."
  },
  "R31": {
   "title": "Mga numerong maaaring kailanganin ko",
   "emergency": "Emerhensiya",
   "emergencyWhen": "Tumawag sa 911 kung nasa panganib ngayon ang buhay o kaligtasan ng isang tao: sunog, medikal na emergency, o krimeng nangyayari ngayon.",
   "p211": "Tulong sa paghahanap ng mga serbisyo ng komunidad, panlipunan at ng gobyerno",
   "p311": "Mga serbisyo ng City of Toronto at mga problemang hindi emergency",
   "hydro": "Iulat ang pagkawala ng kuryente sa Toronto Hydro",
   "hub": "Makipag-usap sa isang taga-Hub",
   "building": "{role} ng iyong gusali",
   "noBuilding": "Wala pa kaming contact para sa iyong gusali. Matutulungan ka ng ambassador ng palapag mo.",
   "call": "Tumawag",
   "callConfirm": "Sa totoong CVH, tatawag ito sa {number}.",
   "lead": "Nakalista ang bawat numero ayon sa kung para saan ito.",
   "others": "Para sa lahat ng iba pa",
   "call911": "Tumawag sa 911",
   "buildingTitle": "Ang iyong gusali",
   "noBuildingNoAmb": "Wala pa kaming contact para sa iyong gusali. Matutulungan ka ng Hub na makausap ang management ng iyong gusali.",
   "noBuildingChosen": "Piliin ang iyong gusali at ipapakita namin dito ang contact nito kapag mayroon na kami. Hanggang doon, makakatulong ang Hub.",
   "chooseBuilding": "Piliin ang iyong gusali",
   "ambRoute": "Nakatira sila sa iyong gusali at puwede nilang iparating ang mga bagay sa management ng gusali.",
   "hubHours": "Bukas Lunes hanggang Huwebes 9 am hanggang 8 pm, Biyernes 9 am hanggang 5 pm, Sabado 10 am hanggang 2 pm",
   "calling": "Tumawag sa {what}",
   "roles": {
    "superintendent": "superintendente"
   },
   "checked": "Sinuri ng Hub, huling na-update {date}",
   "noOthers": "Hindi ma-load ang ibang numero ngayon. Subukang muli pagkalipas ng ilang minuto."
  },
  "R32": {
   "title": "Paalala bago ang bawat season",
   "lead": "Isang maikling paalala sa CVH bago ang matinding init, usok, at pagkawala ng kuryente sa taglamig, na may isa o dalawang bagay na gagawin.",
   "never": "Sa CVH lang lumalabas ang mga paalala. Hindi kailanman dumarating ang mga ito bilang text message.",
   "on": "Nakabukas ang mga paalala",
   "off": "Nakasara ang mga paalala",
   "season": "Kailan: {season}",
   "switchLabel": "Ipakita sa akin ang paalala bago ang bawat season",
   "what": "Ang makikita mo sana",
   "whatOn": "Ang makikita mo",
   "titles": {
    "heat": "Bago dumating ang mainit na panahon",
    "smoke": "Bago ang season ng usok mula sa wildfire",
    "winter": "Bago ang mga bagyo ng taglamig"
   },
   "readGuide": "Basahin ang gabay sa {hazard}",
   "turnedOn": "Nakabukas ang mga paalala. Makikita mo ang mga ito sa Ngayon, sa CVH lang.",
   "turnedOff": "Nakasara ang mga paalala. Walang ibang nagbago.",
   "offLine": "Nakasara ang mga paalala hanggang buksan mo ang mga ito.",
   "whereLine": "Lumalabas ang mga ito sa screen na Ngayon, ilang linggo bago ang bawat season."
  },
  "R33": {
   "title": "Humiling ng pangungumusta",
   "what": "Kapag may babala ng matinding init o pagkawala ng kuryente sa iyong gusali, kukumustahin ka ng ambassador ng palapag mo, at matutulungan ka niyang maabot ang mga serbisyong kailangan mo.",
   "notEmergency": "Hindi pang-emergency na serbisyo ang pangungumusta.",
   "how": "Paano mo gustong kumustahin ka?",
   "call": "Tawag sa telepono",
   "text": "Text message",
   "knock": "Katok sa pinto",
   "unit": "Numero ng unit",
   "unitWhy": "Hinihingi lang namin ang numero ng iyong unit para malaman ng ambassador mo kung aling pinto ang kakatukin.",
   "building": "Ang iyong gusali at palapag",
   "noAmbassador": "Wala pang ambassador sa palapag {floor}, kaya hindi kami makakapangako ng pangungumusta.",
   "hubInstead": "Tawagan na lang ang Hub sa {phone}. Bukas kami {hours}.",
   "request": "Humiling ng pangungumusta",
   "requested": "Nakahiling na ng pangungumusta",
   "requestedBody": "Kapag may babala ng matinding init o pagkawala ng kuryente sa {building}, kukumustahin ka ng ambassador ng palapag mo sa pamamagitan ng {method}.",
   "withdraw": "Itigil ang pangungumusta",
   "withdrawn": "Itinigil ang pangungumusta. Makakatanggap ka pa rin ng mga alerto.",
   "helper": "Tumutulong ako sa isang tao. Pumayag siyang humiling ng pangungumusta.",
   "whatTitle": "Ano ang pangungumusta",
   "askPlace": "Kailangan namin ang iyong gusali at palapag para malaman kung may ambassador ng palapag na makakakumusta sa iyo.",
   "chooseBuilding": "Piliin ang iyong gusali",
   "chooseFloor": "Piliin ang iyong palapag",
   "floorN": "Palapag {n}",
   "change": "Palitan",
   "placeLine": "{building}, palapag {floor}",
   "covered": "May ambassador para sa palapag {floor}.",
   "callHub": "Tawagan ang Hub",
   "stillAlerts": "Makakatanggap ka pa rin ng bawat alerto para sa iyong gusali.",
   "needMethod": "Piliin kung paano mo gustong kumustahin ka.",
   "needUnit": "Idagdag ang numero ng iyong unit para sa katok, o pumili ng tawag o text.",
   "needHelper": "Pakitanong muna siya. Lagyan ng tsek ang kahon kapag pumayag na siya.",
   "needPlace": "Piliin muna ang iyong gusali at palapag.",
   "howWithdraw": "Puwede mong itigil ang pangungumusta anumang oras: dito, sa Mga pinili ko, o sa pagsagot ng NOCHECK sa isang text mula sa Hub.",
   "changeHow": "Palitan kung paano",
   "again": "Humiling muli ng pangungumusta",
   "unitShown": "Unit {unit}",
   "continue": "Magpatuloy",
   "skip": "Hindi muna ngayon",
   "helping": "Tumutulong sa isang tao rito?"
  },
  "R34": {
   "title": "Ang sinabi ko sa CVH",
   "lead": "Ang pinili mo lang. Palitan o alisin ang anuman dito. Agad na nangyayari ang mga pagbabago.",
   "language": "Wika",
   "building": "Gusali at palapag",
   "basic": "Mas malaking teksto, mas kaunting bagay",
   "groups": "Mga grupo",
   "checkin": "Pangungumusta",
   "headsUp": "Mga paalala bawat season",
   "change": "Palitan",
   "remove": "Alisin",
   "removed": "Inalis na. Epektibo na ito ngayon.",
   "nothing": "Wala ka pang sinasabi sa CVH.",
   "onDevice": "Sa device na ito lang nakatago ang mga piniling ito.",
   "invite": "Para makakuha ng mga alerto para sa iyong gusali at mga grupo sa iyong telepono, mag-set up ng text alert. Isang minuto lang ito at hindi kailangan ng account.",
   "inviteYes": "Mag-set up ng text alert",
   "inviteNo": "Hindi muna ngayon",
   "fromTailored": "Ang payo sa ilalim ng \"Ano ang ibig sabihin nito para sa iyo\" ay galing lang sa mga pinili sa pahinang ito. Kapag pinalitan mo ang mga ito rito, magbabago rin ang payo.",
   "neighbourhoodOnly": "Bawat alerto para sa {nbhd}",
   "floorOf": "{building}, palapag {floor}",
   "on": "Bukas",
   "setByHelper": "Binuksan ng taong tumutulong sa iyo",
   "checkinNone": "Hindi hiniling",
   "checkinAsk": "Humiling ng pangungumusta",
   "checkinBy": "Sa pamamagitan ng {method}",
   "checkinNoAmb": "Wala pang ambassador sa palapag mo. Ang Hub na lang ang makakatulong.",
   "unitLine": "Unit {unit}, para sa katok lang",
   "textAlerts": "Text alert",
   "textOn": "Bukas, sa {phone}",
   "textPending": "Hinihintay ang sagot mong YES sa {phone}",
   "howStop": "Para itigil, sumagot ng STOP sa anumang text mula sa Hub.",
   "removedItem": "Inalis: {item}",
   "tellUs": "Puwede mong sabihin sa CVH:",
   "whereLive": "Kung saan ka nakatira",
   "whichGroups": "Kung saang mga grupo ka kabilang",
   "turnOff": "Isara",
   "changeGroups": "Palitan ang mga grupo",
   "groupsNone": "Walang napili",
   "chooseGroups": "Pumili ng mga grupo",
   "langNote": "Ang wikang ginagamit mo sa pagbasa ng CVH.",
   "removedBuildingOne": "Wala na sa listahan ng mga gusali ang 1 gusaling na-save mo, kaya inalis ito.",
   "removedBuildingMany": "Wala na sa listahan ng mga gusali ang {n} gusaling na-save mo, kaya inalis ang mga ito.",
   "removedFloorOne": "Wala na ang 1 palapag na na-save mo, kaya inalis ito.",
   "removedFloorMany": "Wala na ang {n} palapag na na-save mo, kaya inalis ang mga ito.",
   "removedRest": "Walang nagbago sa lahat ng iba pang pinili mo.",
   "clearAll": "Burahin lahat",
   "clearTitle": "Burahin lahat sa teleponong ito?",
   "clearBody": "Aalisin nito ang iyong wika, mga grupo, gusali at palapag sa teleponong ito. Magsisimula ka ulit sa pagpili ng wika.",
   "clearYes": "Oo, burahin lahat",
   "loading": "Nilo-load ang iyong mga gusali...",
   "listFailed": "Hindi ma-load ang listahan ng mga gusali ngayon. Naka-save pa rin ang mga pinili mo.",
   "buildingByRsn": "Gusali {rsn}",
   "floorsOne": "1 palapag ang napili",
   "floorsMany": "{n} palapag ang napili",
   "buildingsNone": "Walang napili",
   "removeItem": "Alisin: {item}"
  },
  "R35": {
   "title": "Kumuha ng mga alerto para sa iyong gusali",
   "lead": "Piliin kung saan ka nakatira para unang makita ang mga alerto ng iyong gusali. Hindi kailangan ang bawat hakbang.",
   "nbhd": "Kapitbahayan",
   "building": "Gusali",
   "floor": "Palapag",
   "nbhdOnly": "Ang buong kapitbahayan lang",
   "floorLine": "Kapag pumili ka ng palapag, makakakuha ka rin ng mga alerto para lang sa iyong palapag, tulad ng elevator o pagpatay ng tubig.",
   "noUnit": "Hindi namin kailanman hinihingi dito ang numero ng iyong unit.",
   "preselected": "Mula sa iyong abiso",
   "skipLine": "Kung lalaktawan mo, makikita mo pa rin ang bawat alerto para sa iyong kapitbahayan.",
   "finishedTitle": "Ang pinili mo",
   "invite": "Para makakuha ng mga alerto para sa iyong gusali, palapag at mga grupo sa iyong telepono, mag-set up ng text alert. Isang minuto lang ito at hindi kailangan ng account.",
   "inviteYes": "Mag-set up ng text alert",
   "inviteNo": "Hindi muna ngayon",
   "helper": "Tumutulong ako sa isang tao. Pumayag siya sa piniling ito.",
   "step": "Hakbang 2 ng 2",
   "buildingSearch": "Hanapin ang iyong gusali",
   "more": "{n} pa. I-type ang bahagi ng address para mahanap ang sa iyo.",
   "noMatch": "Walang gusaling tugma sa \"{q}\".",
   "change": "Palitan",
   "noFloor": "Walang palapag, gusali lang",
   "floorN": "Palapag {n}",
   "sample": "Halimbawang gusali",
   "nextCheckin": "Susunod: kung paano mo gustong kumustahin ka.",
   "helperNeeded": "Pakitanong muna siya. Lagyan ng tsek ang kahon kapag pumayag na siya, o laktawan ang tanong na ito.",
   "save": "I-save",
   "saved": "Na-save. Epektibo na ito ngayon.",
   "both": "Thorncliffe Park at Flemingdon Park",
   "nothingSummary": "Wala pa. Makikita mo ang bawat alerto para sa Thorncliffe Park at Flemingdon Park.",
   "everyAlert": "Bawat alerto para sa {nbhd}",
   "floorOf": "{building}, palapag {floor}",
   "checkinBy": "Pangungumusta sa pamamagitan ng {method}",
   "changeAll": "Palitan ang pinili mo",
   "toHome": "Pumunta sa Ngayon",
   "manyLine": "Piliin ang sarili mong gusali o ang sa isang kamag-anak. Puwede kang pumili ng kahit ilan.",
   "chosenNone": "Wala pang napiling gusali",
   "chosenOne": "1 gusali ang napili",
   "chosenMany": "{n} gusali ang napili",
   "floorsIn": "Mga palapag sa {building}. Hindi kailangan.",
   "noFloorsListed": "Wala pang nakalistang palapag para sa gusaling ito.",
   "loading": "Nilo-load ang listahan ng mga gusali...",
   "loadFailed": "Hindi ma-load ang listahan ng mga gusali. Tingnan ang iyong koneksyon at subukang muli, o laktawan ang hakbang na ito.",
   "retry": "Subukan muli"
  },
  "A01": {
   "title": "Ang gusali ko",
   "assigned": "Ikaw ang ambassador para sa {building}, mga palapag {floors}.",
   "canPost": "Puwede kang mag-post ng update para sa kahit anong palapag ng {building}.",
   "post": "Mag-post ng update sa gusali",
   "active": "Nangyayari sa iyong gusali",
   "nothing": "Walang aktibong problema sa iyong gusali.",
   "round": "Pag-ikot ng pangungumusta: {n} sa iyong mga palapag",
   "openRound": "Buksan ang pag-ikot ko",
   "role": "Ambassador ng gusali",
   "roundFloors": "Ang iyong pag-ikot: mga palapag {a} hanggang {b}.",
   "offline": "Walang signal. Naka-save sa iyong telepono ang ginagawa mo at ipapadala ito kapag may signal ka na.",
   "noRound": "Walang pag-ikot ng pangungumusta ngayon. Magsisimula ito kapag nagpadala ang Hub ng alerto tungkol sa init o kuryente para sa iyong gusali.",
   "toDo": "{n} pa ang gagawin",
   "tellInPerson": "{n} sambahayan na sasabihan nang personal",
   "practice": "Pampraktis na pag-ikot",
   "myRound": "Ang pag-ikot ko",
   "myPosts": "Ang iyong mga update",
   "postedAgo": "Ipinost {t}",
   "fromHub": "Mula sa Hub",
   "fromAmb": "Mula sa isang ambassador ng gusali",
   "fromOfficial": "Opisyal na alerto",
   "fromPartner": "Mula sa isang partner",
   "verifiedWord": "Beripikado",
   "notVerifiedWord": "Hindi pa beripikado"
  },
  "A02": {
   "title": "Mag-post ng update sa gusali",
   "types": "Ano ang nangyayari? Piliin ang lahat ng naaangkop",
   "floors": "Aling mga palapag?",
   "wholeBuilding": "Buong gusali",
   "range": "Mula palapag {a} hanggang {b}",
   "pick": "Pumili ng mga palapag",
   "photo": "Magdagdag ng litrato",
   "line": "Magdagdag ng isang linya",
   "lineRequired": "Sabihin kung ano ang nangyayari, sa isang linya",
   "optional": "Hindi kailangan",
   "other911": "Kung may nasa panganib, tumawag muna sa 911.",
   "appearsAs": "Lalabas ito bilang: Ambassador ng gusali, {building}",
   "goesNow": "Ipapadala ito ngayon.",
   "waits": "Susuriin muna ito ng Hub bago ipadala.",
   "post": "I-post ang update",
   "notOffered": "Galing sa Hub ang mga alerto tungkol sa init at usok, para sa buong kapitbahayan.",
   "exOutcome": "Praktis: sa Hub lang ito mapupunta. Walang ipinapadala sa mga residente.",
   "exNote": "Pagsasanay: praktis ang post na ito. Sa Hub lang ito mapupunta, hindi kailanman sa mga residente.",
   "typeMore": {
    "fire": "fire alarm o paglikas",
    "water": "o tubero"
   },
   "required": "Kailangan",
   "wholeLine": "Lahat ng {n} palapag",
   "mineLabel": "Mga palapag {a} hanggang {b}",
   "mineLine": "Ang iyong pag-ikot",
   "pickLabel": "Pumili ng mga palapag",
   "pickLine": "Pindutin ang unang palapag, saka ang huli",
   "pickNone": "Wala pang napiling palapag",
   "pickOne": "Palapag {a}",
   "pickRange": "Mga palapag {a} hanggang {b}",
   "floorAria": "Palapag {n}",
   "more": "Magdagdag pa kung gusto mo",
   "photoAdded": "Naidagdag ang litrato (halimbawa)",
   "remove": "Alisin",
   "lineAdded": "Ang iyong linya",
   "ownLine": "O isulat ang sarili mong linya",
   "sampleBn": "Halimbawang linya sa Bengali",
   "sampleTag": "Prototype",
   "mtNote": "Makikita ito ng mga residenteng nagbabasa sa ibang wika na may label na isinalin ng makina.",
   "phrases": ["Nasabihan na ang mga staff ng gusali.", "Mag-ingat sa paggamit ng hagdan.", "Pakikumusta ang mga kapitbahay na maaaring nangangailangan ng tulong."],
   "otherPhrases": ["Hindi nakakandado ang pintuan sa harap.", "Patay ang mga ilaw sa pasilyo.", "Barado ang garbage chute."],
   "otherFirst": "Tumawag muna sa 911 kung may nasa panganib. Saka sabihin dito kung ano ang nangyayari.",
   "someWait": "Laging naghihintay sa Hub ang isa sa mga uring ito, kaya maghihintay rin ang update na ito.",
   "offlineBar": "Walang signal ngayon. Naka-save ito sa iyong telepono at ipapadala kapag may signal ka na.",
   "postTo": "I-post ang update: {floors}",
   "wholeWord": "buong gusali",
   "errTypes": "Piliin kung ano ang nangyayari.",
   "errFloors": "Pindutin ang mga palapag, o piliin ang Buong gusali.",
   "errLine": "Kailangan ng Iba pa ng isang linya: sabihin kung ano ang nangyayari."
  },
  "A03": {
   "liveTitle": "Naipost",
   "live": "Live na ngayon sa bawat channel, kasama ang mga text message. Lalabas itong \"Hindi pa beripikado\" hanggang masuri ito ng Hub.",
   "waitingTitle": "Naghihintay sa Hub",
   "waiting": "Sinusuri na ito ng Hub ngayon. Ipapadala ito sa sandaling maaprubahan.",
   "approved": "Naaprubahan at naipadala {t}.",
   "declined": "Hindi ito ipinadala ng Hub. Dahilan: {reason}",
   "verified": "Beripikado na ng Hub ang iyong update {t}.",
   "corrected": "Itinama ng Hub ang iyong update. Dahilan: {reason}",
   "withdrawn": "Binawi ng Hub ang iyong update. Dahilan: {reason}",
   "slow": "Ipinapadala pa. Mahina ang signal dito. Matatapos ito kapag lumakas ang iyong signal.",
   "where": "Ipinadala sa: {channels}",
   "when": "Ipinost {t}",
   "states": {
    "queued": "Naka-save sa iyong telepono. Ipapadala kapag may signal ka na",
    "live": "Live. Hindi pa beripikado",
    "waiting": "Naghihintay sa Hub",
    "approved": "Naaprubahan at naipadala",
    "declined": "Hindi ipinadala ng Hub",
    "verified": "Beripikado ng Hub",
    "withdrawn": "Binawi ng Hub",
    "corrected": "Itinama ng Hub",
    "exercise": "Pagsasanay. Hindi ipinadala sa mga residente"
   },
   "queuedTitle": "Naka-save sa iyong telepono",
   "queued": "Naka-save sa iyong telepono. Ipapadala ito kapag may signal ka na.",
   "writtenAt": "Isinulat {t}. Wala ka nang ibang kailangang gawin.",
   "approvedTitle": "Naaprubahan at naipadala",
   "declinedTitle": "Hindi naipadala",
   "verifiedTitle": "Beripikado ng Hub",
   "correctedTitle": "Itinama ng Hub",
   "withdrawnTitle": "Binawi ng Hub",
   "exerciseTitle": "Na-save ang pampraktis na post",
   "exercise": "Pagsasanay ito. Walang ipinadala sa mga residente.",
   "approvedLine": "Lumalabas na itong beripikado ng Hub.",
   "verifiedLine": "Nakikita na ng mga residente ang \"Beripikado ng Hub\" sa iyong update. Walang ipinadalang pangalawang mensahe.",
   "correctedLine": "Binago ng Hub ang iyong update: {text}",
   "correctedWhen": "Itinama {t}.",
   "yourUpdate": "Ang iyong update",
   "floorsAll": "Buong gusali",
   "floorsOne": "Palapag {a}",
   "floorsRange": "Mga palapag {a} hanggang {b}",
   "photoYes": "May litrato",
   "whereWhen": "Ano ang napunta saan, at kailan",
   "chText": "Mga text message",
   "chWeb": "Ang CVH app at website",
   "sentTo": "Ipinadala {t} sa mga residente ng {building}, {floors}",
   "liveOn": "Ipinapakita mula {t} para sa {building}, {floors}",
   "notYet": "Hindi pa naipapadala",
   "notSent": "Hindi naipadala",
   "takenDown": "Tinanggal {t}",
   "waitAfter": "Ipapadala sa bawat channel sa sandaling aprubahan ito ng Hub.",
   "howSeen": "Paano ito nakikita ng mga residente",
   "willSeen": "Kapag naaprubahan, makikita ng mga residente",
   "seeIt": "Tingnan ito gaya ng nakikita ng mga residente",
   "toHome": "Bumalik sa gusali ko",
   "another": "Mag-post ng isa pang update",
   "notFound": "Hindi mahanap ang update na ito sa teleponong ito.",
   "reasonLabel": "Dahilan: {reason}"
  },
  "A04": {
   "title": "Ang pag-ikot ko",
   "checkins": "Mga hiniling na pangungumusta sa iyong mga palapag",
   "unreachable": "Mga sambahayan sa iyong mga palapag na hindi maabot sa telepono o app",
   "carry": "Alertong sasabihin sa kanila",
   "floorDoor": "Palapag {floor}, pinto {door}",
   "floorPhone": "Palapag {floor}, {method} {phone}",
   "method": {
    "call": "tawag",
    "text": "i-text",
    "knock": "katok"
   },
   "done": "Tapos na",
   "notReached": "Hindi naabot",
   "needsHelp": "Nangangailangan ng tulong",
   "connected": "Naikonekta sa isang serbisyo",
   "passed": "Ipinasa sa Hub",
   "offline": "Walang signal. Naka-save ang mga pinindot mo at ipapadala kapag may signal ka na.",
   "deleted": "Kapag natapos ang aberyang ito, buburahin ang mga talang ito. Ang bilang lang ang itatago.",
   "addDoor": "Magdagdag ng pinto sa hiling ng residente",
   "addConfirm": "Pumayag ang residente na maidagdag, dito sa screen ko.",
   "addedByRequest": "Idinagdag sa hiling ng residente",
   "addNote": "Buburahin ang pintong ito kapag natapos ang aberya. Para makumusta sa bawat pagkakataon, puwede nila itong piliin sa CVH.",
   "exercise": "Pampraktis na pag-ikot ito.",
   "forAlert": "Para sa: {headline}",
   "practiceFor": "Pampraktis na pag-ikot. Walang umaabot sa mga residente.",
   "floorN": "Palapag {n}",
   "doorN": "Pinto {door}",
   "methodWord": {
    "call": "Tawag",
    "text": "I-text",
    "knock": "Katok"
   },
   "tally": "{todo} gagawin · {done} tapos · {nr} hindi naabot · {help} nangangailangan ng tulong",
   "connectedCat": "Naikonekta sa isang serbisyo: {category}",
   "queued": "Naka-save sa iyong telepono. Ipapadala kapag may signal ka na.",
   "taken": "Kinuha ng Hub",
   "change": "Palitan",
   "connect": "Ikonekta sa isang serbisyo",
   "tellInPerson": "Kumatok at sabihin sa kanila ang alertong ito",
   "whereLabel": "Saan",
   "doLabel": "Ano ang gagawin ngayon",
   "noRound": "Walang pag-ikot ng pangungumusta ngayon. Kapag nagpadala ang Hub ng alerto tungkol sa init o kuryente para sa iyong gusali, lalabas dito ang mga pangungumusta sa iyong mga palapag.",
   "addTitle": "Magdagdag ng pinto",
   "addFloor": "Palapag",
   "addDoorLabel": "Numero ng pinto",
   "addMethod": "Paano nila gustong maabot",
   "addPhone": "Numero ng telepono",
   "addBtn": "Idagdag sa pag-ikot ko",
   "cancel": "Kanselahin",
   "added": "Naidagdag sa iyong pag-ikot.",
   "errDoor": "Idagdag ang numero ng pinto.",
   "errPhone": "Magdagdag ng numero ng telepono para sa tawag o text.",
   "errMethod": "Piliin kung paano nila gustong maabot.",
   "errAgree": "Tanungin muna sila. Lagyan ng tsek ang kahon kapag pumayag na sila, dito sa iyong screen.",
   "practiceNoAlert": "Praktis: walang alertong dadalhin."
  },
  "A05": {
   "title": "Ikonekta sa isang serbisyo",
   "urgent": "Anumang apurahan o mapanganib: tumawag sa 911 ngayon.",
   "list": "Bukas ngayon, sa wika ng residente",
   "choose": "Sabihin ito sa kanila",
   "chosen": "Sabihin sa residente kung paano maabot ang {service}, o isulat ito para sa kanila.",
   "neverText": "Hindi namin ito ipinapadala sa text message.",
   "recorded": "Naitala bilang: {category}. Wala nang ibang sine-save.",
   "exNote": "Pagsasanay: praktis ito. Sa tala ng drill lang itatago ang pipiliin mo.",
   "forWho": "Para kay: {who}",
   "theirLang": "Ang kanilang wika",
   "all": "Lahat",
   "openNowIn": "Bukas ngayon sa {lang}, o hindi alam ang oras",
   "hoursUnknown": "Hindi alam ang oras. Tumawag muna.",
   "speaks": "Nagsasalita ng {lang}",
   "none": "Walang bukas ngayon sa {lang} para dito. Bukas ngayon ang mga ito sa ibang wika:",
   "noneAtAll": "Walang bukas dito ngayon. Makakatulong ang Hub: {phone}.",
   "tellTitle": "Sabihin sa kanila",
   "sayOr": "Sabihin ito sa kanila, o isulat ito para sa kanila. Puwede mo ring ipakita sa kanila ang screen na ito.",
   "again": "Pumili ng ibang serbisyo",
   "backRound": "Bumalik sa pag-ikot ko",
   "already": "Naikonekta na sa isang serbisyo: {category}.",
   "queued": "Naka-save sa iyong telepono. Mapupunta ito sa Hub kapag may signal ka na.",
   "callLabel": "Telepono",
   "whereLabel": "Saan",
   "hoursLabel": "Ngayon"
  },
  "building": {
   "registerTitle": "Mula sa talaan ng Lungsod",
   "updated": "Huling na-update {date}",
   "registerLead": "May talaan ang City of Toronto ng mga apartment building. Galing doon ang mga impormasyong ito.",
   "checking": "Sinusuri ng Hub ang mga detalye ng gusaling ito. Maaaring magbago ang nakikita mo rito.",
   "facts": {
    "storeys": "Bilang ng palapag",
    "elevators": "Mga elevator",
    "emergencyPower": "Pang-emergency na kuryente",
    "coolingRoom": "Silid na pampalamig",
    "airConditioning": "Aircon",
    "barrierFree": "Pasukang walang hadlang"
   },
   "airNone": "Wala",
   "airIndividual": "Sa bawat unit",
   "roles": {
    "superintendent": "Superintendente",
    "buildingManagement": "Management ng gusali",
    "propertyOffice": "Opisina ng property"
   },
   "contactTitle": "Contact ng gusali",
   "providedByHub": "Ibinigay ng Hub, huling na-update {date}"
  },
  "guides": {
   "reviewed": "Sinuri ng Hub, huling na-update {date}"
  }
 });
  /* AD-11 pilot change (2026-10-03): the label of a directory description a model translated and no person has reviewed. AI-generated (Claude), not yet checked by native readers. */
  m(t, { "x04": { "unreviewed": "Isinalin ng makina; hindi pa nasuri ng tao" } });
  /* The resident map (S02.07): the "map" strings. AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "map": {
    "lead": "Mga serbisyo, organisasyon at gusali ng apartment sa Thorncliffe Park at Flemingdon Park. I-tap ang isang pin para makita kung ano ito.",
    "service": "Serbisyo o organisasyon",
    "building": "Gusali ng apartment",
    "pinName": "{name}: {kind}",
    "noSignal": "Hindi magagamit ang mapa nang walang signal",
    "noSignalBody": "Nasa listahan ang lahat ng lugar na nasa mapa.",
    "notSaved": "Hindi naka-save sa iyong telepono ang bahaging ito ng mapa",
    "notSavedBody": "Nananatili sa iyong telepono ang mga bahagi ng mapa na tiningnan mo nang may signal. Gumagana pa rin ang mga pin at ang listahan.",
    "listTitle": "Mga lugar sa bahaging ito ng mapa",
    "listLead": "Ang parehong mga lugar na ipinapakita ng mapa. Igalaw o i-zoom ang mapa para baguhin ang listahang ito.",
    "listEmpty": "Walang nandito sa bahaging ito ng mapa. Igalaw o i-zoom ang mapa, o ipakita ang buong lugar.",
    "wholeArea": "Ipakita ang buong lugar",
    "buildings": "Mga gusali ng apartment",
    "buildingsCount": "{n} gusali",
    "buildingsCountOne": "1 gusali",
    "filtered": "Ipinapakita lang ang mga lugar na tugma sa mga filter na pinili mo sa direktoryo."
   }
  });
  /* S07.02: the web sign-up for text alerts and the confirmation text. YES, STOP, START and CVH stay in English. AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "signup": {
    "termsAgree": "Nabasa ko ang pahina ng mga tuntunin at privacy, at pumapayag ako.",
    "termsLink": "Basahin ang pahina ng mga tuntunin at privacy",
    "termsVersion": "Bersyon ng mga tuntunin {version}",
    "age": "Ako ay 16 taong gulang o higit pa, o tinutulungan ako ng magulang o tagapag-alaga.",
    "missingTerms": "ang pagpayag ninyo sa mga tuntunin",
    "missingAge": "ang pahayag tungkol sa edad",
    "sending": "Ipinapadala...",
    "onItsWay": "Kung nakakatanggap ng text ang numerong ito, may mensaheng papunta na.",
    "expect": "Sumagot ng YES sa mensaheng iyon sa loob ng 48 oras para magsimulang makatanggap ng alerto. Hangga't hindi kayo sumasagot ng YES, wala kayong matatanggap na alerto sa text.",
    "howChange": "Para palitan ang inyong gusali, palapag o wika sa ibang pagkakataon, sumagot ng 1 o 2 sa anumang text mula sa Hub.",
    "startHelp": "Walang text sa loob ng 5 minuto? Mag-text ng START sa {number}, pagkatapos ay mag-sign up ulit.",
    "startHelpNoNumber": "Walang text sa loob ng 5 minuto? Mag-text ng START sa numerong pinanggagalingan ng aming mga text, pagkatapos ay mag-sign up ulit.",
    "error": {
     "invalid_request": "May bahagi ng form na hindi mabasa. I-reload ang pahina at subukan ulit.",
     "phone_not_canadian": "Gumamit ng numero ng telepono sa Canada na may 10 digit, tulad ng 416 555 0123.",
     "neighbourhood_missing": "Piliin ang inyong kapitbahayan.",
     "terms_not_agreed": "Para mag-sign up, pumayag sa mga tuntunin.",
     "age_not_confirmed": "Para mag-sign up, kumpirmahin ang pahayag tungkol sa edad.",
     "terms_changed": "Nagbago ang mga tuntunin habang bukas ang pahinang ito. Basahin ulit ang mga ito, pagkatapos ay pumayag.",
     "place_unknown": "Wala na sa listahan ang isa sa inyong mga gusali o palapag. Tingnan ang inyong mga gusali at subukan ulit.",
     "rate_limited": "Masyadong maraming sign-up ang nanggaling sa koneksyong ito. Subukan ulit pagkalipas ng isang oras.",
     "signup_unavailable": "Hindi magagamit ngayon ang pag-sign up para sa text. Subukan ulit mamaya.",
     "network": "Hindi namin maabot ang CVH. Tingnan ang inyong koneksyon at subukan ulit."
    }
   }
  });
  m(t, {"smsTexts": {"confirmation": "Mga alerto ng CVH mula sa Thorncliffe Park Community Hub: sumagot ng YES para kumpirmahin. Nag-iiba ang dalas ng mensahe. Maaaring may singil sa mensahe at data. HELP para sa tulong, STOP para tumigil."}});
  /* S07.04: the welcome, the replies of the inbound router and the words for yes (YES, STOP and CVH stay in English). */
  m(t, {"smsTexts": {"welcome": "Naka-sign up ka na sa CVH alert. Sinusuri ng staff ng Hub ang bawat mensahe, kaya maaaring hindi maipadala ang alert sa gabi. Sumagot ng 1 para palitan ang iyong gusali o palapag, 2 para palitan ang iyong wika, 3 para bawiin ang hiling na pangungumusta, 0 para itigil at burahin ang iyong subscription. Sumagot ng STOP para itigil.", "alreadySignedUp": "Naka-sign up ka na sa CVH alert.", "deletePrompt": "Sumagot ulit ng 0 sa loob ng 10 minuto para burahin ang subscription. Wala ka nang matatanggap na text.", "signupInfo": "Para makatanggap ng CVH alert sa text, mag-sign up dito: {link} Sumagot ng STOP para itigil."}, "smsKeywords": {"yes": "oo, opo, oho"}});
  /* S07.05: the numbered text menus and their replies (see the English file for what each is and the one-text rule; 0, 1, 8, 9, 10, 5
     and {placeholders} stay as written). AI-generated (Claude), not yet checked by native readers. */
  m(t, {"smsTexts": {"menuStreet": "Kalye:", "menuBuilding": "Gusali:", "menuFloor": "Palapag:", "menuWholeBuilding": "Buong gusali", "menuLanguage": "Wika:", "menuNav": "0 Balik 9 Hub", "menuNavMore": "0 Balik 8 Iba pa 9 Hub", "menuWarn": "Papalitan nito ang iyong {n} naka-save na gusali. 1 Ituloy, 0 Bumalik", "menuHub": "Tawagan ang Hub sa {hub}.", "menuClosed": "Sarado na ang menu. Walang binago.", "menuReset": "Nagsara ang iyong menu dahil walang sagot sa loob ng 10 minuto. Walang binago.", "menuLimit": "Nagamit mo na ang 5 menu ngayong araw. Subukan bukas, o tawagan ang Hub sa {hub}.", "menuLimitLink": "Nagamit mo na ang 5 menu ngayong araw. Sumagot ng 1 para sa link para magbago online, o tawagan ang Hub sa {hub}.", "buildingSaved": "Na-save. Ang iyong gusali ay {building}, palapag {floor}.", "buildingSavedWhole": "Na-save. Ang iyong gusali ay {building}.", "languageSaved": "Na-save. Tagalog na ang iyong mga text.", "noCheckinRequest": "Wala kang hiling na pangungumusta.", "checkinWithdrawn": "Nabawi na ang iyong hiling na pangungumusta."}});
  /* S07.06: the one-time web link's texts and its page (see the English file for what each is; menuClosedLink must fit one text; 0, 1, 30
     and {placeholders} stay as written; the error lines other than edit_unavailable are the sign-up's own). AI-generated (Claude), not yet
     checked by native readers. */
  m(t, {"smsTexts":{"menuClosedLink":"Sarado na ang menu. Walang binago. Sumagot ng 1 para sa link para magbago online.","editLink":"Baguhin o burahin ang iyong CVH text alert dito: {link} Gumagana ang link nang isang beses, sa loob ng 30 minuto.","editSaved":"Binago sa web page ang iyong mga pinili sa CVH alert. Hindi ikaw? Tawagan ang Hub sa {hub}."},"subscriptionEdit":{"title":"Baguhin ang iyong text alert","loading":"Binubuksan ang iyong mga pinili...","forNumber":"Para sa numero ng telepono na nagtatapos sa {digits}.","lead":"Baguhin ang anumang pinili, saka i-save. Para itigil ang lahat ng text, burahin ang iyong subscription sa dulo ng page na ito.","topicsTitle":"Mga paksang ayaw mong ma-text","topicsLead":"Lagyan ng tsek ang isang paksa para itigil ang mga alert nito. Laging dumarating ang mga alert tungkol sa sunog o paglikas.","save":"I-save ang mga binago ko","saving":"Sine-save...","savedTitle":"Na-save ang iyong mga binago","savedBody":"May darating na text para kumpirmahin ito. Nagamit na ang link na ito: para magbago ng iba pa, humingi ng bagong link sa text.","deleteTitle":"Burahin ang subscription ko","deleteLead":"Wala ka nang matatanggap na text mula sa CVH, at mabubura ang lahat ng itinatago tungkol sa iyong numero. Hindi na ito maibabalik.","deleteSure":"Burahin na ang iyong subscription? Wala ka nang matatanggap na text mula sa CVH.","deleteYes":"Oo, burahin","deleteNo":"Hindi, panatilihin","deleting":"Binubura...","deletedTitle":"Nabura na ang iyong subscription","deletedBody":"Wala ka nang matatanggap na text mula sa CVH, at walang itinatago tungkol sa iyong numero. Walang text na ipapadala para kumpirmahin ito.","signUpAgain":"Mag-sign up ulit","expiredTitle":"Nag-expire na ang link na ito","expiredBody":"Gumagana ang link nang isang beses, sa loob ng 30 minuto mula nang ipadala.","expiredHow":"Para makakuha ng bagong link sa text, sumagot ng 1 sa isang text mula sa CVH. Kung menu ang sagot, magpadala ng 0 para isara ito. Kapag nag-alok ng link ang sagot, magpadala ng 1.","callHub":"O tawagan ang Hub sa {hub}.","error":{"invalid_request":"May bahagi ng form na hindi mabasa. I-reload ang pahina at subukan ulit.","neighbourhood_missing":"Piliin ang inyong kapitbahayan.","place_unknown":"Wala na sa listahan ang isa sa inyong mga gusali o palapag. Tingnan ang inyong mga gusali at subukan ulit.","edit_unavailable":"Hindi pa puwedeng gumawa ng pagbabago ngayon. Subukan ulit mamaya.","network":"Hindi namin maabot ang CVH. Tingnan ang inyong koneksyon at subukan ulit."}}});
  /* S08.05: the check-in request's texts and wording (see the English file for what each is; checkinMoved and checkinUncoveredNow must fit one
     text; 1, YES, CVH, Hub and {placeholders} stay as written). AI-generated (Claude), not yet checked by native readers. */
  m(t, {"smsTexts":{"checkinMoved":"Nabawi ang iyong hiling na pangungumusta dahil nagbago ang palapag mo. Sumagot ng 1 para sa link.","checkinUncoveredNow":"Walang ambassador sa iyong palapag ngayon. Tawagan ang Hub sa {hub}."},"signup":{"error":{"checkin_consent_missing":"Para humiling ng pangungumusta, lagyan ng tsek ang kahon para pumayag."}},"subscriptionEdit":{"error":{"checkin_consent_missing":"Para humiling ng pangungumusta, lagyan ng tsek ang kahon para pumayag."}},"checkin":{"consentMissing":"Para humiling ng pangungumusta, lagyan ng tsek ang kahon para pumayag.","sees":"Makikita ng ambassador sa iyong palapag ang numero ng telepono at palapag mo, para matawagan o ma-text ka.","isNot":"Ang pangungumusta ay tawag o text para itanong kung ayos ka. Hindi ito pangangalagang medikal, at hindi ito pangako na may darating agad.","howTitle":"Paano humiling","howNew":"Kailangan mo ang mga text alert ng CVH. Mag-sign up at humiling ng pangungumusta sa parehong form.","howHelp":"Sa isang event ng CVH o sa Hub, matutulungan ka ng staff o ng ambassador ng gusali na mag-sign up.","howSubscribed":"Nakakatanggap ka na ng text ng CVH? Humiling ng pangungumusta sa page kung saan mo binabago ang iyong mga pinili.","noCoverage":"Kung wala pang ambassador sa iyong palapag, sasabihin namin agad. Puwede mong tawagan ang Hub sa {hub} sa halip.","ask":"Kumustahin ako ng ambassador sa aking palapag","whereHint":"Piliin ang gusali at palapag kung saan ka nakatira, mula sa mga nasa itaas.","agree":"Pumapayag ako na makita ng ambassador sa aking palapag ang numero ng telepono at palapag ko, at kumustahin ako.","untilYes":"Magsisimula ang iyong hiling na pangungumusta kapag sumagot ka ng YES sa aming text.","uncovered":"Wala pang ambassador sa iyong palapag. Tawagan ang Hub sa {hub}.","withdraw":"Bawiin ang aking hiling na pangungumusta","withdrawNote":"Babawiin ito kapag nag-save ka. Makakatanggap ka pa rin ng mga alert.","moved":"Nagbago kung saan ka nakatira, kaya babawiin ang iyong hiling na pangungumusta. Para humiling muli para sa bago mong palapag, piliin ito at pumayag muli.","savedRequested":"Na-save ang iyong hiling na pangungumusta.","savedMethod":"Nabago ang paraan ng pangungumusta sa iyo."}});
  /* The last resident wording that showed in English: the home's alert list and its failures (R03, status.none), the ask screen's waiting and
     failure states (R09, R10.shownIn) and the directory (S02.06). AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "status": {
    "none": "Walang aktibo"
   },
   "R03": {
    "currentAlerts": "Mga kasalukuyang alerto",
    "noCurrentAlerts": "Walang kasalukuyang alerto",
    "myBuildings": "Ang iyong mga gusali",
    "checking": "Tinitingnan kung may alerto",
    "feedFailed": "Hindi namin matingnan ang mga alerto ngayon. Ang lugar na may nakasulat na \"Hindi alam\" ay maaaring may alerto pa rin. Susubukan naming muli.",
    "feedFailedOld": "Hindi namin matingnan ang mga bagong alerto. Ipinapakita ang huling na-load {t}."
   },
   "R09": {
    "searching": "Naghahanap",
    "needsSignal": "Kailangan ng signal para maghanap",
    "needsSignalBody": "Maaari ka pa ring pumili ng paksa sa ibaba, o tawagan ang Hub.",
    "busy": "Abala ang paghahanap, subukan muli pagkalipas ng ilang minuto",
    "busyBody": "Maaari kang pumili ng paksa sa ibaba, o tawagan ang Hub.",
    "updating": "Ina-update ang mga resulta ng paghahanap, subukan muli",
    "updatingBody": "Maaari kang pumili ng paksa sa ibaba habang ina-update ang mga ito, o tawagan ang Hub.",
    "browseAll": "Tingnan ang lahat ng serbisyo at organisasyon",
    "loading": "Nilo-load ang mga paksa"
   },
   "R10": {
    "shownIn": "Ipinapakita sa {lang}"
   },
   "directory": {
    "title": "Mga serbisyo at organisasyon",
    "lead": "Ang mga kinumpirma ng Hub sa Thorncliffe Park at Flemingdon Park. Pumili ng paksa o kapitbahayan para paikliin ang listahan.",
    "count": "{n} serbisyo",
    "countOne": "1 serbisyo",
    "topic": "Paksa",
    "emergency": "Tumutulong sa emerhensiya",
    "emergencyRole": "Tungkulin sa emerhensiya",
    /* The verified badge's line on a provider (it replaces the earlier last-confirmed line). AI-generated (Claude), not yet checked by native readers. */
    "checkedByHub": "Sinuri ng Hub · {date}",
    "lastUpdated": "Huling na-update {time}",
    "loading": "Nilo-load ang direktoryo",
    "couldNotLoad": "Hindi na-load ang direktoryo",
    "couldNotLoadBody": "Matutulungan ka ng Hub na makahanap ng serbisyo sa telepono.",
    "couldNotLoadNumbers": "Nasa pahina ng mga numero ang iba pang numerong maaaring kailanganin mo.",
    "numbersLink": "Tingnan ang mahahalagang numero",
    "backToList": "Lahat ng serbisyo at organisasyon",
    "suggestApply": "Ipakita lang ang {place}"
   }
  });
  /* Reading without signal (S02.12): the offline page and R-34's note. AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "offline": {
    "title": "Hindi naka-save sa iyong telepono ang pahinang ito",
    "body": "Hindi pa ito nabubuksan sa teleponong ito nang may signal, kaya kailangan nito ng signal. Laging naka-save sa iyong telepono ang mga numero.",
    "available": "Mababasa mo ang mga ito nang walang signal",
    "none": "Wala pang ibang naka-save sa teleponong ito. Ang mga pahinang binubuksan mo nang may signal ay sine-save para sa susunod."
   },
   "R34": {
    "offlineTitle": "Pagbasa nang walang signal",
    "offlineHelp": "Ang mga pahinang binubuksan mo nang may signal ay sine-save sa teleponong ito, kaya mababasa mo ulit ang mga ito nang walang signal. Laging naka-save ang mga numero. Sa unang pagkakataon, kailangan ng CVH ng signal para bumukas.",
    "offlineNote": "Maaaring hindi mag-save ang teleponong ito ng mga pahina para magamit nang walang signal"
   }
  });
  /* S08.02: an ambassador's post (A-02): the one screen's new words (an unsent post is held only in the open page's memory), and A03.states.ended. AI-generated, not yet checked by native readers. */
  m(t, {
   "A02": {
    "building": "Aling gusali?",
    "allFloorsLine": "Lahat ng {n} palapag",
    "listLabel": "Ilang palapag",
    "listLine": "Lagyan ng tsek ang bawat palapag",
    "rangeLabel": "Sunud-sunod na mga palapag",
    "rangeLine": "Mula sa isang palapag hanggang sa isa pa",
    "fromFloor": "Mula sa palapag",
    "toFloor": "Hanggang sa palapag",
    "chooseFloor": "Pumili",
    "phaseTitle": "Ano ang lagay",
    "phaseProblem": "May problema",
    "phaseProgress": "Inaayos na",
    "validTitle": "Hanggang kailan?",
    "validResolved": "Hanggang maayos ito (24 oras mula ngayon)",
    "validAt": "Hanggang sa isang petsa at oras",
    "dateLabel": "Petsa",
    "timeLabel": "Oras (oras sa Toronto)",
    "validHint": "Hanggang 7 araw mula ngayon lamang.",
    "textLabel": "Ano ang nangyayari, sa Ingles",
    "textHint": "Hanggang {max} titik. Binabasa ito ng mga residente sa kanilang wika; sinusuri muna ito ng Hub.",
    "inAlert": "Mapupunta ang update na ito sa alerto: {headline}",
    "typesFixed": "Ano ang nangyayari: {types}",
    "unsent": "Hindi pa naipapadala. Panatilihing bukas ang pahinang ito; ipapadala ito kapag may signal ka na.",
    "unsentClose": "Kapag isinara mo ang pahinang ito, mawawala ang update na ito.",
    "sending": "Ipinapadala sa Hub...",
    "errPhase": "Piliin kung ano ang lagay.",
    "errText": "Sabihin kung ano ang nangyayari, sa Ingles.",
    "errTextLong": "Masyadong mahaba ito. Gumamit ng hanggang {max} titik lamang.",
    "errValid": "Maglagay ng petsa at oras.",
    "errValidPast": "Lumipas na ang oras na iyon. Pumili ng mas huling oras.",
    "errValidFar": "Pumili ng oras na hanggang 7 araw mula ngayon lamang.",
    "errValidSkipped": "Nagbabago ang orasan sa gabing iyon, kaya hindi malinaw ang oras na iyon. Pumili ng ibang oras.",
    "errRange": "Mas mataas ang unang palapag kaysa sa huli. Unahin ang mas mababang palapag.",
    "errNotAssigned": "Hindi ka naka-assign sa gusaling ito ngayon, kaya hindi ka makakapag-post para dito.",
    "errClosed": "Natapos na ang alertong ito. Mag-post na lang ng bagong update.",
    "errSignedOut": "Na-sign out ka, kaya hindi ito naipadala. Mag-sign in ulit, saka i-post ito ulit.",
    "errFailed": "Hindi ito naipadala. Subukan ulit. Kung patuloy itong mangyari, tawagan ang Hub."
   },
   "A03": {
    "states": {
     "ended": "Hindi naipadala: natapos ang alerto bago ito nasuri ng Hub"
    }
   }
  });
  /* S09.07: the end-of-pilot re-consent texts (the campaign text with {date}, the confirmation after YES, the answer after the deadline, the answer
     while sign-ups are paused) and the sign-up form's refusal while sign-ups are paused. YES and CVH stay in English. Each text fits one text message
     with the longest date. smsDate is how a text writes the deadline (the month names, the order of day and month, the numerals), fixed here
     from CLDR 47 so the frozen text is the same on every runtime. AI-generated (Claude), not yet checked by native readers: the texts and the
     date words are reviewed before launch (Launch Readiness). */
  m(t, {"smsDate": {"months":["Enero","Pebrero","Marso","Abril","Mayo","Hunyo","Hulyo","Agosto","Setyembre","Oktubre","Nobyembre","Disyembre"],"dayMonth":"{month} {day}","digits":"0123456789"}, "smsTexts": {"reconsent": "Matatapos na ang pilot ng CVH. I-reply ang YES para patuloy na makatanggap ng alerto. Kung walang sagot hanggang {date}, buburahin ang numero mo.", "reconsentKept": "Salamat. Patuloy kang makakatanggap ng mga alerto ng CVH.", "pilotEnded": "Tapos na ang pilot ng CVH; hindi itinago ang numero mo.", "signupsPaused": "Nakahinto ang pag-sign up sa text ng CVH habang nagtatapos ang pilot."}, "signup": {"error": {"signups_paused": "Nakahinto ang pag-sign up habang nagtatapos ang pilot."}}});
  /* The opt-in disclosures carriers ask for (program, frequency, rates, HELP and STOP) under the sign-up form. AI-generated (Claude), not yet checked by native readers. */
  m(t, {"signup": {"smsTerms": "Mga text alert ng CVH mula sa Thorncliffe Park Community Hub. Nag-iiba ang dalas ng mensahe. Maaaring may singil sa mensahe at data. Sumagot ng HELP para sa tulong o STOP para tumigil."}});
  /* The per-group advice lines of the tailored block (X-12) and the simpler-view switch (X-07, retranslated from the current English
     "Simpler view"). AI-generated (Claude) on 2026-10-09 under the product owner's pilot decision that everything is translated;
     not yet checked by native readers (launch checklist, section 8). */
  m(t, {"tailored": {"power": {"seniors": ["Kung gumagamit ka ng medical device na kailangan ng kuryente, pumunta ka na ngayon sa lugar na may pag-charge.", "Gumamit lang ng hagdan kung kaya mo. Puwedeng magdala ng mga bagay sa iyo ang ambassador ng palapag mo."], "newcomers": ["Hindi humihingi ng ID o immigration status ang mga lugar para mag-charge.", "Hindi kailanman hihingi sa iyo ng pera o papeles sa telepono ang Toronto Hydro at ang Lungsod ng Toronto habang walang kuryente."], "families": ["Kung mainit na ang ref, ilagay ang formula ng sanggol at ang gatas sa cooler na may yelo.", "Gumamit ng flashlight, hindi kandila, kapag may mga bata."]}, "flood": {"seniors": ["Ilipat na ngayon ang mga gamot at papeles sa mataas na istante.", "Humingi ng tulong sa isang kapitbahay o sa ambassador ng palapag mo kung kailangan mong umalis."], "newcomers": ["Puwede mong iulat sa landlord mo ang tagas nang hindi naaapektuhan ang immigration status mo.", "Ang libreng tulong legal ay makapagpapaliwanag sa iyong wika tungkol sa pagkukumpuni at upa pagkatapos ng baha."], "families": ["Ilayo ang mga bata sa mga basang lugar at sa mga saksakan ng kuryente.", "Itapon ang mga laruan at pagkaing nadikit sa tubig-baha."]}, "elevator": {"seniors": ["Maaaring isaayos ng ambassador ng palapag mo na maiakyat sa iyo ang grocery o mga gamot.", "Puwedeng isaayos ang sasakyan papunta sa mga medical appointment habang sira ang elevator."], "newcomers": ["Hindi humihingi ng ID o status ang tulong sa grocery at transportasyon.", "May karapatan kang itanong sa landlord mo kung kailan maaayos ang elevator."], "families": ["Puwedeng tumulong ang mga kapitbahay sa pagbubuhat ng stroller at grocery paakyat sa hagdan.", "Kung may medical appointment ang isang bata, magtanong tungkol sa tulong sa transportasyon."]}, "heat": {"seniors": ["May mga gamot na nagpapahirap sa katawan kapag mainit. Magtanong sa iyong pharmacist.", "Pumunta sa lugar na pampalamig sa unang bahagi ng hapon, bago ang pinakamainit na oras ng araw."], "newcomers": ["Libre ang mga lugar na pampalamig at hindi humihingi ng ID o immigration status.", "Libre ang tulong sa bayarin sa kuryente. Magtanong sa Hub."], "families": ["Mas mabilis mainitan ang mga sanggol at maliliit na bata kaysa sa mga nasa hustong gulang. Painumin sila ng tubig nang madalas.", "Huwag kailanman iwan ang bata sa nakaparadang sasakyan, kahit isang minuto lang."]}, "smoke": {"seniors": ["Kung may hika ka o sakit sa puso, panatilihing malapit sa iyo ang mga gamot mo.", "Bukas ang mga lugar na may na-filter na hangin. Magpasama sa isang kapitbahay."], "newcomers": ["Libre ang mga lugar na may na-filter na hangin at hindi humihingi ng ID o immigration status.", "Libre ang mga mask sa Hub habang may supply pa."], "families": ["Panatilihin ang mga bata sa loob ng bahay at limitahan ang pagtakbo at paglalaro.", "Nakakatulong sa pagtulog ng mga bata ang filter na nakakabit sa box fan sa kanilang kuwarto."]}, "fire": {"seniors": ["Kung hindi mo kayang gumamit ng hagdan, manatili sa iyong unit nang nakasara ang pinto at tumawag sa 911.", "Alam ng ambassador ng palapag mo kung aling mga residente ang maaaring mangailangan ng tulong sa paglabas."], "newcomers": ["Hindi nagtatanong ng immigration status ang mga reception point at ang suporta pagkatapos ng sunog.", "Matutulungan ka ng mga settlement worker na palitan ang mga nawalang dokumento."], "families": ["Magsanay kasama ang mga anak mo: paano pumunta sa hagdanan, at saan magkikita sa labas.", "Maglagay ng bag na may mga gamot at papeles ng mga bata malapit sa pinto."]}, "winter": {"seniors": ["I-charge ang telepono mo at ilapit sa iyo ang mga kumot sakaling mawalan ng kuryente."], "newcomers": ["Libre ang mga lugar na pampainit at hindi humihingi ng ID o status."], "families": ["Kung mamatay ang heating, bihisan ang mga bata ng patong-patong na damit kahit nasa loob ng bahay."]}}, "x07": {"label": "Mas simpleng view", "turnOn": "Buksan ang mas simpleng view", "turnOff": "Isara ang mas simpleng view"}});
})();
