/* Spanish string table. Phase 1: shell and shared components. AI-generated; to be checked by native readers. */
window.CVH_STRINGS = window.CVH_STRINGS || {};
window.CVH_STRINGS.es = {
 meta: { code: 'es', name: 'Español', aiNote: 'Todo el texto de este prototipo fue generado con IA. Personas lo revisarán antes de lanzar el CVH.' },
 time: { justNow: 'Ahora mismo', ago: 'hace {t}', join: ' y ', second: '1 segundo', seconds: '{n} segundos', minute: '1 minuto', minutes: '{n} minutos', hour: '1 hora', hours: '{n} horas', day: '1 día', days: '{n} días', today: 'Hoy', tomorrow: 'Mañana', until: 'hasta {t}', closed: 'Cerrado',
   days7: { mon: 'lunes', tue: 'martes', wed: 'miércoles', thu: 'jueves', fri: 'viernes', sat: 'sábado', sun: 'domingo' } },
 shell: { cvhName: 'Centro Virtual Comunitario', prototype: 'Prototipo', prototypeNote: 'No es un servicio real. Todo el contenido fue generado con IA.',
   language: 'Idioma', changeLanguage: 'Cambiar idioma', languageTitle: 'Elija su idioma', languageCurrent: 'Se muestra ahora', languageReturn: 'La pantalla se queda donde estaba.',
   choices: 'Lo que le he dicho al CVH', choicesShort: 'Mis opciones', nav: { now: 'Alertas', help: 'Buscar ayuda', map: 'Mapa', ready: 'Prepararse' }, navLabel: 'Principal',
   close: 'Cerrar', back: 'Atrás', next: 'Continuar', skip: 'Omitir', done: 'Listo', cancel: 'Cancelar', more: 'Más',
   notInPrototype: 'No está en este prototipo', notInPrototypeBody: 'Esta parte no está construida en el prototipo. No cambió nada.', ok: 'De acuerdo',
   about: 'Acerca del CVH', aboutBody: 'El Centro Virtual Comunitario lo gestiona Thorncliffe Park Community Hub para Thorncliffe Park y Flemingdon Park.', builtBy: 'Creado con Sprout Climate',
   rules: 'Las reglas de este espacio', ambassador: 'Embajador', offline: 'Está sin conexión. Se muestra lo cargado {t}.', aiLabel: 'Generado con IA para el prototipo', illustrative: 'Ilustrativo' },
 x01: { text: 'El CVH no es un servicio de emergencia.', call: 'Si alguien está en peligro, llame al 911.', short: 'No es un servicio de emergencia. ¿Peligro? Llame al 911.',
   sms: 'El Hub no es un servicio de emergencia. Si alguien está en peligro, llame al 911.', print: 'Esto no es un servicio de emergencia. Si alguien está en peligro, llame al 911.' },
 x02: { official: 'Alerta oficial de {source}', community: 'Alerta comunitaria de {author}', verifiedBy: 'Verificado por {org}', notYetVerified: 'Aún no verificado',
   corrected: 'Corregido {t}', whatMeans: 'Qué significa', hub: 'el Hub', theHub: 'El Hub', ambassador: 'Embajador del edificio, {building}', postedBy: 'Publicado por {author}',
   levelOfficial: 'Alerta oficial', levelCommunity: 'Alerta comunitaria', sources: { ECCC: 'Environment and Climate Change Canada', CITY: 'Ciudad de Toronto', ALERTREADY: 'Alert Ready' } },
 x03: { title: 'Las reglas de este espacio', intro: 'El CVH es para vecinos que se ayudan. Antes de añadir algo, lea esto.',
   rules: ['Comparta lugares y ayuda gratuitos o de bajo costo, abiertos a la comunidad.', 'Escriba sobre un lugar, no sobre una persona. No comparta nombres, números de unidad ni teléfonos.',
     'Sea amable. Nada que insulte o ataque a un grupo de personas.', 'Comparta solo lo que sabe que es cierto. Si no está seguro, elija "No estoy seguro".'],
   market: 'El CVH no es un mercado. Nada de ventas ni publicidad.', review: 'Alguien del Hub lee todo antes de que aparezca en el mapa.', agree: 'Entiendo', readMore: 'Leer las reglas' },
 x04: { label: 'Traducido por máquina', from: 'del {lang}', report: 'Informar un problema de traducción', reportTitle: '¿Qué está mal en esta traducción?',
   reasons: { meaning: 'El significado está mal', words: 'Algunas palabras están mal', unclear: 'Es difícil de entender' }, send: 'Enviar', reported: 'Gracias. Alguien del Hub revisará esta traducción.',
   unavailable: 'Aún no disponible en este idioma', unavailableBody: 'Esto aún no se ha traducido al {lang}.', showSource: 'Leer en {lang}', original: 'Original ({lang})' },
 x07: { label: 'Letra más grande, menos cosas', on: 'Sí', off: 'No', setByHelper: 'Lo activó alguien que le ayuda', remembered: 'Se recuerda en este dispositivo', turnOn: 'Activar', turnOff: 'Desactivar' },
 x08: { idle: 'Escuchar · {t}', loading: 'Cargando el audio', playing: 'Reproduciendo', paused: 'En pausa', left: 'Quedan {t}',
   failed: 'El audio no pudo cargarse con esta conexión. Todo lo que dice está escrito aquí.', retry: 'Intentar de nuevo', play: 'Reproducir', pause: 'Pausa', section: 'Escuchar esta sección · {t}' },
 x09: { open: 'Abierto', full: 'Lleno', closed: 'Cerrado', unconfirmed: 'Sin confirmar',
   purpose: { cooling: 'para refrescarse', cleanAir: 'para aire limpio', warming: 'para calentarse', charging: 'para cargar dispositivos' },
   confirmed: 'Confirmado {t}', unconfirmedNote: 'Sin confirmar desde hace {t}. Puede que no esté abierto. Llame antes de ir.', hoursToday: 'Hoy de {from} a {to}', closedToday: 'Cerrado hoy',
   water: 'Agua potable', seating: 'Asientos', charging: 'Carga de teléfono', washrooms: 'Baños', stepFree: 'Sin escalones', notStepFree: 'Tiene escalones', noId: 'No pide identificación', idAsked: 'Pide identificación',
   runBy: 'Lo gestiona {org}', yes: 'Sí', no: 'No', unknown: 'No se sabe' },
 x10: { word: 'Simulacro', running: 'Simulacro. Esto es práctica.', runningSub: 'No se envía nada a los residentes.', ended: 'Simulacro terminado', sms: 'Simulacro. Solo práctica.' },
 x11: { title: 'Filtros activos', remove: 'Quitar filtro: {f}', hiding: 'Estos filtros ocultan {n} lugares', hidingOne: 'Estos filtros ocultan 1 lugar',
   fromChoices: 'Algunos filtros vienen de sus opciones', clear: 'Quitar todos los filtros', none: 'Sin filtros' },
 x12: { title: 'Qué significa para usted', fromHub: 'Consejo del Hub', tailoredLink: 'Adaptado a sus opciones', standard: 'Ver la versión que recibe todo el mundo',
   standardShown: 'Está viendo la versión que recibe todo el mundo.', showMine: 'Ver qué significa para mí', checkin: 'El embajador de su piso pasará a ver cómo está hoy.',
   noCheckin: 'Todavía no hay embajador en su piso, así que no podemos ir a verle. Llame al Hub al {phone}. Abrimos {hours}.',
   hubHours: 'de lunes a jueves de 9 a 20 h, viernes de 9 a 17 h, sábado de 10 a 14 h', listen: 'Escuchar · {t}' },
 x13: { fire: 'Incendio', power: 'Electricidad', water: 'Agua', elevator: 'Ascensor', flood: 'Inundación o fuga', heat: 'Calor', smoke: 'Humo', winter: 'Tormenta invernal', other: 'Otro', fireAlarm: 'Alarma de incendio o evacuación', waterPlumbing: 'Agua o fontanería' },
 x14: { label: 'Cómo pueden ayudar' },
 status: { active: 'Problema activo', progress: 'Trabajo en curso', resolved: 'Resuelto', unknown: 'No se sabe' },
 R02: { title: 'Elija su idioma', changed: 'Ahora se muestra en {lang}.' }
};
