/* Tagalog string table. Phase 1: shell and shared components. AI-generated; to be checked by native readers. */
window.CVH_STRINGS = window.CVH_STRINGS || {};
window.CVH_STRINGS.tl = {
 meta: { code: 'tl', name: 'Tagalog', aiNote: 'Lahat ng teksto sa prototype na ito ay gawa ng AI. Susuriin ito ng mga tao bago ilunsad ang CVH.' },
 time: { justNow: 'Ngayon lang', ago: '{t} ang nakalipas', join: ' at ', second: '1 segundo', seconds: '{n} segundo', minute: '1 minuto', minutes: '{n} minuto', hour: '1 oras', hours: '{n} oras', day: '1 araw', days: '{n} araw', today: 'Ngayon', tomorrow: 'Bukas', until: 'hanggang {t}', closed: 'Sarado',
   days7: { mon: 'Lunes', tue: 'Martes', wed: 'Miyerkules', thu: 'Huwebes', fri: 'Biyernes', sat: 'Sabado', sun: 'Linggo' } },
 shell: { cvhName: 'Community Virtual Hub', prototype: 'Prototype', prototypeNote: 'Hindi ito totoong serbisyo. Gawa ng AI ang lahat ng nilalaman.',
   language: 'Wika', changeLanguage: 'Palitan ang wika', languageTitle: 'Piliin ang iyong wika', languageCurrent: 'Ipinapakita ngayon', languageReturn: 'Mananatili ang screen kung nasaan ka.',
   choices: 'Ang sinabi ko sa CVH', choicesShort: 'Mga pinili ko', nav: { now: 'Ngayon', help: 'Humanap ng tulong', map: 'Mapa', ready: 'Maging handa' }, navLabel: 'Pangunahin',
   close: 'Isara', back: 'Bumalik', next: 'Magpatuloy', skip: 'Laktawan', done: 'Tapos na', cancel: 'Kanselahin', more: 'Iba pa',
   notInPrototype: 'Wala sa prototype na ito', notInPrototypeBody: 'Hindi pa nagagawa ang bahaging ito sa prototype. Walang nagbago.', ok: 'Sige',
   about: 'Tungkol sa CVH', aboutBody: 'Pinapatakbo ng Thorncliffe Park Community Hub ang Community Virtual Hub para sa Thorncliffe Park at Flemingdon Park.', builtBy: 'Ginawa kasama ang Sprout Climate',
   rules: 'Ang mga patakaran ng espasyong ito', ambassador: 'Ambassador', offline: 'Offline ka. Ipinapakita ang huling na-load {t}.', aiLabel: 'Gawa ng AI para sa prototype', illustrative: 'Halimbawa lamang' },
 x01: { text: 'Hindi pang-emergency na serbisyo ang CVH.', call: 'Kung may nasa panganib, tumawag sa 911.', short: 'Hindi pang-emergency. May panganib? Tumawag sa 911.',
   sms: 'Hindi pang-emergency na serbisyo ang Hub. Kung may nasa panganib, tumawag sa 911.', print: 'Hindi ito pang-emergency na serbisyo. Kung may nasa panganib, tumawag sa 911.' },
 x02: { official: 'Opisyal na alerto mula sa {source}', community: 'Alerto ng komunidad mula sa {author}', verifiedBy: 'Beripikado ng {org}', notYetVerified: 'Hindi pa beripikado',
   corrected: 'Itinama {t}', whatMeans: 'Ano ang ibig sabihin', hub: 'Hub', theHub: 'Ang Hub', ambassador: 'Ambassador ng gusali, {building}', postedBy: 'Ipinost ng {author}',
   levelOfficial: 'Opisyal na alerto', levelCommunity: 'Alerto ng komunidad', sources: { ECCC: 'Environment and Climate Change Canada', CITY: 'Lungsod ng Toronto', ALERTREADY: 'Alert Ready' } },
 x03: { title: 'Ang mga patakaran ng espasyong ito', intro: 'Ang CVH ay para sa magkakapitbahay na nagtutulungan. Bago magdagdag, pakibasa ito.',
   rules: ['Ibahagi ang mga lugar at tulong na libre o mura at bukas sa komunidad.', 'Sumulat tungkol sa lugar, hindi sa tao. Huwag ibahagi ang pangalan, numero ng unit o telepono ng iba.',
     'Maging mabait. Walang pang-iinsulto o pagtutok sa anumang grupo ng tao.', 'Ibahagi lang ang alam mong totoo. Kung hindi sigurado, piliin ang "Hindi sigurado".'],
   market: 'Hindi palengke ang CVH. Walang pagbebenta at walang advertising.', review: 'May taga-Hub na nagbabasa ng lahat bago ito lumabas sa mapa.', agree: 'Naiintindihan ko', readMore: 'Basahin ang mga patakaran' },
 x04: { label: 'Isinalin ng makina', from: 'mula sa {lang}', report: 'Iulat ang problema sa salin', reportTitle: 'Ano ang mali sa saling ito?',
   reasons: { meaning: 'Mali ang kahulugan', words: 'May maling salita', unclear: 'Mahirap intindihin' }, send: 'Ipadala', reported: 'Salamat. Susuriin ng taga-Hub ang saling ito.',
   unavailable: 'Wala pa sa wikang ito', unavailableBody: 'Hindi pa ito naisasalin sa {lang}.', showSource: 'Basahin sa {lang}', original: 'Orihinal ({lang})' },
 x07: { label: 'Mas malaking teksto, mas kaunting bagay', on: 'Bukas', off: 'Sarado', setByHelper: 'Binuksan ng taong tumutulong sa iyo', remembered: 'Naaalala sa device na ito', turnOn: 'Buksan', turnOff: 'Isara' },
 x08: { idle: 'Makinig · {t}', loading: 'Nilo-load ang audio', playing: 'Tumutugtog', paused: 'Naka-pause', left: '{t} pa',
   failed: 'Hindi na-load ang audio sa koneksyong ito. Nakasulat dito ang lahat ng sinasabi nito.', retry: 'Subukan muli', play: 'I-play', pause: 'I-pause', section: 'Pakinggan ang bahaging ito · {t}' },
 x09: { open: 'Bukas', full: 'Puno', closed: 'Sarado', unconfirmed: 'Hindi kumpirmado',
   purpose: { cooling: 'para magpalamig', cleanAir: 'para sa malinis na hangin', warming: 'para magpainit', charging: 'para mag-charge' },
   confirmed: 'Nakumpirma {t}', unconfirmedNote: 'Hindi nakumpirma sa loob ng {t}. Baka hindi bukas. Tumawag bago pumunta.', hoursToday: 'Ngayon {from} hanggang {to}', closedToday: 'Sarado ngayon',
   water: 'Inuming tubig', seating: 'Upuan', charging: 'Pag-charge ng telepono', washrooms: 'Banyo', stepFree: 'Walang hagdan', notStepFree: 'May hagdan', noId: 'Hindi humihingi ng ID', idAsked: 'Humihingi ng ID',
   runBy: 'Pinapatakbo ng {org}', yes: 'Oo', no: 'Hindi', unknown: 'Hindi alam' },
 x10: { word: 'Pagsasanay', running: 'Pagsasanay. Praktis lang ito.', runningSub: 'Walang ipinapadala sa mga residente mula rito.', ended: 'Tapos na ang pagsasanay', sms: 'Pagsasanay. Praktis lang.' },
 x11: { title: 'Mga filter na nakabukas', remove: 'Alisin ang filter: {f}', hiding: '{n} lugar ang nakatago dahil sa mga filter', hidingOne: '1 lugar ang nakatago dahil sa mga filter',
   fromChoices: 'May mga filter na galing sa mga pinili mo', clear: 'Alisin lahat', none: 'Walang filter' },
 x12: { title: 'Ano ang ibig sabihin nito para sa iyo', fromHub: 'Payo mula sa Hub', tailoredLink: 'Iniangkop sa mga pinili mo', standard: 'Ipakita ang bersyong nakukuha ng lahat',
   standardShown: 'Nakikita mo ang bersyong nakukuha ng lahat.', showMine: 'Ipakita ang para sa akin', checkin: 'Kukumustahin ka ng ambassador ng palapag mo ngayong araw.',
   noCheckin: 'Wala pang ambassador sa palapag mo, kaya hindi ka namin makukumusta. Tawagan ang Hub sa {phone}. Bukas kami {hours}.',
   hubHours: 'Lunes hanggang Huwebes 9 am hanggang 8 pm, Biyernes 9 am hanggang 5 pm, Sabado 10 am hanggang 2 pm', listen: 'Makinig · {t}' },
 x13: { fire: 'Sunog', power: 'Kuryente', water: 'Tubig', elevator: 'Elevator', flood: 'Baha o tagas', heat: 'Init', smoke: 'Usok', winter: 'Bagyo ng niyebe', other: 'Iba pa', fireAlarm: 'Fire alarm o paglikas', waterPlumbing: 'Tubig o tubero' },
 x14: { label: 'Paano sila makakatulong' },
 status: { active: 'Aktibong problema', progress: 'Inaayos pa', resolved: 'Naayos na', unknown: 'Hindi alam' },
 filters: { short: { openNow: 'Bukas ngayon', free: 'Libre', lowCost: 'Libre o mura', noId: 'Hindi humihingi ng ID', stepFree: 'Walang hagdan', noAppointment: 'Walang appointment', nbhdTP: 'Thorncliffe Park', nbhdFP: 'Flemingdon Park', language: 'Nagsasalita ng {lang}' } },
 R02: { title: 'Piliin ang iyong wika', changed: 'Ipinapakita na sa {lang}.' }
};
