/* Slovak string table. Phase 1: shell and shared components. AI-generated; to be checked by native readers. */
window.CVH_STRINGS = window.CVH_STRINGS || {};
window.CVH_STRINGS.sk = {
 meta: { code: 'sk', name: 'Slovenčina', aiNote: 'Všetok text v tomto prototype vytvorila umelá inteligencia. Pred spustením CVH ho skontrolujú ľudia.' },
 time: { justNow: 'Práve teraz', ago: 'pred {t}', join: ' ', second: '1 sekundou', seconds: '{n} sekundami', minute: '1 minútou', minutes: '{n} minútami', hour: '1 hodinou', hours: '{n} hodinami', day: '1 dňom', days: '{n} dňami', today: 'Dnes', tomorrow: 'Zajtra', until: 'do {t}', closed: 'Zatvorené',
   days7: { mon: 'pondelok', tue: 'utorok', wed: 'streda', thu: 'štvrtok', fri: 'piatok', sat: 'sobota', sun: 'nedeľa' } },
 shell: { cvhName: 'Komunitné virtuálne centrum', prototype: 'Prototyp', prototypeNote: 'Nie je to skutočná služba. Všetok obsah vytvorila umelá inteligencia.',
   language: 'Jazyk', changeLanguage: 'Zmeniť jazyk', languageTitle: 'Vyberte si jazyk', languageCurrent: 'Práve zobrazené', languageReturn: 'Obrazovka zostane tam, kde ste boli.',
   choices: 'Čo som povedal CVH', choicesShort: 'Moje voľby', nav: { now: 'Teraz', help: 'Nájsť pomoc', map: 'Mapa', ready: 'Buďte pripravení' }, navLabel: 'Hlavné',
   close: 'Zavrieť', back: 'Späť', next: 'Pokračovať', skip: 'Preskočiť', done: 'Hotovo', cancel: 'Zrušiť', more: 'Viac',
   notInPrototype: 'V tomto prototype nie je', notInPrototypeBody: 'Táto časť nie je v prototype vytvorená. Nič sa nezmenilo.', ok: 'OK',
   about: 'O CVH', aboutBody: 'Komunitné virtuálne centrum prevádzkuje Thorncliffe Park Community Hub pre Thorncliffe Park a Flemingdon Park.', builtBy: 'Vytvorené so Sprout Climate',
   rules: 'Pravidlá tohto priestoru', ambassador: 'Ambasádor', offline: 'Ste offline. Zobrazuje sa obsah načítaný {t}.', aiLabel: 'Vytvorené umelou inteligenciou pre prototyp', illustrative: 'Ilustračné' },
 x01: { text: 'CVH nie je záchranná služba.', call: 'Ak je niekto v ohrození, volajte 911.', short: 'Nie je to záchranná služba. Ohrozenie? Volajte 911.',
   sms: 'Hub nie je záchranná služba. Ak je niekto v ohrození, volajte 911.', print: 'Toto nie je záchranná služba. Ak je niekto v ohrození, volajte 911.' },
 x02: { official: 'Oficiálne upozornenie od {source}', community: 'Komunitné upozornenie od {author}', verifiedBy: 'Overil(a) {org}', notYetVerified: 'Zatiaľ neoverené',
   corrected: 'Opravené {t}', whatMeans: 'Čo to znamená', hub: 'Hub', theHub: 'Hub', ambassador: 'Ambasádor budovy, {building}', postedBy: 'Zverejnil(a) {author}',
   levelOfficial: 'Oficiálne upozornenie', levelCommunity: 'Komunitné upozornenie', sources: { ECCC: 'Environment and Climate Change Canada', CITY: 'Mesto Toronto', ALERTREADY: 'Alert Ready' } },
 x03: { title: 'Pravidlá tohto priestoru', intro: 'CVH je pre susedov, ktorí si pomáhajú. Skôr ako niečo pridáte, prečítajte si toto.',
   rules: ['Zdieľajte miesta a pomoc, ktoré sú zadarmo alebo lacné a otvorené pre komunitu.', 'Píšte o mieste, nie o človeku. Nezdieľajte mená, čísla bytov ani telefónne čísla.',
     'Buďte láskaví. Nič, čo uráža alebo cieli na skupinu ľudí.', 'Zdieľajte len to, o čom viete, že je pravda. Ak si nie ste istí, zvoľte „Nie som si istý“.'],
   market: 'CVH nie je trhovisko. Žiadny predaj ani reklama.', review: 'Niekto z Hubu si všetko prečíta, kým sa to objaví na mape.', agree: 'Rozumiem', readMore: 'Prečítať pravidlá' },
 x04: { label: 'Strojový preklad', from: 'z jazyka {lang}', report: 'Nahlásiť problém s prekladom', reportTitle: 'Čo je na tomto preklade zlé?',
   reasons: { meaning: 'Význam je zlý', words: 'Niektoré slová sú zlé', unclear: 'Ťažko sa to chápe' }, send: 'Odoslať', reported: 'Ďakujeme. Niekto z Hubu preklad skontroluje.',
   unavailable: 'V tomto jazyku zatiaľ nie je', unavailableBody: 'Toto ešte nie je preložené do jazyka {lang}.', showSource: 'Čítať v jazyku {lang}', original: 'Originál ({lang})' },
 x07: { label: 'Väčšie písmo, menej vecí', on: 'Zapnuté', off: 'Vypnuté', setByHelper: 'Zapol to niekto, kto vám pomáha', remembered: 'Zapamätané v tomto zariadení', turnOn: 'Zapnúť', turnOff: 'Vypnúť' },
 x08: { idle: 'Vypočuť · {t}', loading: 'Načítava sa zvuk', playing: 'Prehráva sa', paused: 'Pozastavené', left: 'Zostáva {t}',
   failed: 'Zvuk sa pri tomto pripojení nenačítal. Všetko, čo hovorí, je napísané tu.', retry: 'Skúsiť znova', play: 'Prehrať', pause: 'Pozastaviť', section: 'Vypočuť túto časť · {t}' },
 x09: { open: 'Otvorené', full: 'Plné', closed: 'Zatvorené', unconfirmed: 'Nepotvrdené',
   purpose: { cooling: 'na ochladenie', cleanAir: 'na čistý vzduch', warming: 'na zohriatie', charging: 'na nabíjanie zariadení' },
   confirmed: 'Potvrdené {t}', unconfirmedNote: 'Nepotvrdené už {t}. Možno nie je otvorené. Pred cestou zavolajte.', hoursToday: 'Dnes od {from} do {to}', closedToday: 'Dnes zatvorené',
   water: 'Pitná voda', seating: 'Sedenie', charging: 'Nabíjanie telefónu', washrooms: 'Toalety', stepFree: 'Bez schodov', notStepFree: 'So schodmi', noId: 'Nežiadajú doklad', idAsked: 'Žiadajú doklad',
   runBy: 'Prevádzkuje {org}', yes: 'Áno', no: 'Nie', unknown: 'Neznáme' },
 x10: { word: 'Cvičenie', running: 'Cvičenie. Toto je nácvik.', runningSub: 'Obyvateľom sa nič neposiela.', ended: 'Cvičenie skončilo', sms: 'Cvičenie. Len nácvik.' },
 x11: { title: 'Zapnuté filtre', remove: 'Odstrániť filter: {f}', hiding: 'Tieto filtre skrývajú {n} miest', hidingOne: 'Tieto filtre skrývajú 1 miesto',
   fromChoices: 'Niektoré filtre sú z vašich volieb', clear: 'Odstrániť všetky filtre', none: 'Žiadne filtre' },
 x12: { title: 'Čo to znamená pre vás', fromHub: 'Rada od Hubu', tailoredLink: 'Podľa vašich volieb', standard: 'Zobraziť verziu, ktorú dostanú všetci',
   standardShown: 'Vidíte verziu, ktorú dostanú všetci.', showMine: 'Zobraziť, čo to znamená pre mňa', checkin: 'Ambasádor vášho poschodia sa dnes za vami zastaví.',
   noCheckin: 'Na vašom poschodí zatiaľ nie je ambasádor, preto sa za vami nemôžeme zastaviť. Zavolajte do Hubu na {phone}. Máme otvorené {hours}.',
   hubHours: 'pondelok až štvrtok 9.00 až 20.00, piatok 9.00 až 17.00, sobota 10.00 až 14.00', listen: 'Vypočuť · {t}' },
 x13: { fire: 'Požiar', power: 'Elektrina', water: 'Voda', elevator: 'Výťah', flood: 'Záplava alebo únik', heat: 'Horúčava', smoke: 'Dym', winter: 'Snehová búrka', other: 'Iné', fireAlarm: 'Požiarny poplach alebo evakuácia', waterPlumbing: 'Voda alebo potrubie' },
 x14: { label: 'Ako môžu pomôcť' },
 status: { active: 'Aktívny problém', progress: 'Prebieha práca', resolved: 'Vyriešené', unknown: 'Neznáme' },
 R02: { title: 'Vyberte si jazyk', changed: 'Teraz sa zobrazuje: {lang}.' }
};
