/* French strings for the resident and ambassador screens, merged into the French table by
   screen ID. AI-generated (Claude), not yet checked by native readers. Staff screens stay in English. */
(function () {
  var t = window.CVH_STRINGS.fr;
  function m(t, s) { for (var k in s) { if (!Object.prototype.hasOwnProperty.call(s, k) || k === "__proto__" || k === "constructor" || k === "prototype") continue; if (s[k] && typeof s[k] === "object" && !Array.isArray(s[k]) && t[k] && typeof t[k] === "object" && !Array.isArray(t[k])) m(t[k], s[k]); else t[k] = s[k]; } }
  m(t, {
  "terms": {
   "version": "Version",
   "owner": "Responsable",
   "updated": "Dernière mise à jour",
   "privacyContact": "Contact pour la vie privée",
   "draftTitle": "Ébauche : pas encore publiée",
   "draftBody": "Ce texte n'a pas encore été approuvé. Ce ne sont pas les conditions finales. Ne vous inscrivez pas en vous fiant à ce texte.",
   "draftWhy": "Pas publié parce que :",
   "translationNote": "Une partie de cette page n'a pas encore été traduite en {lang}. Ces parties s'affichent en anglais.",
   /* S09.08: the day the pilot's resident data was deleted, shown once the end-of-pilot purge has completed. AI-generated (Claude), not yet checked by native readers. */
   "dataDeleted": "Données des résidents supprimées",
   "dataDeletedNote": "Le projet pilote CVH est terminé. À cette date, nous avons supprimé le numéro de téléphone et les choix de toutes les personnes qui n'ont pas répondu YES pour continuer à recevoir les alertes."
  },
  "shell": {
   "hubName": "Thorncliffe Park Community Hub",
   "hubLogoAlt": "Thorncliffe Park Community Hub",
   "pageNotFound": "Cette page est introuvable.",
   "pageNotFoundBody": "Le lien est peut-être ancien ou mal écrit. Utilisez le menu ci-dessous pour continuer."
  },
  "x01": {
   "partner": "Cet espace n'appelle le 911 pour personne. Si quelqu'un est en danger, appelez vous-même le 911. Ne supposez pas qu'un autre organisme l'a fait."
  },
  "x05": {
   "title": "Recevez des alertes et de l'aide dans votre langue",
   "lead": "Le Carrefour virtuel communautaire vous avertit quand il se passe quelque chose dans votre immeuble et vous aide à trouver des services près de chez vous.",
   "steps": ["Ouvrez le lien ou balayez le code avec votre téléphone.", "Choisissez votre langue.", "Vous n'avez pas besoin de compte ni d'application."],
   "link": "Lien court",
   "scan": "Balayez avec l'appareil photo de votre téléphone",
   "building": "Immeuble",
   "floor": "Étage",
   "writeIn": "Rempli à la main par votre ambassadeur",
   "text": "Pas de téléphone intelligent? Demandez à l'ambassadeur de votre étage de vous aider à recevoir les alertes par texto.",
   "from": "De la part du Thorncliffe Park Community Hub",
   "sampleLink": "Lien d'exemple, non actif"
  },
  "x06": {
   "doing": "Nous nous en occupons",
   "canTake": "Nous pouvons nous en charger",
   "cannotCover": "Nous ne pouvons pas nous en charger",
   "need": "Nous en avons besoin",
   "claimed": "Pris en charge par {org}",
   "supply": "Fourniture : {item}",
   "recordDecision": "Noter comme décision"
  },
  "groups": {
   "seniors": {
    "label": "Aînés",
    "line": "Avertissements de chaleur et services pour les résidents âgés, et des conseils pour vous dans chaque alerte."
   },
   "newcomers": {
    "label": "Nouveaux arrivants",
    "line": "Des services qui ne demandent pas votre statut, et des conseils pour vous dans chaque alerte."
   },
   "families": {
    "label": "Familles avec de jeunes enfants",
    "line": "Alertes et conseils sur les bébés et les jeunes enfants, et services pour les familles."
   },
   "checkin": {
    "label": "J'aimerais qu'on prenne de mes nouvelles pendant la chaleur et les pannes",
    "line": "L'ambassadeur de votre étage prend de vos nouvelles lors d'un avertissement de chaleur ou d'une panne de courant."
   }
  },
  "categories": {
   "food": "Alimentation",
   "housing": "Logement et loyer",
   "health": "Santé",
   "money": "Argent et prestations",
   "settlement": "Immigration et établissement",
   "jobs": "Emploi et formation",
   "children": "Enfants et jeunes",
   "seniors": "Aînés",
   "legal": "Aide juridique",
   "mentalHealth": "Santé mentale"
  },
  "filters": {
   "openNow": "Est-ce ouvert en ce moment?",
   "nbhd": "Quel quartier?",
   "language": "Parlent-ils ma langue?",
   "cost": "Combien ça coûte?",
   "noId": "Vont-ils demander une pièce d'identité ou mon statut?",
   "stepFree": "Puis-je entrer sans marches?",
   "noAppointment": "Ai-je besoin d'un rendez-vous?",
   "short": {
    "openNow": "Ouvert maintenant",
    "nbhdTP": "Thorncliffe Park",
    "nbhdFP": "Flemingdon Park",
    "language": "Parle {lang}",
    "free": "Gratuit",
    "lowCost": "Gratuit ou peu coûteux",
    "noId": "Ne demande pas de pièce d'identité",
    "stepFree": "Sans marches",
    "noAppointment": "Sans rendez-vous"
   },
   "answers": {
    "yes": "Oui",
    "no": "Non",
    "any": "Peu importe",
    "free": "Gratuit seulement",
    "lowCost": "Gratuit ou peu coûteux",
    "noIdOnly": "Seulement les lieux qui ne demandent pas",
    "stepFreeOnly": "Seulement les lieux sans marches",
    "walkIn": "Seulement sans rendez-vous"
   }
  },
  "utilities": {
   "ac": "Climatisation",
   "wifi": "Wi-Fi",
   "charging": "Recharge",
   "washrooms": "Toilettes",
   "water": "Eau potable",
   "food": "Nourriture",
   "kit": "Trousses de préparation ici",
   "space": "Ouvert comme lieu d'accueil maintenant"
  },
  "orgKinds": {
   "grassroots": "Groupe citoyen",
   "nonprofit": "Organisme sans but lucratif",
   "faith": "Organisme religieux",
   "public": "Service public",
   "business": "Entreprise",
   "communityOffer": "Offre communautaire"
  },
  "neighbourhoods": {
   "TP": "Thorncliffe Park",
   "FP": "Flemingdon Park"
  },
  "subcats": {
   "Police Station": "Poste de police",
   "Fire Station": "Caserne de pompiers",
   "Food Collaboratives": "Banques alimentaires et programmes alimentaires",
   "Shelter": "Refuges",
   "Faith-Based Organizations": "Communautés religieuses",
   "Legal Services": "Services juridiques",
   "Government Documentation": "Documents gouvernementaux",
   "Schools": "Écoles",
   "Childminding & EarlyON": "Garde d'enfants et EarlyON",
   "Dental Clinics": "Cliniques dentaires",
   "Midwives Clinic": "Sages-femmes",
   "Health Clinics": "Cliniques de santé",
   "Non-Profits": "Organismes communautaires",
   "Community Centres": "Centres communautaires",
   "Public Washrooms": "Toilettes publiques",
   "Libraries": "Bibliothèques",
   "Water Fountains": "Eau potable",
   "Museums": "Musées",
   "Cooling Spaces": "Lieux de rafraîchissement",
   "Multi-Service Agencies": "Agences multiservices",
   "Food Security & Climate Resilience": "Groupes alimentation et climat",
   "Employment & Skills Training": "Emploi et compétences",
   "Family & Parenting Support": "Famille et rôle parental",
   "Social & Cultural Organizations": "Groupes sociaux et culturels",
   "Newcomer Supports": "Soutien aux nouveaux arrivants",
   "Housing & Tenant Supports": "Logement et locataires",
   "Neighbourhood & Individual Empowerment": "Groupes de quartier"
  },
  "hazards": {
   "power": "Panne de courant",
   "flood": "Inondation ou bris de plomberie",
   "elevator": "Panne d'ascenseur",
   "heat": "Chaleur extrême",
   "smoke": "Fumée des feux de forêt",
   "fire": "Incendie et évacuation"
  },
  "stages": {
   "before": "Avant",
   "during": "Pendant",
   "after": "Après"
  },
  "R01": {
   "title": "Choisissez votre langue",
   "preselected": "Choisie d'après votre avis",
   "selected": "Sélectionnée",
   "continue": "Continuer",
   "helperBasic": "Vous aidez quelqu'un? Activez « Texte plus grand, moins d'éléments » pour cette personne.",
   "forwardedNote": "Quelqu'un vous a transmis une alerte. Choisissez d'abord votre langue.",
   "fromPhone": "D'après la langue de votre téléphone",
   "chooseFirst": "Touchez une langue pour continuer.",
   "youChose": "Votre langue :",
   "helperOn": "« Texte plus grand, moins d'éléments » est activé. Il reste activé pour cette personne."
  },
  "R02": {
   "current": "Affiché en ce moment",
   "unavailable": "Pas encore offert dans cette langue",
   "unavailableBody": "Certains éléments de cet écran n'ont pas encore été traduits en {lang}. Nous l'indiquerons partout où c'est le cas.",
   "continueIn": "Continuer en {lang}",
   "chooseOther": "Choisir une autre langue"
  },
  "R03": {
   "getTextAlerts": "Recevoir les alertes par texto",
   "getTextAlertsLine": "Les alertes pour votre immeuble par texto. Pas d'application, pas de compte.",
   "signedUp": "Alertes par texto activées",
   "sent": "Répondez YES sur votre téléphone pour activer les alertes par texto",
   "alertsNow": "Alertes en ce moment",
   "myBuilding": "Votre immeuble",
   "myFloor": "Votre étage",
   "nothingActive": "Rien ne se passe en ce moment.",
   "nothingActiveBody": "Quand quelque chose touche votre immeuble ou votre quartier, cela s'affichera ici en premier.",
   "noBuildingChosen": "Choisissez votre immeuble pour voir ses alertes en premier",
   "ongoing": "En cours",
   "updated": "Mis à jour {t}",
   "posted": "Publié {t}",
   "everyday": "Tous les jours",
   "findHelp": "Trouver de l'aide",
   "map": "Carte",
   "beReady": "Se préparer",
   "findHelpLine": "Services et soutien près de chez vous",
   "mapLine": "Lieux près de chez vous, et ce qui est ouvert maintenant",
   "beReadyLine": "Guides, numéros et prises de nouvelles",
   "archive": "Alertes terminées",
   "basicTurnOn": "Texte plus grand, moins d'éléments",
   "headsUpTitle": "Avant les chaleurs",
   "headsUpFrom": "Un avertissement que vous avez choisi",
   "headsUpGuide": "Lire le guide sur la chaleur",
   "headsUpEvent": "Atelier près de chez vous",
   "ongoingDay": "En cours : jour {n} sur {total}",
   "readAlert": "Lire l'alerte",
   "neighbourhoods": "Thorncliffe Park et Flemingdon Park",
   "headsUpAction": "Une chose à faire maintenant",
   "ambassadorHome": "Ambassadeur : mon immeuble",
   "ambassadorLine": "Publier une mise à jour ou faire votre tournée pour {building}",
   "noBuildingLine": "Les alertes pour votre quartier s'affichent ici. Ajoutez votre immeuble pour voir ses alertes en premier."
  },
  "R04": {
   "deviceLabel": "Texto sur un téléphone de base",
   "from": "Thorncliffe Hub",
   "fromNumber": "Alertes CVH",
   "lockScreen": "Écran verrouillé",
   "now": "maintenant",
   "levelOfficial": "Alerte officielle de {source}.",
   "levelCommunity": "Alerte communautaire du Hub. Vérifiée par le Hub.",
   "fromHub": "Alerte communautaire du Hub",
   "levelAmbassador": "Alerte communautaire d'un ambassadeur de l'immeuble. Pas encore vérifiée.",
   "stop": "Pour arrêter tous les messages du Hub, répondez STOP.",
   "verifiedKeyword": "Pour savoir ce que « vérifié » veut dire, répondez INFO.",
   "ackMore": "D'autres informations suivront.",
   "update": "Mise à jour de l'alerte « {headline} » :",
   "correction": "Correction de l'alerte « {headline} » : {changed}",
   "resolved": "Réglé : « {headline} ». {final}",
   "nearestSpace": "Lieu ouvert le plus proche : {space}, {hours}.",
   "confirmRequest": "Thorncliffe Park Community Hub : quelqu'un a demandé des alertes par texto pour ce téléphone, en {lang}, pour {where}. Pour accepter, répondez YES. Pour arrêter tous les messages du Hub, répondez STOP.",
   "keywordChange": "Répondez GROUPS pour changer les groupes que vous avez choisis.",
   "checkinWithdraw": "Répondez NOCHECK pour arrêter les prises de nouvelles.",
   "link": "Plus d'infos : {url}",
   "sampleLabel": "Message d'exemple. Rien n'est envoyé.",
   "tapOpen": "Touchez le message pour l'ouvrir",
   "back": "Retour à l'application",
   "annotOn": "Quelles lignes sont traduites",
   "annotOff": "Masquer les notes de traduction",
   "bigOn": "Texte le plus grand",
   "bigOff": "Texte normal",
   "tagTemplate": "Modèle vérifié",
   "tagAlert": "Écrit pour cette alerte",
   "annotNote": "La phase 2 est présentée en anglais. Les lignes marquées « Modèle vérifié » existent dans les quinze langues de lancement et ont été vérifiées par des personnes. Les lignes marquées « Écrit pour cette alerte » sont traduites pour chaque alerte. Les versions en ourdou et en grec ne sont pas encore dans ce prototype.",
   "officialNote": "Les alertes officielles partent d'un modèle vérifié par des personnes dans chaque langue. L'alerte communautaire qui suit indique ce qu'elle ajoute ici.",
   "notKnownPrefix": "Pas encore connu : {what}.",
   "you": "Vous",
   "exNote": "Exercice. Seules les personnes inscrites à l'exercice reçoivent ce texto. Les résidents ne reçoivent rien."
  },
  "R05": {
   "title": "Recevoir les alertes par texto",
   "lead": "Nous envoyons un texto quand il se passe quelque chose dans votre immeuble ou votre quartier. Pas d'application, pas de compte, pas de courriel.",
   "required": "Obligatoire",
   "optional": "Facultatif",
   "phone": "Numéro de téléphone",
   "phoneHelp": "Vous pouvez l'écrire comme vous voulez.",
   "phoneShown": "Nous enverrons un texto au {phone}",
   "phoneError": "Ce numéro doit avoir 10 chiffres, par exemple 416 555 0123.",
   "nbhd": "Quartier",
   "building": "Immeuble",
   "floor": "Étage",
   "buildingSearch": "Cherchez votre immeuble",
   "notListed": "Mon immeuble n'est pas dans la liste",
   "notListedResult": "Vous recevrez toutes les alertes pour {nbhd}. Nous avons dit au Hub que votre immeuble manque à la liste.",
   "language": "Langue",
   "languageFrom": "D'après votre premier choix",
   "groupsTitle": "De quels groupes faites-vous partie?",
   "groupsSkip": "Passer cette étape",
   "send": "M'envoyer un texto de confirmation",
   "formError": "Nous ne pouvons pas encore envoyer ceci. Veuillez ajouter : {missing}.",
   "whatYouGet": "Les textos servent seulement aux alertes. Nous n'envoyons jamais de nouvelles quotidiennes ni de publicités par texto.",
   "sentTitle": "Regardez votre téléphone",
   "sentBody": "Nous avons envoyé un message au {phone}. Répondez YES pour commencer à recevoir les alertes.",
   "resend": "L'envoyer de nouveau",
   "fix": "Corriger le numéro",
   "signedUpTitle": "Inscription faite",
   "signedUpBody": "Le {phone} recevra les alertes en {lang}.",
   "noAccount": "Vous n'avez pas besoin de compte.",
   "missingPhone": "un numéro de téléphone à 10 chiffres",
   "missingNbhd": "votre quartier",
   "and": " et ",
   "nbhdError": "Choisissez votre quartier.",
   "change": "Changer",
   "noFloor": "Pas d'étage, seulement l'immeuble",
   "floorN": "Étage {n}",
   "step1": "Étape 1 sur 2",
   "step2": "Étape 2 sur 2",
   "continue": "Continuer",
   "groupsLead": "C'est facultatif. Choisir un groupe vous donne des alertes et des conseils pour ce groupe.",
   "consent": "La personne qui a ce téléphone accepte en répondant YES, y compris pour les groupes choisis ici.",
   "resent": "Nous l'avons envoyé de nouveau au {phone}.",
   "protoSee": "Voir le message arriver sur le téléphone",
   "protoTag": "Prototype",
   "howStop": "Pour arrêter tous les messages du Hub, répondez STOP à n'importe quel texto.",
   "howChange": "Pour changer vos groupes, répondez GROUPS.",
   "toHome": "Aller à Maintenant",
   "sample": "Immeuble d'exemple",
   "moreBuildings": "{n} de plus. Tapez une partie de l'adresse."
  },
  "R06": {
   "thanks": "Merci. Vous recevrez les alertes du Hub pour {where}, en {lang}.",
   "howStop": "Pour arrêter tous les messages, répondez STOP.",
   "howChange": "Pour changer vos groupes, répondez GROUPS.",
   "groupsChanged": "C'est fait. Vous ne recevrez plus les alertes pour : {group}.",
   "checkinWithdrawn": "C'est fait. Votre demande de prise de nouvelles est retirée. Vous recevrez quand même les alertes.",
   "stopped": "Vous ne recevrez plus aucun message du Hub. Pour recommencer, répondez START.",
   "deviceLabel": "Textos sur un téléphone de base",
   "back": "Retour à l'application",
   "replyHint": "Touchez une réponse pour l'envoyer",
   "you": "Vous",
   "groupsMenu": "Répondez avec un numéro pour arrêter les alertes de ce groupe : {list}.",
   "noGroups": "Vous n'avez choisi aucun groupe. Vous recevez toutes les alertes pour {where}.",
   "started": "Bon retour. Vous recevrez les alertes du Hub pour {where}, en {lang}.",
   "now": "maintenant",
   "exNote": "Exercice. Cette conversation est une pratique, sur le téléphone d'une personne inscrite à l'exercice. Aucun résident n'est inscrit ni modifié."
  },
  "R07": {
   "moreComing": "D'autres informations suivront",
   "moreComingLine": "Nous mettrons ceci à jour dès que nous en saurons plus.",
   "notYetKnown": "Pas encore connu",
   "where": "Où",
   "whatToDo": "Quoi faire",
   "validUntil": "Valide {until}",
   "untilResolved": "jusqu'à ce que ce soit réglé",
   "posted": "Publié {t}",
   "updated": "Mis à jour {t}",
   "latest": "Plus récent",
   "thread": "Mises à jour, les plus récentes d'abord",
   "earlier": "Mises à jour précédentes",
   "update": "Mise à jour",
   "correction": "Correction",
   "corrected": "Corrigé {t}",
   "whatChanged": "Ce qui a changé : {changed}",
   "earlierWording": "Formulation précédente",
   "final": "Dernière mise à jour",
   "resolvedTitle": "Réglé {t}",
   "expiredTitle": "Expiré {t}",
   "expiredNote": "Cette alerte a atteint son heure de fin sans dernière mise à jour.",
   "fromArchive": "Cette alerte est terminée. Elle reste ici pour que vous puissiez la lire.",
   "ongoingDays": "En cours : jour {n} sur {total}",
   "supportOffer": "Aide pour ceci",
   "openNear": "Ouvert près de chez vous",
   "openNearAll": "Voir tous les lieux ouverts",
   "officialLink": "Alerte officielle sur le même événement",
   "officialFrom": "De {source}",
   "adds": "Ce message ajoute ce qui se passe dans votre immeuble.",
   "officialText": "Texte officiel",
   "officialTemplate": "Traduit à partir d'un modèle vérifié",
   "guide": "Quoi faire : le guide « {hazard} »",
   "services": "Services qui peuvent aider pour ceci",
   "share": "Partager",
   "amberNote": "Exemple fictif. Ceci montre seulement la mise en page.",
   "ambLine": "Message de l'ambassadeur",
   "readingOrder": "Ordre du lecteur d'écran : origine et vérification, heure de publication, l'alerte, la mention « pas le 911 », puis les actions.",
   "kinds": {
    "ack": "Premier message",
    "alert": "Alerte",
    "issued": "Émise",
    "update": "Mise à jour",
    "correction": "Correction",
    "final": "Dernière mise à jour",
    "ambassador": "Message de l'ambassadeur"
   },
   "whereLabel": "Où",
   "actionLabel": "Quoi faire maintenant",
   "notYetKnownLabel": "Pas encore connu",
   "latestTag": "Plus récent",
   "ambassadorOriginal": "Original, en {lang}",
   "officialCard": "Alerte officielle sur le même événement",
   "openOfficial": "Lire l'alerte officielle",
   "fromCommunity": "Ceci relaie une alerte officielle. Le Hub ajoute ce qui se passe ici.",
   "spacesFiltered": "Lieux qui ne demandent pas de pièce d'identité, selon vos choix.",
   "supportSee": "Voir le lieu",
   "amberBody": "Les alertes AMBER sont des alertes officielles au sujet d'un enfant disparu. Le vrai texte vient toujours d'En Alerte.",
   "endedResolved": "Cette alerte est terminée. Le problème a été réglé {t}.",
   "endedWithdrawn": "Le Hub a retiré cette alerte. {reason}",
   "endedExpired": "Cette alerte est terminée. Elle a expiré {t} sans dernière mise à jour.",
   "validLine": "Valide {until}",
   "timeLine": "Publié {posted} · Mis à jour {updated}",
   "timeLineOne": "Publié {posted}",
   "basicMore": "Mises à jour précédentes : {n}"
  },
  "R08": {
   "title": "Alertes terminées",
   "resolved": "Réglé {t}",
   "expired": "Expiré {t}",
   "empty": "Aucune alerte n'est encore terminée.",
   "emptyBody": "Quand une alerte se termine, elle vient ici et reste lisible.",
   "lead": "Chaque alerte reste lisible ici une fois terminée.",
   "endedOn": "Publié {posted}",
   "backHome": "Retour à Maintenant"
  },
  "R09": {
   "title": "Trouver de l'aide",
   "prompt": "Par exemple : mon propriétaire veut que je déménage",
   "promptAlt": ["Par exemple : j'ai besoin de nourriture pour ma famille cette semaine", "Par exemple : quelqu'un à qui parler de mon stress"],
   "searchLabel": "Dites-nous ce dont vous avez besoin, dans vos propres mots",
   "search": "Chercher",
   "orChoose": "Ou choisissez un sujet",
   "within": "Chercher dans {cat}",
   "clearCat": "Tous les sujets",
   "lead": "Dites ce qui ne va pas, comme vous le diriez à un ami. Vous n'avez pas besoin du nom d'un service.",
   "focusHint": "D'autres choses que les gens écrivent",
   "topic": "Sujet : {cat}",
   "seeAll": "Tout voir dans {cat}",
   "moreTopics": "Afficher les {n} sujets",
   "clear": "Effacer ce que j'ai écrit",
   "testTitle": "Recherches de test",
   "testNote": "Pour les animateurs : touchez-en une pour lancer une recherche préparée tirée du document de cadrage. Les résidents ne voient pas ceci.",
   "testGloss": "(Dari : {gloss})"
  },
  "R10": {
   "title": "Résultats",
   "resultsFor": "{n} résultats pour « {q} »",
   "matched": "Correspond : {reason}",
   "crossLanguage": "Écrit en {lang}, affiché traduit",
   "contributed": "Ajouté par un voisin",
   "filters": "Filtres",
   "helpListTitle": "Services qui peuvent aider pour : {hazard}",
   "helpListNote": "Seuls les services qui disent comment ils peuvent aider pour ceci sont affichés. Classés selon leur pertinence, s'ils sont ouverts maintenant, la distance et la date de leur dernière confirmation.",
   "noMatch": "Aucun lieu gratuit et sans pièce d'identité n'est ouvert en ce moment.",
   "noMatchSuggest": "Si vous retirez « {f} », {n} lieux correspondent. Le plus proche ouvre {when}.",
   "applySuggestion": "Retirer « {f} »",
   "emergency": "Si quelqu'un est blessé en ce moment, appelez le 911.",
   "openNow": "Ouvert maintenant",
   "closedNow": "Fermé maintenant",
   "opensAt": "Ouvre {t}",
   "distance": "{d} km",
   "resultsForOne": "1 résultat pour « {q} »",
   "catTitle": "{cat} : {n} services",
   "catTitleOne": "{cat} : 1 service",
   "changeSearch": "Changer ma recherche",
   "filtersCount": "Filtres ({n})",
   "crossQuery": "Correspondance entre langues. Vous avez écrit en {qlang}; ceci est écrit en {lang}.",
   "noMatchAny": "Rien ne correspond à tous ces filtres.",
   "noMatchSuggestShort": "Si vous retirez « {f} », {n} lieux correspondent.",
   "removeAll": "Retirer tous les filtres",
   "noneTitle": "Nous n'avons pas encore trouvé",
   "noneBody": "Une personne du Hub peut vous aider à trouver le bon service.",
   "toPerson": "Parler à une personne du Hub",
   "showMore": "Afficher {n} de plus",
   "hoursUnknown": "Heures inconnues",
   "communityOffer": "Offre communautaire",
   "inCat": "Sujet : {cat}",
   "helpEmpty": "Aucun service qui peut aider pour ceci ne correspond à ces filtres."
  },
  "R11": {
   "title": "Nous n'avons pas encore trouvé",
   "body": "Une personne du Hub peut vous aider à trouver le bon service.",
   "person": "Parler à l'intervenante communautaire du Hub",
   "call": "Appeler le {phone}",
   "hours": "Ouvert {hours}",
   "visit": "Ou venez au 45 Overlea Boulevard",
   "tryAgain": "Essayer d'autres mots",
   "categories": "Choisir plutôt un sujet",
   "searched": "Vous avez demandé : « {q} ».",
   "navigatorName": "Samira",
   "navigatorRole": "Intervenante communautaire au Hub",
   "navigatorLine": "Elle connaît les services du coin et peut trouver le bon avec vous, au téléphone ou en personne.",
   "sampleName": "Nom d'exemple",
   "openNow": "Ouvert maintenant, jusqu'à {t}",
   "closedNow": "Fermé maintenant. Ouvre {t}",
   "callConfirm": "Dans le vrai CVH, ceci appellerait le {phone}.",
   "directionsConfirm": "Dans le vrai CVH, ceci ouvrirait l'itinéraire vers le 45 Overlea Boulevard.",
   "directions": "Itinéraire",
   "hoursFull": "Du lundi au jeudi de 9 h à 20 h, le vendredi de 9 h à 17 h, le samedi de 10 h à 14 h"
  },
  "R12": {
   "status": "En ce moment",
   "openNow": "Ouvert maintenant, jusqu'à {t}",
   "closed": "Fermé maintenant",
   "opens": "Ouvre {t}",
   "address": "Adresse et comment s'y rendre",
   "directions": "Itinéraire",
   "hours": "Heures",
   "languages": "Langues parlées",
   "cost": "Coût",
   "bring": "Quoi apporter",
   "id": "Vont-ils demander une pièce d'identité ou mon statut?",
   "access": "Accessibilité",
   "contact": "Contact",
   "call": "Appeler",
   "email": "Courriel",
   "website": "Site Web",
   "unknown": "Inconnu",
   "languagesUnknown": "Inconnu. Le Hub ne sait pas quelles langues sont parlées ici.",
   "noAddress": "Pas d'adresse civique",
   "whereToFind": "Où le trouver",
   "confirmedBy": "Confirmé par {org} le {date}",
   "publicSource": "Tiré de sources publiques. Pas encore confirmé par l'organisme.",
   "contributedBy": "Ajouté par un voisin le {date}, vérifié par le Hub",
   "kind": "Type d'organisme",
   "services": "Services",
   "org": "Qui le gère",
   "otherServices": "Voir ce que {org} offre d'autre",
   "onMap": "Voir sur la carte",
   "correct": "Une erreur? Corrigez-la",
   "communityOffer": "Offre communautaire",
   "communityOfferLine": "Offert par des voisins, pas un service officiel.",
   "callConfirm": "Dans le vrai CVH, ceci appellerait le {phone}.",
   "directionsConfirm": "Dans le vrai CVH, ceci ouvrirait l'itinéraire vers {place}.",
   "illustrative": "Détails d'exemple pour le prototype",
   "appointment": "Ai-je besoin d'un rendez-vous?",
   "apptYes": "Oui. Appelez d'abord pour prendre rendez-vous.",
   "apptNo": "Non. Vous pouvez y aller sans rendez-vous.",
   "apptSometimes": "Parfois. Appelez pour vérifier.",
   "unknownCall": "Appelez pour demander avant d'y aller.",
   "unknownAsk": "Demandez au Hub avant d'y aller.",
   "stepFreeYes": "Sans marches.",
   "stepFreeNo": "Il y a des marches.",
   "idNo": "Non.",
   "idYes": "Oui.",
   "emailConfirm": "Dans le vrai CVH, ceci ouvrirait un courriel à {email}.",
   "webConfirm": "Dans le vrai CVH, ceci ouvrirait {web}.",
   "noContact": "Aucun téléphone ni courriel indiqué.",
   "todayTag": "Aujourd'hui",
   "hoursUnknown": "Heures inconnues",
   "seeAll": "Afficher tous les détails",
   "source": "D'où viennent ces informations",
   "derivedNote": "Pour l'instant, le Hub a seulement le nom, le lieu et le type de cette fiche.",
   "addedRecently": "récemment",
   "notFound": "Ce lieu est introuvable.",
   "spaceHours": "Ouvert comme lieu d'accueil aujourd'hui, de {from} à {to}. Autres heures inconnues.",
   "someUnknown": "Certains détails ne sont pas encore connus. {ask}"
  },
  "R13": {
   "services": "Services",
   "about": "À propos",
   "servicesCount": "Services ici : {n}",
   "contact": "Contact",
   "call": "Appeler le {phone}",
   "website": "Site Web",
   "illustrative": "Description d'exemple pour le prototype",
   "webConfirm": "Dans le vrai CVH, ceci ouvrirait {web}.",
   "callConfirm": "Dans le vrai CVH, ceci appellerait le {phone}.",
   "showAll": "Afficher les {n} services",
   "notFound": "Cet organisme est introuvable.",
   "aboutLines": {
    "TNO": "Un organisme communautaire de Thorncliffe Park qui offre au quartier des programmes d'alimentation, d'établissement, d'emploi, pour les jeunes et pour les familles.",
    "HUB": "Le carrefour communautaire au 45 Overlea Boulevard, où de nombreux services et groupes locaux partagent un même immeuble.",
    "TPL": "La bibliothèque publique, avec des livres, des ordinateurs, le Wi-Fi et des programmes gratuits pour tous les âges.",
    "CITY": "Les centres communautaires et programmes de la Ville de Toronto à Thorncliffe Park et Flemingdon Park."
   }
  },
  "R14": {
   "title": "Carte",
   "list": "Liste",
   "mapView": "Carte",
   "loading": "Chargement de la carte",
   "unavailable": "La carte n'a pas pu se charger. La liste contient tout.",
   "showList": "Afficher la liste",
   "noneInView": "Rien ici. Essayez de faire un zoom arrière.",
   "places": "{n} lieux",
   "place": "1 lieu",
   "add": "Ajouter un lieu",
   "rules": "Les règles de cet espace",
   "filters": "De quoi avez-vous besoin?",
   "disruptionView": "Lieux qui peuvent aider pour : {hazard}",
   "legend": "Types de lieux",
   "newlyAdded": "Nouveau",
   "tapForHours": "Touchez un lieu pour voir ses heures",
   "legendFormal": "Un service ou un lieu public",
   "legendInformal": "Un groupe communautaire ou une communauté religieuse",
   "legendOffer": "Une offre communautaire de voisins",
   "legendSpace": "Ouvert comme lieu d'accueil maintenant",
   "legendCluster": "Lieux proches les uns des autres. Touchez pour faire un zoom avant.",
   "legendTitle": "Ce que les formes veulent dire",
   "zoomIn": "Zoom avant",
   "zoomOut": "Zoom arrière",
   "here": "{n} lieux ici",
   "mapLabel": "Carte de Thorncliffe Park et Flemingdon Park",
   "allPlaces": "Afficher tous les lieux",
   "subAll": "Tous les types de lieux",
   "subLabel": "Quel type de lieu?",
   "spaceFor": "Ouvert comme lieu d'accueil maintenant {purpose}",
   "basicList": "Avec le texte plus grand, les lieux s'affichent en liste, du plus proche au plus loin.",
   "noneMatch": "Aucun lieu ne correspond à ces filtres.",
   "addShort": "Ajouter un lieu",
   "missing": "Il manque quelque chose ou il y a une erreur?"
  },
  "R15": {
   "title": "Lieux près de chez vous",
   "byDistance": "Les plus proches d'abord",
   "empty": "Aucun lieu ne correspond à ces filtres.",
   "emptyBody": "Retirez un filtre pour en voir plus.",
   "add": "Ajouter un lieu",
   "count": "{n} lieux",
   "countOne": "1 lieu",
   "more": "Afficher {n} de plus",
   "distanceHome": "{d} km",
   "clearAll": "Retirer tous les filtres",
   "missing": "Il manque quelque chose ou il y a une erreur ici?",
   "suggest": "Si vous retirez « {f} », {n} lieux correspondent. Le plus proche est à {d}.",
   "suggestOne": "Si vous retirez « {f} », 1 lieu correspond. Il est à {d}.",
   "suggestButton": "Retirer « {f} »"
  },
  "R16": {
   "open": "Voir les détails",
   "hoursToday": "Aujourd'hui : {hours}",
   "close": "Fermer",
   "less": "Moins",
   "wrong": "Une erreur sur ce lieu?",
   "distance": "À {d} km de votre secteur",
   "contributed": "Ajouté par un voisin"
  },
  "R17": {
   "title": "Ajouter ou corriger un lieu",
   "add": "Ajouter un lieu qui manque",
   "correct": "Corriger un lieu qui semble faux",
   "fromEntry": "Corriger ce lieu",
   "addLine": "Quelque chose qui aide les voisins et qui n'est pas encore sur la carte. Deux courtes étapes.",
   "correctLine": "Les heures, le lieu ou un détail n'est plus à jour.",
   "fromEntryLine": "Changez seulement ce qui est faux. Tout le reste ne change pas.",
   "lookingAt": "Vous regardiez",
   "pickTitle": "Quel lieu semble faux?",
   "pickHint": "Les plus proches de vous d'abord. Chaque lieu a aussi « Une erreur? Corrigez-la » sur sa page.",
   "addDifferent": "Ajouter un autre lieu qui manque"
  },
  "R18": {
   "title": "Avant d'ajouter un lieu",
   "continue": "Je comprends, continuer",
   "step": "Étape 1 sur 2 : les règles",
   "readIn": "Lire les règles en",
   "readInHint": "Les règles sont écrites dans toutes les langues offertes par le CVH.",
   "after": "Ensuite, vous nous parlez du lieu. Vous aurez surtout à choisir, pas à écrire."
  },
  "R19": {
   "title": "Ajouter un lieu",
   "name": "Comment s'appelle-t-il?",
   "what": "Ce qui s'y passe, en une phrase",
   "whatHint": "Jusqu'à 140 caractères",
   "category": "Quel type d'aide est-ce?",
   "type": "Est-ce un service officiel ou une offre communautaire?",
   "official": "Un service officiel",
   "offer": "Une offre communautaire de voisins",
   "hours": "Quand est-ce ouvert?",
   "sameWeekdays": "Pareil tous les jours de semaine",
   "notSure": "Pas sûr",
   "from": "De",
   "to": "À",
   "closedDay": "Fermé",
   "cost": "Combien ça coûte?",
   "idQ": "Vont-ils demander une pièce d'identité ou un statut?",
   "stepFreeQ": "Peut-on entrer sans marches?",
   "languagesQ": "Quelles langues y sont parlées?",
   "location": "Où est-ce?",
   "submit": "Envoyer au Hub",
   "optional": "Facultatif",
   "ready": "Prêt à envoyer",
   "saved": "Enregistré sur ce téléphone",
   "step": "Étape 2 sur 2 : le lieu",
   "choose": "Choisissez-en un",
   "catNotSure": "Pas sûr",
   "offerLine": "Offert par des voisins, pas un service officiel. Il s'affiche sur la carte avec un contour en pointillé.",
   "officialLine": "Géré par un organisme, une agence ou la Ville.",
   "whereBtn": "Indiquer où c'est",
   "whereChange": "Changer",
   "whereNone": "Pas encore choisi",
   "costFree": "Gratuit",
   "costLow": "Peu coûteux",
   "costFee": "Payant",
   "yes": "Oui",
   "no": "Non",
   "weekdays": "Du lundi au vendredi",
   "langsHint": "Choisissez toutes les réponses qui s'appliquent.",
   "count": "{n} sur 140",
   "missingTitle": "Ajoutez ceci, puis envoyez :",
   "resubmitNote": "Le Hub vous a renvoyé ceci. {change}",
   "closedOpt": "Fermé",
   "notSureOpt": "Pas sûr",
   "toOpt": "Jusqu'à",
   "fromOpt": "Ouvre",
   "hoursNotSureLine": "Ce n'est pas grave. Le Hub posera la question au lieu.",
   "whatPh": "Par exemple : épicerie gratuite le jeudi soir, pour tout le monde",
   "namePh": "Par exemple : banque alimentaire du jeudi"
  },
  "R20": {
   "title": "Où est-ce?",
   "pin": "Mettre une épingle sur la carte",
   "building": "Dans un immeuble",
   "described": "Décrivez où c'est dans l'immeuble",
   "describedHint": "Par exemple : la salle communautaire derrière la mosquée",
   "landmark": "Près d'un point de repère",
   "landmarkHint": "Par exemple : près des jeux d'eau du parc R.V. Burgess",
   "address": "Adresse civique",
   "noAddress": "Vous n'avez pas besoin d'une adresse civique.",
   "howTitle": "Comment les gens peuvent-ils le trouver?",
   "use": "Utiliser ce lieu",
   "pinHint": "Déplacez la carte jusqu'à ce que l'épingle soit sur le lieu.",
   "pinNear": "Une épingle sur la carte, près de {place}",
   "nearLandmark": "Près de {place}",
   "buildingChoose": "Choisir un immeuble",
   "landmarkChoose": "Choisir un point de repère",
   "landmarkMore": "Autre chose qui aide les gens à le trouver",
   "addressHint": "Seulement si vous la connaissez.",
   "needOne": "Choisissez une des façons ci-dessus.",
   "needBuilding": "Choisissez d'abord l'immeuble.",
   "needLandmark": "Choisissez d'abord le point de repère.",
   "needAddress": "Tapez d'abord l'adresse.",
   "pinWhere": "L'épingle est près de {place}.",
   "mapLabel": "Carte pour placer l'épingle"
  },
  "R21": {
   "title": "Envoyé au Hub",
   "general": "Une personne du Hub le lira d'ici environ une semaine. Nous vous dirons quand il sera sur la carte.",
   "ambassador": "Vous êtes ambassadeur, donc ceci est vérifié en priorité. C'est habituellement sur la carte en moins d'une journée.",
   "lane": "Type de vérification : {lane}",
   "laneGeneral": "Vérification communautaire",
   "laneAmbassador": "Vérification ambassadeur, plus rapide",
   "youSent": "Vous avez envoyé : {name}",
   "next": "Ce qui se passe ensuite",
   "n1": "Une personne du Hub le lit.",
   "n2": "S'il respecte les règles, il est ajouté à la carte et à la recherche.",
   "n3": "S'il faut changer quelque chose, nous vous disons quoi, et vous pouvez l'envoyer de nouveau.",
   "n1Amb": "Une personne du Hub le lit avant la file d'attente générale.",
   "howLong": "Combien de temps",
   "weekLine": "Environ une semaine",
   "dayLine": "Habituellement en moins d'une journée",
   "toMap": "Retour à la carte",
   "another": "Ajouter un autre lieu",
   "protoLabel": "Prototype seulement",
   "protoDecline": "Voir un lieu que le Hub a renvoyé",
   "protoAccepted": "Voir un lieu ajouté par un voisin, sur la carte"
  },
  "R22": {
   "title": "Corriger ce lieu",
   "changeOne": "Changez ce qui est faux. Tout le reste ne change pas.",
   "submit": "Envoyer la correction",
   "sent": "Merci. Le Hub vérifiera le changement.",
   "change": "Changer",
   "changedTag": "Changé",
   "was": "Avant : {v}",
   "undo": "Annuler",
   "nothingYet": "Changez au moins une chose, puis envoyez.",
   "doneEditing": "Terminé",
   "onlyThis": "Seul ce que vous changez est envoyé. Le Hub le vérifie avant que le lieu soit mis à jour.",
   "toPlace": "Retour au lieu",
   "toMap": "Retour à la carte",
   "sentTitle": "Correction envoyée",
   "whatChanged": "Ce que vous avez changé",
   "whereLabel": "Où c'est",
   "namePlace": "Nom"
  },
  "R23": {
   "title": "Votre lieu n'a pas encore été ajouté",
   "reason": "Pourquoi",
   "whatToChange": "Quoi changer",
   "resubmit": "Le changer et l'envoyer de nouveau",
   "kept": "Tout ce que vous avez écrit est gardé.",
   "sentAgo": "Vous avez envoyé ceci {t}.",
   "youWrote": "Ce que vous avez écrit",
   "whereNone": "Aucun lieu indiqué",
   "toMap": "Retour à la carte",
   "reasons": {
    "advert": {
     "why": "Il vend quelque chose ou demande de l'argent. Le CVH n'est pas un marché.",
     "change": "S'il y a une partie gratuite que tout le monde peut utiliser, décrivez seulement cette partie. N'indiquez ni prix ni paiement."
    },
    "noLocation": {
     "why": "Nous n'avons pas pu savoir où c'est.",
     "change": "Ajoutez un immeuble, un point de repère proche ou une épingle sur la carte. Vous n'avez pas besoin d'une adresse civique."
    },
    "duplicate": {
     "why": "Ce lieu est déjà sur la carte.",
     "change": "Si quelque chose est faux, ouvrez-le et choisissez plutôt « Corrigez-la »."
    },
    "unclear": {
     "why": "Nous n'avons pas pu savoir de quel lieu il s'agit ni ce qui s'y passe.",
     "change": "Donnez son nom et dites en une phrase ce que les gens peuvent y obtenir."
    },
    "outOfArea": {
     "why": "Il est en dehors de Thorncliffe Park et de Flemingdon Park.",
     "change": "Le CVH montre seulement les lieux situés dans ces deux quartiers ou tout près."
    },
    "notCommunity": {
     "why": "Il n'est pas ouvert à tout le monde dans le quartier.",
     "change": "Envoyez-le de nouveau si n'importe qui du quartier peut l'utiliser."
    }
   }
  },
  "R24": {
   "title": "Se préparer",
   "lead": "Quoi faire avant, pendant et après les six types de perturbations qui arrivent ici.",
   "numbers": "Numéros dont je pourrais avoir besoin",
   "headsUp": "Un avertissement avant chaque saison",
   "checkin": "Demander qu'on prenne de vos nouvelles pendant la chaleur et les pannes",
   "readTime": "Lecture de {n} minutes",
   "guides": "Guides : quoi faire avant, pendant et après",
   "more": "D'autres façons d'être prêt",
   "checkinLine": "L'ambassadeur de votre étage prend de vos nouvelles. Ce n'est pas un service d'urgence.",
   "numbersLine": "911, 211, 311, Toronto Hydro et le Hub",
   "headsUpLine": "Dans le CVH seulement, jamais par texto",
   "none": "Les guides n'ont pas pu se charger en ce moment. Si quelqu'un est en danger, appelez le 911."
  },
  "R25": {
   "stagesNav": "Aller à",
   "aiLabel": "Écrit par IA pour le prototype. Des personnes le vérifieront avant le lancement du CVH.",
   "kit": "Ce guide correspond à la trousse de préparation locale imprimée.",
   "numbers": "Numéros dont je pourrais avoir besoin",
   "services": "Services qui peuvent aider",
   "spaces": "Lieux ouverts pour {purpose}",
   "forYou": "Pour vous d'abord",
   "fullGuide": "Le guide complet",
   "next": "Suite : {stage}",
   "stageNow": "Vous lisez : {stage}",
   "unavailable": "Ce guide n'est pas encore offert en {lang}.",
   "guideWord": "Guide",
   "readTime": "Lecture de {n} minutes",
   "helpTitle": "Aide pour ceci",
   "tailoredLink": "Adapté à vos choix",
   "allSteps": "Afficher les {n} étapes",
   "purposeWords": {
    "cooling": "se rafraîchir",
    "cleanAir": "respirer de l'air pur",
    "charging": "recharger"
   },
   "endLine": "C'est la dernière partie de ce guide. Si vous avez besoin de plus d'aide :",
   "numbersLine": "911, 211, 311, Toronto Hydro et le Hub",
   "openedDuring": "Ouvert à « Pendant » parce que cela se passe maintenant."
  },
  "R26": {
   "title": "De quels groupes faites-vous partie?",
   "lead": "Choisissez ceux qui vous correspondent. Cela change les alertes que vous recevez et les conseils que vous voyez. Nous ne demandons jamais pourquoi.",
   "skipLine": "Passer cette étape ne change rien aux alertes que vous recevez.",
   "helperConfirm": "J'aide quelqu'un. Cette personne est d'accord avec ces choix.",
   "helperNote": "Demandez-lui d'abord, s'il vous plaît.",
   "step": "Étape 1 sur 2",
   "checkinNext": "Ensuite, vous choisissez votre immeuble et votre étage, puis comment vous voulez qu'on prenne de vos nouvelles.",
   "helperNeeded": "Demandez-lui d'abord, s'il vous plaît. Cochez la case quand la personne est d'accord, ou passez cette question.",
   "save": "Enregistrer",
   "saved": "Enregistré. Cela s'applique maintenant.",
   "choose": "Choisissez ceux qui vous correspondent",
   "helping": "Vous aidez quelqu'un à faire ceci?"
  },
  "R27": {
   "title": "Filtres",
   "apply": "Afficher {n} résultats",
   "clear": "Tout effacer",
   "lead": "Répondez seulement aux questions qui comptent pour vous. Le reste reste ouvert.",
   "openNowOnly": "Seulement les lieux ouverts maintenant",
   "anyLang": "Toutes les langues",
   "langHint": "Affiche les lieux où quelqu'un la parle. Les lieux qui ne nous l'ont pas dit sont exclus.",
   "noIdHint": "Affiche seulement les lieux qui ont dit au Hub qu'ils ne demanderont pas de pièce d'identité, de papiers ni de statut d'immigration pour vous aider. Les lieux qui ne nous l'ont pas dit sont exclus, pour qu'on ne vous le demande pas une fois sur place.",
   "private": "Vos réponses restent sur ce téléphone. Elles ne sont ni enregistrées ni envoyées à personne.",
   "fromChoices": "D'après vos choix",
   "cancel": "Retour sans changement",
   "applyOne": "Afficher 1 résultat",
   "moreQuestions": "Plus de questions ({n})",
   "applyNone": "Appliquer (rien ne correspond pour l'instant)"
  },
  "R28": {
   "title": "Ce que « vérifié » veut dire",
   "body": "Vérifié veut dire qu'une personne du Hub, ou d'un organisme partenaire avec qui le Hub travaille, a vérifié cette alerte auprès des gens sur place avant qu'elle soit envoyée.",
   "who": "{org} a vérifié cette alerte {t}.",
   "notYet": "Pas encore vérifié veut dire que l'alerte vient d'un ambassadeur d'immeuble, qui est souvent le premier au courant. Le Hub la vérifie dès qu'il le peut.",
   "official": "Les alertes officielles viennent de {source} et sont transmises sans changer leurs mots.",
   "notFalse": "Pas encore vérifié ne veut pas dire que c'est faux.",
   "thisAlert": "Cette alerte",
   "ambFirst": "Elle a d'abord été publiée {t} par un ambassadeur de l'immeuble {building}.",
   "ambPosted": "Elle a été publiée {t} par un ambassadeur de l'immeuble {building}.",
   "notYetAct": "Vous pouvez agir dès maintenant. Quand le Hub l'aura vérifiée, elle indiquera plutôt « Vérifié par le Hub ».",
   "correctedLine": "Elle a été corrigée {t}. L'alerte montre ce qui a changé, et la formulation précédente reste lisible.",
   "officialAdds": "Le Hub ne change jamais les mots d'une alerte officielle. Il peut ajouter ce qui se passe dans votre immeuble dans sa propre alerte communautaire.",
   "legendTitle": "Les mots que vous verrez sur les alertes",
   "thisOne": "Cette alerte",
   "legendVerified": "Une personne du Hub ou d'un partenaire l'a vérifiée avant qu'elle soit envoyée.",
   "legendUnverified": "Publiée par un ambassadeur d'immeuble. Le Hub ne l'a pas encore vérifiée.",
   "legendOfficial": "D'une source gouvernementale, transmise mot pour mot.",
   "backToAlert": "Retour à l'alerte"
  },
  "R29": {
   "title": "Partager cette alerte",
   "preview": "Voici ce que vos voisins recevront",
   "everyone": "Tout le monde reçoit cette version. Rien d'adapté à vous n'est partagé.",
   "notRecorded": "Le CVH ne garde pas de trace de qui partage les alertes ni à qui vous les envoyez.",
   "send": "Partager",
   "handed": "Les options de partage de votre téléphone s'ouvriraient ici.",
   "lead": "Vos voisins reçoivent l'alerte telle que le Hub l'a écrite, avec sa source et un lien vers la version la plus récente.",
   "postedAt": "Publié {t}",
   "updatedAt": "Mis à jour {t}",
   "todayAt": "aujourd'hui à {time}",
   "dayAt": "{day} à {time}",
   "linkLine": "Dernières mises à jour et corrections : {url}",
   "sendLine": "Votre téléphone vous demandera avec quelle application l'envoyer.",
   "placeMore": "et {n} de plus"
  },
  "R30": {
   "deviceLabel": "L'alerte dans un groupe WhatsApp",
   "group": "Voisins du 4e étage",
   "openedLater": "Ouvert plus tard : on voit la dernière mise à jour et une correction.",
   "groupBuilding": "Voisins de {building}",
   "members": "{name}, Maria, vous et 9 autres",
   "membersOut": "Maria, Farhan et 10 autres",
   "today": "Aujourd'hui",
   "forwarded": "Transféré",
   "you": "Vous",
   "askLine": "Est-ce que d'autres ont une panne de courant?",
   "askLineOther": "Quelqu'un sait ce qui se passe avec l'ascenseur?",
   "proto": "Prototype",
   "backToApp": "Retour à l'application",
   "removeLink": "Retirer le lien",
   "restoreLink": "Remettre le lien",
   "openLater": "Ouvrir le lien, des heures plus tard",
   "senderLang": "{name} lit le CVH en {lang}. Le lien s'ouvre dans la langue de la personne qui l'ouvre, pas dans celle de l'expéditeur.",
   "linkRemovedNote": "Le lien a été retiré. Le message dit quand même ce qui s'est passé, où, de qui il vient, s'il est vérifié, quand, et quoi faire.",
   "sinceSent": "Depuis que {name} a envoyé ceci :",
   "showSince": "Voir ce qui a changé",
   "noChange": "Ouvert plus tard : rien de nouveau n'a été publié depuis l'envoi.",
   "nowVerified": "Ouvert plus tard : le Hub a depuis vérifié cette publication, donc l'alerte indique maintenant « Vérifié par le Hub ».",
   "exNote": "Exercice. Si un message de pratique est transféré, le mot « Exercice » le suit en première ligne, pour que personne ne le prenne pour une vraie alerte."
  },
  "R31": {
   "title": "Numéros dont je pourrais avoir besoin",
   "emergency": "Urgence",
   "emergencyWhen": "Appelez le 911 si la vie ou la sécurité de quelqu'un est en danger en ce moment : un incendie, une urgence médicale ou un crime en train de se produire.",
   "p211": "Aide pour trouver des services communautaires, sociaux et gouvernementaux",
   "p311": "Services de la Ville de Toronto et problèmes non urgents",
   "hydro": "Signaler une panne de courant à Toronto Hydro",
   "hub": "Parler à une personne du Hub",
   "building": "Le {role} de votre immeuble",
   "noBuilding": "Nous n'avons pas encore de contact pour votre immeuble. L'ambassadeur de votre étage peut vous aider.",
   "call": "Appeler",
   "callConfirm": "Dans le vrai CVH, ceci appellerait le {number}.",
   "lead": "Chaque numéro est classé selon ce à quoi il sert.",
   "others": "Pour tout le reste",
   "call911": "Appeler le 911",
   "buildingTitle": "Votre immeuble",
   "noBuildingNoAmb": "Nous n'avons pas encore de contact pour votre immeuble. Le Hub peut vous aider à joindre la gestion de votre immeuble.",
   "noBuildingChosen": "Choisissez votre immeuble et nous afficherons son contact ici quand nous en aurons un. D'ici là, le Hub peut vous aider.",
   "chooseBuilding": "Choisir votre immeuble",
   "ambRoute": "Cette personne habite dans votre immeuble et peut transmettre des choses à la gestion de l'immeuble.",
   "hubHours": "Ouvert du lundi au jeudi de 9 h à 20 h, le vendredi de 9 h à 17 h, le samedi de 10 h à 14 h",
   "calling": "Appeler {what}",
   "roles": {
    "superintendent": "concierge"
   },
   "checked": "Vérifié par le Hub, dernière mise à jour le {date}",
   "noOthers": "Les autres numéros n'ont pas pu se charger en ce moment. Réessayez dans quelques minutes."
  },
  "R32": {
   "title": "Un avertissement avant chaque saison",
   "lead": "Un court rappel dans le CVH avant la chaleur, la fumée et les pannes d'hiver, avec une ou deux choses à faire.",
   "never": "Les avertissements de saison s'affichent seulement dans le CVH. Ils n'arrivent jamais par texto.",
   "on": "Avertissements de saison activés",
   "off": "Avertissements de saison désactivés",
   "season": "Quand : {season}",
   "switchLabel": "M'afficher un avertissement avant chaque saison",
   "what": "Ce que vous verriez",
   "whatOn": "Ce que vous verrez",
   "titles": {
    "heat": "Avant les chaleurs",
    "smoke": "Avant la saison de la fumée des feux de forêt",
    "winter": "Avant les tempêtes d'hiver"
   },
   "readGuide": "Lire le guide « {hazard} »",
   "turnedOn": "Avertissements de saison activés. Vous les verrez dans Maintenant, dans le CVH seulement.",
   "turnedOff": "Avertissements de saison désactivés. Rien d'autre n'a changé.",
   "offLine": "Les avertissements de saison sont désactivés jusqu'à ce que vous les activiez.",
   "whereLine": "Ils s'affichent sur l'écran Maintenant, quelques semaines avant chaque saison."
  },
  "R33": {
   "title": "Demander qu'on prenne de vos nouvelles",
   "what": "Lors d'un avertissement de chaleur ou d'une panne de courant dans votre immeuble, l'ambassadeur de votre étage prendra de vos nouvelles et peut vous aider à joindre les services dont vous avez besoin.",
   "notEmergency": "La prise de nouvelles n'est pas un service d'urgence.",
   "how": "Comment voulez-vous qu'on prenne de vos nouvelles?",
   "call": "Un appel téléphonique",
   "text": "Un texto",
   "knock": "Quelqu'un cogne à la porte",
   "unit": "Numéro d'appartement",
   "unitWhy": "Nous demandons votre numéro d'appartement seulement pour que votre ambassadeur sache à quelle porte cogner.",
   "building": "Votre immeuble et votre étage",
   "noAmbassador": "Il n'y a pas encore d'ambassadeur à l'étage {floor}, donc nous ne pouvons pas promettre de prendre de vos nouvelles.",
   "hubInstead": "Appelez plutôt le Hub au {phone}. Nous sommes ouverts {hours}.",
   "request": "Demander qu'on prenne de mes nouvelles",
   "requested": "Prise de nouvelles demandée",
   "requestedBody": "Lors d'un avertissement de chaleur ou d'une panne de courant à {building}, l'ambassadeur de votre étage prendra de vos nouvelles par {method}.",
   "withdraw": "Arrêter les prises de nouvelles",
   "withdrawn": "Prises de nouvelles arrêtées. Vous recevrez quand même les alertes.",
   "helper": "J'aide quelqu'un. Cette personne est d'accord pour demander qu'on prenne de ses nouvelles.",
   "whatTitle": "Ce qu'est une prise de nouvelles",
   "askPlace": "Nous avons besoin de votre immeuble et de votre étage pour savoir si un ambassadeur d'étage peut prendre de vos nouvelles.",
   "chooseBuilding": "Choisir votre immeuble",
   "chooseFloor": "Choisir votre étage",
   "floorN": "Étage {n}",
   "change": "Changer",
   "placeLine": "{building}, étage {floor}",
   "covered": "Un ambassadeur d'étage s'occupe de l'étage {floor}.",
   "callHub": "Appeler le Hub",
   "stillAlerts": "Vous recevrez quand même toutes les alertes pour votre immeuble.",
   "needMethod": "Choisissez comment vous voulez qu'on prenne de vos nouvelles.",
   "needUnit": "Ajoutez votre numéro d'appartement pour qu'on cogne à votre porte, ou choisissez un appel ou un texto.",
   "needHelper": "Demandez-lui d'abord, s'il vous plaît. Cochez la case quand la personne est d'accord.",
   "needPlace": "Choisissez d'abord votre immeuble et votre étage.",
   "howWithdraw": "Vous pouvez arrêter les prises de nouvelles à tout moment : ici, dans Mes choix, ou en répondant NOCHECK à un texto du Hub.",
   "changeHow": "Changer la façon",
   "again": "Redemander qu'on prenne de mes nouvelles",
   "unitShown": "Appartement {unit}",
   "continue": "Continuer",
   "skip": "Pas maintenant",
   "helping": "Vous aidez quelqu'un à faire ceci?"
  },
  "R34": {
   "title": "Ce que j'ai dit au CVH",
   "lead": "Seulement ce que vous avez choisi. Changez ou retirez n'importe quoi ici. Les changements s'appliquent tout de suite.",
   "language": "Langue",
   "building": "Immeuble et étage",
   "basic": "Texte plus grand, moins d'éléments",
   "groups": "Groupes",
   "checkin": "Prises de nouvelles",
   "headsUp": "Avertissements de saison",
   "change": "Changer",
   "remove": "Retirer",
   "removed": "Retiré. Cela s'applique maintenant.",
   "nothing": "Vous n'avez encore rien dit au CVH.",
   "onDevice": "Ces choix sont gardés sur cet appareil seulement.",
   "invite": "Pour recevoir sur votre téléphone les alertes pour votre immeuble et vos groupes, activez les alertes par texto. Cela prend une minute et ne demande pas de compte.",
   "inviteYes": "Activer les alertes par texto",
   "inviteNo": "Pas maintenant",
   "fromTailored": "Les conseils sous « Ce que cela veut dire pour vous » viennent seulement des choix de cette page. Changez-les ici et les conseils changent aussi.",
   "neighbourhoodOnly": "Toutes les alertes pour {nbhd}",
   "floorOf": "{building}, étage {floor}",
   "on": "Activé",
   "setByHelper": "Activé par une personne qui vous aide",
   "checkinNone": "Pas demandé",
   "checkinAsk": "Demander qu'on prenne de vos nouvelles",
   "checkinBy": "Par {method}",
   "checkinNoAmb": "Pas encore d'ambassadeur à votre étage. Le Hub peut vous aider à la place.",
   "unitLine": "Appartement {unit}, seulement pour cogner à la porte",
   "textAlerts": "Alertes par texto",
   "textOn": "Activées, au {phone}",
   "textPending": "En attente de votre réponse YES au {phone}",
   "howStop": "Pour arrêter, répondez STOP à n'importe quel texto du Hub.",
   "removedItem": "Retiré : {item}",
   "tellUs": "Vous pouvez dire au CVH :",
   "whereLive": "Où vous habitez",
   "whichGroups": "De quels groupes vous faites partie",
   "turnOff": "Désactiver",
   "changeGroups": "Changer les groupes",
   "groupsNone": "Aucun choisi",
   "chooseGroups": "Choisir des groupes",
   "langNote": "La langue dans laquelle vous lisez le CVH.",
   "removedBuildingOne": "1 immeuble que vous aviez enregistré n'est plus dans la liste des immeubles, donc il a été retiré.",
   "removedBuildingMany": "{n} immeubles que vous aviez enregistrés ne sont plus dans la liste des immeubles, donc ils ont été retirés.",
   "removedFloorOne": "1 étage que vous aviez enregistré n'existe plus, donc il a été retiré.",
   "removedFloorMany": "{n} étages que vous aviez enregistrés n'existent plus, donc ils ont été retirés.",
   "removedRest": "Tout le reste de vos choix n'a pas changé.",
   "clearAll": "Tout effacer",
   "clearTitle": "Tout effacer de ce téléphone?",
   "clearBody": "Ceci retire votre langue, vos groupes, vos immeubles et vos étages de ce téléphone. Vous recommencerez en choisissant une langue.",
   "clearYes": "Oui, tout effacer",
   "loading": "Chargement de vos immeubles...",
   "listFailed": "La liste des immeubles n'a pas pu se charger pour l'instant. Vos choix sont toujours enregistrés.",
   "buildingByRsn": "Immeuble {rsn}",
   "floorsOne": "1 étage choisi",
   "floorsMany": "{n} étages choisis",
   "buildingsNone": "Aucun choisi",
   "removeItem": "Retirer : {item}"
  },
  "R35": {
   "title": "Recevoir les alertes pour votre immeuble",
   "lead": "Choisissez où vous habitez pour voir les alertes de votre immeuble en premier. Chaque étape est facultative.",
   "nbhd": "Quartier",
   "building": "Immeuble",
   "floor": "Étage",
   "nbhdOnly": "Seulement le quartier en entier",
   "floorLine": "Si vous choisissez un étage, vous recevez aussi les alertes pour votre étage seulement, comme une panne d'ascenseur ou une coupure d'eau.",
   "noUnit": "Nous ne demandons jamais votre numéro d'appartement ici.",
   "preselected": "D'après votre avis",
   "skipLine": "Si vous passez cette étape, vous voyez quand même toutes les alertes pour votre quartier.",
   "finishedTitle": "Vous avez choisi",
   "invite": "Pour recevoir sur votre téléphone les alertes pour votre immeuble, votre étage et vos groupes, activez les alertes par texto. Cela prend une minute et ne demande pas de compte.",
   "inviteYes": "Activer les alertes par texto",
   "inviteNo": "Pas maintenant",
   "helper": "J'aide quelqu'un. Cette personne est d'accord avec ce choix.",
   "step": "Étape 2 sur 2",
   "buildingSearch": "Cherchez votre immeuble",
   "more": "{n} de plus. Tapez une partie de l'adresse pour trouver le vôtre.",
   "noMatch": "Aucun immeuble ne correspond à « {q} ».",
   "change": "Changer",
   "noFloor": "Pas d'étage, seulement l'immeuble",
   "floorN": "Étage {n}",
   "sample": "Immeuble d'exemple",
   "nextCheckin": "Ensuite : comment vous voulez qu'on prenne de vos nouvelles.",
   "helperNeeded": "Demandez-lui d'abord, s'il vous plaît. Cochez la case quand la personne est d'accord, ou passez cette question.",
   "save": "Enregistrer",
   "saved": "Enregistré. Cela s'applique maintenant.",
   "both": "Thorncliffe Park et Flemingdon Park",
   "nothingSummary": "Rien pour l'instant. Vous verrez toutes les alertes pour Thorncliffe Park et Flemingdon Park.",
   "everyAlert": "Toutes les alertes pour {nbhd}",
   "floorOf": "{building}, étage {floor}",
   "checkinBy": "Prises de nouvelles par {method}",
   "changeAll": "Changer vos choix",
   "toHome": "Aller à Maintenant",
   "manyLine": "Choisissez votre immeuble ou celui d'un proche. Vous pouvez en choisir autant que vous voulez.",
   "chosenNone": "Aucun immeuble choisi pour l'instant",
   "chosenOne": "1 immeuble choisi",
   "chosenMany": "{n} immeubles choisis",
   "floorsIn": "Étages de {building}. Facultatif.",
   "noFloorsListed": "Aucun étage n'est encore indiqué pour cet immeuble.",
   "loading": "Chargement de la liste des immeubles...",
   "loadFailed": "La liste des immeubles n'a pas pu se charger. Vérifiez votre connexion et réessayez, ou passez cette étape.",
   "retry": "Réessayer"
  },
  "A01": {
   "title": "Mon immeuble",
   "assigned": "Vous êtes l'ambassadeur pour {building}, étages {floors}.",
   "canPost": "Vous pouvez publier des mises à jour pour n'importe quel étage de {building}.",
   "post": "Publier une mise à jour de l'immeuble",
   "active": "En cours dans votre immeuble",
   "nothing": "Rien en cours dans votre immeuble.",
   "round": "Tournée de prise de nouvelles : {n} à vos étages",
   "openRound": "Ouvrir ma tournée",
   "role": "Ambassadeur d'immeuble",
   "roundFloors": "Votre tournée : étages {a} à {b}.",
   "offline": "Pas de réseau. Ce que vous faites est enregistré sur votre téléphone et sera envoyé quand vous aurez du réseau.",
   "noRound": "Pas de tournée de prise de nouvelles en ce moment. Elle commence quand le Hub envoie une alerte de chaleur ou de panne de courant pour votre immeuble.",
   "toDo": "Encore {n} à faire",
   "tellInPerson": "{n} ménages à prévenir en personne",
   "practice": "Tournée de pratique",
   "myRound": "Ma tournée",
   "myPosts": "Vos mises à jour",
   "postedAgo": "Publié {t}",
   "fromHub": "Du Hub",
   "fromAmb": "D'un ambassadeur d'immeuble",
   "fromOfficial": "Alerte officielle",
   "fromPartner": "D'un partenaire",
   "verifiedWord": "Vérifié",
   "notVerifiedWord": "Pas encore vérifié"
  },
  "A02": {
   "title": "Publier une mise à jour de l'immeuble",
   "types": "Que se passe-t-il? Choisissez toutes les réponses qui s'appliquent",
   "floors": "Quels étages?",
   "wholeBuilding": "Tout l'immeuble",
   "range": "De l'étage {a} à {b}",
   "pick": "Choisir les étages",
   "photo": "Ajouter une photo",
   "line": "Ajouter une ligne",
   "lineRequired": "Dites ce qui se passe, en une ligne",
   "optional": "Facultatif",
   "other911": "Si quelqu'un est en danger, appelez d'abord le 911.",
   "appearsAs": "Ceci apparaîtra comme : Ambassadeur d'immeuble, {building}",
   "goesNow": "Ceci sera envoyé maintenant.",
   "waits": "Le Hub vérifiera ceci avant que ce soit envoyé.",
   "post": "Publier la mise à jour",
   "notOffered": "Les alertes de chaleur et de fumée viennent du Hub, pour tout le quartier.",
   "exOutcome": "Pratique : ceci va seulement au Hub. Rien n'est envoyé aux résidents.",
   "exNote": "Exercice : cette publication est une pratique. Elle va seulement au Hub, jamais aux résidents.",
   "typeMore": {
    "fire": "alarme ou évacuation",
    "water": "ou plomberie"
   },
   "required": "Obligatoire",
   "wholeLine": "Les {n} étages",
   "mineLabel": "Étages {a} à {b}",
   "mineLine": "Votre tournée",
   "pickLabel": "Choisir les étages",
   "pickLine": "Touchez le premier étage, puis le dernier",
   "pickNone": "Aucun étage choisi pour l'instant",
   "pickOne": "Étage {a}",
   "pickRange": "Étages {a} à {b}",
   "floorAria": "Étage {n}",
   "more": "Ajoutez-en plus si vous voulez",
   "photoAdded": "Photo ajoutée (exemple)",
   "remove": "Retirer",
   "lineAdded": "Votre ligne",
   "ownLine": "Ou écrivez votre propre ligne",
   "sampleBn": "Ligne d'exemple en bengali",
   "sampleTag": "Prototype",
   "mtNote": "Les résidents qui lisent dans une autre langue la voient avec la mention « Traduit automatiquement ».",
   "phrases": ["Le personnel de l'immeuble a été prévenu.", "Prenez l'escalier avec prudence.", "Prenez des nouvelles des voisins qui pourraient avoir besoin d'aide."],
   "otherPhrases": ["La porte d'entrée ne se verrouille pas.", "Les lumières du corridor sont éteintes.", "La chute à déchets est bloquée."],
   "otherFirst": "Si quelqu'un est en danger, appelez d'abord le 911. Ensuite, dites ici ce qui se passe.",
   "someWait": "Un de ces types attend toujours le Hub, donc cette mise à jour attend aussi.",
   "offlineBar": "Pas de réseau en ce moment. C'est enregistré sur votre téléphone et sera envoyé quand vous aurez du réseau.",
   "postTo": "Publier la mise à jour : {floors}",
   "wholeWord": "tout l'immeuble",
   "errTypes": "Choisissez ce qui se passe.",
   "errFloors": "Touchez les étages, ou choisissez Tout l'immeuble.",
   "errLine": "« Autre » demande une ligne : dites ce qui se passe."
  },
  "A03": {
   "liveTitle": "Publié",
   "live": "En ligne maintenant sur tous les canaux, y compris par texto. C'est affiché comme « Pas encore vérifié » jusqu'à ce que le Hub le vérifie.",
   "waitingTitle": "En attente du Hub",
   "waiting": "Le Hub vérifie ceci maintenant. Ce sera envoyé dès que ce sera approuvé.",
   "approved": "Approuvé et envoyé {t}.",
   "declined": "Le Hub n'a pas envoyé ceci. Raison : {reason}",
   "verified": "Le Hub a vérifié votre mise à jour {t}.",
   "corrected": "Le Hub a corrigé votre mise à jour. Raison : {reason}",
   "withdrawn": "Le Hub a retiré votre mise à jour. Raison : {reason}",
   "slow": "Envoi en cours. Le réseau est faible ici. L'envoi se terminera quand votre réseau sera meilleur.",
   "where": "Envoyé à : {channels}",
   "when": "Publié {t}",
   "states": {
    "queued": "Enregistré sur votre téléphone. Sera envoyé quand vous aurez du réseau",
    "live": "En ligne. Pas encore vérifié",
    "waiting": "En attente du Hub",
    "approved": "Approuvé et envoyé",
    "declined": "Pas envoyé par le Hub",
    "verified": "Vérifié par le Hub",
    "withdrawn": "Retiré par le Hub",
    "corrected": "Corrigé par le Hub",
    "exercise": "Exercice. Pas envoyé aux résidents"
   },
   "queuedTitle": "Enregistré sur votre téléphone",
   "queued": "Enregistré sur votre téléphone. Ce sera envoyé quand vous aurez du réseau.",
   "writtenAt": "Écrit {t}. Vous n'avez rien d'autre à faire.",
   "approvedTitle": "Approuvé et envoyé",
   "declinedTitle": "Pas envoyé",
   "verifiedTitle": "Vérifié par le Hub",
   "correctedTitle": "Corrigé par le Hub",
   "withdrawnTitle": "Retiré par le Hub",
   "exerciseTitle": "Publication de pratique enregistrée",
   "exercise": "Ceci est un exercice. Rien n'a été envoyé aux résidents.",
   "approvedLine": "C'est maintenant affiché comme vérifié par le Hub.",
   "verifiedLine": "Les résidents voient maintenant « Vérifié par le Hub » sur votre mise à jour. Aucun deuxième message n'a été envoyé.",
   "correctedLine": "Le Hub a changé votre mise à jour : {text}",
   "correctedWhen": "Corrigé {t}.",
   "yourUpdate": "Votre mise à jour",
   "floorsAll": "Tout l'immeuble",
   "floorsOne": "Étage {a}",
   "floorsRange": "Étages {a} à {b}",
   "photoYes": "Avec une photo",
   "whereWhen": "Ce qui est allé où, et quand",
   "chText": "Textos",
   "chWeb": "L'application et le site Web du CVH",
   "sentTo": "Envoyé {t} aux résidents de {building}, {floors}",
   "liveOn": "Affiché depuis {t} pour {building}, {floors}",
   "notYet": "Pas encore envoyé",
   "notSent": "Pas envoyé",
   "takenDown": "Retiré {t}",
   "waitAfter": "Sera envoyé sur tous les canaux dès que le Hub l'approuvera.",
   "howSeen": "Comment les résidents le voient",
   "willSeen": "Une fois approuvé, les résidents verront",
   "seeIt": "Le voir comme les résidents",
   "toHome": "Retour à mon immeuble",
   "another": "Publier une autre mise à jour",
   "notFound": "Cette mise à jour est introuvable sur ce téléphone.",
   "reasonLabel": "Raison : {reason}"
  },
  "A04": {
   "title": "Ma tournée",
   "checkins": "Prises de nouvelles demandées à vos étages",
   "unreachable": "Ménages de vos étages qu'on ne peut pas joindre par téléphone ou par l'application",
   "carry": "Alerte à leur transmettre",
   "floorDoor": "Étage {floor}, porte {door}",
   "floorPhone": "Étage {floor}, {method} {phone}",
   "method": {
    "call": "appel",
    "text": "texto",
    "knock": "cogner à la porte"
   },
   "done": "Fait",
   "notReached": "Pas joint",
   "needsHelp": "A besoin d'aide",
   "connected": "Mis en contact avec un service",
   "passed": "Transmis au Hub",
   "offline": "Pas de réseau. Vos choix sont enregistrés et seront envoyés quand vous aurez du réseau.",
   "deleted": "Quand cette perturbation sera terminée, ces dossiers seront supprimés. Seuls les totaux sont gardés.",
   "addDoor": "Ajouter une porte à la demande d'un résident",
   "addConfirm": "Le résident a accepté d'être ajouté, ici sur mon écran.",
   "addedByRequest": "Ajouté à la demande du résident",
   "addNote": "Cette porte sera supprimée quand la perturbation sera terminée. Pour qu'on prenne de ses nouvelles à chaque fois, la personne peut le choisir dans le CVH.",
   "exercise": "Ceci est une tournée de pratique.",
   "forAlert": "Pour : {headline}",
   "practiceFor": "Tournée de pratique. Rien n'est envoyé aux résidents.",
   "floorN": "Étage {n}",
   "doorN": "Porte {door}",
   "methodWord": {
    "call": "Appel",
    "text": "Texto",
    "knock": "Cogner"
   },
   "tally": "{todo} à faire · {done} faits · {nr} pas joints · {help} ont besoin d'aide",
   "connectedCat": "Mis en contact avec un service : {category}",
   "queued": "Enregistré sur votre téléphone. Sera envoyé quand vous aurez du réseau.",
   "taken": "Pris en charge par le Hub",
   "change": "Changer",
   "connect": "Mettre en contact avec un service",
   "tellInPerson": "Cognez et transmettez-leur cette alerte",
   "whereLabel": "Où",
   "doLabel": "Quoi faire maintenant",
   "noRound": "Il n'y a pas de tournée de prise de nouvelles en ce moment. Quand le Hub envoie une alerte de chaleur ou de panne de courant pour votre immeuble, les prises de nouvelles à vos étages s'affichent ici.",
   "addTitle": "Ajouter une porte",
   "addFloor": "Étage",
   "addDoorLabel": "Numéro de porte",
   "addMethod": "Comment la personne veut être jointe",
   "addPhone": "Numéro de téléphone",
   "addBtn": "Ajouter à ma tournée",
   "cancel": "Annuler",
   "added": "Ajouté à votre tournée.",
   "errDoor": "Ajoutez le numéro de porte.",
   "errPhone": "Ajoutez un numéro de téléphone pour un appel ou un texto.",
   "errMethod": "Choisissez comment la personne veut être jointe.",
   "errAgree": "Demandez-lui d'abord. Cochez la case quand la personne est d'accord, ici sur votre écran.",
   "practiceNoAlert": "Pratique : il n'y a pas d'alerte à transmettre."
  },
  "A05": {
   "title": "Mettre en contact avec un service",
   "urgent": "Pour toute urgence ou tout danger : appelez le 911 maintenant.",
   "list": "Ouvert maintenant, dans la langue du résident",
   "choose": "Parlez-leur de ceci",
   "chosen": "Dites au résident comment joindre {service}, ou écrivez-le pour lui.",
   "neverText": "Nous n'envoyons pas ceci par texto.",
   "recorded": "Noté comme : {category}. Rien d'autre n'est enregistré.",
   "exNote": "Exercice : ceci est une pratique. Ce que vous choisissez est gardé seulement dans le dossier de l'exercice.",
   "forWho": "Pour : {who}",
   "theirLang": "Sa langue",
   "all": "Toutes",
   "openNowIn": "Ouvert maintenant en {lang}, ou heures inconnues",
   "hoursUnknown": "Heures inconnues. Appelez d'abord.",
   "speaks": "Parle {lang}",
   "none": "Rien n'est ouvert maintenant en {lang} pour ceci. Ces services sont ouverts maintenant dans d'autres langues :",
   "noneAtAll": "Rien ici n'est ouvert maintenant. Le Hub peut aider : {phone}.",
   "tellTitle": "Dites-leur",
   "sayOr": "Dites-le à la personne, ou écrivez-le pour elle. Vous pouvez aussi lui montrer cet écran.",
   "again": "Choisir un autre service",
   "backRound": "Retour à ma tournée",
   "already": "Déjà mis en contact avec un service : {category}.",
   "queued": "Enregistré sur votre téléphone. Ce sera envoyé au Hub quand vous aurez du réseau.",
   "callLabel": "Téléphone",
   "whereLabel": "Où",
   "hoursLabel": "Aujourd'hui"
  },
  "building": {
   "registerTitle": "Tiré du registre de la Ville",
   "updated": "Dernière mise à jour le {date}",
   "registerLead": "La Ville de Toronto tient un registre des immeubles d'appartements. Ces faits en viennent.",
   "checking": "Le Hub vérifie les détails de cet immeuble. Ce que vous voyez ici pourrait changer.",
   "facts": {
    "storeys": "Étages",
    "elevators": "Ascenseurs",
    "emergencyPower": "Alimentation de secours",
    "coolingRoom": "Salle de rafraîchissement",
    "airConditioning": "Climatisation",
    "barrierFree": "Entrée sans obstacles"
   },
   "airNone": "Aucune",
   "airIndividual": "Dans chaque logement",
   "roles": {
    "superintendent": "Concierge",
    "buildingManagement": "Gestion de l'immeuble",
    "propertyOffice": "Bureau de gestion"
   },
   "contactTitle": "Contact de l'immeuble",
   "providedByHub": "Fourni par le Hub, dernière mise à jour le {date}"
  },
  "guides": {
   "reviewed": "Vérifié par le Hub, dernière mise à jour le {date}"
  }
 });
  /* AD-11 pilot change (2026-10-03): the label of a directory description a model translated and no person has reviewed. AI-generated (Claude), not yet checked by native readers. */
  m(t, { "x04": { "unreviewed": "Traduction automatique, non révisée par une personne" } });
  /* The resident map (S02.07): the "map" strings. AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "map": {
    "lead": "Services, organismes et immeubles d'habitation à Thorncliffe Park et Flemingdon Park. Touchez une épingle pour voir de quoi il s'agit.",
    "service": "Service ou organisme",
    "building": "Immeuble d'habitation",
    "pinName": "{name} : {kind}",
    "noSignal": "La carte n'est pas disponible sans réseau",
    "noSignalBody": "La liste contient tous les lieux de la carte.",
    "notSaved": "Cette partie de la carte n'est pas enregistrée sur votre téléphone",
    "notSavedBody": "Les parties de la carte que vous avez vues avec du réseau restent sur votre téléphone. Les épingles et la liste fonctionnent toujours.",
    "listTitle": "Lieux sur cette partie de la carte",
    "listLead": "Les mêmes lieux que ceux de la carte. Déplacez la carte ou zoomez pour changer cette liste.",
    "listEmpty": "Rien sur cette partie de la carte. Déplacez la carte ou zoomez, ou affichez tout le secteur.",
    "wholeArea": "Afficher tout le secteur",
    "buildings": "Immeubles d'habitation",
    "buildingsCount": "{n} immeubles",
    "buildingsCountOne": "1 immeuble",
    "filtered": "Seuls les lieux qui correspondent aux filtres choisis dans le répertoire sont affichés."
   }
  });
  /* S07.02: the web sign-up for text alerts and the confirmation text. YES, STOP, START and CVH stay in English. AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "signup": {
    "termsAgree": "J'ai lu la page des conditions et de la confidentialité, et j'accepte.",
    "termsLink": "Lire la page des conditions et de la confidentialité",
    "termsVersion": "Version des conditions {version}",
    "age": "J'ai 16 ans ou plus, ou un parent ou un tuteur m'aide.",
    "missingTerms": "votre accord avec les conditions",
    "missingAge": "la déclaration d'âge",
    "sending": "Envoi en cours...",
    "onItsWay": "Si ce numéro peut recevoir des textos, un message est en route.",
    "expect": "Répondez YES à ce message dans les 48 heures pour commencer à recevoir les alertes. Tant que vous n'avez pas répondu YES, vous ne recevez aucune alerte par texto.",
    "howChange": "Pour changer plus tard d'immeuble, d'étage ou de langue, répondez 1 ou 2 à n'importe quel texto du Hub.",
    "startHelp": "Pas de texto après 5 minutes ? Envoyez START au {number}, puis inscrivez-vous de nouveau.",
    "startHelpNoNumber": "Pas de texto après 5 minutes ? Envoyez START au numéro d'où viennent nos textos, puis inscrivez-vous de nouveau.",
    "error": {
     "invalid_request": "Une partie du formulaire n'a pas pu être lue. Rechargez la page et réessayez.",
     "phone_not_canadian": "Utilisez un numéro de téléphone canadien à 10 chiffres, par exemple 416 555 0123.",
     "neighbourhood_missing": "Choisissez votre quartier.",
     "terms_not_agreed": "Pour vous inscrire, acceptez les conditions.",
     "age_not_confirmed": "Pour vous inscrire, confirmez la déclaration d'âge.",
     "terms_changed": "Les conditions ont changé pendant que cette page était ouverte. Relisez-les, puis acceptez-les.",
     "place_unknown": "Un de vos immeubles ou étages n'est plus dans la liste. Vérifiez vos immeubles et réessayez.",
     "rate_limited": "Trop d'inscriptions sont venues de cette connexion. Réessayez dans une heure.",
     "signup_unavailable": "L'inscription par texto n'est pas disponible pour le moment. Réessayez plus tard.",
     "network": "Nous n'avons pas pu joindre le CVH. Vérifiez votre connexion et réessayez."
    }
   }
  });
  m(t, {"smsTexts": {"confirmation": "Alertes CVH du Thorncliffe Park Community Hub : répondez YES pour confirmer. Fréquence variable. Des frais de messages et de données peuvent s'appliquer. HELP : aide. STOP pour vous désabonner."}});
  /* S07.04: the welcome, the replies of the inbound router and the words for yes (YES, STOP and CVH stay in English). */
  m(t, {"smsTexts": {"welcome": "Vous êtes inscrit aux alertes du CVH. Le personnel du Hub vérifie chaque message, donc les alertes peuvent ne pas être envoyées la nuit. Répondez 1 pour changer d'immeuble ou d'étage, 2 pour changer de langue, 3 pour retirer votre demande de prise de nouvelles, 0 pour arrêter et supprimer votre abonnement. Répondez STOP pour arrêter.", "alreadySignedUp": "Vous êtes déjà inscrit aux alertes du CVH.", "deletePrompt": "Répondez 0 à nouveau d'ici 10 minutes pour supprimer votre abonnement. Vous ne recevrez plus de messages.", "signupInfo": "Pour recevoir les alertes du CVH par texto, inscrivez-vous ici : {link} Répondez STOP pour arrêter."}, "smsKeywords": {"yes": "oui"}});
  /* S07.05: the numbered text menus and their replies (see the English file for what each is and the one-text rule; 0, 1, 8, 9, 10, 5
     and {placeholders} stay as written). AI-generated (Claude), not yet checked by native readers. */
  m(t, {"smsTexts": {"menuStreet": "Rue :", "menuBuilding": "Immeuble :", "menuFloor": "Étage :", "menuWholeBuilding": "Tout l'immeuble", "menuLanguage": "Langue :", "menuNav": "0 Retour 9 Hub", "menuNavMore": "0 Retour 8 Plus 9 Hub", "menuWarn": "Ceci remplace vos {n} immeubles enregistrés. 1 Continuer, 0 Retour", "menuHub": "Appelez le Hub au {hub}.", "menuClosed": "Menu fermé. Rien n'a été changé.", "menuReset": "Votre menu s'est fermé après 10 minutes sans réponse. Rien n'a été changé.", "menuLimit": "Vous avez utilisé vos 5 menus du jour. Réessayez demain ou appelez le Hub au {hub}.", "menuLimitLink": "Vous avez utilisé vos 5 menus du jour. Répondez 1 pour un lien de modification en ligne, ou appelez le Hub au {hub}.", "buildingSaved": "Enregistré. Votre immeuble est {building}, étage {floor}.", "buildingSavedWhole": "Enregistré. Votre immeuble est {building}.", "languageSaved": "Enregistré. Vous recevrez vos messages en français.", "noCheckinRequest": "Vous n'avez aucune demande de prise de nouvelles.", "checkinWithdrawn": "Votre demande de prise de nouvelles est retirée."}});
  /* S07.06: the one-time web link's texts and its page (see the English file for what each is; menuClosedLink must fit one text; 0, 1, 30
     and {placeholders} stay as written; the error lines other than edit_unavailable are the sign-up's own). AI-generated (Claude), not yet
     checked by native readers. */
  m(t, {"smsTexts":{"menuClosedLink":"Menu fermé. Rien n'a été changé. Répondez 1 pour un lien de modification en ligne.","editLink":"Modifiez ou supprimez vos alertes du CVH ici : {link} Le lien fonctionne une fois, pendant 30 minutes.","editSaved":"Vos choix d'alertes du CVH ont été modifiés sur la page web. Ce n'était pas vous ? Appelez le Hub au {hub}."},"subscriptionEdit":{"title":"Modifier vos alertes par texto","loading":"Ouverture de vos choix...","forNumber":"Pour le numéro de téléphone qui se termine par {digits}.","lead":"Modifiez ce que vous voulez, puis enregistrez. Pour arrêter tous les messages, supprimez votre abonnement en bas de cette page.","topicsTitle":"Sujets pour lesquels vous ne voulez pas de messages","topicsLead":"Cochez un sujet pour ne plus recevoir ses alertes. Les alertes d'incendie ou d'évacuation arrivent toujours.","save":"Enregistrer mes changements","saving":"Enregistrement...","savedTitle":"Vos changements sont enregistrés","savedBody":"Un texto de confirmation est en route. Ce lien a maintenant servi : pour changer autre chose, demandez un nouveau lien par texto.","deleteTitle":"Supprimer mon abonnement","deleteLead":"Vous ne recevrez plus de messages du CVH, et tout ce qui est conservé sur votre numéro est supprimé. C'est définitif.","deleteSure":"Supprimer votre abonnement maintenant ? Vous ne recevrez plus de messages du CVH.","deleteYes":"Oui, le supprimer","deleteNo":"Non, le garder","deleting":"Suppression...","deletedTitle":"Votre abonnement est supprimé","deletedBody":"Vous ne recevrez plus de messages du CVH, et rien n'est conservé sur votre numéro. Aucun texto n'est envoyé pour le confirmer.","signUpAgain":"Se réinscrire","expiredTitle":"Ce lien a expiré","expiredBody":"Un lien fonctionne une seule fois, pendant 30 minutes après son envoi.","expiredHow":"Pour recevoir un nouveau lien par texto, répondez 1 à un texto du CVH. Si la réponse est un menu, envoyez 0 pour le fermer. Quand la réponse propose un lien, envoyez 1.","callHub":"Ou appelez le Hub au {hub}.","error":{"invalid_request":"Une partie du formulaire n'a pas pu être lue. Rechargez la page et réessayez.","neighbourhood_missing":"Choisissez votre quartier.","place_unknown":"Un de vos immeubles ou étages n'est plus dans la liste. Vérifiez vos immeubles et réessayez.","edit_unavailable":"Les modifications ne sont pas possibles pour le moment. Réessayez plus tard.","network":"Nous n'avons pas pu joindre le CVH. Vérifiez votre connexion et réessayez."}}});
  /* S08.05: the check-in request's texts and wording (see the English file for what each is; checkinMoved and checkinUncoveredNow must fit one
     text; 1, YES, CVH, Hub and {placeholders} stay as written). AI-generated (Claude), not yet checked by native readers. */
  m(t, {"smsTexts":{"checkinMoved":"Votre étage a changé : votre demande de prise de nouvelles est retirée. Répondez 1 pour un lien.","checkinUncoveredNow":"Aucun ambassadeur ne couvre votre étage pour l'instant. Appelez le Hub au {hub}."},"signup":{"error":{"checkin_consent_missing":"Pour demander une prise de nouvelles, cochez la case pour accepter."}},"subscriptionEdit":{"error":{"checkin_consent_missing":"Pour demander une prise de nouvelles, cochez la case pour accepter."}},"checkin":{"consentMissing":"Pour demander une prise de nouvelles, cochez la case pour accepter.","sees":"Un ambassadeur de votre étage verra votre numéro de téléphone et votre étage, pour pouvoir vous appeler ou vous écrire.","isNot":"Une prise de nouvelles est un appel ou un message pour demander si vous allez bien. Ce ne sont pas des soins médicaux, ni la promesse que quelqu'un viendra tout de suite.","howTitle":"Comment la demander","howNew":"Il vous faut les alertes par texto du CVH. Inscrivez-vous et demandez la prise de nouvelles dans le même formulaire.","howHelp":"Lors d'un événement du CVH ou au Hub, le personnel ou un ambassadeur d'immeuble peut vous aider à vous inscrire.","howSubscribed":"Vous recevez déjà les textos du CVH ? Demandez-la sur la page où vous modifiez vos choix.","noCoverage":"Si aucun ambassadeur ne couvre encore votre étage, nous vous le disons tout de suite. Vous pouvez plutôt appeler le Hub au {hub}.","ask":"Qu'un ambassadeur de mon étage prenne de mes nouvelles","whereHint":"Choisissez l'immeuble et l'étage où vous habitez, parmi ceux du haut.","agree":"J'accepte qu'un ambassadeur de mon étage voie mon numéro de téléphone et mon étage, et prenne de mes nouvelles.","untilYes":"Votre demande de prise de nouvelles commence quand vous répondez YES à notre texto.","uncovered":"Aucun ambassadeur ne couvre encore votre étage. Appelez le Hub au {hub}.","withdraw":"Retirer ma demande de prise de nouvelles","withdrawNote":"Elle est retirée quand vous enregistrez. Vous recevrez toujours les alertes.","moved":"Votre lieu de résidence a changé, donc votre demande de prise de nouvelles sera retirée. Pour la redemander pour votre nouvel étage, choisissez-le et acceptez de nouveau.","savedRequested":"Votre demande de prise de nouvelles est enregistrée.","savedMethod":"La façon de prendre de vos nouvelles a changé."}});
  /* The last resident wording that showed in English: the home's alert list and its failures (R03, status.none), the ask screen's waiting and
     failure states (R09, R10.shownIn) and the directory (S02.06). AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "status": {
    "none": "Rien en cours"
   },
   "R03": {
    "currentAlerts": "Alertes en cours",
    "noCurrentAlerts": "Aucune alerte en cours",
    "myBuildings": "Vos immeubles",
    "checking": "Vérification des alertes",
    "feedFailed": "Nous n'avons pas pu vérifier les alertes pour le moment. Un lieu marqué « Inconnu » peut tout de même avoir une alerte. Nous allons réessayer.",
    "feedFailedOld": "Nous n'avons pas pu vérifier s'il y a de nouvelles alertes. Affichage de ce qui a été chargé pour la dernière fois {t}."
   },
   "R09": {
    "searching": "Recherche en cours",
    "needsSignal": "La recherche a besoin de réseau",
    "needsSignalBody": "Vous pouvez quand même choisir un sujet ci-dessous, ou appeler le Hub.",
    "busy": "La recherche est surchargée, réessayez dans quelques minutes",
    "busyBody": "Vous pouvez choisir un sujet ci-dessous, ou appeler le Hub.",
    "updating": "Les résultats de recherche sont en cours de mise à jour, réessayez",
    "updatingBody": "Vous pouvez choisir un sujet ci-dessous pendant leur mise à jour, ou appeler le Hub.",
    "browseAll": "Voir tous les services et organismes",
    "loading": "Chargement des sujets"
   },
   "R10": {
    "shownIn": "Affiché en {lang}"
   },
   "directory": {
    "title": "Services et organismes",
    "lead": "Ce que le Hub a confirmé à Thorncliffe Park et Flemingdon Park. Choisissez un sujet ou un quartier pour réduire la liste.",
    "count": "{n} services",
    "countOne": "1 service",
    "topic": "Sujet",
    "emergency": "Aide en cas d'urgence",
    "emergencyRole": "Rôle en cas d'urgence",
    /* The verified badge's line on a provider (it replaces the earlier last-confirmed line). AI-generated (Claude), not yet checked by native readers. */
    "checkedByHub": "Vérifié par le Hub · {date}",
    "lastUpdated": "Dernière mise à jour le {time}",
    "loading": "Chargement du répertoire",
    "couldNotLoad": "Le répertoire n'a pas pu se charger",
    "couldNotLoadBody": "Le Hub peut vous aider à trouver un service par téléphone.",
    "couldNotLoadNumbers": "La page des numéros donne les autres numéros dont vous pourriez avoir besoin.",
    "numbersLink": "Voir les numéros essentiels",
    "backToList": "Tous les services et organismes",
    "suggestApply": "Afficher seulement {place}"
   }
  });
  /* Reading without signal (S02.12): the offline page and R-34's note. AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "offline": {
    "title": "Cette page n'est pas enregistrée sur votre téléphone",
    "body": "Elle n'a pas encore été ouverte sur ce téléphone avec du réseau, elle a donc besoin de réseau. Les numéros sont toujours enregistrés sur votre téléphone.",
    "available": "Vous pouvez lire ceci sans réseau",
    "none": "Rien d'autre n'est encore enregistré sur ce téléphone. Les pages que vous ouvrez avec du réseau sont enregistrées pour plus tard."
   },
   "R34": {
    "offlineTitle": "Lire sans réseau",
    "offlineHelp": "Les pages que vous ouvrez avec du réseau sont enregistrées sur ce téléphone, pour que vous puissiez les relire sans réseau. Les numéros sont toujours enregistrés. La première fois, le CVH a besoin de réseau pour s'ouvrir.",
    "offlineNote": "Ce téléphone ne gardera peut-être pas les pages pour une utilisation hors ligne"
   }
  });
  /* S08.02: an ambassador's post (A-02): the one screen's new words (an unsent post is held only in the open page's memory), and A03.states.ended. AI-generated, not yet checked by native readers. */
  m(t, {
   "A02": {
    "building": "Quel immeuble?",
    "allFloorsLine": "Les {n} étages",
    "listLabel": "Certains étages",
    "listLine": "Cochez chaque étage",
    "rangeLabel": "Une suite d'étages",
    "rangeLine": "D'un étage à un autre",
    "fromFloor": "De l'étage",
    "toFloor": "À l'étage",
    "chooseFloor": "Choisir",
    "phaseTitle": "Où en sont les choses",
    "phaseProblem": "Il y a un problème",
    "phaseProgress": "Des travaux sont en cours",
    "validTitle": "Jusqu'à quand?",
    "validResolved": "Jusqu'à ce que ce soit réglé (24 heures à partir de maintenant)",
    "validAt": "Jusqu'à une date et une heure",
    "dateLabel": "Date",
    "timeLabel": "Heure (heure de Toronto)",
    "validHint": "Au plus 7 jours à l'avance.",
    "textLabel": "Ce qui se passe, en anglais",
    "textHint": "Au plus {max} caractères. Les résidents le lisent dans leur langue; le Hub le vérifie d'abord.",
    "inAlert": "Cette mise à jour va dans l'alerte : {headline}",
    "typesFixed": "Ce qui se passe : {types}",
    "unsent": "Pas encore envoyé. Gardez cette page ouverte; l'envoi se fera quand vous aurez du réseau.",
    "unsentClose": "Si vous fermez cette page, cette mise à jour est perdue.",
    "sending": "Envoi au Hub...",
    "errPhase": "Choisissez où en sont les choses.",
    "errText": "Dites ce qui se passe, en anglais.",
    "errTextLong": "C'est trop long. Utilisez au plus {max} caractères.",
    "errValid": "Entrez une date et une heure.",
    "errValidPast": "Cette heure est passée. Choisissez une heure plus tard.",
    "errValidFar": "Choisissez une heure dans les 7 prochains jours au plus.",
    "errValidSkipped": "On change l'heure cette nuit-là, donc cette heure n'est pas claire. Choisissez une autre heure.",
    "errRange": "Le premier étage est au-dessus du dernier. Mettez l'étage le plus bas en premier.",
    "errNotAssigned": "Vous n'êtes pas affecté à cet immeuble en ce moment, donc vous ne pouvez pas publier pour lui.",
    "errClosed": "Cette alerte est terminée. Publiez plutôt une nouvelle mise à jour.",
    "errSignedOut": "Vous avez été déconnecté, donc ceci n'a pas été envoyé. Reconnectez-vous, puis publiez-le de nouveau.",
    "errFailed": "Ceci n'a pas été envoyé. Réessayez. Si cela continue, appelez le Hub."
   },
   "A03": {
    "states": {
     "ended": "Pas envoyé : l'alerte a pris fin avant que le Hub la vérifie"
    }
   }
  });
  /* S09.07: the end-of-pilot re-consent texts (the campaign text with {date}, the confirmation after YES, the answer after the deadline, the answer
     while sign-ups are paused) and the sign-up form's refusal while sign-ups are paused. YES and CVH stay in English. Each text fits one text message
     with the longest date. smsDate is how a text writes the deadline (the month names, the order of day and month, the numerals), fixed here
     from CLDR 47 so the frozen text is the same on every runtime. AI-generated (Claude), not yet checked by native readers: the texts and the
     date words are reviewed before launch (Launch Readiness). */
  m(t, {"smsDate": {"months":["janvier","février","mars","avril","mai","juin","juillet","aout","septembre","octobre","novembre","décembre"],"dayMonth":"{day} {month}","digits":"0123456789"}, "smsTexts": {"reconsent": "Le projet pilote CVH se termine. Répondez YES pour continuer à recevoir les alertes. Sans réponse d'ici le {date}, votre numéro sera supprimé.", "reconsentKept": "Merci. Vous continuerez à recevoir les alertes CVH.", "pilotEnded": "Le projet pilote CVH est terminé; votre numéro n'a pas été conservé.", "signupsPaused": "Les inscriptions aux textos CVH sont suspendues pendant la fin du projet pilote."}, "signup": {"error": {"signups_paused": "Les inscriptions sont suspendues pendant la fin du projet pilote."}}});
  /* The opt-in disclosures carriers ask for (program, frequency, rates, HELP and STOP) under the sign-up form. AI-generated (Claude), not yet checked by native readers. */
  m(t, {"signup": {"smsTerms": "Alertes CVH par texto du Thorncliffe Park Community Hub. La fréquence des messages varie. Des frais de messages et de données peuvent s'appliquer. Répondez HELP pour obtenir de l'aide ou STOP pour vous désabonner."}});
})();
