/* Slovak strings for the resident and ambassador screens, merged into the Slovak table by
   screen ID. AI-generated (Claude), not yet checked by native readers. Staff screens stay in English. */
(function () {
  var t = window.CVH_STRINGS.sk;
  function m(t, s) { for (var k in s) { if (s[k] && typeof s[k] === "object" && !Array.isArray(s[k]) && t[k] && typeof t[k] === "object" && !Array.isArray(t[k])) m(t[k], s[k]); else t[k] = s[k]; } }
  m(t, {
  "terms": {
   "version": "Verzia",
   "owner": "Vlastník",
   "updated": "Naposledy aktualizované",
   "privacyContact": "Kontakt pre ochranu súkromia",
   "draftTitle": "Návrh: zatiaľ nezverejnené",
   "draftBody": "Tento text ešte nebol schválený. Nie sú to konečné podmienky. Neprihlasujte sa na základe tohto textu.",
   "draftWhy": "Nezverejnené, pretože:",
   "translationNote": "Časť tejto stránky ešte nie je preložená do jazyka {lang}. Tieto časti sa zobrazujú po anglicky.",
   /* S09.08: the day the pilot's resident data was deleted, shown once the end-of-pilot purge has completed. AI-generated (Claude), not yet checked by native readers. */
   "dataDeleted": "Údaje obyvateľov vymazané",
   "dataDeletedNote": "Pilot CVH sa skončil. V ten deň sme vymazali telefónne číslo a voľby všetkých, ktorí neodpovedali YES, aby dostávali upozornenia aj naďalej."
  },
  "shell": {
   "hubName": "Thorncliffe Park Community Hub",
   "hubLogoAlt": "Thorncliffe Park Community Hub",
   "pageNotFound": "Túto stránku sa nepodarilo nájsť.",
   "pageNotFoundBody": "Odkaz môže byť starý alebo zle napísaný. Pokračujte cez menu nižšie."
  },
  "x01": {
   "partner": "Tento priestor nikomu nevolá 911. Ak je niekto v ohrození, volajte 911 sami. Nepredpokladajte, že to už urobila iná organizácia."
  },
  "x05": {
   "title": "Dostávajte upozornenia a pomoc vo svojom jazyku",
   "lead": "Komunitné virtuálne centrum vám dá vedieť, keď sa vo vašej budove niečo stane, a pomôže vám nájsť služby blízko vás.",
   "steps": ["Otvorte odkaz alebo naskenujte kód telefónom.", "Vyberte si jazyk.", "Nepotrebujete účet ani aplikáciu."],
   "link": "Krátky odkaz",
   "scan": "Naskenujte fotoaparátom telefónu",
   "building": "Budova",
   "floor": "Poschodie",
   "writeIn": "Doplnil ambasádor vašej budovy",
   "text": "Nemáte smartfón? Ambasádor vášho poschodia vám pomôže dostávať upozornenia cez SMS.",
   "from": "Od Thorncliffe Park Community Hub",
   "sampleLink": "Ukážkový odkaz, nefunguje"
  },
  "x06": {
   "doing": "Toto robíme",
   "canTake": "Toto môžeme prevziať",
   "cannotCover": "Toto nemôžeme zabezpečiť",
   "need": "Toto potrebujeme",
   "claimed": "Prevzal(a) {org}",
   "supply": "Zásoby: {item}",
   "recordDecision": "Zaznamenať ako rozhodnutie"
  },
  "groups": {
   "seniors": {
    "label": "Seniori",
    "line": "Varovania pred horúčavou a služby pre starších obyvateľov. V každom upozornení aj rady pre vás."
   },
   "newcomers": {
    "label": "Novoprichádzajúci",
    "line": "Služby, ktoré sa nepýtajú na váš pobytový status. V každom upozornení aj rady pre vás."
   },
   "families": {
    "label": "Rodiny s malými deťmi",
    "line": "Upozornenia a rady o bábätkách a malých deťoch a služby pre rodiny."
   },
   "checkin": {
    "label": "Chcem, aby sa na mňa niekto prišiel pozrieť počas horúčav a výpadkov",
    "line": "Ambasádor vášho poschodia sa na vás príde pozrieť, keď je varovanie pred horúčavou alebo výpadok elektriny."
   }
  },
  "categories": {
   "food": "Jedlo",
   "housing": "Bývanie a nájom",
   "health": "Zdravie",
   "money": "Peniaze a dávky",
   "settlement": "Imigrácia a usadenie sa",
   "jobs": "Práca a odborná príprava",
   "children": "Deti a mládež",
   "seniors": "Seniori",
   "legal": "Právna pomoc",
   "mentalHealth": "Duševné zdravie"
  },
  "filters": {
   "openNow": "Je to práve teraz otvorené?",
   "nbhd": "Ktorá štvrť?",
   "language": "Hovoria mojím jazykom?",
   "cost": "Koľko to stojí?",
   "noId": "Budú chcieť doklad alebo pobytový status?",
   "stepFree": "Dostanem sa dnu bez schodov?",
   "noAppointment": "Potrebujem sa objednať?",
   "short": {
    "openNow": "Teraz otvorené",
    "nbhdTP": "Thorncliffe Park",
    "nbhdFP": "Flemingdon Park",
    "language": "Hovoria jazykom: {lang}",
    "free": "Zadarmo",
    "lowCost": "Zadarmo alebo lacno",
    "noId": "Nežiadajú doklad",
    "stepFree": "Bez schodov",
    "noAppointment": "Netreba sa objednať"
   },
   "answers": {
    "yes": "Áno",
    "no": "Nie",
    "any": "Nezáleží",
    "free": "Len zadarmo",
    "lowCost": "Zadarmo alebo lacno",
    "noIdOnly": "Len miesta, ktoré sa nepýtajú",
    "stepFreeOnly": "Len miesta bez schodov",
    "walkIn": "Len bez objednania"
   }
  },
  "utilities": {
   "ac": "Klimatizácia",
   "wifi": "Wi-Fi",
   "charging": "Nabíjanie",
   "washrooms": "Toalety",
   "water": "Pitná voda",
   "food": "Jedlo",
   "kit": "Tu sú balíčky na núdzové situácie",
   "space": "Teraz otvorené ako priestor"
  },
  "orgKinds": {
   "grassroots": "Miestna občianska skupina",
   "nonprofit": "Nezisková organizácia",
   "faith": "Náboženská organizácia",
   "public": "Verejná služba",
   "business": "Firma",
   "communityOffer": "Ponuka od susedov"
  },
  "neighbourhoods": {
   "TP": "Thorncliffe Park",
   "FP": "Flemingdon Park"
  },
  "subcats": {
   "Police Station": "Policajná stanica",
   "Fire Station": "Požiarna stanica",
   "Food Collaboratives": "Potravinové banky a programy s jedlom",
   "Shelter": "Núdzové ubytovanie (útulky)",
   "Faith-Based Organizations": "Náboženské spoločenstvá",
   "Legal Services": "Právne služby",
   "Government Documentation": "Úradné dokumenty",
   "Schools": "Školy",
   "Childminding & EarlyON": "Starostlivosť o deti a EarlyON",
   "Dental Clinics": "Zubné ordinácie",
   "Midwives Clinic": "Pôrodné asistentky",
   "Health Clinics": "Zdravotné ambulancie",
   "Non-Profits": "Komunitné organizácie",
   "Community Centres": "Komunitné centrá",
   "Public Washrooms": "Verejné toalety",
   "Libraries": "Knižnice",
   "Water Fountains": "Pitná voda",
   "Museums": "Múzeá",
   "Cooling Spaces": "Miesta na ochladenie počas horúčav",
   "Multi-Service Agencies": "Agentúry poskytujúce viacero služieb",
   "Food Security & Climate Resilience": "Skupiny pre jedlo a klímu",
   "Employment & Skills Training": "Práca a zručnosti",
   "Family & Parenting Support": "Rodina a rodičovstvo",
   "Social & Cultural Organizations": "Spoločenské a kultúrne skupiny",
   "Newcomer Supports": "Podpora pre novoprichádzajúcich",
   "Housing & Tenant Supports": "Bývanie a nájomníci",
   "Neighbourhood & Individual Empowerment": "Susedské skupiny"
  },
  "hazards": {
   "power": "Výpadok elektriny",
   "flood": "Záplava alebo porucha potrubia",
   "elevator": "Porucha výťahu",
   "heat": "Extrémna horúčava",
   "smoke": "Dym z lesných požiarov",
   "fire": "Požiar a evakuácia"
  },
  "stages": {
   "before": "Pred",
   "during": "Počas",
   "after": "Po"
  },
  "R01": {
   "title": "Vyberte si jazyk",
   "preselected": "Vybrané podľa vášho oznamu",
   "selected": "Vybrané",
   "continue": "Pokračovať",
   "helperBasic": "Pomáhate niekomu? Zapnite pre tohto človeka režim „Väčšie písmo, menej vecí“.",
   "forwardedNote": "Niekto vám poslal upozornenie. Najprv si vyberte jazyk.",
   "fromPhone": "Podľa jazyka vášho telefónu",
   "chooseFirst": "Ťuknite na jazyk a pokračujte.",
   "youChose": "Váš jazyk:",
   "helperOn": "Režim „Väčšie písmo, menej vecí“ je zapnutý. Pre tohto človeka zostane zapnutý."
  },
  "R02": {
   "current": "Práve zobrazené",
   "unavailable": "V tomto jazyku zatiaľ nie je",
   "unavailableBody": "Niektoré veci na tejto obrazovke ešte nie sú preložené do jazyka {lang}. Všade, kde sa to stane, to napíšeme.",
   "continueIn": "Pokračovať v jazyku {lang}",
   "chooseOther": "Vybrať iný jazyk"
  },
  "R03": {
   "getTextAlerts": "Dostávať upozornenia cez SMS",
   "getTextAlertsLine": "Upozornenia pre vašu budovu cez SMS. Bez aplikácie, bez účtu.",
   "signedUp": "Upozornenia cez SMS sú zapnuté",
   "sent": "Odpovedzte na telefóne YES a začnete dostávať upozornenia cez SMS",
   "alertsNow": "Upozornenia teraz",
   "myBuilding": "Vaša budova",
   "myFloor": "Vaše poschodie",
   "nothingActive": "Práve sa nič nedeje.",
   "nothingActiveBody": "Keď sa niečo bude týkať vašej budovy alebo štvrte, zobrazí sa to najprv tu.",
   "noBuildingChosen": "Vyberte si budovu a jej upozornenia uvidíte ako prvé",
   "ongoing": "Prebieha",
   "updated": "Aktualizované {t}",
   "posted": "Zverejnené {t}",
   "everyday": "Každý deň",
   "findHelp": "Nájsť pomoc",
   "map": "Mapa",
   "beReady": "Buďte pripravení",
   "findHelpLine": "Služby a pomoc blízko vás",
   "mapLine": "Miesta blízko vás a čo je teraz otvorené",
   "beReadyLine": "Návody, telefónne čísla a kontroly, či ste v poriadku",
   "archive": "Skončené upozornenia",
   "basicTurnOn": "Väčšie písmo, menej vecí",
   "headsUpTitle": "Pred horúcim počasím",
   "headsUpFrom": "Pripomienka, ktorú ste si vybrali",
   "headsUpGuide": "Prečítajte si návod pri horúčave",
   "headsUpEvent": "Workshop blízko vás",
   "ongoingDay": "Prebieha: deň {n} z {total}",
   "readAlert": "Prečítať upozornenie",
   "neighbourhoods": "Thorncliffe Park a Flemingdon Park",
   "headsUpAction": "Jedna vec, ktorú treba urobiť teraz",
   "ambassadorHome": "Ambasádor: moja budova",
   "ambassadorLine": "Zverejnite aktualizáciu alebo urobte svoje kolo v budove {building}",
   "noBuildingLine": "Tu sa zobrazujú upozornenia pre vašu štvrť. Pridajte svoju budovu a jej upozornenia uvidíte ako prvé."
  },
  "R04": {
   "deviceLabel": "SMS na obyčajnom telefóne",
   "from": "Thorncliffe Hub",
   "fromNumber": "Upozornenia CVH",
   "lockScreen": "Uzamknutá obrazovka",
   "now": "teraz",
   "levelOfficial": "Oficiálne upozornenie od {source}.",
   "levelCommunity": "Komunitné upozornenie od Hubu. Overil ho Hub.",
   "fromHub": "Komunitné upozornenie od Hubu",
   "levelAmbassador": "Komunitné upozornenie od ambasádora budovy. Zatiaľ neoverené.",
   "stop": "Ak už nechcete dostávať žiadne správy od Hubu, odpovedzte STOP.",
   "verifiedKeyword": "Ak chcete vedieť, čo znamená „overené“, odpovedzte INFO.",
   "ackMore": "Ďalšie informácie čoskoro.",
   "update": "Aktualizácia upozornenia „{headline}“:",
   "correction": "Oprava upozornenia „{headline}“: {changed}",
   "resolved": "Vyriešené: „{headline}“. {final}",
   "nearestSpace": "Najbližšie otvorené miesto: {space}, {hours}.",
   "confirmRequest": "Thorncliffe Park Community Hub: niekto požiadal o upozornenia cez SMS pre tento telefón, v jazyku {lang}, pre {where}. Ak súhlasíte, odpovedzte YES. Ak už nechcete dostávať žiadne správy od Hubu, odpovedzte STOP.",
   "keywordChange": "Ak chcete zmeniť vybrané skupiny, odpovedzte GROUPS.",
   "checkinWithdraw": "Ak chcete zrušiť kontroly, odpovedzte NOCHECK.",
   "link": "Viac: {url}",
   "sampleLabel": "Ukážková správa. Nič sa neposiela.",
   "tapOpen": "Ťuknite na správu a otvorte ju",
   "back": "Späť do aplikácie",
   "annotOn": "Ktoré riadky sú preložené",
   "annotOff": "Skryť poznámky k prekladu",
   "bigOn": "Najväčšie písmo",
   "bigOff": "Normálne písmo",
   "tagTemplate": "Skontrolovaná šablóna",
   "tagAlert": "Napísané pre toto upozornenie",
   "annotNote": "Fáza 2 je nakreslená po anglicky. Riadky označené „Skontrolovaná šablóna“ existujú vo všetkých pätnástich jazykoch pri spustení a skontrolovali ich ľudia. Riadky označené „Napísané pre toto upozornenie“ sa prekladajú pre každé upozornenie. Verzie v urdčine a gréčtine v tomto prototype zatiaľ nie sú.",
   "officialNote": "Oficiálne upozornenia sa posielajú zo šablóny v každom jazyku, ktorú skontrolovali ľudia. Komunitné upozornenie, ktoré nasleduje, hovorí, čo k tomu pridáva tu.",
   "notKnownPrefix": "Zatiaľ nevieme: {what}.",
   "you": "Vy",
   "exNote": "Cvičenie. Túto SMS dostanú len ľudia prihlásení do cvičenia. Obyvatelia nedostanú nič."
  },
  "R05": {
   "title": "Dostávať upozornenia cez SMS",
   "lead": "Pošleme vám SMS, keď sa niečo stane vo vašej budove alebo štvrti. Bez aplikácie, bez účtu, bez e-mailu.",
   "required": "Povinné",
   "optional": "Nepovinné",
   "phone": "Telefónne číslo",
   "phoneHelp": "Môžete ho napísať akokoľvek.",
   "phoneShown": "Pošleme SMS na {phone}",
   "phoneError": "Číslo musí mať 10 číslic, napríklad 416 555 0123.",
   "nbhd": "Štvrť",
   "building": "Budova",
   "floor": "Poschodie",
   "buildingSearch": "Vyhľadajte svoju budovu",
   "notListed": "Moja budova nie je v zozname",
   "notListedResult": "Budete dostávať všetky upozornenia pre {nbhd}. Povedali sme Hubu, že vaša budova v zozname chýba.",
   "language": "Jazyk",
   "languageFrom": "Podľa vašej prvej voľby",
   "groupsTitle": "Do ktorých skupín patríte?",
   "groupsSkip": "Preskočiť",
   "send": "Pošlite mi SMS na potvrdenie",
   "formError": "Zatiaľ sme to nemohli poslať. Doplňte, prosím: {missing}.",
   "whatYouGet": "SMS posielame len pri upozorneniach. Bežné správy ani reklamy cez SMS nikdy neposielame.",
   "sentTitle": "Pozrite sa do telefónu",
   "sentBody": "Poslali sme správu na {phone}. Odpovedzte YES a začnete dostávať upozornenia.",
   "resend": "Poslať znova",
   "fix": "Opraviť číslo",
   "signedUpTitle": "Prihlásené",
   "signedUpBody": "Na {phone} budú chodiť upozornenia v jazyku {lang}.",
   "noAccount": "Nepotrebujete účet.",
   "missingPhone": "telefónne číslo s 10 číslicami",
   "missingNbhd": "vašu štvrť",
   "and": " a ",
   "nbhdError": "Vyberte svoju štvrť.",
   "change": "Zmeniť",
   "noFloor": "Bez poschodia, len budova",
   "floorN": "Poschodie {n}",
   "step1": "Krok 1 z 2",
   "step2": "Krok 2 z 2",
   "continue": "Pokračovať",
   "groupsLead": "Toto je nepovinné. Keď si vyberiete skupinu, dostanete upozornenia a rady pre ňu.",
   "consent": "Človek s týmto telefónom súhlasí tak, že odpovie YES. Súhlasí tým aj so skupinami, ktoré sú tu vybrané.",
   "resent": "Znova sme to poslali na {phone}.",
   "protoSee": "Pozrite sa, ako správa príde do telefónu",
   "protoTag": "Prototyp",
   "howStop": "Ak už nechcete dostávať žiadne správy od Hubu, odpovedzte STOP na ktorúkoľvek SMS.",
   "howChange": "Ak chcete zmeniť skupiny, odpovedzte GROUPS.",
   "toHome": "Prejsť na Teraz",
   "sample": "Ukážková budova",
   "moreBuildings": "Ďalšie budovy: {n}. Napíšte časť adresy."
  },
  "R06": {
   "thanks": "Ďakujeme. Budete dostávať upozornenia od Hubu pre {where}, v jazyku {lang}.",
   "howStop": "Ak už nechcete dostávať žiadne správy, odpovedzte STOP.",
   "howChange": "Ak chcete zmeniť skupiny, odpovedzte GROUPS.",
   "groupsChanged": "Hotovo. Už nebudete dostávať upozornenia pre: {group}.",
   "checkinWithdrawn": "Hotovo. Vaša žiadosť o kontrolu je zrušená. Upozornenia budete dostávať naďalej.",
   "stopped": "Od Hubu už nedostanete žiadne správy. Ak ich chcete znova dostávať, odpovedzte START.",
   "deviceLabel": "SMS na obyčajnom telefóne",
   "back": "Späť do aplikácie",
   "replyHint": "Ťuknite na odpoveď a pošlite ju",
   "you": "Vy",
   "groupsMenu": "Odpovedzte číslom a zrušíte upozornenia pre túto skupinu: {list}.",
   "noGroups": "Nevybrali ste si žiadne skupiny. Dostávate všetky upozornenia pre {where}.",
   "started": "Vitajte späť. Budete dostávať upozornenia od Hubu pre {where}, v jazyku {lang}.",
   "now": "teraz",
   "exNote": "Cvičenie. Táto konverzácia je nácvik na telefóne človeka prihláseného do cvičenia. Žiadny obyvateľ nie je prihlásený ani zmenený."
  },
  "R07": {
   "moreComing": "Ďalšie informácie čoskoro",
   "moreComingLine": "Aktualizujeme to hneď, ako budeme vedieť viac.",
   "notYetKnown": "Zatiaľ nevieme",
   "where": "Kde",
   "whatToDo": "Čo robiť",
   "validUntil": "Platí {until}",
   "untilResolved": "do vyriešenia",
   "posted": "Zverejnené {t}",
   "updated": "Aktualizované {t}",
   "latest": "Najnovšie",
   "thread": "Aktualizácie, najnovšie navrchu",
   "earlier": "Staršie aktualizácie",
   "update": "Aktualizácia",
   "correction": "Oprava",
   "corrected": "Opravené {t}",
   "whatChanged": "Čo sa zmenilo: {changed}",
   "earlierWording": "Predchádzajúce znenie",
   "final": "Posledná aktualizácia",
   "resolvedTitle": "Vyriešené {t}",
   "expiredTitle": "Platnosť skončila {t}",
   "expiredNote": "Čas tohto upozornenia skončil bez poslednej aktualizácie.",
   "fromArchive": "Toto upozornenie skončilo. Zostáva tu, aby ste si ho mohli prečítať.",
   "ongoingDays": "Prebieha: deň {n} z {total}",
   "supportOffer": "Pomoc s týmto",
   "openNear": "Otvorené blízko vás",
   "openNearAll": "Zobraziť všetky otvorené miesta",
   "officialLink": "Oficiálne upozornenie k tej istej udalosti",
   "officialFrom": "Od {source}",
   "adds": "Táto správa dopĺňa, čo sa deje vo vašej budove.",
   "officialText": "Oficiálne znenie",
   "officialTemplate": "Preložené zo skontrolovanej šablóny",
   "guide": "Čo robiť: návod ({hazard})",
   "services": "Služby, ktoré s tým môžu pomôcť",
   "share": "Zdieľať",
   "amberNote": "Vymyslený zástupný text. Ukazuje len rozloženie.",
   "ambLine": "Správa od ambasádora",
   "readingOrder": "Poradie pre čítačku obrazovky: pôvod a overenie, čas zverejnenia, upozornenie, informácia, že to nie je 911, potom akcie.",
   "kinds": {
    "ack": "Prvá správa",
    "alert": "Upozornenie",
    "issued": "Vydané",
    "update": "Aktualizácia",
    "correction": "Oprava",
    "final": "Posledná aktualizácia",
    "ambassador": "Správa od ambasádora"
   },
   "whereLabel": "Kde",
   "actionLabel": "Čo robiť teraz",
   "notYetKnownLabel": "Zatiaľ nevieme",
   "latestTag": "Najnovšie",
   "ambassadorOriginal": "Originál v jazyku {lang}",
   "officialCard": "Oficiálne upozornenie k tej istej udalosti",
   "openOfficial": "Prečítať oficiálne upozornenie",
   "fromCommunity": "Toto odovzdáva ďalej oficiálne upozornenie. Hub dopĺňa, čo sa deje tu.",
   "spacesFiltered": "Podľa vašich volieb sa zobrazujú miesta, ktoré nežiadajú doklad.",
   "supportSee": "Zobraziť miesto",
   "amberBody": "Amber Alert je oficiálne upozornenie o nezvestnom dieťati. Skutočné znenie vždy pochádza od Alert Ready.",
   "endedResolved": "Toto upozornenie skončilo. Vyriešené {t}.",
   "endedWithdrawn": "Hub toto upozornenie stiahol. {reason}",
   "endedExpired": "Toto upozornenie skončilo. Platnosť skončila {t} bez poslednej aktualizácie.",
   "validLine": "Platí {until}",
   "timeLine": "Zverejnené {posted} · Aktualizované {updated}",
   "timeLineOne": "Zverejnené {posted}",
   "basicMore": "Staršie aktualizácie: {n}"
  },
  "R08": {
   "title": "Skončené upozornenia",
   "resolved": "Vyriešené {t}",
   "expired": "Platnosť skončila {t}",
   "empty": "Zatiaľ neskončilo žiadne upozornenie.",
   "emptyBody": "Keď upozornenie skončí, presunie sa sem a dá sa stále čítať.",
   "lead": "Každé upozornenie sa tu dá čítať aj po tom, čo skončí.",
   "endedOn": "Zverejnené {posted}",
   "backHome": "Späť na Teraz"
  },
  "R09": {
   "title": "Nájsť pomoc",
   "prompt": "Napríklad: prenajímateľ ma chce vysťahovať",
   "promptAlt": ["Napríklad: tento týždeň potrebujem jedlo pre rodinu", "Napríklad: niekto, s kým sa môžem porozprávať o strese"],
   "searchLabel": "Povedzte nám vlastnými slovami, čo potrebujete",
   "search": "Hľadať",
   "orChoose": "Alebo vyberte tému",
   "within": "Hľadať v téme {cat}",
   "clearCat": "Všetky témy",
   "lead": "Povedzte, čo je zlé, tak ako by ste to povedali kamarátovi. Nemusíte poznať názov služby.",
   "focusHint": "Čo píšu iní ľudia",
   "topic": "Téma: {cat}",
   "seeAll": "Zobraziť všetko v téme {cat}",
   "moreTopics": "Zobraziť všetky témy ({n})",
   "clear": "Vymazať napísaný text",
   "testTitle": "Testovacie otázky",
   "testNote": "Pre moderátorov: ťuknite na jednu a spustí sa pripravené vyhľadávanie zo zadania. Obyvatelia to nevidia.",
   "testGloss": "(dárí: {gloss})"
  },
  "R10": {
   "title": "Výsledky",
   "resultsFor": "Výsledky pre „{q}“: {n}",
   "matched": "Zhoda: {reason}",
   "crossLanguage": "Napísané v jazyku {lang}, zobrazené v preklade",
   "contributed": "Pridal(a) sused alebo suseda",
   "filters": "Filtre",
   "helpListTitle": "Služby, ktoré môžu pomôcť pri tejto situácii: {hazard}",
   "helpListNote": "Zobrazujú sa len služby, ktoré uvádzajú, ako s tým môžu pomôcť. Sú zoradené podľa toho, ako dobre sa hodia, či sú teraz otvorené, ako sú ďaleko a kedy boli naposledy potvrdené.",
   "noMatch": "Teraz nie je otvorené nič, čo je zadarmo a nežiada doklad.",
   "noMatchSuggest": "Ak odstránite „{f}“, počet vhodných miest bude {n}. Najbližšie sa otvára {when}.",
   "applySuggestion": "Odstrániť „{f}“",
   "emergency": "Ak je niekto práve teraz zranený, volajte 911.",
   "openNow": "Teraz otvorené",
   "closedNow": "Teraz zatvorené",
   "opensAt": "Otvára sa {t}",
   "distance": "{d} km",
   "resultsForOne": "1 výsledok pre „{q}“",
   "catTitle": "{cat}: počet služieb {n}",
   "catTitleOne": "{cat}: 1 služba",
   "changeSearch": "Zmeniť vyhľadávanie",
   "filtersCount": "Filtre ({n})",
   "crossQuery": "Zhoda naprieč jazykmi. Písali ste v jazyku {qlang}. Toto je napísané v jazyku {lang}.",
   "noMatchAny": "Všetkým týmto filtrom nezodpovedá nič.",
   "noMatchSuggestShort": "Ak odstránite „{f}“, počet vhodných miest bude {n}.",
   "removeAll": "Odstrániť všetky filtre",
   "noneTitle": "Zatiaľ sme to nenašli",
   "noneBody": "Človek v Hube vám pomôže nájsť správnu službu.",
   "toPerson": "Porozprávať sa s človekom v Hube",
   "showMore": "Zobraziť ďalšie ({n})",
   "hoursUnknown": "Otváracie hodiny nie sú známe",
   "communityOffer": "Ponuka od susedov",
   "inCat": "Téma: {cat}",
   "helpEmpty": "Týmto filtrom nezodpovedá žiadna služba, ktorá s tým môže pomôcť."
  },
  "R11": {
   "title": "Zatiaľ sme to nenašli",
   "body": "Človek v Hube vám pomôže nájsť správnu službu.",
   "person": "Porozprávať sa s komunitnou sprievodkyňou Hubu",
   "call": "Zavolať {phone}",
   "hours": "Otvorené {hours}",
   "visit": "Alebo príďte na 45 Overlea Boulevard",
   "tryAgain": "Skúsiť iné slová",
   "categories": "Radšej vybrať tému",
   "searched": "Pýtali ste sa na „{q}“.",
   "navigatorName": "Samira",
   "navigatorRole": "Komunitná sprievodkyňa v Hube",
   "navigatorLine": "Pozná služby v okolí a spolu s vami nájde tú správnu, cez telefón alebo osobne.",
   "sampleName": "Ukážkové meno",
   "openNow": "Teraz otvorené, do {t}",
   "closedNow": "Teraz zatvorené. Otvára sa {t}",
   "callConfirm": "V skutočnom CVH by sa tu volalo na {phone}.",
   "directionsConfirm": "V skutočnom CVH by sa tu otvorila cesta na 45 Overlea Boulevard.",
   "directions": "Cesta",
   "hoursFull": "pondelok až štvrtok 9.00 až 20.00, piatok 9.00 až 17.00, sobota 10.00 až 14.00"
  },
  "R12": {
   "status": "Práve teraz",
   "openNow": "Teraz otvorené, do {t}",
   "closed": "Teraz zatvorené",
   "opens": "Otvára sa {t}",
   "address": "Adresa a ako sa tam dostať",
   "directions": "Cesta",
   "hours": "Otváracie hodiny",
   "languages": "Jazyky, ktorými sa tu hovorí",
   "cost": "Cena",
   "bring": "Čo si priniesť",
   "id": "Budú chcieť doklad alebo pobytový status?",
   "access": "Prístupnosť",
   "contact": "Kontakt",
   "call": "Zavolať",
   "email": "E-mail",
   "website": "Webová stránka",
   "unknown": "Nie je známe",
   "languagesUnknown": "Nie je známe. Hub nevie, akými jazykmi sa tu hovorí.",
   "noAddress": "Bez adresy",
   "whereToFind": "Kde to nájdete",
   "confirmedBy": "Potvrdil(a) {org} dňa {date}",
   "publicSource": "Z verejných zdrojov. Organizácia to zatiaľ nepotvrdila.",
   "contributedBy": "Pridal(a) sused alebo suseda dňa {date}, skontroloval Hub",
   "kind": "Druh organizácie",
   "services": "Služby",
   "org": "Kto to prevádzkuje",
   "otherServices": "Pozrite sa, čo ešte ponúka {org}",
   "onMap": "Zobraziť na mape",
   "correct": "Niečo nie je správne? Opravte to",
   "communityOffer": "Ponuka od susedov",
   "communityOfferLine": "Ponúkajú to susedia, nie je to oficiálna služba.",
   "callConfirm": "V skutočnom CVH by sa tu volalo na {phone}.",
   "directionsConfirm": "V skutočnom CVH by sa tu otvorila cesta k miestu {place}.",
   "illustrative": "Ukážkové údaje pre prototyp",
   "appointment": "Potrebujem sa objednať?",
   "apptYes": "Áno. Najprv zavolajte a objednajte sa.",
   "apptNo": "Nie. Môžete prísť bez objednania.",
   "apptSometimes": "Niekedy. Zavolajte a overte si to.",
   "unknownCall": "Pred cestou zavolajte a opýtajte sa.",
   "unknownAsk": "Pred cestou sa opýtajte v Hube.",
   "stepFreeYes": "Bez schodov.",
   "stepFreeNo": "Sú tam schody.",
   "idNo": "Nie.",
   "idYes": "Áno.",
   "emailConfirm": "V skutočnom CVH by sa tu napísal e-mail na {email}.",
   "webConfirm": "V skutočnom CVH by sa tu otvorila stránka {web}.",
   "noContact": "Nie je uvedený telefón ani e-mail.",
   "todayTag": "Dnes",
   "hoursUnknown": "Otváracie hodiny nie sú známe",
   "seeAll": "Zobraziť všetky údaje",
   "source": "Odkiaľ sú tieto informácie",
   "derivedNote": "Hub má k tomuto záznamu zatiaľ len názov, miesto a druh.",
   "addedRecently": "nedávno",
   "notFound": "Toto miesto sa nepodarilo nájsť.",
   "spaceHours": "Dnes otvorené ako priestor od {from} do {to}. Iné hodiny nie sú známe.",
   "someUnknown": "Niektoré údaje zatiaľ nie sú známe. {ask}"
  },
  "R13": {
   "services": "Služby",
   "about": "O organizácii",
   "servicesCount": "Služby tu: {n}",
   "contact": "Kontakt",
   "call": "Zavolať {phone}",
   "website": "Webová stránka",
   "illustrative": "Ukážkový popis pre prototyp",
   "webConfirm": "V skutočnom CVH by sa tu otvorila stránka {web}.",
   "callConfirm": "V skutočnom CVH by sa tu volalo na {phone}.",
   "showAll": "Zobraziť všetky služby ({n})",
   "notFound": "Túto organizáciu sa nepodarilo nájsť.",
   "aboutLines": {
    "TNO": "Komunitná organizácia v Thorncliffe Parku, ktorá pre štvrť robí programy pre jedlo, usadenie sa, prácu, mládež a rodiny.",
    "HUB": "Komunitné centrum na 45 Overlea Boulevard, kde má v jednej budove miesto veľa miestnych služieb a skupín.",
    "TPL": "Verejná knižnica s knihami, počítačmi a Wi-Fi zadarmo a s programami pre všetky vekové skupiny.",
    "CITY": "Komunitné centrá a programy mesta Toronto v Thorncliffe Parku a Flemingdon Parku."
   }
  },
  "R14": {
   "title": "Mapa",
   "list": "Zoznam",
   "mapView": "Mapa",
   "loading": "Mapa sa načítava",
   "unavailable": "Mapu sa nepodarilo načítať. V zozname je všetko.",
   "showList": "Zobraziť zoznam",
   "noneInView": "Tu nič nie je. Skúste mapu oddialiť.",
   "places": "Počet miest: {n}",
   "place": "1 miesto",
   "add": "Pridať miesto",
   "rules": "Pravidlá tohto priestoru",
   "filters": "Čo potrebujete?",
   "disruptionView": "Zobrazujú sa miesta, ktoré môžu pomôcť pri tejto situácii: {hazard}",
   "legend": "Druhy miest",
   "newlyAdded": "Nové",
   "tapForHours": "Ťuknite na miesto a uvidíte otváracie hodiny",
   "legendFormal": "Služba alebo verejné miesto",
   "legendInformal": "Komunitná skupina alebo náboženské spoločenstvo",
   "legendOffer": "Ponuka od susedov",
   "legendSpace": "Teraz otvorené ako priestor",
   "legendCluster": "Miesta blízko seba. Ťuknite a priblížte.",
   "legendTitle": "Čo znamenajú tvary",
   "zoomIn": "Priblížiť",
   "zoomOut": "Oddialiť",
   "here": "Miesta tu: {n}",
   "mapLabel": "Mapa Thorncliffe Parku a Flemingdon Parku",
   "allPlaces": "Zobraziť všetky miesta",
   "subAll": "Všetky druhy miest",
   "subLabel": "Aký druh miesta?",
   "spaceFor": "Teraz otvorené ako priestor {purpose}",
   "basicList": "Pri väčšom písme sa miesta zobrazujú ako zoznam, najbližšie navrchu.",
   "noneMatch": "Týmto filtrom nezodpovedá žiadne miesto.",
   "addShort": "Pridať miesto",
   "missing": "Niečo chýba alebo nie je správne?"
  },
  "R15": {
   "title": "Miesta blízko vás",
   "byDistance": "Najbližšie navrchu",
   "empty": "Týmto filtrom nezodpovedá žiadne miesto.",
   "emptyBody": "Odstráňte filter a uvidíte viac.",
   "add": "Pridať miesto",
   "count": "Počet miest: {n}",
   "countOne": "1 miesto",
   "more": "Zobraziť ďalšie ({n})",
   "distanceHome": "{d} km",
   "clearAll": "Odstrániť všetky filtre",
   "missing": "Chýba tu niečo alebo nie je niečo správne?",
   "suggest": "Ak odstránite „{f}“, počet vhodných miest bude {n}. Najbližšie je vzdialené {d}.",
   "suggestOne": "Ak odstránite „{f}“, vyhovuje 1 miesto. Je vzdialené {d}.",
   "suggestButton": "Odstrániť „{f}“"
  },
  "R16": {
   "open": "Zobraziť podrobnosti",
   "hoursToday": "Dnes: {hours}",
   "close": "Zavrieť",
   "less": "Menej",
   "wrong": "Niečo nie je správne pri tomto mieste?",
   "distance": "{d} km od miesta, kde bývate",
   "contributed": "Pridal(a) sused alebo suseda"
  },
  "R17": {
   "title": "Pridať alebo opraviť miesto",
   "add": "Pridať miesto, ktoré chýba",
   "correct": "Opraviť miesto, ktoré nevyzerá správne",
   "fromEntry": "Opraviť toto miesto",
   "addLine": "Niečo, čo pomáha susedom a zatiaľ nie je na mape. Dva krátke kroky.",
   "correctLine": "Otváracie hodiny, miesto alebo nejaký údaj už neplatí.",
   "fromEntryLine": "Zmeňte len to, čo nie je správne. Všetko ostatné zostane, ako je.",
   "lookingAt": "Pozerali ste sa na",
   "pickTitle": "Ktoré miesto nevyzerá správne?",
   "pickHint": "Najbližšie k vám sú navrchu. Každé miesto má na svojej stránke aj „Niečo nie je správne? Opravte to“.",
   "addDifferent": "Pridať iné miesto, ktoré chýba"
  },
  "R18": {
   "title": "Skôr ako pridáte miesto",
   "continue": "Rozumiem, pokračovať",
   "step": "Krok 1 z 2: pravidlá",
   "readIn": "Prečítať pravidlá v jazyku",
   "readInHint": "Pravidlá sú napísané vo všetkých jazykoch, ktoré CVH ponúka.",
   "after": "Potom nám poviete o mieste. Väčšinou budete vyberať, nie písať."
  },
  "R19": {
   "title": "Pridať miesto",
   "name": "Ako sa to volá?",
   "what": "Čo sa tam deje, jednou vetou",
   "whatHint": "Najviac 140 znakov",
   "category": "Aký druh pomoci to je?",
   "type": "Je to oficiálna služba alebo ponuka od susedov?",
   "official": "Oficiálna služba",
   "offer": "Ponuka od susedov",
   "hours": "Kedy je otvorené?",
   "sameWeekdays": "Každý pracovný deň rovnako",
   "notSure": "Neviem",
   "from": "Od",
   "to": "Do",
   "closedDay": "Zatvorené",
   "cost": "Koľko to stojí?",
   "idQ": "Budú chcieť doklad alebo pobytový status?",
   "stepFreeQ": "Dá sa dostať dnu bez schodov?",
   "languagesQ": "Akými jazykmi sa tam hovorí?",
   "location": "Kde to je?",
   "submit": "Poslať do Hubu",
   "optional": "Nepovinné",
   "ready": "Pripravené na odoslanie",
   "saved": "Uložené v tomto telefóne",
   "step": "Krok 2 z 2: miesto",
   "choose": "Vyberte jednu možnosť",
   "catNotSure": "Neviem",
   "offerLine": "Ponúkajú to susedia, nie je to oficiálna služba. Na mape sa zobrazí s prerušovaným okrajom.",
   "officialLine": "Prevádzkuje to organizácia, agentúra alebo mesto.",
   "whereBtn": "Ukázať, kde to je",
   "whereChange": "Zmeniť",
   "whereNone": "Zatiaľ nevybrané",
   "costFree": "Zadarmo",
   "costLow": "Lacno",
   "costFee": "Platí sa",
   "yes": "Áno",
   "no": "Nie",
   "weekdays": "Pondelok až piatok",
   "langsHint": "Vyberte všetky, ktoré platia.",
   "count": "{n} zo 140",
   "missingTitle": "Doplňte toto a potom pošlite:",
   "resubmitNote": "Hub vám to poslal späť. {change}",
   "closedOpt": "Zatvorené",
   "notSureOpt": "Neviem",
   "toOpt": "Do",
   "fromOpt": "Otvára sa",
   "hoursNotSureLine": "To nevadí. Hub sa opýta na mieste.",
   "whatPh": "Napríklad: potraviny zadarmo vo štvrtok večer, pre každého",
   "namePh": "Napríklad: štvrtková potravinová banka"
  },
  "R20": {
   "title": "Kde to je?",
   "pin": "Označiť miesto špendlíkom na mape",
   "building": "V budove",
   "described": "Opíšte, kde v budove to je",
   "describedHint": "Napríklad: spoločenská miestnosť za mešitou",
   "landmark": "Pri známom mieste",
   "landmarkHint": "Napríklad: pri vodnom ihrisku v R.V. Burgess Park",
   "address": "Adresa",
   "noAddress": "Adresu nepotrebujete.",
   "howTitle": "Ako to ľudia nájdu?",
   "use": "Použiť toto miesto",
   "pinHint": "Posúvajte mapu, kým špendlík nebude na mieste.",
   "pinNear": "Špendlík na mape, blízko miesta {place}",
   "nearLandmark": "Blízko miesta {place}",
   "buildingChoose": "Vyberte budovu",
   "landmarkChoose": "Vyberte známe miesto",
   "landmarkMore": "Čokoľvek ďalšie, čo ľuďom pomôže to nájsť",
   "addressHint": "Len ak ju poznáte.",
   "needOne": "Vyberte jeden spôsob vyššie.",
   "needBuilding": "Najprv vyberte budovu.",
   "needLandmark": "Najprv vyberte známe miesto.",
   "needAddress": "Najprv napíšte adresu.",
   "pinWhere": "Špendlík je blízko miesta {place}.",
   "mapLabel": "Mapa na umiestnenie špendlíka"
  },
  "R21": {
   "title": "Poslané do Hubu",
   "general": "Niekto v Hube si to prečíta asi do týždňa. Dáme vám vedieť, keď to bude na mape.",
   "ambassador": "Ste ambasádor, preto sa to kontroluje prednostne. Na mape to zvyčajne bude do jedného dňa.",
   "lane": "Spôsob kontroly: {lane}",
   "laneGeneral": "Kontrola komunity",
   "laneAmbassador": "Kontrola pre ambasádorov, rýchlejšia",
   "youSent": "Poslali ste: {name}",
   "next": "Čo sa stane ďalej",
   "n1": "Niekto v Hube si to prečíta.",
   "n2": "Ak to dodržiava pravidlá, objaví sa to na mape a vo vyhľadávaní.",
   "n3": "Ak treba niečo zmeniť, povieme vám čo a môžete to poslať znova.",
   "n1Amb": "Niekto v Hube si to prečíta skôr ako ostatné príspevky v poradí.",
   "howLong": "Ako dlho",
   "weekLine": "Asi týždeň",
   "dayLine": "Zvyčajne do jedného dňa",
   "toMap": "Späť na mapu",
   "another": "Pridať ďalšie miesto",
   "protoLabel": "Len prototyp",
   "protoDecline": "Pozrite si miesto, ktoré Hub poslal späť",
   "protoAccepted": "Pozrite si na mape miesto, ktoré pridal sused"
  },
  "R22": {
   "title": "Opraviť toto miesto",
   "changeOne": "Zmeňte, čo nie je správne. Všetko ostatné zostane, ako je.",
   "submit": "Poslať opravu",
   "sent": "Ďakujeme. Hub zmenu skontroluje.",
   "change": "Zmeniť",
   "changedTag": "Zmenené",
   "was": "Predtým: {v}",
   "undo": "Vrátiť späť",
   "nothingYet": "Zmeňte aspoň jednu vec a potom pošlite.",
   "doneEditing": "Hotovo",
   "onlyThis": "Pošle sa len to, čo zmeníte. Hub to skontroluje, než sa miesto aktualizuje.",
   "toPlace": "Späť na miesto",
   "toMap": "Späť na mapu",
   "sentTitle": "Oprava poslaná",
   "whatChanged": "Čo ste zmenili",
   "whereLabel": "Kde to je",
   "namePlace": "Názov"
  },
  "R23": {
   "title": "Vaše miesto zatiaľ nebolo pridané",
   "reason": "Prečo",
   "whatToChange": "Čo treba zmeniť",
   "resubmit": "Zmeniť a poslať znova",
   "kept": "Všetko, čo ste napísali, zostáva uložené.",
   "sentAgo": "Poslali ste to {t}.",
   "youWrote": "Čo ste napísali",
   "whereNone": "Miesto nebolo zadané",
   "toMap": "Späť na mapu",
   "reasons": {
    "advert": {
     "why": "Niečo to predáva alebo žiada peniaze. CVH nie je trhovisko.",
     "change": "Ak je tam časť zadarmo, ktorú môže použiť ktokoľvek, opíšte len túto časť. Nepíšte ceny ani platby."
    },
    "noLocation": {
     "why": "Nevedeli sme zistiť, kde to je.",
     "change": "Pridajte budovu, známe miesto v blízkosti alebo špendlík na mape. Adresu nepotrebujete."
    },
    "duplicate": {
     "why": "Toto miesto už je na mape.",
     "change": "Ak na ňom niečo nie je správne, otvorte ho a radšej vyberte „Opravte to“."
    },
    "unclear": {
     "why": "Nevedeli sme zistiť, o aké miesto ide alebo čo sa tam deje.",
     "change": "Napíšte jeho názov a jednou vetou, čo tam ľudia môžu dostať."
    },
    "outOfArea": {
     "why": "Je to mimo Thorncliffe Parku a Flemingdon Parku.",
     "change": "CVH zobrazuje len miesta v týchto dvoch štvrtiach alebo blízko nich."
    },
    "notCommunity": {
     "why": "Nie je to otvorené pre každého zo štvrte.",
     "change": "Pošlite to znova, ak to môže použiť ktokoľvek zo štvrte."
    }
   }
  },
  "R24": {
   "title": "Buďte pripravení",
   "lead": "Čo robiť pred, počas a po šiestich problémoch, ktoré sa tu stávajú.",
   "numbers": "Čísla, ktoré môžem potrebovať",
   "headsUp": "Pripomienka pred každou sezónou",
   "checkin": "Požiadať o kontrolu počas horúčav a výpadkov",
   "readTime": "Čítanie: {n} min",
   "guides": "Návody: čo robiť pred, počas a po",
   "more": "Ďalšie spôsoby, ako sa pripraviť",
   "checkinLine": "Ambasádor vášho poschodia sa na vás príde pozrieť. Nie je to záchranná služba.",
   "numbersLine": "911, 211, 311, Toronto Hydro a Hub",
   "headsUpLine": "Len v CVH, nikdy cez SMS",
   "none": "Návody sa teraz nepodarilo načítať. Ak je niekto v ohrození, volajte 911."
  },
  "R25": {
   "stagesNav": "Prejsť na",
   "aiLabel": "Napísala umelá inteligencia pre prototyp. Ľudia to skontrolujú, než sa CVH spustí.",
   "kit": "Tento návod zodpovedá vytlačenému balíčku Local Preparedness Kit.",
   "numbers": "Čísla, ktoré môžem potrebovať",
   "services": "Služby, ktoré môžu pomôcť",
   "spaces": "Otvorené miesta na {purpose}",
   "forYou": "Najprv pre vás",
   "fullGuide": "Celý návod",
   "next": "Ďalej: {stage}",
   "stageNow": "Čítate: {stage}",
   "unavailable": "Tento návod zatiaľ nie je v jazyku {lang}.",
   "guideWord": "Návod",
   "readTime": "Čítanie: {n} min",
   "helpTitle": "Pomoc s týmto",
   "tailoredLink": "Podľa vašich volieb",
   "allSteps": "Zobraziť všetky kroky ({n})",
   "purposeWords": {
    "cooling": "ochladenie",
    "cleanAir": "čistý vzduch",
    "charging": "nabíjanie"
   },
   "endLine": "Toto je posledná časť návodu. Ak potrebujete ďalšiu pomoc:",
   "numbersLine": "911, 211, 311, Toronto Hydro a Hub",
   "openedDuring": "Otvorené na časti „Počas“, pretože sa to deje práve teraz."
  },
  "R26": {
   "title": "Do ktorých skupín patríte?",
   "lead": "Vyberte všetky, ktoré sa vás týkajú. Podľa toho dostanete upozornenia a rady. Nikdy sa nepýtame prečo.",
   "skipLine": "Ak to preskočíte, na upozorneniach, ktoré dostávate, sa nič nezmení.",
   "helperConfirm": "Pomáham niekomu. Tento človek s týmito voľbami súhlasil.",
   "helperNote": "Najprv sa, prosím, opýtajte tohto človeka.",
   "step": "Krok 1 z 2",
   "checkinNext": "Potom si vyberiete budovu a poschodie a ako chcete, aby sa na vás prišli pozrieť.",
   "helperNeeded": "Najprv sa, prosím, opýtajte tohto človeka. Keď súhlasí, zaškrtnite políčko, alebo túto otázku preskočte.",
   "save": "Uložiť",
   "saved": "Uložené. Platí to hneď.",
   "choose": "Vyberte všetky, ktoré sa vás týkajú",
   "helping": "Pomáhate s tým niekomu?"
  },
  "R27": {
   "title": "Filtre",
   "apply": "Zobraziť výsledky ({n})",
   "clear": "Vymazať všetko",
   "lead": "Odpovedzte len na otázky, na ktorých vám záleží. Všetko ostatné zostane otvorené.",
   "openNowOnly": "Len miesta, ktoré sú teraz otvorené",
   "anyLang": "Akýkoľvek jazyk",
   "langHint": "Zobrazí miesta, kde ním niekto hovorí. Miesta, ktoré nám to nepovedali, sa nezobrazia.",
   "noIdHint": "Zobrazí len miesta, ktoré Hubu povedali, že nebudú chcieť doklad, papiere ani imigračný status, aby vám pomohli. Miesta, ktoré nám to nepovedali, sa nezobrazia. Tak neprídete niekam, kde sa vás na to opýtajú.",
   "private": "Vaše odpovede zostanú v tomto telefóne. Neukladajú sa ani sa nikomu neposielajú.",
   "fromChoices": "Podľa vašich volieb",
   "cancel": "Späť bez zmien",
   "applyOne": "Zobraziť 1 výsledok",
   "moreQuestions": "Ďalšie otázky ({n})",
   "applyNone": "Použiť (zatiaľ nič nezodpovedá)"
  },
  "R28": {
   "title": "Čo znamená „overené“",
   "body": "Overené znamená, že niekto v Hube alebo v partnerskej organizácii, s ktorou Hub spolupracuje, toto upozornenie pred odoslaním overil u ľudí priamo na mieste.",
   "who": "{org} overil(a) toto upozornenie {t}.",
   "notYet": "Zatiaľ neoverené znamená, že upozornenie prišlo od ambasádora budovy, ktorý sa to často dozvie ako prvý. Hub ho skontroluje, hneď ako bude môcť.",
   "official": "Oficiálne upozornenia prichádzajú od {source} a posielajú sa ďalej bez zmeny slov.",
   "notFalse": "Zatiaľ neoverené neznamená, že je to nesprávne.",
   "thisAlert": "Toto upozornenie",
   "ambFirst": "Prvýkrát ho zverejnil ambasádor budovy {building} {t}.",
   "ambPosted": "Zverejnil ho ambasádor budovy {building} {t}.",
   "notYetAct": "Môžete podľa neho konať už teraz. Keď ho Hub skontroluje, bude na ňom namiesto toho „Overil Hub“.",
   "correctedLine": "Opravené {t}. Upozornenie ukazuje, čo sa zmenilo, a predchádzajúce znenie sa dá stále prečítať.",
   "officialAdds": "Hub nikdy nemení slová oficiálneho upozornenia. Môže však vo vlastnom komunitnom upozornení doplniť, čo sa deje vo vašej budove.",
   "legendTitle": "Slová, ktoré uvidíte pri upozorneniach",
   "thisOne": "Toto upozornenie",
   "legendVerified": "Niekto v Hube alebo u partnera to skontroloval pred odoslaním.",
   "legendUnverified": "Zverejnil to ambasádor budovy. Hub to zatiaľ neskontroloval.",
   "legendOfficial": "Od štátneho zdroja, odovzdané ďalej slovo za slovom.",
   "backToAlert": "Späť na upozornenie"
  },
  "R29": {
   "title": "Zdieľať toto upozornenie",
   "preview": "Toto dostanú vaši susedia",
   "everyone": "Túto verziu dostanú všetci. Nič, čo je prispôsobené vám, sa nezdieľa.",
   "notRecorded": "CVH nezaznamenáva, kto zdieľa upozornenia, ani komu ich posielate.",
   "send": "Zdieľať",
   "handed": "Tu by sa otvorili možnosti zdieľania vo vašom telefóne.",
   "lead": "Vaši susedia dostanú upozornenie tak, ako ho napísal Hub, aj s tým, odkiaľ pochádza, a s odkazom na najnovšiu verziu.",
   "postedAt": "Zverejnené {t}",
   "updatedAt": "Aktualizované {t}",
   "todayAt": "dnes o {time}",
   "dayAt": "{day} o {time}",
   "linkLine": "Najnovšie aktualizácie a opravy: {url}",
   "sendLine": "Telefón sa vás opýta, cez ktorú aplikáciu to chcete poslať.",
   "placeMore": "a {n} ďalších"
  },
  "R30": {
   "deviceLabel": "Upozornenie v skupine na WhatsAppe",
   "group": "Susedia zo 4. poschodia",
   "openedLater": "Otvorené neskôr: ukazuje najnovšiu aktualizáciu a opravu.",
   "groupBuilding": "Susedia z budovy {building}",
   "members": "{name}, Maria, vy a 9 ďalších",
   "membersOut": "Maria, Farhan a 10 ďalších",
   "today": "Dnes",
   "forwarded": "Preposlané",
   "you": "Vy",
   "askLine": "Nejde elektrina aj niekomu inému?",
   "askLineOther": "Vie niekto, čo sa deje s výťahom?",
   "proto": "Prototyp",
   "backToApp": "Späť do aplikácie",
   "removeLink": "Odstrániť odkaz",
   "restoreLink": "Vrátiť odkaz",
   "openLater": "Otvoriť odkaz o niekoľko hodín neskôr",
   "senderLang": "{name} číta CVH v jazyku {lang}. Odkaz sa otvorí v jazyku toho, kto ho otvorí, nie odosielateľa.",
   "linkRemovedNote": "Odkaz bol odstránený. Správa aj tak hovorí, čo sa stalo, kde, od koho je, či je overená, kedy a čo robiť.",
   "sinceSent": "Odkedy to {name} poslal(a):",
   "showSince": "Ukázať, čo sa zmenilo",
   "noChange": "Otvorené neskôr: odkedy to bolo poslané, nebolo zverejnené nič nové.",
   "nowVerified": "Otvorené neskôr: Hub medzitým tento príspevok skontroloval, takže pri upozornení je teraz „Overil Hub“.",
   "exNote": "Cvičenie. Ak niekto prepošle cvičnú správu, slovo „Cvičenie“ ide s ňou ako prvý riadok, aby si ju nikto nepomýlil so skutočným upozornením."
  },
  "R31": {
   "title": "Čísla, ktoré môžem potrebovať",
   "emergency": "Tiesňová situácia",
   "emergencyWhen": "Volajte 911, ak je práve teraz v ohrození niečí život alebo bezpečnosť: požiar, náhle zdravotné problémy alebo trestný čin, ktorý sa práve deje.",
   "p211": "Pomoc pri hľadaní komunitných, sociálnych a štátnych služieb",
   "p311": "Služby mesta Toronto a problémy, ktoré nie sú tiesňové",
   "hydro": "Nahlásiť výpadok elektriny firme Toronto Hydro",
   "hub": "Porozprávať sa s niekým v Hube",
   "building": "Vaša budova: {role}",
   "noBuilding": "Kontakt na vašu budovu zatiaľ nemáme. Pomôže vám ambasádor vášho poschodia.",
   "call": "Zavolať",
   "callConfirm": "V skutočnom CVH by sa tu volalo na {number}.",
   "lead": "Pri každom čísle je napísané, na čo slúži.",
   "others": "Na všetko ostatné",
   "call911": "Volať 911",
   "buildingTitle": "Vaša budova",
   "noBuildingNoAmb": "Kontakt na vašu budovu zatiaľ nemáme. Hub vám pomôže spojiť sa so správou budovy.",
   "noBuildingChosen": "Vyberte svoju budovu a jej kontakt tu ukážeme, keď ho budeme mať. Dovtedy vám pomôže Hub.",
   "chooseBuilding": "Vyberte svoju budovu",
   "ambRoute": "Býva vo vašej budove a môže veci odovzdať správe budovy.",
   "hubHours": "Otvorené pondelok až štvrtok 9.00 až 20.00, piatok 9.00 až 17.00, sobota 10.00 až 14.00",
   "calling": "Zavolať: {what}",
   "roles": {
    "superintendent": "domovník"
   },
   "checked": "Skontroloval Hub, naposledy aktualizované {date}",
   "noOthers": "Ostatné čísla sa teraz nepodarilo načítať. Skúste to znova o pár minút."
  },
  "R32": {
   "title": "Pripomienka pred každou sezónou",
   "lead": "Krátka pripomienka v CVH pred horúčavami, dymom a zimnými výpadkami, s jednou alebo dvoma vecami, ktoré treba urobiť.",
   "never": "Pripomienky sa zobrazujú len v CVH. Nikdy neprídu ako SMS.",
   "on": "Pripomienky zapnuté",
   "off": "Pripomienky vypnuté",
   "season": "Kedy: {season}",
   "switchLabel": "Ukázať mi pripomienku pred každou sezónou",
   "what": "Čo by ste videli",
   "whatOn": "Čo uvidíte",
   "titles": {
    "heat": "Pred horúcim počasím",
    "smoke": "Pred sezónou dymu z lesných požiarov",
    "winter": "Pred zimnými búrkami"
   },
   "readGuide": "Prečítajte si návod: {hazard}",
   "turnedOn": "Pripomienky zapnuté. Uvidíte ich na obrazovke Teraz, len v CVH.",
   "turnedOff": "Pripomienky vypnuté. Nič iné sa nezmenilo.",
   "offLine": "Pripomienky sú vypnuté, kým ich nezapnete.",
   "whereLine": "Zobrazujú sa na obrazovke Teraz, pár týždňov pred každou sezónou."
  },
  "R33": {
   "title": "Požiadať o kontrolu",
   "what": "Keď bude vo vašej budove varovanie pred horúčavou alebo výpadok elektriny, ambasádor vášho poschodia sa na vás príde pozrieť a môže vám pomôcť spojiť sa so službami, ktoré potrebujete.",
   "notEmergency": "Kontrola nie je záchranná služba.",
   "how": "Ako chcete, aby sa na vás prišli pozrieť?",
   "call": "Telefonát",
   "text": "SMS",
   "knock": "Zaklopanie na dvere",
   "unit": "Číslo bytu",
   "unitWhy": "Číslo bytu potrebujeme len preto, aby váš ambasádor vedel, na ktoré dvere zaklopať.",
   "building": "Vaša budova a poschodie",
   "noAmbassador": "Na poschodí {floor} zatiaľ nie je ambasádor, preto vám kontrolu nemôžeme sľúbiť.",
   "hubInstead": "Namiesto toho zavolajte do Hubu na {phone}. Máme otvorené {hours}.",
   "request": "Požiadať o kontroly",
   "requested": "O kontroly ste požiadali",
   "requestedBody": "Keď bude v budove {building} varovanie pred horúčavou alebo výpadok elektriny, ambasádor vášho poschodia sa na vás príde pozrieť. Spôsob: {method}.",
   "withdraw": "Zrušiť kontroly",
   "withdrawn": "Kontroly sú zrušené. Upozornenia budete dostávať naďalej.",
   "helper": "Pomáham niekomu. Tento človek súhlasil, že chce požiadať o kontroly.",
   "whatTitle": "Čo je kontrola",
   "askPlace": "Potrebujeme vašu budovu a poschodie, aby sme vedeli, či sa na vás môže prísť pozrieť ambasádor poschodia.",
   "chooseBuilding": "Vyberte svoju budovu",
   "chooseFloor": "Vyberte svoje poschodie",
   "floorN": "Poschodie {n}",
   "change": "Zmeniť",
   "placeLine": "{building}, poschodie {floor}",
   "covered": "Poschodie {floor} má ambasádora poschodia.",
   "callHub": "Zavolať do Hubu",
   "stillAlerts": "Naďalej budete dostávať všetky upozornenia pre svoju budovu.",
   "needMethod": "Vyberte, ako chcete, aby sa na vás prišli pozrieť.",
   "needUnit": "Pri zaklopaní doplňte číslo bytu, alebo vyberte telefonát či SMS.",
   "needHelper": "Najprv sa, prosím, opýtajte tohto človeka. Keď súhlasí, zaškrtnite políčko.",
   "needPlace": "Najprv vyberte budovu a poschodie.",
   "howWithdraw": "Kontroly môžete kedykoľvek zrušiť: tu, v časti Moje voľby alebo odpoveďou NOCHECK na SMS od Hubu.",
   "changeHow": "Zmeniť spôsob",
   "again": "Znova požiadať o kontroly",
   "unitShown": "Byt {unit}",
   "continue": "Pokračovať",
   "skip": "Teraz nie",
   "helping": "Pomáhate s tým niekomu?"
  },
  "R34": {
   "title": "Čo som povedal CVH",
   "lead": "Len to, čo ste si vybrali. Tu môžete čokoľvek zmeniť alebo odstrániť. Zmeny platia hneď.",
   "language": "Jazyk",
   "building": "Budova a poschodie",
   "basic": "Väčšie písmo, menej vecí",
   "groups": "Skupiny",
   "checkin": "Kontroly",
   "headsUp": "Sezónne pripomienky",
   "change": "Zmeniť",
   "remove": "Odstrániť",
   "removed": "Odstránené. Platí to hneď.",
   "nothing": "CVH ste zatiaľ nič nepovedali.",
   "onDevice": "Tieto voľby sú uložené len v tomto zariadení.",
   "invite": "Ak chcete dostávať upozornenia pre svoju budovu a skupiny do telefónu, nastavte si upozornenia cez SMS. Trvá to minútu a nepotrebujete účet.",
   "inviteYes": "Nastaviť upozornenia cez SMS",
   "inviteNo": "Teraz nie",
   "fromTailored": "Rady v časti „Čo to znamená pre vás“ vychádzajú len z volieb na tejto stránke. Keď ich tu zmeníte, zmenia sa aj rady.",
   "neighbourhoodOnly": "Všetky upozornenia pre {nbhd}",
   "floorOf": "{building}, poschodie {floor}",
   "on": "Zapnuté",
   "setByHelper": "Zapol to niekto, kto vám pomáha",
   "checkinNone": "Nepožiadali ste",
   "checkinAsk": "Požiadať o kontrolu",
   "checkinBy": "Spôsob: {method}",
   "checkinNoAmb": "Na vašom poschodí zatiaľ nie je ambasádor. Namiesto toho vám pomôže Hub.",
   "unitLine": "Byt {unit}, len na zaklopanie",
   "textAlerts": "Upozornenia cez SMS",
   "textOn": "Zapnuté, na číslo {phone}",
   "textPending": "Čaká sa na vašu odpoveď YES z čísla {phone}",
   "howStop": "Ak to chcete zastaviť, odpovedzte STOP na ktorúkoľvek SMS od Hubu.",
   "removedItem": "Odstránené: {item}",
   "tellUs": "CVH môžete povedať:",
   "whereLive": "Kde bývate",
   "whichGroups": "Do ktorých skupín patríte",
   "turnOff": "Vypnúť",
   "changeGroups": "Zmeniť skupiny",
   "groupsNone": "Nič nevybrané",
   "chooseGroups": "Vybrať skupiny",
   "langNote": "Jazyk, v ktorom čítate CVH.",
   "removedBuildingOne": "1 uložená budova už nie je v zozname budov, preto bola odstránená.",
   "removedBuildingMany": "Niektoré uložené budovy už nie sú v zozname budov, preto boli odstránené. Počet: {n}.",
   "removedFloorOne": "1 uložené poschodie už neexistuje, preto bolo odstránené.",
   "removedFloorMany": "Niektoré uložené poschodia už neexistujú, preto boli odstránené. Počet: {n}.",
   "removedRest": "Všetko ostatné, čo ste si vybrali, zostáva bez zmeny.",
   "clearAll": "Vymazať všetko",
   "clearTitle": "Vymazať všetko z tohto telefónu?",
   "clearBody": "Z tohto telefónu sa odstráni váš jazyk, skupiny, budovy a poschodia. Začnete znova výberom jazyka.",
   "clearYes": "Áno, vymazať všetko",
   "loading": "Vaše budovy sa načítavajú...",
   "listFailed": "Zoznam budov sa teraz nepodarilo načítať. Vaše voľby sú stále uložené.",
   "buildingByRsn": "Budova {rsn}",
   "floorsOne": "1 vybrané poschodie",
   "floorsMany": "Vybrané poschodia: {n}",
   "buildingsNone": "Nič nevybrané",
   "removeItem": "Odstrániť: {item}"
  },
  "R35": {
   "title": "Dostávať upozornenia pre vašu budovu",
   "lead": "Vyberte, kde bývate, a upozornenia pre vašu budovu uvidíte ako prvé. Každý krok je nepovinný.",
   "nbhd": "Štvrť",
   "building": "Budova",
   "floor": "Poschodie",
   "nbhdOnly": "Len celá štvrť",
   "floorLine": "Keď vyberiete poschodie, dostanete aj upozornenia len pre vaše poschodie, napríklad o výťahu alebo vypnutí vody.",
   "noUnit": "Na číslo bytu sa tu nikdy nepýtame.",
   "preselected": "Podľa vášho oznamu",
   "skipLine": "Ak to preskočíte, aj tak uvidíte všetky upozornenia pre svoju štvrť.",
   "finishedTitle": "Vybrali ste",
   "invite": "Ak chcete dostávať upozornenia pre svoju budovu, poschodie a skupiny do telefónu, nastavte si upozornenia cez SMS. Trvá to minútu a nepotrebujete účet.",
   "inviteYes": "Nastaviť upozornenia cez SMS",
   "inviteNo": "Teraz nie",
   "helper": "Pomáham niekomu. Tento človek s touto voľbou súhlasil.",
   "step": "Krok 2 z 2",
   "buildingSearch": "Vyhľadajte svoju budovu",
   "more": "Ďalšie budovy: {n}. Napíšte časť adresy a nájdite svoju.",
   "noMatch": "Žiadna budova nezodpovedá „{q}“.",
   "change": "Zmeniť",
   "noFloor": "Bez poschodia, len budova",
   "floorN": "Poschodie {n}",
   "sample": "Ukážková budova",
   "nextCheckin": "Ďalej: ako chcete, aby sa na vás prišli pozrieť.",
   "helperNeeded": "Najprv sa, prosím, opýtajte tohto človeka. Keď súhlasí, zaškrtnite políčko, alebo túto otázku preskočte.",
   "save": "Uložiť",
   "saved": "Uložené. Platí to hneď.",
   "both": "Thorncliffe Park a Flemingdon Park",
   "nothingSummary": "Zatiaľ nič. Uvidíte všetky upozornenia pre Thorncliffe Park a Flemingdon Park.",
   "everyAlert": "Všetky upozornenia pre {nbhd}",
   "floorOf": "{building}, poschodie {floor}",
   "checkinBy": "Kontroly: {method}",
   "changeAll": "Zmeniť, čo ste vybrali",
   "toHome": "Prejsť na Teraz",
   "manyLine": "Vyberte svoju budovu alebo budovu príbuzného. Môžete ich vybrať koľko chcete.",
   "chosenNone": "Zatiaľ nie je vybraná žiadna budova",
   "chosenOne": "1 vybraná budova",
   "chosenMany": "Vybrané budovy: {n}",
   "floorsIn": "Poschodia v budove {building}. Nepovinné.",
   "noFloorsListed": "Pre túto budovu zatiaľ nie sú uvedené žiadne poschodia.",
   "loading": "Zoznam budov sa načítava...",
   "loadFailed": "Zoznam budov sa nepodarilo načítať. Skontrolujte pripojenie a skúste to znova, alebo tento krok preskočte.",
   "retry": "Skúsiť znova"
  },
  "A01": {
   "title": "Moja budova",
   "assigned": "Ste ambasádor pre budovu {building}, poschodia {floors}.",
   "canPost": "Môžete zverejňovať aktualizácie pre ktorékoľvek poschodie budovy {building}.",
   "post": "Zverejniť aktualizáciu o budove",
   "active": "Deje sa vo vašej budove",
   "nothing": "Vo vašej budove sa nič nedeje.",
   "round": "Kolo kontrol na vašich poschodiach: {n}",
   "openRound": "Otvoriť moje kolo",
   "role": "Ambasádor budovy",
   "roundFloors": "Vaše kolo: poschodia {a} až {b}.",
   "offline": "Nie je signál. Čo urobíte, sa uloží v telefóne a pošle sa, keď budete mať signál.",
   "noRound": "Teraz nie je žiadne kolo kontrol. Začne sa, keď Hub pošle upozornenie na horúčavu alebo výpadok elektriny pre vašu budovu.",
   "toDo": "Zostáva urobiť: {n}",
   "tellInPerson": "Domácnosti, ktorým to treba povedať osobne: {n}",
   "practice": "Cvičné kolo",
   "myRound": "Moje kolo",
   "myPosts": "Vaše aktualizácie",
   "postedAgo": "Zverejnené {t}",
   "fromHub": "Od Hubu",
   "fromAmb": "Od ambasádora budovy",
   "fromOfficial": "Oficiálne upozornenie",
   "fromPartner": "Od partnera",
   "verifiedWord": "Overené",
   "notVerifiedWord": "Zatiaľ neoverené"
  },
  "A02": {
   "title": "Zverejniť aktualizáciu o budove",
   "types": "Čo sa deje? Vyberte všetko, čo platí",
   "floors": "Ktoré poschodia?",
   "wholeBuilding": "Celá budova",
   "range": "Od poschodia {a} po {b}",
   "pick": "Vybrať poschodia",
   "photo": "Pridať fotku",
   "line": "Pridať jeden riadok",
   "lineRequired": "Jedným riadkom napíšte, čo sa deje",
   "optional": "Nepovinné",
   "other911": "Ak je niekto v ohrození, najprv volajte 911.",
   "appearsAs": "Zobrazí sa ako: Ambasádor budovy, {building}",
   "goesNow": "Toto sa pošle hneď.",
   "waits": "Hub to skontroluje pred odoslaním.",
   "post": "Zverejniť aktualizáciu",
   "notOffered": "Upozornenia na horúčavu a dym posiela Hub pre celú štvrť.",
   "exOutcome": "Nácvik: toto ide len do Hubu. Obyvateľom sa nič neposiela.",
   "exNote": "Cvičenie: tento príspevok je nácvik. Ide len do Hubu, nikdy nie obyvateľom.",
   "typeMore": {
    "fire": "poplach alebo evakuácia",
    "water": "alebo potrubie"
   },
   "required": "Povinné",
   "wholeLine": "Všetky poschodia ({n})",
   "mineLabel": "Poschodia {a} až {b}",
   "mineLine": "Vaše kolo",
   "pickLabel": "Vybrať poschodia",
   "pickLine": "Ťuknite na prvé poschodie, potom na posledné",
   "pickNone": "Zatiaľ nie sú vybrané žiadne poschodia",
   "pickOne": "Poschodie {a}",
   "pickRange": "Poschodia {a} až {b}",
   "floorAria": "Poschodie {n}",
   "more": "Ak chcete, pridajte viac",
   "photoAdded": "Fotka pridaná (ukážka)",
   "remove": "Odstrániť",
   "lineAdded": "Váš riadok",
   "ownLine": "Alebo napíšte vlastný riadok",
   "sampleBn": "Ukážkový riadok v bengálčine",
   "sampleTag": "Prototyp",
   "mtNote": "Obyvatelia, ktorí čítajú v inom jazyku, to uvidia s označením strojového prekladu.",
   "phrases": ["Personál budovy o tom vie.", "Na schodoch buďte opatrní.", "Pozrite sa, prosím, na susedov, ktorí môžu potrebovať pomoc."],
   "otherPhrases": ["Hlavné dvere sa nezamykajú.", "Na chodbe nesvietia svetlá.", "Šachta na odpadky je upchatá."],
   "otherFirst": "Ak je niekto v ohrození, najprv volajte 911. Potom napíšte, čo sa tu deje.",
   "someWait": "Jeden z týchto druhov vždy čaká na Hub, preto čaká aj táto aktualizácia.",
   "offlineBar": "Teraz nie je signál. Uloží sa to v telefóne a pošle sa, keď budete mať signál.",
   "postTo": "Zverejniť aktualizáciu: {floors}",
   "wholeWord": "celá budova",
   "errTypes": "Vyberte, čo sa deje.",
   "errFloors": "Ťuknite na poschodia alebo vyberte Celá budova.",
   "errLine": "Pri možnosti Iné treba jeden riadok: napíšte, čo sa deje."
  },
  "A03": {
   "liveTitle": "Zverejnené",
   "live": "Už je to vo všetkých kanáloch, aj v SMS. Kým to Hub neskontroluje, zobrazuje sa to ako „Zatiaľ neoverené“.",
   "waitingTitle": "Čaká na Hub",
   "waiting": "Hub to práve kontroluje. Pošle sa to hneď, ako to bude schválené.",
   "approved": "Schválené a poslané {t}.",
   "declined": "Hub to neposlal. Dôvod: {reason}",
   "verified": "Hub overil vašu aktualizáciu {t}.",
   "corrected": "Hub opravil vašu aktualizáciu. Dôvod: {reason}",
   "withdrawn": "Hub stiahol vašu aktualizáciu. Dôvod: {reason}",
   "slow": "Stále sa posiela. Signál je tu slabý. Dokončí sa to, keď bude signál lepší.",
   "where": "Poslané do: {channels}",
   "when": "Zverejnené {t}",
   "states": {
    "queued": "Uložené v telefóne. Pošle sa, keď budete mať signál",
    "live": "Zverejnené. Zatiaľ neoverené",
    "waiting": "Čaká na Hub",
    "approved": "Schválené a poslané",
    "declined": "Hub to neposlal",
    "verified": "Overil Hub",
    "withdrawn": "Stiahol Hub",
    "corrected": "Opravil Hub",
    "exercise": "Cvičenie. Neposlané obyvateľom"
   },
   "queuedTitle": "Uložené v telefóne",
   "queued": "Uložené v telefóne. Pošle sa, keď budete mať signál.",
   "writtenAt": "Napísané {t}. Nemusíte robiť nič ďalšie.",
   "approvedTitle": "Schválené a poslané",
   "declinedTitle": "Neposlané",
   "verifiedTitle": "Overil Hub",
   "correctedTitle": "Opravil Hub",
   "withdrawnTitle": "Stiahol Hub",
   "exerciseTitle": "Cvičný príspevok uložený",
   "exercise": "Toto je cvičenie. Obyvateľom sa nič neposlalo.",
   "approvedLine": "Teraz sa zobrazuje ako overené Hubom.",
   "verifiedLine": "Obyvatelia teraz pri vašej aktualizácii vidia „Overil Hub“. Druhá správa sa neposlala.",
   "correctedLine": "Hub zmenil vašu aktualizáciu: {text}",
   "correctedWhen": "Opravené {t}.",
   "yourUpdate": "Vaša aktualizácia",
   "floorsAll": "Celá budova",
   "floorsOne": "Poschodie {a}",
   "floorsRange": "Poschodia {a} až {b}",
   "photoYes": "S fotkou",
   "whereWhen": "Čo kam išlo a kedy",
   "chText": "SMS",
   "chWeb": "Aplikácia a webová stránka CVH",
   "sentTo": "Poslané {t} obyvateľom budovy {building}, {floors}",
   "liveOn": "Zobrazuje sa od {t} pre budovu {building}, {floors}",
   "notYet": "Zatiaľ neposlané",
   "notSent": "Neposlané",
   "takenDown": "Stiahnuté {t}",
   "waitAfter": "Pošle sa do všetkých kanálov hneď, ako to Hub schváli.",
   "howSeen": "Ako to vidia obyvatelia",
   "willSeen": "Po schválení obyvatelia uvidia",
   "seeIt": "Pozrieť sa ako obyvateľ",
   "toHome": "Späť na moju budovu",
   "another": "Zverejniť ďalšiu aktualizáciu",
   "notFound": "Túto aktualizáciu sa v tomto telefóne nepodarilo nájsť.",
   "reasonLabel": "Dôvod: {reason}"
  },
  "A04": {
   "title": "Moje kolo",
   "checkins": "Žiadosti o kontrolu na vašich poschodiach",
   "unreachable": "Domácnosti na vašich poschodiach, ktoré sa nedá zastihnúť telefónom ani cez aplikáciu",
   "carry": "Upozornenie, ktoré im treba povedať",
   "floorDoor": "Poschodie {floor}, dvere {door}",
   "floorPhone": "Poschodie {floor}, {method} {phone}",
   "method": {
    "call": "telefonát",
    "text": "SMS",
    "knock": "zaklopanie"
   },
   "done": "Hotovo",
   "notReached": "Nezastihnutí",
   "needsHelp": "Potrebujú pomoc",
   "connected": "Spojení so službou",
   "passed": "Odovzdané Hubu",
   "offline": "Nie je signál. Vaše ťuknutia sú uložené a pošlú sa, keď budete mať signál.",
   "deleted": "Keď sa tento problém uzavrie, tieto záznamy sa vymažú. Zostanú len počty.",
   "addDoor": "Pridať dvere na žiadosť obyvateľa",
   "addConfirm": "Obyvateľ súhlasil, že ho pridám, tu na mojej obrazovke.",
   "addedByRequest": "Pridané na žiadosť obyvateľa",
   "addNote": "Tieto dvere sa vymažú, keď sa problém uzavrie. Ak chce obyvateľ kontrolu zakaždým, môže si ju vybrať v CVH.",
   "exercise": "Toto je cvičné kolo.",
   "forAlert": "Pre: {headline}",
   "practiceFor": "Cvičné kolo. K obyvateľom sa nič nedostane.",
   "floorN": "Poschodie {n}",
   "doorN": "Dvere {door}",
   "methodWord": {
    "call": "Zavolať",
    "text": "SMS",
    "knock": "Zaklopať"
   },
   "tally": "Zostáva: {todo} · Hotovo: {done} · Nezastihnutí: {nr} · Potrebujú pomoc: {help}",
   "connectedCat": "Spojení so službou: {category}",
   "queued": "Uložené v telefóne. Pošle sa, keď budete mať signál.",
   "taken": "Prevzal Hub",
   "change": "Zmeniť",
   "connect": "Spojiť so službou",
   "tellInPerson": "Zaklopte a povedzte im toto upozornenie",
   "whereLabel": "Kde",
   "doLabel": "Čo robiť teraz",
   "noRound": "Teraz nie je žiadne kolo kontrol. Keď Hub pošle upozornenie na horúčavu alebo výpadok elektriny pre vašu budovu, kontroly na vašich poschodiach sa zobrazia tu.",
   "addTitle": "Pridať dvere",
   "addFloor": "Poschodie",
   "addDoorLabel": "Číslo dverí",
   "addMethod": "Ako chcú byť kontaktovaní",
   "addPhone": "Telefónne číslo",
   "addBtn": "Pridať do môjho kola",
   "cancel": "Zrušiť",
   "added": "Pridané do vášho kola.",
   "errDoor": "Doplňte číslo dverí.",
   "errPhone": "Pri telefonáte alebo SMS doplňte telefónne číslo.",
   "errMethod": "Vyberte, ako chcú byť kontaktovaní.",
   "errAgree": "Najprv sa ich opýtajte. Keď súhlasia, zaškrtnite políčko, tu na vašej obrazovke.",
   "practiceNoAlert": "Nácvik: nie je žiadne upozornenie, ktoré treba povedať."
  },
  "A05": {
   "title": "Spojiť so službou",
   "urgent": "Čokoľvek naliehavé alebo nebezpečné: hneď volajte 911.",
   "list": "Teraz otvorené, v jazyku obyvateľa",
   "choose": "Povedzte im o tomto",
   "chosen": "Povedzte obyvateľovi, ako sa spojiť so službou {service}, alebo mu to napíšte.",
   "neverText": "Toto neposielame cez SMS.",
   "recorded": "Zaznamenané ako: {category}. Nič iné sa neukladá.",
   "exNote": "Cvičenie: toto je nácvik. Čo vyberiete, sa uloží len do záznamu o cvičení.",
   "forWho": "Pre: {who}",
   "theirLang": "Ich jazyk",
   "all": "Všetky",
   "openNowIn": "Teraz otvorené v jazyku {lang}, alebo hodiny nie sú známe",
   "hoursUnknown": "Otváracie hodiny nie sú známe. Najprv zavolajte.",
   "speaks": "Hovoria jazykom: {lang}",
   "none": "Na toto teraz nie je nič otvorené v jazyku {lang}. Tieto miesta sú teraz otvorené v iných jazykoch:",
   "noneAtAll": "Nič tu teraz nie je otvorené. Hub môže pomôcť: {phone}.",
   "tellTitle": "Povedzte im",
   "sayOr": "Povedzte im to alebo im to napíšte. Môžete im ukázať aj túto obrazovku.",
   "again": "Vybrať inú službu",
   "backRound": "Späť na moje kolo",
   "already": "Už spojení so službou: {category}.",
   "queued": "Uložené v telefóne. Pošle sa do Hubu, keď budete mať signál.",
   "callLabel": "Telefón",
   "whereLabel": "Kde",
   "hoursLabel": "Dnes"
  },
  "building": {
   "registerTitle": "Z mestského registra",
   "updated": "Naposledy aktualizované {date}",
   "registerLead": "Mesto Toronto vedie register bytových domov. Tieto údaje pochádzajú z neho.",
   "checking": "Hub kontroluje údaje o tejto budove. Čo tu vidíte, sa môže zmeniť.",
   "facts": {
    "storeys": "Počet poschodí",
    "elevators": "Výťahy",
    "emergencyPower": "Núdzové napájanie",
    "coolingRoom": "Miestnosť na ochladenie",
    "airConditioning": "Klimatizácia",
    "barrierFree": "Bezbariérový vchod"
   },
   "airNone": "Žiadna",
   "airIndividual": "V jednotlivých bytoch",
   "roles": {
    "superintendent": "Domovník",
    "buildingManagement": "Správa budovy",
    "propertyOffice": "Kancelária správcu"
   },
   "contactTitle": "Kontakt na budovu",
   "providedByHub": "Poskytol Hub, naposledy aktualizované {date}"
  },
  "guides": {
   "reviewed": "Skontroloval Hub, naposledy aktualizované {date}"
  }
 });
  /* AD-11 pilot change (2026-10-03): the label of a directory description a model translated and no person has reviewed. AI-generated (Claude), not yet checked by native readers. */
  m(t, { "x04": { "unreviewed": "Strojový preklad; nekontroloval ho človek" } });
  /* The resident map (S02.07): the "map" strings. AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "map": {
    "lead": "Služby, organizácie a bytové domy v Thorncliffe Parku a Flemingdon Parku. Ťuknite na špendlík a uvidíte, čo to je.",
    "service": "Služba alebo organizácia",
    "building": "Bytový dom",
    "pinName": "{name}: {kind}",
    "noSignal": "Mapa nie je dostupná bez signálu",
    "noSignalBody": "V zozname sú všetky miesta, ktoré má mapa.",
    "notSaved": "Táto časť mapy nie je uložená vo vašom telefóne",
    "notSavedBody": "Časti mapy, ktoré ste si pozreli so signálom, zostávajú vo vašom telefóne. Špendlíky a zoznam stále fungujú.",
    "listTitle": "Miesta v tejto časti mapy",
    "listLead": "Tie isté miesta, ktoré ukazuje mapa. Ak chcete zmeniť tento zoznam, posuňte alebo priblížte mapu.",
    "listEmpty": "V tejto časti mapy nič nie je. Posuňte alebo priblížte mapu, alebo zobrazte celú oblasť.",
    "wholeArea": "Zobraziť celú oblasť",
    "buildings": "Bytové domy",
    "buildingsCount": "Počet domov: {n}",
    "buildingsCountOne": "1 dom",
    "filtered": "Zobrazujú sa len miesta, ktoré zodpovedajú filtrom, ktoré ste si vybrali v adresári."
   }
  });
  /* S07.02: the web sign-up for text alerts and the confirmation text. YES, STOP, START and CVH stay in English. AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "signup": {
    "termsAgree": "Prečítal(a) som si stránku s podmienkami a ochranou súkromia a súhlasím.",
    "termsLink": "Prečítajte si stránku s podmienkami a ochranou súkromia",
    "termsVersion": "Verzia podmienok {version}",
    "age": "Mám 16 rokov alebo viac, alebo mi pomáha rodič či opatrovník.",
    "missingTerms": "váš súhlas s podmienkami",
    "missingAge": "vyhlásenie o veku",
    "sending": "Odosiela sa...",
    "onItsWay": "Ak toto číslo môže prijímať SMS, správa je na ceste.",
    "expect": "Odpovedzte na túto správu YES do 48 hodín a začnete dostávať upozornenia. Kým neodpoviete YES, nedostanete cez SMS žiadne upozornenia.",
    "howChange": "Ak budete chcieť neskôr zmeniť budovu, poschodie alebo jazyk, odpovedzte 1 alebo 2 na ktorúkoľvek SMS od Hubu.",
    "startHelp": "Neprišla SMS do 5 minút? Pošlite START na {number} a potom sa prihláste znova.",
    "startHelpNoNumber": "Neprišla SMS do 5 minút? Pošlite START na číslo, z ktorého chodia naše SMS, a potom sa prihláste znova.",
    "error": {
     "invalid_request": "Niečo vo formulári sa nedalo prečítať. Načítajte stránku znova a skúste to znova.",
     "phone_not_canadian": "Použite kanadské telefónne číslo s 10 číslicami, napríklad 416 555 0123.",
     "neighbourhood_missing": "Vyberte svoju štvrť.",
     "terms_not_agreed": "Ak sa chcete prihlásiť, súhlaste s podmienkami.",
     "age_not_confirmed": "Ak sa chcete prihlásiť, potvrďte vyhlásenie o veku.",
     "terms_changed": "Podmienky sa zmenili, kým bola táto stránka otvorená. Prečítajte si ich znova a potom súhlaste.",
     "place_unknown": "Jedna z vašich budov alebo poschodí už nie je v zozname. Skontrolujte svoje budovy a skúste to znova.",
     "rate_limited": "Z tohto pripojenia prišlo priveľa prihlásení. Skúste to znova o hodinu.",
     "signup_unavailable": "Prihlásenie na SMS teraz nie je k dispozícii. Skúste to znova neskôr.",
     "network": "Nepodarilo sa spojiť s CVH. Skontrolujte pripojenie a skúste to znova."
    }
   }
  });
  m(t, {"smsTexts": {"confirmation": "Upozornenia CVH: potvrďte odpoveďou YES. Počet správ sa mení. Môžu sa účtovať poplatky za správy a dáta. HELP pomoc, STOP koniec."}});
  /* S07.04: the welcome, the replies of the inbound router and the words for yes (YES, STOP and CVH stay in English). */
  m(t, {"smsTexts": {"welcome": "Ste prihlásení na upozornenia CVH. Pracovníci Hubu kontrolujú každú správu, takže v noci sa upozornenia nemusia posielať. Odpovedzte 1 na zmenu budovy alebo poschodia, 2 na zmenu jazyka, 3 na zrušenie žiadosti o kontrolu, 0 na ukončenie a vymazanie odberu. Odpovedzte STOP a správy skončia.", "alreadySignedUp": "Na upozornenia CVH ste už prihlásení.", "deletePrompt": "Pošlite znova 0 do 10 minút a odber sa vymaže. Potom už nič nepríde.", "signupInfo": "Ak chcete upozornenia CVH v SMS, prihláste sa tu: {link} Odpovedzte STOP a správy skončia."}, "smsKeywords": {"yes": "áno, ano"}});
  /* S07.05: the numbered text menus and their replies (see the English file for what each is and the one-text rule; 0, 1, 8, 9, 10, 5
     and {placeholders} stay as written). AI-generated (Claude), not yet checked by native readers. */
  m(t, {"smsTexts": {"menuStreet": "Ulica:", "menuBuilding": "Budova:", "menuFloor": "Poschodie:", "menuWholeBuilding": "Celá budova", "menuLanguage": "Jazyk:", "menuNav": "0 Späť 9 Hub", "menuNavMore": "0 Späť 8 Ďalej 9 Hub", "menuWarn": "Toto nahradí vaše uložené budovy ({n}). 1 Pokračovať, 0 Späť", "menuHub": "Zavolajte Hub na {hub}.", "menuClosed": "Menu sa zavrelo. Nič sa nezmenilo.", "menuReset": "Menu sa zavrelo po 10 minútach bez odpovede. Nič sa nezmenilo.", "menuLimit": "Dnes ste využili 5 menu. Skúste zajtra alebo Hub: {hub}", "menuLimitLink": "Dnes ste využili 5 menu. Pošlite 1 pre odkaz alebo Hub: {hub}", "buildingSaved": "Uložené. Vaša budova: {building}, poschodie {floor}.", "buildingSavedWhole": "Uložené. Vaša budova: {building}.", "languageSaved": "Uložené. Správy budete dostávať po slovensky.", "noCheckinRequest": "Nemáte žiadnu žiadosť o kontrolu.", "checkinWithdrawn": "Vaša žiadosť o kontrolu bola zrušená."}});
  /* S07.06: the one-time web link's texts and its page (see the English file for what each is; menuClosedLink must fit one text; 0, 1, 30
     and {placeholders} stay as written; the error lines other than edit_unavailable are the sign-up's own). AI-generated (Claude), not yet
     checked by native readers. */
  m(t, {"smsTexts":{"menuClosedLink":"Menu sa zavrelo. Nič sa nezmenilo. Pošlite 1 pre webový odkaz.","editLink":"Upozornenia CVH zmeníte alebo zrušíte tu: {link} Odkaz funguje raz, 30 minút.","editSaved":"Vaše voľby upozornení CVH sa zmenili na webe. Neboli ste to vy? Zavolajte Hub na {hub}."},"subscriptionEdit":{"title":"Zmeňte upozornenia cez SMS","loading":"Otvárajú sa vaše voľby...","forNumber":"Pre telefónne číslo končiace na {digits}.","lead":"Zmeňte, čo chcete, a potom uložte. Ak chcete zastaviť všetky správy, zrušte odber na konci tejto stránky.","topicsTitle":"Témy, o ktorých nechcete správy","topicsLead":"Zaškrtnite tému a jej upozornenia prestanú. Upozornenia na požiar alebo evakuáciu prídu vždy.","save":"Uložiť moje zmeny","saving":"Ukladá sa...","savedTitle":"Vaše zmeny sú uložené","savedBody":"Príde vám SMS s potvrdením. Tento odkaz je už použitý: ak chcete zmeniť niečo ďalšie, požiadajte cez SMS o nový odkaz.","deleteTitle":"Zrušiť môj odber","deleteLead":"Od CVH už nedostanete žiadne správy a všetko, čo sa o vašom čísle uchováva, sa vymaže. Nedá sa to vrátiť.","deleteSure":"Zrušiť odber hneď teraz? Od CVH už nedostanete žiadne správy.","deleteYes":"Áno, zrušiť","deleteNo":"Nie, ponechať","deleting":"Ruší sa...","deletedTitle":"Váš odber je zrušený","deletedBody":"Od CVH už nedostanete žiadne správy a o vašom čísle sa nič neuchováva. Potvrdenie sa neposiela.","signUpAgain":"Prihlásiť sa znova","expiredTitle":"Platnosť tohto odkazu vypršala","expiredBody":"Odkaz funguje raz, 30 minút po odoslaní.","expiredHow":"Nový odkaz cez SMS dostanete, keď odpoviete 1 na správu od CVH. Ak príde menu, zatvorte ho odpoveďou 0. Keď odpoveď ponúkne odkaz, pošlite 1.","callHub":"Alebo zavolajte Hub na {hub}.","error":{"invalid_request":"Niečo vo formulári sa nedalo prečítať. Načítajte stránku znova a skúste to znova.","neighbourhood_missing":"Vyberte svoju štvrť.","place_unknown":"Jedna z vašich budov alebo poschodí už nie je v zozname. Skontrolujte svoje budovy a skúste to znova.","edit_unavailable":"Zmeny sa teraz nedajú urobiť. Skúste to neskôr.","network":"Nepodarilo sa spojiť s CVH. Skontrolujte pripojenie a skúste to znova."}}});
  /* S08.05: the check-in request's texts and wording (see the English file for what each is; checkinMoved and checkinUncoveredNow must fit one
     text; 1, YES, CVH, Hub and {placeholders} stay as written). AI-generated (Claude), not yet checked by native readers. */
  m(t, {"smsTexts":{"checkinMoved":"Zmena poschodia zrušila žiadosť o kontrolu. Pošlite 1 pre odkaz.","checkinUncoveredNow":"Vaše poschodie teraz nemá ambasádora. Volajte Hub: {hub}"},"signup":{"error":{"checkin_consent_missing":"Ak chcete požiadať o kontrolu, zaškrtnite súhlas."}},"subscriptionEdit":{"error":{"checkin_consent_missing":"Ak chcete požiadať o kontrolu, zaškrtnite súhlas."}},"checkin":{"consentMissing":"Ak chcete požiadať o kontrolu, zaškrtnite súhlas.","sees":"Ambasádor vášho poschodia uvidí vaše telefónne číslo a poschodie, aby vám mohol zavolať alebo napísať.","isNot":"Kontrola je hovor alebo správa s otázkou, či ste v poriadku. Nie je to zdravotná starostlivosť ani sľub, že niekto príde hneď.","howTitle":"Ako požiadať","howNew":"Potrebujete textové upozornenia CVH. Prihláste sa a požiadajte o kontrolu v tom istom formulári.","howHelp":"Na podujatí CVH alebo v Hube vám s prihlásením pomôžu zamestnanci alebo ambasádor budovy.","howSubscribed":"Už dostávate správy CVH? Požiadajte o kontrolu na stránke, kde meníte svoje voľby.","noCoverage":"Ak vaše poschodie ešte nemá ambasádora, povieme vám to hneď. Namiesto toho môžete zavolať Hub na {hub}.","ask":"Nech ma ambasádor môjho poschodia skontroluje","whereHint":"Vyberte budovu a poschodie, kde bývate, z tých vyššie.","agree":"Súhlasím, že ambasádor môjho poschodia uvidí moje telefónne číslo a poschodie a skontroluje ma.","untilYes":"Vaša žiadosť o kontrolu začne platiť, keď odpoviete YES na našu správu.","uncovered":"Vaše poschodie zatiaľ nemá ambasádora. Zavolajte Hub na {hub}.","withdraw":"Zrušiť moju žiadosť o kontrolu","withdrawNote":"Zruší sa, keď uložíte. Upozornenia budete dostávať ďalej.","moved":"Zmenilo sa, kde bývate, preto sa vaša žiadosť o kontrolu zruší. Ak chcete požiadať znova pre nové poschodie, vyberte ho a znova súhlaste.","savedRequested":"Vaša žiadosť o kontrolu je uložená.","savedMethod":"Spôsob kontroly sa zmenil."}});
  /* The last resident wording that showed in English: the home's alert list and its failures (R03, status.none), the ask screen's waiting and
     failure states (R09, R10.shownIn) and the directory (S02.06). AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "status": {
    "none": "Nič aktívne"
   },
   "R03": {
    "currentAlerts": "Aktuálne upozornenia",
    "noCurrentAlerts": "Žiadne aktuálne upozornenia",
    "myBuildings": "Vaše budovy",
    "checking": "Kontrolujú sa upozornenia",
    "feedFailed": "Upozornenia sa práve nepodarilo skontrolovať. Miesto s nápisom „Neznáme“ môže mať aj tak upozornenie. Skúsime to znova.",
    "feedFailedOld": "Nové upozornenia sa nepodarilo skontrolovať. Zobrazuje sa to, čo sa naposledy načítalo {t}."
   },
   "R09": {
    "searching": "Hľadá sa",
    "needsSignal": "Vyhľadávanie potrebuje signál",
    "needsSignalBody": "Stále môžete vybrať tému nižšie alebo zavolať do Hubu.",
    "busy": "Vyhľadávanie je preťažené, skúste to znova o pár minút",
    "busyBody": "Môžete vybrať tému nižšie alebo zavolať do Hubu.",
    "updating": "Výsledky vyhľadávania sa aktualizujú, skúste to znova",
    "updatingBody": "Kým sa aktualizujú, môžete vybrať tému nižšie alebo zavolať do Hubu.",
    "browseAll": "Zobraziť všetky služby a organizácie",
    "loading": "Témy sa načítavajú"
   },
   "R10": {
    "shownIn": "Zobrazené v jazyku {lang}"
   },
   "directory": {
    "title": "Služby a organizácie",
    "lead": "To, čo Hub overil v Thorncliffe Parku a Flemingdon Parku. Zoznam zúžite výberom témy alebo štvrte.",
    "count": "Počet služieb: {n}",
    "countOne": "1 služba",
    "topic": "Téma",
    "emergency": "Pomáha v tiesňovej situácii",
    "emergencyRole": "Úloha v tiesňovej situácii",
    /* The verified badge's line on a provider (it replaces the earlier last-confirmed line). AI-generated (Claude), not yet checked by native readers. */
    "checkedByHub": "Overené Hubom · {date}",
    "lastUpdated": "Naposledy aktualizované {time}",
    "loading": "Adresár sa načítava",
    "couldNotLoad": "Adresár sa nepodarilo načítať",
    "couldNotLoadBody": "Hub vám môže pomôcť nájsť službu cez telefón.",
    "couldNotLoadNumbers": "Na stránke s číslami sú ďalšie čísla, ktoré môžete potrebovať.",
    "numbersLink": "Zobraziť dôležité čísla",
    "backToList": "Všetky služby a organizácie",
    "suggestApply": "Zobraziť len {place}"
   }
  });
  /* Reading without signal (S02.12): the offline page and R-34's note. AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "offline": {
    "title": "Táto stránka nie je uložená vo vašom telefóne",
    "body": "V tomto telefóne ešte nebola otvorená so signálom, preto potrebuje signál. Čísla sú vo vašom telefóne uložené vždy.",
    "available": "Toto si môžete prečítať bez signálu",
    "none": "V tomto telefóne zatiaľ nie je uložené nič iné. Stránky, ktoré otvoríte so signálom, sa uložia na neskôr."
   },
   "R34": {
    "offlineTitle": "Čítanie bez signálu",
    "offlineHelp": "Stránky, ktoré otvoríte so signálom, sa uložia v tomto telefóne, takže si ich neskôr môžete znova prečítať bez signálu. Čísla sú uložené vždy. Prvýkrát potrebuje CVH na otvorenie signál.",
    "offlineNote": "Tento telefón nemusí uchovávať stránky na použitie bez signálu"
   }
  });
  /* S08.02: an ambassador's post (A-02): the one screen's new words (an unsent post is held only in the open page's memory), and A03.states.ended. AI-generated, not yet checked by native readers. */
  m(t, {
   "A02": {
    "building": "Ktorá budova?",
    "allFloorsLine": "Všetky poschodia ({n})",
    "listLabel": "Niektoré poschodia",
    "listLine": "Označte každé poschodie",
    "rangeLabel": "Poschodia za sebou",
    "rangeLine": "Od jedného poschodia po druhé",
    "fromFloor": "Od poschodia",
    "toFloor": "Po poschodie",
    "chooseFloor": "Vybrať",
    "phaseTitle": "Aká je situácia",
    "phaseProblem": "Je tu problém",
    "phaseProgress": "Prebieha práca",
    "validTitle": "Dokedy?",
    "validResolved": "Kým sa to neopraví (24 hodín odteraz)",
    "validAt": "Do určitého dátumu a času",
    "dateLabel": "Dátum",
    "timeLabel": "Čas (torontský čas)",
    "validHint": "Najviac 7 dní dopredu.",
    "textLabel": "Čo sa deje, po anglicky",
    "textHint": "Najviac {max} znakov. Obyvatelia si to prečítajú vo svojom jazyku; Hub to najprv skontroluje.",
    "inAlert": "Táto aktualizácia pôjde do upozornenia: {headline}",
    "typesFixed": "Čo sa deje: {types}",
    "unsent": "Ešte to nie je odoslané. Nechajte túto stránku otvorenú; odošle sa, keď budete mať signál.",
    "unsentClose": "Ak túto stránku zatvoríte, táto aktualizácia sa stratí.",
    "sending": "Posiela sa do Hubu...",
    "errPhase": "Vyberte, aká je situácia.",
    "errText": "Napíšte po anglicky, čo sa deje.",
    "errTextLong": "Je to príliš dlhé. Použite najviac {max} znakov.",
    "errValid": "Zadajte dátum a čas.",
    "errValidPast": "Ten čas už prešiel. Vyberte neskorší čas.",
    "errValidFar": "Vyberte čas najviac 7 dní dopredu.",
    "errValidSkipped": "V tú noc sa mení čas, takže tento čas nie je jasný. Vyberte iný čas.",
    "errRange": "Prvé poschodie je nad posledným. Dajte nižšie poschodie na prvé miesto.",
    "errNotAssigned": "Teraz nie ste priradený k tejto budove, takže za ňu nemôžete zverejňovať.",
    "errClosed": "Toto upozornenie sa skončilo. Radšej zverejnite novú aktualizáciu.",
    "errSignedOut": "Boli ste odhlásený, takže sa to neodoslalo. Znova sa prihláste a potom to zverejnite znova.",
    "errFailed": "Toto sa neodoslalo. Skúste to znova. Ak sa to bude opakovať, zavolajte do Hubu."
   },
   "A03": {
    "states": {
     "ended": "Neodoslané: upozornenie sa skončilo skôr, ako ho Hub skontroloval"
    }
   }
  });
  /* S09.07: the end-of-pilot re-consent texts (the campaign text with {date}, the confirmation after YES, the answer after the deadline, the answer
     while sign-ups are paused) and the sign-up form's refusal while sign-ups are paused. YES and CVH stay in English. Each text fits one text message
     with the longest date. smsDate is how a text writes the deadline (the month names, the order of day and month, the numerals), fixed here
     from CLDR 47 so the frozen text is the same on every runtime. AI-generated (Claude), not yet checked by native readers: the texts and the
     date words are reviewed before launch (Launch Readiness). */
  m(t, {"smsDate": {"months":["januára","februára","marca","apríla","mája","júna","júla","augusta","septembra","októbra","novembra","decembra"],"dayMonth":"{day}. {month}","digits":"0123456789"}, "smsTexts": {"reconsent": "Pilot CVH končí. Pre správy YES do {date}, inak číslo zmažeme.", "reconsentKept": "Ďakujeme. Upozornenia CVH budete dostávať aj naďalej.", "pilotEnded": "Pilot CVH sa skončil; vaše číslo sme neuchovali.", "signupsPaused": "Prihlasovanie na SMS CVH je do konca pilotu pozastavené."}, "signup": {"error": {"signups_paused": "Prihlasovanie je do konca pilotu pozastavené."}}});
  /* The opt-in disclosures carriers ask for (program, frequency, rates, HELP and STOP) under the sign-up form. AI-generated (Claude), not yet checked by native readers. */
  m(t, {"signup": {"smsTerms": "Textové upozornenia CVH od Thorncliffe Park Community Hub. Počet správ sa mení. Môžu sa účtovať poplatky za správy a dáta. Odpovedzte HELP pre pomoc alebo STOP pre zrušenie."}});
})();
