/* French string table. Phase 1: shell and shared components. AI-generated; to be checked by native readers. */
window.CVH_STRINGS = window.CVH_STRINGS || {};
window.CVH_STRINGS.fr = {
 meta: { code: 'fr', name: 'Français', aiNote: 'Tout le texte de ce prototype est généré par IA. Des personnes le vérifieront avant le lancement du CVH.' },
 time: { justNow: 'À l\'instant', ago: 'il y a {t}', join: ' ', second: '1 seconde', seconds: '{n} secondes', minute: '1 minute', minutes: '{n} minutes', hour: '1 heure', hours: '{n} heures', day: '1 jour', days: '{n} jours', today: 'Aujourd\'hui', tomorrow: 'Demain', until: 'jusqu\'à {t}', closed: 'Fermé',
   days7: { mon: 'lundi', tue: 'mardi', wed: 'mercredi', thu: 'jeudi', fri: 'vendredi', sat: 'samedi', sun: 'dimanche' } },
 shell: { cvhName: 'Carrefour virtuel communautaire', prototype: 'Prototype', prototypeNote: 'Ce n\'est pas un service réel. Tout le contenu est généré par IA.',
   language: 'Langue', changeLanguage: 'Changer de langue', languageTitle: 'Choisissez votre langue', languageCurrent: 'Affiché en ce moment', languageReturn: 'L\'écran reste là où vous étiez.',
   choices: 'Ce que j\'ai dit au CVH', choicesShort: 'Mes choix', nav: { now: 'Maintenant', help: 'Trouver de l\'aide', map: 'Carte', ready: 'Être prêt' }, navLabel: 'Principal',
   close: 'Fermer', back: 'Retour', next: 'Continuer', skip: 'Passer', done: 'Terminé', cancel: 'Annuler', more: 'Plus',
   notInPrototype: 'Pas dans ce prototype', notInPrototypeBody: 'Cette partie n\'est pas construite dans le prototype. Rien n\'a changé.', ok: 'OK',
   about: 'À propos du CVH', aboutBody: 'Le Carrefour virtuel communautaire est géré par le Thorncliffe Park Community Hub pour Thorncliffe Park et Flemingdon Park.', builtBy: 'Conçu avec Sprout Climate',
   rules: 'Les règles de cet espace', ambassador: 'Ambassadeur', offline: 'Vous êtes hors ligne. Contenu chargé {t}.', aiLabel: 'Généré par IA pour le prototype', illustrative: 'Illustratif' },
 x01: { text: 'Le CVH n\'est pas un service d\'urgence.', call: 'Si quelqu\'un est en danger, appelez le 911.', short: 'Pas un service d\'urgence. En danger? Appelez le 911.',
   sms: 'Le Hub n\'est pas un service d\'urgence. Si quelqu\'un est en danger, appelez le 911.', print: 'Ceci n\'est pas un service d\'urgence. Si quelqu\'un est en danger, appelez le 911.' },
 x02: { official: 'Alerte officielle de {source}', community: 'Alerte communautaire de {author}', verifiedBy: 'Vérifié par {org}', notYetVerified: 'Pas encore vérifié',
   corrected: 'Corrigé {t}', whatMeans: 'Ce que cela veut dire', hub: 'le Hub', theHub: 'Le Hub', ambassador: 'Ambassadeur de l\'immeuble, {building}', postedBy: 'Publié par {author}',
   levelOfficial: 'Alerte officielle', levelCommunity: 'Alerte communautaire', sources: { ECCC: 'Environnement et Changement climatique Canada', CITY: 'Ville de Toronto', ALERTREADY: 'En Alerte' } },
 x03: { title: 'Les règles de cet espace', intro: 'Le CVH sert aux voisins qui s\'entraident. Avant d\'ajouter quelque chose, lisez ceci.',
   rules: ['Partagez des lieux et de l\'aide gratuits ou peu coûteux, ouverts à la communauté.', 'Écrivez sur un lieu, pas sur une personne. Ne partagez ni nom, ni numéro d\'appartement, ni numéro de téléphone.',
     'Soyez bienveillant. Rien qui insulte ou vise un groupe de personnes.', 'Ne partagez que ce que vous savez être vrai. Si vous n\'êtes pas sûr, choisissez « Pas sûr ».'],
   market: 'Le CVH n\'est pas un marché. Ni vente, ni publicité.', review: 'Une personne du Hub lit tout avant que ce soit sur la carte.', agree: 'Je comprends', readMore: 'Lire les règles' },
 x04: { label: 'Traduit automatiquement', from: 'de : {lang}', report: 'Signaler un problème de traduction', reportTitle: 'Qu\'est-ce qui ne va pas dans cette traduction?',
   reasons: { meaning: 'Le sens est faux', words: 'Certains mots sont faux', unclear: 'C\'est difficile à comprendre' }, send: 'Envoyer', reported: 'Merci. Une personne du Hub vérifiera cette traduction.',
   unavailable: 'Pas encore offert dans cette langue', unavailableBody: 'Ceci n\'a pas encore été traduit en {lang}.', showSource: 'Lire en {lang}', original: 'Original ({lang})' },
 x07: { label: 'Texte plus grand, moins d\'éléments', on: 'Activé', off: 'Désactivé', setByHelper: 'Activé par une personne qui vous aide', remembered: 'Mémorisé sur cet appareil', turnOn: 'Activer', turnOff: 'Désactiver' },
 x08: { idle: 'Écouter · {t}', loading: 'Chargement de l\'audio', playing: 'Lecture', paused: 'En pause', left: 'Il reste {t}',
   failed: 'L\'audio n\'a pas pu se charger avec cette connexion. Tout ce qu\'il dit est écrit ici.', retry: 'Réessayer', play: 'Lire', pause: 'Pause', section: 'Écouter cette section · {t}' },
 x09: { open: 'Ouvert', full: 'Complet', closed: 'Fermé', unconfirmed: 'Non confirmé',
   purpose: { cooling: 'pour se rafraîchir', cleanAir: 'pour de l\'air pur', warming: 'pour se réchauffer', charging: 'pour recharger un appareil' },
   confirmed: 'Confirmé {t}', unconfirmedNote: 'Non confirmé depuis {t}. Peut-être fermé. Appelez avant d\'y aller.', hoursToday: 'Aujourd\'hui de {from} à {to}', closedToday: 'Fermé aujourd\'hui',
   water: 'Eau potable', seating: 'Places assises', charging: 'Recharge de téléphone', washrooms: 'Toilettes', stepFree: 'Sans marches', notStepFree: 'Avec marches', noId: 'Ne demande pas de pièce d\'identité', idAsked: 'Demande une pièce d\'identité',
   runBy: 'Géré par {org}', yes: 'Oui', no: 'Non', unknown: 'Inconnu' },
 x10: { word: 'Exercice', running: 'Exercice. Ceci est une pratique.', runningSub: 'Rien n\'est envoyé aux résidents.', ended: 'Exercice terminé', sms: 'Exercice. Pratique seulement.' },
 x11: { title: 'Filtres actifs', remove: 'Retirer le filtre : {f}', hiding: '{n} lieux sont masqués par ces filtres', hidingOne: '1 lieu est masqué par ces filtres',
   fromChoices: 'Certains filtres viennent de vos choix', clear: 'Retirer tous les filtres', none: 'Aucun filtre' },
 x12: { title: 'Ce que cela veut dire pour vous', fromHub: 'Conseil du Hub', tailoredLink: 'Adapté à vos choix', standard: 'Voir la version que tout le monde reçoit',
   standardShown: 'Vous voyez la version que tout le monde reçoit.', showMine: 'Voir ce que cela veut dire pour moi', checkin: 'L\'ambassadeur de votre étage passera prendre de vos nouvelles aujourd\'hui.',
   noCheckin: 'Il n\'y a pas encore d\'ambassadeur à votre étage, donc nous ne pouvons pas prendre de vos nouvelles. Appelez le Hub au {phone}. Nous sommes ouverts {hours}.',
   hubHours: 'du lundi au jeudi de 9 h à 20 h, le vendredi de 9 h à 17 h, le samedi de 10 h à 14 h', listen: 'Écouter · {t}' },
 x13: { fire: 'Incendie', power: 'Électricité', water: 'Eau', elevator: 'Ascenseur', flood: 'Inondation ou fuite', heat: 'Chaleur', smoke: 'Fumée', winter: 'Tempête hivernale', other: 'Autre', fireAlarm: 'Alarme incendie ou évacuation', waterPlumbing: 'Eau ou plomberie' },
 x14: { label: 'Comment ils peuvent aider' },
 status: { active: 'Problème en cours', progress: 'Travaux en cours', resolved: 'Réglé', unknown: 'Inconnu' },
 R02: { title: 'Choisissez votre langue', changed: 'Affiché maintenant en {lang}.' }
};
