/* Chinese strings for the resident and ambassador screens, merged into the Chinese table by
   screen ID. AI-generated (Claude), not yet checked by native readers. Staff screens stay in English. */
(function () {
  var t = window.CVH_STRINGS.zh;
  function m(t, s) { for (var k in s) { if (s[k] && typeof s[k] === "object" && !Array.isArray(s[k]) && t[k] && typeof t[k] === "object" && !Array.isArray(t[k])) m(t[k], s[k]); else t[k] = s[k]; } }
  m(t, {
  "terms": {
   "version": "版本",
   "owner": "负责方",
   "updated": "最后更新",
   "privacyContact": "隐私联系人",
   "draftTitle": "草稿：尚未发布",
   "draftBody": "此文本尚未获批准，不是最终条款。请不要依据它来注册。",
   "draftWhy": "尚未发布，原因是：",
   "translationNote": "本页部分内容尚未翻译成{lang}。这些部分以英文显示。",
   /* S09.08: the day the pilot's resident data was deleted, shown once the end-of-pilot purge has completed. AI-generated (Claude), not yet checked by native readers. */
   "dataDeleted": "居民数据删除日期",
   "dataDeletedNote": "CVH试点已结束。我们在该日期删除了所有未回复YES以继续接收提醒的人的电话号码和选择。"
  },
  "shell": {
   "hubName": "Thorncliffe Park Community Hub",
   "hubLogoAlt": "Thorncliffe Park Community Hub",
   "pageNotFound": "找不到此页面。",
   "pageNotFoundBody": "链接可能已过期或输入有误。请使用下方菜单继续。"
  },
  "x01": {
   "partner": "本空间不会替任何人拨打 911。如有人身处危险，请您自己拨打 911。不要以为其他机构已经打过。"
  },
  "x05": {
   "title": "用您的语言接收警报和获得帮助",
   "lead": "社区虚拟中心会在您的楼里发生情况时通知您，并帮助您找到附近的服务。",
   "steps": ["用手机打开链接或扫描二维码。", "选择您的语言。", "不需要账户，也不需要下载应用。"],
   "link": "短链接",
   "scan": "用手机相机扫描",
   "building": "楼宇",
   "floor": "楼层",
   "writeIn": "由您的联络员填写",
   "text": "没有智能手机？请您的楼层联络员帮您开通短信警报。",
   "from": "来自 Thorncliffe Park Community Hub",
   "sampleLink": "示例链接，无法使用"
  },
  "x06": {
   "doing": "我们正在做",
   "canTake": "我们可以承担",
   "cannotCover": "我们无法承担",
   "need": "我们需要这个",
   "claimed": "由{org}承担",
   "supply": "物资：{item}",
   "recordDecision": "记录为决定"
  },
  "groups": {
   "seniors": {
    "label": "长者",
    "line": "为年长居民提供高温警告和服务，并在每条警报中为您提供建议。"
   },
   "newcomers": {
    "label": "新移民",
    "line": "不询问身份的服务，并在每条警报中为您提供建议。"
   },
   "families": {
    "label": "有幼儿的家庭",
    "line": "关于婴儿和幼儿的警报和建议，以及为家庭提供的服务。"
   },
   "checkin": {
    "label": "高温和停电期间，我希望有人来探望我",
    "line": "出现高温警告或停电时，您的楼层联络员会来探望您。"
   }
  },
  "categories": {
   "food": "食物",
   "housing": "住房和租金",
   "health": "健康",
   "money": "钱和福利",
   "settlement": "移民和安置",
   "jobs": "工作和培训",
   "children": "儿童和青少年",
   "seniors": "长者",
   "legal": "法律帮助",
   "mentalHealth": "心理健康"
  },
  "filters": {
   "openNow": "现在开放吗？",
   "nbhd": "哪个社区？",
   "language": "他们说我的语言吗？",
   "cost": "需要多少钱？",
   "noId": "他们会要求身份证件或身份证明吗？",
   "stepFree": "不用走台阶能进去吗？",
   "noAppointment": "需要预约吗？",
   "short": {
    "openNow": "现在开放",
    "nbhdTP": "Thorncliffe Park",
    "nbhdFP": "Flemingdon Park",
    "language": "说{lang}",
    "free": "免费",
    "lowCost": "免费或低价",
    "noId": "不要求身份证件",
    "stepFree": "无台阶",
    "noAppointment": "无需预约"
   },
   "answers": {
    "yes": "是",
    "no": "否",
    "any": "不限",
    "free": "只看免费",
    "lowCost": "免费或低价",
    "noIdOnly": "只看不要求的地方",
    "stepFreeOnly": "只看无台阶的地方",
    "walkIn": "只看无需预约的"
   }
  },
  "utilities": {
   "ac": "空调",
   "wifi": "Wi-Fi",
   "charging": "充电",
   "washrooms": "洗手间",
   "water": "饮用水",
   "food": "食物",
   "kit": "这里有应急包",
   "space": "现在作为场所开放"
  },
  "orgKinds": {
   "grassroots": "草根团体",
   "nonprofit": "非营利组织",
   "faith": "宗教组织",
   "public": "公共服务",
   "business": "商家",
   "communityOffer": "社区提供"
  },
  "neighbourhoods": {
   "TP": "Thorncliffe Park",
   "FP": "Flemingdon Park"
  },
  "subcats": {
   "Police Station": "警察局",
   "Fire Station": "消防站",
   "Food Collaboratives": "食物银行和食物项目",
   "Shelter": "避难所",
   "Faith-Based Organizations": "宗教团体",
   "Legal Services": "法律服务",
   "Government Documentation": "政府证件",
   "Schools": "学校",
   "Childminding & EarlyON": "儿童看护和 EarlyON",
   "Dental Clinics": "牙科诊所",
   "Midwives Clinic": "助产士",
   "Health Clinics": "健康诊所",
   "Non-Profits": "社区组织",
   "Community Centres": "社区中心",
   "Public Washrooms": "公共洗手间",
   "Libraries": "图书馆",
   "Water Fountains": "饮用水",
   "Museums": "博物馆",
   "Cooling Spaces": "降温空间",
   "Multi-Service Agencies": "多服务机构",
   "Food Security & Climate Resilience": "食物和气候团体",
   "Employment & Skills Training": "工作和技能",
   "Family & Parenting Support": "家庭与育儿",
   "Social & Cultural Organizations": "社会和文化团体",
   "Newcomer Supports": "新移民支持",
   "Housing & Tenant Supports": "住房和租户",
   "Neighbourhood & Individual Empowerment": "社区团体"
  },
  "hazards": {
   "power": "停电",
   "flood": "水浸或管道故障",
   "elevator": "电梯故障",
   "heat": "极端高温",
   "smoke": "山火烟雾",
   "fire": "火灾和疏散"
  },
  "stages": {
   "before": "之前",
   "during": "期间",
   "after": "之后"
  },
  "R01": {
   "title": "选择您的语言",
   "preselected": "根据您的通知选择",
   "selected": "已选择",
   "continue": "继续",
   "helperBasic": "在帮助别人？为他们开启“字体更大，内容更少”。",
   "forwardedNote": "有人与您分享了一条警报。请先选择您的语言。",
   "fromPhone": "根据您手机的语言",
   "chooseFirst": "点击一种语言以继续。",
   "youChose": "您的语言：",
   "helperOn": "“字体更大，内容更少”已开启。它会为他们保持开启。"
  },
  "R02": {
   "current": "当前显示",
   "unavailable": "暂无此语言版本",
   "unavailableBody": "此屏幕上有些内容尚未翻译成{lang}。凡是这种情况，我们都会注明。",
   "continueIn": "用{lang}继续",
   "chooseOther": "选择其他语言"
  },
  "R03": {
   "getTextAlerts": "接收短信警报",
   "getTextAlertsLine": "通过短信接收您所在楼宇的警报。不需要应用，不需要账户。",
   "signedUp": "短信警报已开启",
   "sent": "请在手机上回复 YES 开始接收短信警报",
   "alertsNow": "当前警报",
   "myBuilding": "您的楼宇",
   "myFloor": "您的楼层",
   "nothingActive": "目前没有发生任何情况。",
   "nothingActiveBody": "如有情况影响您的楼宇或社区，会首先显示在这里。",
   "noBuildingChosen": "选择您的楼宇，优先查看它的警报",
   "ongoing": "持续中",
   "updated": "{t}更新",
   "posted": "{t}发布",
   "everyday": "日常",
   "findHelp": "寻求帮助",
   "map": "地图",
   "beReady": "做好准备",
   "findHelpLine": "您附近的服务和支持",
   "mapLine": "您附近的地点，以及现在开放的地方",
   "beReadyLine": "指南、电话号码和探望",
   "archive": "已结束的警报",
   "basicTurnOn": "字体更大，内容更少",
   "headsUpTitle": "炎热天气到来之前",
   "headsUpFrom": "您选择接收的提前提醒",
   "headsUpGuide": "阅读高温指南",
   "headsUpEvent": "您附近的讲座",
   "ongoingDay": "持续中：第 {n} 天，共 {total} 天",
   "readAlert": "阅读警报",
   "neighbourhoods": "Thorncliffe Park 和 Flemingdon Park",
   "headsUpAction": "现在可以做的一件事",
   "ambassadorHome": "联络员：我的楼宇",
   "ambassadorLine": "为 {building} 发布更新或进行巡查",
   "noBuildingLine": "您所在社区的警报会显示在这里。添加您的楼宇，优先查看它的警报。"
  },
  "R04": {
   "deviceLabel": "普通手机上的短信",
   "from": "Thorncliffe Hub",
   "fromNumber": "CVH 警报",
   "lockScreen": "锁屏",
   "now": "现在",
   "levelOfficial": "来自{source}的官方警报。",
   "levelCommunity": "来自中心的社区警报。已由中心核实。",
   "fromHub": "来自中心的社区警报",
   "levelAmbassador": "来自楼宇联络员的社区警报。尚未核实。",
   "stop": "如要停止接收中心的所有短信，请回复 STOP。",
   "verifiedKeyword": "如想了解“已核实”的意思，请回复 INFO。",
   "ackMore": "更多信息稍后公布。",
   "update": "警报“{headline}”的更新：",
   "correction": "警报“{headline}”的更正：{changed}",
   "resolved": "已解决：“{headline}”。{final}",
   "nearestSpace": "最近的开放场所：{space}，{hours}。",
   "confirmRequest": "Thorncliffe Park Community Hub：有人为这部手机申请了{lang}短信警报，范围是{where}。如同意，请回复 YES。如要停止接收中心的所有短信，请回复 STOP。",
   "keywordChange": "如要更改您选择的群体，请回复 GROUPS。",
   "checkinWithdraw": "如要停止探望，请回复 NOCHECK。",
   "link": "更多：{url}",
   "sampleLabel": "示例短信。不会发送任何内容。",
   "tapOpen": "点击短信打开",
   "back": "返回应用",
   "annotOn": "哪些行是翻译的",
   "annotOff": "隐藏翻译说明",
   "bigOn": "最大字体",
   "bigOff": "正常字体",
   "tagTemplate": "已审核模板",
   "tagAlert": "为本警报撰写",
   "annotNote": "第 2 阶段以英文绘制。标有“已审核模板”的行在全部 15 种上线语言中都有，并经过人工审核。标有“为本警报撰写”的行会针对每条警报翻译；乌尔都语和希腊语版本尚未加入本原型。",
   "officialNote": "官方警报使用每种语言经人工审核的模板发出。随后的社区警报会说明它在这里补充了什么。",
   "notKnownPrefix": "尚不清楚：{what}。",
   "you": "您",
   "exNote": "演练。只有参加演练的人会收到这条短信。居民不会收到任何内容。"
  },
  "R05": {
   "title": "接收短信警报",
   "lead": "当您的楼宇或社区发生情况时，我们会发短信通知您。不需要应用，不需要账户，不需要电子邮件。",
   "required": "必填",
   "optional": "选填",
   "phone": "电话号码",
   "phoneHelp": "用任何格式填写都可以。",
   "phoneShown": "我们会发短信到 {phone}",
   "phoneError": "这个号码需要 10 位数字，例如 416 555 0123。",
   "nbhd": "社区",
   "building": "楼宇",
   "floor": "楼层",
   "buildingSearch": "搜索您的楼宇",
   "notListed": "列表中没有我的楼宇",
   "notListedResult": "您会收到 {nbhd} 的所有警报。我们已告诉中心，列表中缺少您的楼宇。",
   "language": "语言",
   "languageFrom": "根据您最初的选择",
   "groupsTitle": "您属于哪些群体？",
   "groupsSkip": "跳过",
   "send": "给我发一条确认短信",
   "formError": "我们暂时无法发送。请添加：{missing}。",
   "whatYouGet": "短信只用于警报。我们绝不会通过短信发送日常新闻或广告。",
   "sentTitle": "请查看您的手机",
   "sentBody": "我们已向 {phone} 发送了一条短信。回复 YES 即可开始接收警报。",
   "resend": "再发一次",
   "fix": "修改号码",
   "signedUpTitle": "已注册",
   "signedUpBody": "{phone} 将收到{lang}警报。",
   "noAccount": "您不需要账户。",
   "missingPhone": "10 位数字的电话号码",
   "missingNbhd": "您的社区",
   "and": "和",
   "nbhdError": "请选择您的社区。",
   "change": "更改",
   "noFloor": "不选楼层，只选楼宇",
   "floorN": "{n} 楼",
   "step1": "第 1 步，共 2 步",
   "step2": "第 2 步，共 2 步",
   "continue": "继续",
   "groupsLead": "这是选填项。选择一个群体，就会收到针对该群体的警报和建议。",
   "consent": "这部手机的主人回复 YES 即表示同意，包括同意在这里选择的任何群体。",
   "resent": "我们已再次发送到 {phone}。",
   "protoSee": "查看短信到达手机",
   "protoTag": "原型",
   "howStop": "如要停止接收中心的所有短信，请对任何一条短信回复 STOP。",
   "howChange": "如要更改您的群体，请回复 GROUPS。",
   "toHome": "前往“现在”",
   "sample": "示例楼宇",
   "moreBuildings": "还有 {n} 栋。请输入部分地址。"
  },
  "R06": {
   "thanks": "谢谢。您将收到中心关于{where}的{lang}警报。",
   "howStop": "如要停止接收所有短信，请回复 STOP。",
   "howChange": "如要更改您的群体，请回复 GROUPS。",
   "groupsChanged": "已完成。您将不再收到以下群体的警报：{group}。",
   "checkinWithdrawn": "已完成。您的探望申请已撤回。您仍会收到警报。",
   "stopped": "您将不再收到中心的任何短信。如要重新开始，请回复 START。",
   "deviceLabel": "普通手机上的短信",
   "back": "返回应用",
   "replyHint": "点击一条回复即可发送",
   "you": "您",
   "groupsMenu": "回复数字，即可停止接收该群体的警报：{list}。",
   "noGroups": "您没有选择任何群体。您会收到{where}的所有警报。",
   "started": "欢迎回来。您将收到中心关于{where}的{lang}警报。",
   "now": "现在",
   "exNote": "演练。这组对话是练习，发生在参加演练者的手机上。没有任何居民被注册或更改。"
  },
  "R07": {
   "moreComing": "更多信息稍后公布",
   "moreComingLine": "我们一了解更多情况就会更新。",
   "notYetKnown": "尚不清楚",
   "where": "地点",
   "whatToDo": "该怎么做",
   "validUntil": "有效期：{until}",
   "untilResolved": "直到解决",
   "posted": "{t}发布",
   "updated": "{t}更新",
   "latest": "最新",
   "thread": "更新，最新的在前",
   "earlier": "较早的更新",
   "update": "更新",
   "correction": "更正",
   "corrected": "{t}已更正",
   "whatChanged": "更改内容：{changed}",
   "earlierWording": "之前的措辞",
   "final": "最后更新",
   "resolvedTitle": "{t}已解决",
   "expiredTitle": "{t}已过期",
   "expiredNote": "这条警报到了结束时间，但没有最后更新。",
   "fromArchive": "这条警报已结束。它会保留在这里，方便您阅读。",
   "ongoingDays": "持续中：第 {n} 天，共 {total} 天",
   "supportOffer": "这方面的帮助",
   "openNear": "您附近开放的地方",
   "openNearAll": "查看所有开放场所",
   "officialLink": "关于同一事件的官方警报",
   "officialFrom": "来自{source}",
   "adds": "这条信息补充了您楼里正在发生的情况。",
   "officialText": "官方措辞",
   "officialTemplate": "根据已审核模板翻译",
   "guide": "该怎么做：{hazard}指南",
   "services": "能帮助处理这件事的服务",
   "share": "分享",
   "amberNote": "虚构的占位内容。这里只展示版面。",
   "ambLine": "联络员的消息",
   "readingOrder": "屏幕阅读器顺序：来源和核实情况，发布时间，警报内容，“非 911”声明，然后是操作。",
   "kinds": {
    "ack": "第一条消息",
    "alert": "警报",
    "issued": "已发布",
    "update": "更新",
    "correction": "更正",
    "final": "最后更新",
    "ambassador": "联络员的消息"
   },
   "whereLabel": "地点",
   "actionLabel": "现在该怎么做",
   "notYetKnownLabel": "尚不清楚",
   "latestTag": "最新",
   "ambassadorOriginal": "原文（{lang}）",
   "officialCard": "关于同一事件的官方警报",
   "openOfficial": "阅读官方警报",
   "fromCommunity": "这条消息转发了一条官方警报。中心补充了这里正在发生的情况。",
   "spacesFiltered": "根据您的选择，显示不要求身份证件的场所。",
   "supportSee": "查看这个地方",
   "amberBody": "Amber Alert（安珀警报）是关于儿童失踪的官方警报。真正的措辞总是来自 Alert Ready。",
   "endedResolved": "这条警报已结束。已于{t}解决。",
   "endedWithdrawn": "中心撤回了这条警报。{reason}",
   "endedExpired": "这条警报已结束。它于{t}过期，没有最后更新。",
   "validLine": "有效期：{until}",
   "timeLine": "{posted}发布 · {updated}更新",
   "timeLineOne": "{posted}发布",
   "basicMore": "较早的更新：{n}"
  },
  "R08": {
   "title": "已结束的警报",
   "resolved": "{t}已解决",
   "expired": "{t}已过期",
   "empty": "还没有已结束的警报。",
   "emptyBody": "警报结束后会移到这里，仍然可以阅读。",
   "lead": "每条警报结束后都会保留在这里，可以阅读。",
   "endedOn": "{posted}发布",
   "backHome": "返回“现在”"
  },
  "R09": {
   "title": "寻求帮助",
   "prompt": "例如：房东要我搬走",
   "promptAlt": ["例如：这周我需要给家人找食物", "例如：想找人聊聊压力"],
   "searchLabel": "用您自己的话告诉我们您需要什么",
   "search": "搜索",
   "orChoose": "或选择一个主题",
   "within": "在{cat}中搜索",
   "clearCat": "所有主题",
   "lead": "像跟朋友说话一样，说出遇到了什么问题。您不需要知道服务的名称。",
   "focusHint": "其他人写过的内容",
   "topic": "主题：{cat}",
   "seeAll": "查看{cat}的全部内容",
   "moreTopics": "显示全部 {n} 个主题",
   "clear": "清除我写的内容",
   "testTitle": "测试查询",
   "testNote": "供主持人使用：点击一项，运行简报中预设的搜索。居民看不到这部分。",
   "testGloss": "（达里语：{gloss}）"
  },
  "R10": {
   "title": "结果",
   "resultsFor": "“{q}”有 {n} 个结果",
   "matched": "匹配原因：{reason}",
   "crossLanguage": "以{lang}撰写，显示为译文",
   "contributed": "由邻居添加",
   "filters": "筛选",
   "helpListTitle": "能帮助处理以下情况的服务：{hazard}",
   "helpListNote": "只显示说明了能如何帮助处理此情况的服务。按照是否合适、现在是否开放、距离和最近确认的时间排序。",
   "noMatch": "现在没有既免费又不要求身份证件的开放地点。",
   "noMatchSuggest": "如果移除“{f}”，有 {n} 个地点符合。最近的一个{when}开放。",
   "applySuggestion": "移除“{f}”",
   "emergency": "如果现在有人受伤，请拨打 911。",
   "openNow": "现在开放",
   "closedNow": "现在关闭",
   "opensAt": "{t}开放",
   "distance": "{d} 公里",
   "resultsForOne": "“{q}”有 1 个结果",
   "catTitle": "{cat}：{n} 项服务",
   "catTitleOne": "{cat}：1 项服务",
   "changeSearch": "更改我的搜索",
   "filtersCount": "筛选（{n}）",
   "crossQuery": "跨语言匹配。您用{qlang}输入；这条内容是用{lang}撰写的。",
   "noMatchAny": "没有同时符合所有这些筛选条件的结果。",
   "noMatchSuggestShort": "如果移除“{f}”，有 {n} 个地点符合。",
   "removeAll": "移除所有筛选",
   "noneTitle": "我们暂时没有找到",
   "noneBody": "中心的工作人员可以帮您找到合适的服务。",
   "toPerson": "和中心的工作人员谈谈",
   "showMore": "再显示 {n} 个",
   "hoursUnknown": "开放时间不详",
   "communityOffer": "社区提供",
   "inCat": "主题：{cat}",
   "helpEmpty": "没有能帮助处理此情况、又符合这些筛选条件的服务。"
  },
  "R11": {
   "title": "我们暂时没有找到",
   "body": "中心的工作人员可以帮您找到合适的服务。",
   "person": "联系中心的社区导航员",
   "call": "拨打 {phone}",
   "hours": "开放时间：{hours}",
   "visit": "或前往 45 Overlea Boulevard",
   "tryAgain": "换个说法试试",
   "categories": "改为选择一个主题",
   "searched": "您询问的是“{q}”。",
   "navigatorName": "Samira",
   "navigatorRole": "中心的社区导航员",
   "navigatorLine": "她了解这一带的服务，可以通过电话或当面和您一起找到合适的服务。",
   "sampleName": "示例姓名",
   "openNow": "现在开放，到{t}",
   "closedNow": "现在关闭。{t}开放",
   "callConfirm": "在正式的 CVH 中，这里会拨打 {phone}。",
   "directionsConfirm": "在正式的 CVH 中，这里会打开前往 45 Overlea Boulevard 的路线。",
   "directions": "路线",
   "hoursFull": "周一至周四上午9点至晚上8点，周五上午9点至下午5点，周六上午10点至下午2点"
  },
  "R12": {
   "status": "目前",
   "openNow": "现在开放，到{t}",
   "closed": "现在关闭",
   "opens": "{t}开放",
   "address": "地址和交通方式",
   "directions": "路线",
   "hours": "开放时间",
   "languages": "使用的语言",
   "cost": "费用",
   "bring": "需要带什么",
   "id": "他们会要求身份证件或身份证明吗？",
   "access": "无障碍",
   "contact": "联系方式",
   "call": "打电话",
   "email": "电子邮件",
   "website": "网站",
   "unknown": "不详",
   "languagesUnknown": "不详。中心不知道这里使用哪些语言。",
   "noAddress": "没有街道地址",
   "whereToFind": "在哪里找到",
   "confirmedBy": "已由{org}于{date}确认",
   "publicSource": "来自公开资料。尚未经该机构确认。",
   "contributedBy": "由邻居于{date}添加，已经中心核查",
   "kind": "机构类型",
   "services": "服务",
   "org": "运营方",
   "otherServices": "查看{org}提供的其他服务",
   "onMap": "在地图上查看",
   "correct": "有错误？请更正",
   "communityOffer": "社区提供",
   "communityOfferLine": "由邻居提供，不是官方服务。",
   "callConfirm": "在正式的 CVH 中，这里会拨打 {phone}。",
   "directionsConfirm": "在正式的 CVH 中，这里会打开前往{place}的路线。",
   "illustrative": "原型使用的示例信息",
   "appointment": "需要预约吗？",
   "apptYes": "需要。请先打电话预约。",
   "apptNo": "不需要。可以直接前往。",
   "apptSometimes": "有时需要。请打电话确认。",
   "unknownCall": "去之前请先打电话问问。",
   "unknownAsk": "去之前请先到中心问问。",
   "stepFreeYes": "无台阶。",
   "stepFreeNo": "有台阶。",
   "idNo": "不会。",
   "idYes": "会。",
   "emailConfirm": "在正式的 CVH 中，这里会给 {email} 写电子邮件。",
   "webConfirm": "在正式的 CVH 中，这里会打开 {web}。",
   "noContact": "没有列出电话或电子邮件。",
   "todayTag": "今天",
   "hoursUnknown": "开放时间不详",
   "seeAll": "显示全部信息",
   "source": "这些信息的来源",
   "derivedNote": "中心目前只有这个条目的名称、地点和类型。",
   "addedRecently": "最近",
   "notFound": "找不到这个地方。",
   "spaceHours": "今天作为场所开放，{from}至{to}。其他开放时间不详。",
   "someUnknown": "部分信息尚不清楚。{ask}"
  },
  "R13": {
   "services": "服务",
   "about": "简介",
   "servicesCount": "这里的服务：{n} 项",
   "contact": "联系方式",
   "call": "拨打 {phone}",
   "website": "网站",
   "illustrative": "原型使用的示例介绍",
   "webConfirm": "在正式的 CVH 中，这里会打开 {web}。",
   "callConfirm": "在正式的 CVH 中，这里会拨打 {phone}。",
   "showAll": "显示全部 {n} 项服务",
   "notFound": "找不到这个机构。",
   "aboutLines": {
    "TNO": "Thorncliffe Park 的一家社区机构，为本社区开展食物、移民安置、就业、青少年和家庭项目。",
    "HUB": "位于 45 Overlea Boulevard 的社区中心，许多本地服务和团体在同一栋楼里办公。",
    "TPL": "公共图书馆，提供免费图书、电脑、Wi-Fi 和适合所有年龄的活动。",
    "CITY": "多伦多市在 Thorncliffe Park 和 Flemingdon Park 的社区中心和项目。"
   }
  },
  "R14": {
   "title": "地图",
   "list": "列表",
   "mapView": "地图",
   "loading": "正在加载地图",
   "unavailable": "地图无法加载。列表中有全部内容。",
   "showList": "显示列表",
   "noneInView": "这里没有内容。请试着缩小地图。",
   "places": "{n} 个地点",
   "place": "1 个地点",
   "add": "添加地点",
   "rules": "本空间的规则",
   "filters": "您需要什么？",
   "disruptionView": "显示能帮助处理以下情况的地点：{hazard}",
   "legend": "地点类型",
   "newlyAdded": "新",
   "tapForHours": "点击地点查看开放时间",
   "legendFormal": "服务机构或公共场所",
   "legendInformal": "社区团体或宗教团体",
   "legendOffer": "邻居提供的社区帮助",
   "legendSpace": "现在作为场所开放",
   "legendCluster": "相距很近的多个地点。点击放大。",
   "legendTitle": "图形的含义",
   "zoomIn": "放大",
   "zoomOut": "缩小",
   "here": "这里有 {n} 个地点",
   "mapLabel": "Thorncliffe Park 和 Flemingdon Park 地图",
   "allPlaces": "显示所有地点",
   "subAll": "所有类型的地点",
   "subLabel": "什么类型的地点？",
   "spaceFor": "现在作为场所开放，{purpose}",
   "basicList": "大字体模式下，地点以列表显示，最近的在前。",
   "noneMatch": "没有符合这些筛选条件的地点。",
   "addShort": "添加地点",
   "missing": "有遗漏或错误？"
  },
  "R15": {
   "title": "您附近的地点",
   "byDistance": "最近的在前",
   "empty": "没有符合这些筛选条件的地点。",
   "emptyBody": "移除一个筛选条件可以看到更多。",
   "add": "添加地点",
   "count": "{n} 个地点",
   "countOne": "1 个地点",
   "more": "再显示 {n} 个",
   "distanceHome": "{d} 公里",
   "clearAll": "移除所有筛选",
   "missing": "这里有遗漏或错误？",
   "suggest": "如果移除“{f}”，有 {n} 个地点符合。最近的一个距离 {d}。",
   "suggestOne": "如果移除“{f}”，有 1 个地点符合。距离 {d}。",
   "suggestButton": "移除“{f}”"
  },
  "R16": {
   "open": "查看详情",
   "hoursToday": "今天：{hours}",
   "close": "关闭",
   "less": "收起",
   "wrong": "这个地点的信息有误？",
   "distance": "距离您的住处 {d} 公里",
   "contributed": "由邻居添加"
  },
  "R17": {
   "title": "添加或更正地点",
   "add": "添加缺少的地点",
   "correct": "更正看起来有误的地点",
   "fromEntry": "更正这个地点",
   "addLine": "能帮助邻居、但还不在地图上的地方。两个简短步骤。",
   "correctLine": "开放时间、地点或某项信息已经过时。",
   "fromEntryLine": "只改错误的地方。其他内容保持不变。",
   "lookingAt": "您刚才在查看",
   "pickTitle": "哪个地点看起来有误？",
   "pickHint": "离您最近的在前。每个地点的页面上也有“有错误？请更正”。",
   "addDifferent": "添加另一个缺少的地点"
  },
  "R18": {
   "title": "添加地点之前",
   "continue": "我明白了，继续",
   "step": "第 1 步，共 2 步：规则",
   "readIn": "用以下语言阅读规则",
   "readInHint": "CVH 提供的每种语言都有规则文本。",
   "after": "接下来，请告诉我们这个地点的情况。大部分是选择，不用打字。"
  },
  "R19": {
   "title": "添加地点",
   "name": "它叫什么名字？",
   "what": "用一句话说明那里提供什么",
   "whatHint": "最多 140 个字符",
   "category": "它提供哪种帮助？",
   "type": "它是官方服务还是社区提供？",
   "official": "官方服务",
   "offer": "邻居提供的社区帮助",
   "hours": "什么时候开放？",
   "sameWeekdays": "每个工作日都一样",
   "notSure": "不确定",
   "from": "从",
   "to": "到",
   "closedDay": "关闭",
   "cost": "需要多少钱？",
   "idQ": "他们会要求身份证件或身份证明吗？",
   "stepFreeQ": "不用走台阶能进去吗？",
   "languagesQ": "使用哪些语言？",
   "location": "它在哪里？",
   "submit": "发送给中心",
   "optional": "选填",
   "ready": "可以发送",
   "saved": "已保存在这部手机上",
   "step": "第 2 步，共 2 步：地点",
   "choose": "选择一项",
   "catNotSure": "不确定",
   "offerLine": "由邻居提供，不是官方服务。它在地图上以虚线轮廓显示。",
   "officialLine": "由机构、团体或市政府运营。",
   "whereBtn": "显示它的位置",
   "whereChange": "更改",
   "whereNone": "尚未选择",
   "costFree": "免费",
   "costLow": "低价",
   "costFee": "收费",
   "yes": "是",
   "no": "否",
   "weekdays": "周一至周五",
   "langsHint": "请选择所有适用的选项。",
   "count": "{n}/140",
   "missingTitle": "请添加以下内容，然后发送：",
   "resubmitNote": "中心退回了这条内容。{change}",
   "closedOpt": "关闭",
   "notSureOpt": "不确定",
   "toOpt": "到",
   "fromOpt": "开放",
   "hoursNotSureLine": "没关系。中心会去问这个地方。",
   "whatPh": "例如：每周四晚上免费发放食品杂货，任何人都可以领",
   "namePh": "例如：周四食物银行"
  },
  "R20": {
   "title": "它在哪里？",
   "pin": "在地图上放置标记",
   "building": "在某栋楼里",
   "described": "说明在楼里的哪个位置",
   "describedHint": "例如：清真寺后面的社区活动室",
   "landmark": "在某个地标附近",
   "landmarkHint": "例如：R.V. Burgess Park 的戏水池旁边",
   "address": "街道地址",
   "noAddress": "您不需要提供街道地址。",
   "howTitle": "大家怎样才能找到它？",
   "use": "使用这个地点",
   "pinHint": "移动地图，直到标记落在这个地点上。",
   "pinNear": "地图上的标记，在{place}附近",
   "nearLandmark": "在{place}附近",
   "buildingChoose": "选择一栋楼",
   "landmarkChoose": "选择一个地标",
   "landmarkMore": "其他能帮助大家找到它的信息",
   "addressHint": "知道的话再填。",
   "needOne": "请在上面选择一种方式。",
   "needBuilding": "请先选择楼宇。",
   "needLandmark": "请先选择地标。",
   "needAddress": "请先输入地址。",
   "pinWhere": "标记在{place}附近。",
   "mapLabel": "用于放置标记的地图"
  },
  "R21": {
   "title": "已发送给中心",
   "general": "中心的工作人员会在大约一周内阅读。它上了地图后，我们会通知您。",
   "ambassador": "您是联络员，所以会优先审核。通常一天之内就会上地图。",
   "lane": "审核途径：{lane}",
   "laneGeneral": "社区审核",
   "laneAmbassador": "联络员审核，更快",
   "youSent": "您发送了：{name}",
   "next": "接下来会怎样",
   "n1": "中心的工作人员会阅读。",
   "n2": "如果符合规则，它会出现在地图和搜索中。",
   "n3": "如果需要修改，我们会告诉您改什么，您可以再次发送。",
   "n1Amb": "中心的工作人员会在一般队列之前优先阅读。",
   "howLong": "需要多久",
   "weekLine": "大约一周",
   "dayLine": "通常一天之内",
   "toMap": "返回地图",
   "another": "再添加一个地点",
   "protoLabel": "仅限原型",
   "protoDecline": "查看中心退回的地点",
   "protoAccepted": "在地图上查看邻居添加的地点"
  },
  "R22": {
   "title": "更正这个地点",
   "changeOne": "修改错误的地方。其他内容保持不变。",
   "submit": "发送更正",
   "sent": "谢谢。中心会核查这项修改。",
   "change": "更改",
   "changedTag": "已更改",
   "was": "原来是：{v}",
   "undo": "撤销",
   "nothingYet": "请至少修改一项，然后发送。",
   "doneEditing": "完成",
   "onlyThis": "只会发送您修改的内容。中心核查后才会更新这个地点。",
   "toPlace": "返回这个地点",
   "toMap": "返回地图",
   "sentTitle": "更正已发送",
   "whatChanged": "您修改的内容",
   "whereLabel": "位置",
   "namePlace": "名称"
  },
  "R23": {
   "title": "您的地点暂时还没有添加",
   "reason": "原因",
   "whatToChange": "需要修改什么",
   "resubmit": "修改后再次发送",
   "kept": "您写的所有内容都已保留。",
   "sentAgo": "您{t}发送了这条内容。",
   "youWrote": "您写的内容",
   "whereNone": "没有提供地点",
   "toMap": "返回地图",
   "reasons": {
    "advert": {
     "why": "它在出售东西或要求付钱。CVH 不是市场。",
     "change": "如果其中有任何人都能使用的免费部分，请只描述这一部分。不要写价格和付款信息。"
    },
    "noLocation": {
     "why": "我们无法判断它在哪里。",
     "change": "请添加一栋楼、附近的地标或地图上的标记。您不需要提供街道地址。"
    },
    "duplicate": {
     "why": "这个地点已经在地图上了。",
     "change": "如果它的某些信息有误，请打开它并选择“请更正”。"
    },
    "unclear": {
     "why": "我们无法判断这是哪个地点，或者那里提供什么。",
     "change": "请写出它的名称，并用一句话说明大家可以在那里得到什么。"
    },
    "outOfArea": {
     "why": "它在 Thorncliffe Park 和 Flemingdon Park 以外。",
     "change": "CVH 只显示这两个社区内或附近的地点。"
    },
    "notCommunity": {
     "why": "它不是向社区所有人开放的。",
     "change": "如果社区里任何人都能使用，请再次发送。"
    }
   }
  },
  "R24": {
   "title": "做好准备",
   "lead": "这里会发生的六种突发情况：之前、期间和之后该怎么做。",
   "numbers": "我可能需要的电话号码",
   "headsUp": "每个季节之前的提前提醒",
   "checkin": "申请在高温和停电期间有人来探望",
   "readTime": "阅读约 {n} 分钟",
   "guides": "指南：之前、期间和之后该怎么做",
   "more": "更多做好准备的方法",
   "checkinLine": "您的楼层联络员会来探望您。这不是紧急服务。",
   "numbersLine": "911、211、311、Toronto Hydro 和中心",
   "headsUpLine": "只在 CVH 中显示，绝不通过短信发送",
   "none": "现在无法加载指南。如有人身处危险，请拨打 911。"
  },
  "R25": {
   "stagesNav": "跳转到",
   "aiLabel": "为原型由人工智能撰写。CVH 上线前会由人工审核。",
   "kit": "本指南与印刷版 Local Preparedness Kit（本地应急准备手册）内容一致。",
   "numbers": "我可能需要的电话号码",
   "services": "能提供帮助的服务",
   "spaces": "开放{purpose}的场所",
   "forYou": "先看适合您的内容",
   "fullGuide": "完整指南",
   "next": "下一部分：{stage}",
   "stageNow": "您正在阅读：{stage}",
   "unavailable": "本指南暂时没有{lang}版本。",
   "guideWord": "指南",
   "readTime": "阅读约 {n} 分钟",
   "helpTitle": "这方面的帮助",
   "tailoredLink": "根据您的选择定制",
   "allSteps": "显示全部 {n} 个步骤",
   "purposeWords": {
    "cooling": "用于避暑降温",
    "cleanAir": "用于呼吸清洁空气",
    "charging": "用于充电"
   },
   "endLine": "本指南到此结束。如果您需要更多帮助：",
   "numbersLine": "911、211、311、Toronto Hydro 和中心",
   "openedDuring": "因为这件事正在发生，所以从“期间”部分开始显示。"
  },
  "R26": {
   "title": "您属于哪些群体？",
   "lead": "选择任何适合您的群体。这会影响您收到的警报和看到的建议。我们绝不会问原因。",
   "skipLine": "跳过不会改变您收到的警报。",
   "helperConfirm": "我在帮助别人。对方同意了这些选择。",
   "helperNote": "请先问过对方。",
   "step": "第 1 步，共 2 步",
   "checkinNext": "接下来，请选择您的楼宇和楼层，然后选择您希望用什么方式被探望。",
   "helperNeeded": "请先问过对方。对方同意后请勾选方框，或跳过这个问题。",
   "save": "保存",
   "saved": "已保存。现在生效。",
   "choose": "选择任何适合您的群体",
   "helping": "在帮别人填写？"
  },
  "R27": {
   "title": "筛选",
   "apply": "显示 {n} 个结果",
   "clear": "全部清除",
   "lead": "只回答对您重要的问题。其他条件保持不限。",
   "openNowOnly": "只看现在开放的地点",
   "anyLang": "任何语言",
   "langHint": "显示有人说这种语言的地点。没有告诉我们的地点不会显示。",
   "noIdHint": "只显示已告诉中心不会为了帮助您而要求身份证件、文件或移民身份的地点。没有告诉我们的地点不会显示，这样您去了就不会被问到。",
   "private": "您的回答只保留在这部手机上，不会被保存或发送给任何人。",
   "fromChoices": "来自您的选择",
   "cancel": "返回，不做更改",
   "applyOne": "显示 1 个结果",
   "moreQuestions": "更多问题（{n}）",
   "applyNone": "应用（暂时没有符合的结果）"
  },
  "R28": {
   "title": "“已核实”是什么意思",
   "body": "已核实是指，中心的工作人员或与中心合作的伙伴机构的人员，在警报发出前已经和现场人员核对过这条警报。",
   "who": "{org}于{t}核实了这条警报。",
   "notYet": "尚未核实是指，这条警报来自楼宇联络员，他们往往最先知道情况。中心会尽快核查。",
   "official": "官方警报来自{source}，转发时不改动原文。",
   "notFalse": "尚未核实并不代表它是错的。",
   "thisAlert": "这条警报",
   "ambFirst": "它最初由 {building} 的楼宇联络员于{t}发布。",
   "ambPosted": "它由 {building} 的楼宇联络员于{t}发布。",
   "notYetAct": "您现在就可以按照它行动。中心核查后，它会改为显示“已由中心核实”。",
   "correctedLine": "它已于{t}更正。警报会显示更改了什么，之前的措辞仍然可以阅读。",
   "officialAdds": "中心绝不会改动官方警报的原文。中心可能会另发一条社区警报，补充您楼里正在发生的情况。",
   "legendTitle": "您会在警报上看到的词语",
   "thisOne": "这条警报",
   "legendVerified": "中心或伙伴机构的人员在发出前已经核查。",
   "legendUnverified": "由楼宇联络员发布。中心还没有核查。",
   "legendOfficial": "来自政府来源，逐字转发。",
   "backToAlert": "返回警报"
  },
  "R29": {
   "title": "分享这条警报",
   "preview": "您的邻居会收到这样的内容",
   "everyone": "所有人收到的都是这个版本。不会分享任何为您定制的内容。",
   "notRecorded": "CVH 不会记录谁分享了警报，也不会记录您发给了谁。",
   "send": "分享",
   "handed": "这里会打开您手机的分享选项。",
   "lead": "您的邻居收到的警报和中心写的一样，并附有来源和最新版本的链接。",
   "postedAt": "{t}发布",
   "updatedAt": "{t}更新",
   "todayAt": "今天{time}",
   "dayAt": "{day} {time}",
   "linkLine": "最新更新和任何更正：{url}",
   "sendLine": "您的手机会问您用哪个应用发送。",
   "placeMore": "以及另外 {n} 处"
  },
  "R30": {
   "deviceLabel": "WhatsApp 群里的警报",
   "group": "4 楼邻居",
   "openedLater": "稍后打开：显示最新更新和一条更正。",
   "groupBuilding": "{building} 邻居",
   "members": "{name}、Maria、您和其他 9 人",
   "membersOut": "Maria、Farhan 和其他 10 人",
   "today": "今天",
   "forwarded": "已转发",
   "you": "您",
   "askLine": "还有谁家停电了吗？",
   "askLineOther": "有人知道电梯怎么了吗？",
   "proto": "原型",
   "backToApp": "返回应用",
   "removeLink": "移除链接",
   "restoreLink": "放回链接",
   "openLater": "几小时后打开链接",
   "senderLang": "{name} 用{lang}阅读 CVH。链接会以打开者的语言显示，而不是发送者的语言。",
   "linkRemovedNote": "链接已移除。这条消息仍然说明了发生了什么、在哪里、来自谁、是否已核实、什么时候，以及该怎么做。",
   "sinceSent": "自 {name} 发送以来：",
   "showSince": "显示更改内容",
   "noChange": "稍后打开：发送以来没有发布新内容。",
   "nowVerified": "稍后打开：中心之后核查了这条帖子，所以警报现在显示“已由中心核实”。",
   "exNote": "演练。如果转发练习消息，演练字样会作为第一行一起转发，这样就没有人会把它误当成真正的警报。"
  },
  "R31": {
   "title": "我可能需要的电话号码",
   "emergency": "紧急情况",
   "emergencyWhen": "如果现在有人的生命或安全处于危险中，请拨打 911：火灾、医疗紧急情况或正在发生的犯罪。",
   "p211": "帮助寻找社区、社会和政府服务",
   "p311": "多伦多市政服务和非紧急问题",
   "hydro": "向 Toronto Hydro 报告停电",
   "hub": "和中心的工作人员谈谈",
   "building": "您楼宇的{role}",
   "noBuilding": "我们还没有您楼宇的联系人。您的楼层联络员可以帮忙。",
   "call": "打电话",
   "callConfirm": "在正式的 CVH 中，这里会拨打 {number}。",
   "lead": "每个号码都按用途列出。",
   "others": "其他所有事情",
   "call911": "拨打 911",
   "buildingTitle": "您的楼宇",
   "noBuildingNoAmb": "我们还没有您楼宇的联系人。中心可以帮您联系楼宇管理处。",
   "noBuildingChosen": "请选择您的楼宇，有联系人时我们会在这里显示。在此之前，中心可以帮忙。",
   "chooseBuilding": "选择您的楼宇",
   "ambRoute": "他们住在您的楼里，可以把事情转告楼宇管理处。",
   "hubHours": "开放时间：周一至周四上午9点至晚上8点，周五上午9点至下午5点，周六上午10点至下午2点",
   "calling": "致电{what}",
   "roles": {
    "superintendent": "大楼管理员"
   },
   "checked": "已由中心核查，最后更新于{date}",
   "noOthers": "现在无法加载其他号码。请几分钟后再试。"
  },
  "R32": {
   "title": "每个季节之前的提前提醒",
   "lead": "在高温、烟雾和冬季停电之前，CVH 中会出现简短提醒，附上一两件要做的事。",
   "never": "提前提醒只在 CVH 中显示，绝不会以短信形式发送。",
   "on": "提前提醒已开启",
   "off": "提前提醒已关闭",
   "season": "时间：{season}",
   "switchLabel": "每个季节之前给我提前提醒",
   "what": "您会看到的内容",
   "whatOn": "您将看到的内容",
   "titles": {
    "heat": "炎热天气到来之前",
    "smoke": "山火烟雾季节之前",
    "winter": "冬季风暴之前"
   },
   "readGuide": "阅读{hazard}指南",
   "turnedOn": "提前提醒已开启。您会在“现在”页面看到，只在 CVH 中显示。",
   "turnedOff": "提前提醒已关闭。其他设置没有改变。",
   "offLine": "提前提醒处于关闭状态，直到您开启。",
   "whereLine": "它们会在每个季节前几周显示在“现在”页面上。"
  },
  "R33": {
   "title": "申请探望",
   "what": "当您的楼宇出现高温警告或停电时，您的楼层联络员会来探望您，并可以帮您联系所需的服务。",
   "notEmergency": "探望不是紧急服务。",
   "how": "您希望用什么方式被探望？",
   "call": "打电话",
   "text": "发短信",
   "knock": "敲门",
   "unit": "单元号",
   "unitWhy": "我们询问您的单元号，只是为了让联络员知道该敲哪扇门。",
   "building": "您的楼宇和楼层",
   "noAmbassador": "{floor} 楼还没有楼层联络员，所以我们无法保证有人来探望。",
   "hubInstead": "请改为拨打 {phone} 联系中心。我们的开放时间是{hours}。",
   "request": "申请探望",
   "requested": "已申请探望",
   "requestedBody": "当 {building} 出现高温警告或停电时，您的楼层联络员会通过{method}来探望您。",
   "withdraw": "停止探望",
   "withdrawn": "探望已停止。您仍会收到警报。",
   "helper": "我在帮助别人。对方同意申请探望。",
   "whatTitle": "什么是探望",
   "askPlace": "我们需要知道您的楼宇和楼层，才能知道是否有楼层联络员可以探望您。",
   "chooseBuilding": "选择您的楼宇",
   "chooseFloor": "选择您的楼层",
   "floorN": "{n} 楼",
   "change": "更改",
   "placeLine": "{building}，{floor} 楼",
   "covered": "{floor} 楼有楼层联络员负责。",
   "callHub": "打电话给中心",
   "stillAlerts": "您仍会收到您楼宇的所有警报。",
   "needMethod": "请选择您希望用什么方式被探望。",
   "needUnit": "选择敲门请添加单元号，或者选择打电话或发短信。",
   "needHelper": "请先问过对方。对方同意后请勾选方框。",
   "needPlace": "请先选择您的楼宇和楼层。",
   "howWithdraw": "您可以随时停止探望：在这里、在“我的选择”中，或者回复中心的短信 NOCHECK。",
   "changeHow": "更改方式",
   "again": "再次申请探望",
   "unitShown": "{unit} 单元",
   "continue": "继续",
   "skip": "暂时不用",
   "helping": "在帮别人填写？"
  },
  "R34": {
   "title": "我告诉过 CVH 的信息",
   "lead": "只有您选择的内容。您可以在这里更改或删除任何一项。更改会立即生效。",
   "language": "语言",
   "building": "楼宇和楼层",
   "basic": "字体更大，内容更少",
   "groups": "群体",
   "checkin": "探望",
   "headsUp": "季节提前提醒",
   "change": "更改",
   "remove": "删除",
   "removed": "已删除。现在生效。",
   "nothing": "您还没有告诉 CVH 任何信息。",
   "onDevice": "这些选择只保存在这台设备上。",
   "invite": "如想在手机上接收您楼宇和群体的警报，请开通短信警报。只需一分钟，不需要账户。",
   "inviteYes": "开通短信警报",
   "inviteNo": "暂时不用",
   "fromTailored": "“这对您意味着什么”下面的建议只根据本页的选择生成。在这里更改，建议也会随之改变。",
   "neighbourhoodOnly": "{nbhd} 的所有警报",
   "floorOf": "{building}，{floor} 楼",
   "on": "开",
   "setByHelper": "由帮助您的人开启",
   "checkinNone": "未申请",
   "checkinAsk": "申请探望",
   "checkinBy": "方式：{method}",
   "checkinNoAmb": "您的楼层还没有楼层联络员。中心可以帮忙。",
   "unitLine": "{unit} 单元，仅用于敲门",
   "textAlerts": "短信警报",
   "textOn": "已开启，发送到 {phone}",
   "textPending": "等待您从 {phone} 回复 YES",
   "howStop": "如要停止，请对中心的任何一条短信回复 STOP。",
   "removedItem": "已删除：{item}",
   "tellUs": "您可以告诉 CVH：",
   "whereLive": "您住在哪里",
   "whichGroups": "您属于哪些群体",
   "turnOff": "关闭",
   "changeGroups": "更改群体",
   "groupsNone": "未选择",
   "chooseGroups": "选择群体",
   "langNote": "您阅读 CVH 所用的语言。",
   "removedBuildingOne": "您保存的 1 栋楼已不在楼宇列表中，所以已被删除。",
   "removedBuildingMany": "您保存的 {n} 栋楼已不在楼宇列表中，所以已被删除。",
   "removedFloorOne": "您保存的 1 个楼层已不存在，所以已被删除。",
   "removedFloorMany": "您保存的 {n} 个楼层已不存在，所以已被删除。",
   "removedRest": "您选择的其他内容都没有改变。",
   "clearAll": "全部清除",
   "clearTitle": "要清除这部手机上的所有内容吗？",
   "clearBody": "这会从这部手机上删除您的语言、群体、楼宇和楼层。您需要重新从选择语言开始。",
   "clearYes": "是的，全部清除",
   "loading": "正在加载您的楼宇……",
   "listFailed": "楼宇列表暂时无法加载。您的选择仍然保存着。",
   "buildingByRsn": "楼宇 {rsn}",
   "floorsOne": "已选择 1 个楼层",
   "floorsMany": "已选择 {n} 个楼层",
   "buildingsNone": "未选择",
   "removeItem": "删除：{item}"
  },
  "R35": {
   "title": "接收您楼宇的警报",
   "lead": "选择您住的地方，优先查看您楼宇的警报。每一步都是选填。",
   "nbhd": "社区",
   "building": "楼宇",
   "floor": "楼层",
   "nbhdOnly": "只选整个社区",
   "floorLine": "选择楼层后，您还会收到只针对您楼层的警报，例如电梯或停水。",
   "noUnit": "我们在这里绝不会询问您的单元号。",
   "preselected": "来自您的通知",
   "skipLine": "如果跳过，您仍然可以看到您社区的所有警报。",
   "finishedTitle": "您选择了",
   "invite": "如想在手机上接收您楼宇、楼层和群体的警报，请开通短信警报。只需一分钟，不需要账户。",
   "inviteYes": "开通短信警报",
   "inviteNo": "暂时不用",
   "helper": "我在帮助别人。对方同意了这个选择。",
   "step": "第 2 步，共 2 步",
   "buildingSearch": "搜索您的楼宇",
   "more": "还有 {n} 栋。请输入部分地址来查找您的楼宇。",
   "noMatch": "没有与“{q}”相符的楼宇。",
   "change": "更改",
   "noFloor": "不选楼层，只选楼宇",
   "floorN": "{n} 楼",
   "sample": "示例楼宇",
   "nextCheckin": "下一步：您希望用什么方式被探望。",
   "helperNeeded": "请先问过对方。对方同意后请勾选方框，或跳过这个问题。",
   "save": "保存",
   "saved": "已保存。现在生效。",
   "both": "Thorncliffe Park 和 Flemingdon Park",
   "nothingSummary": "还没有选择。您会看到 Thorncliffe Park 和 Flemingdon Park 的所有警报。",
   "everyAlert": "{nbhd} 的所有警报",
   "floorOf": "{building}，{floor} 楼",
   "checkinBy": "探望方式：{method}",
   "changeAll": "更改您的选择",
   "toHome": "前往“现在”",
   "manyLine": "选择您自己的楼宇或亲属的楼宇。想选几栋都可以。",
   "chosenNone": "还没有选择楼宇",
   "chosenOne": "已选择 1 栋楼",
   "chosenMany": "已选择 {n} 栋楼",
   "floorsIn": "{building} 的楼层。选填。",
   "noFloorsListed": "这栋楼还没有列出楼层。",
   "loading": "正在加载楼宇列表……",
   "loadFailed": "无法加载楼宇列表。请检查网络连接后再试，或跳过这一步。",
   "retry": "重试"
  },
  "A01": {
   "title": "我的楼宇",
   "assigned": "您是 {building} {floors} 楼的联络员。",
   "canPost": "您可以为 {building} 的任何楼层发布更新。",
   "post": "发布楼宇更新",
   "active": "您楼里正在发生的情况",
   "nothing": "您楼里目前没有正在发生的情况。",
   "round": "探望巡查：您负责的楼层有 {n} 户",
   "openRound": "打开我的巡查",
   "role": "楼宇联络员",
   "roundFloors": "您的巡查：{a} 楼至 {b} 楼。",
   "offline": "没有信号。您的操作会保存在手机上，有信号时再发送。",
   "noRound": "目前没有探望巡查。当中心为您的楼宇发出高温或停电警报时，巡查就会开始。",
   "toDo": "还有 {n} 户待完成",
   "tellInPerson": "需要当面告知的住户：{n} 户",
   "practice": "练习巡查",
   "myRound": "我的巡查",
   "myPosts": "您的更新",
   "postedAgo": "{t}发布",
   "fromHub": "来自中心",
   "fromAmb": "来自楼宇联络员",
   "fromOfficial": "官方警报",
   "fromPartner": "来自伙伴机构",
   "verifiedWord": "已核实",
   "notVerifiedWord": "尚未核实"
  },
  "A02": {
   "title": "发布楼宇更新",
   "types": "发生了什么？请选择所有适用的选项",
   "floors": "哪些楼层？",
   "wholeBuilding": "整栋楼",
   "range": "从 {a} 楼到 {b} 楼",
   "pick": "选择楼层",
   "photo": "添加照片",
   "line": "添加一句话",
   "lineRequired": "用一句话说明发生了什么",
   "optional": "选填",
   "other911": "如有人身处危险，请先拨打 911。",
   "appearsAs": "显示为：楼宇联络员，{building}",
   "goesNow": "这条更新会立即发出。",
   "waits": "中心会先核查，然后再发出。",
   "post": "发布更新",
   "notOffered": "高温和烟雾警报由中心面向整个社区发布。",
   "exOutcome": "练习：这条只发给中心。不会向居民发送任何内容。",
   "exNote": "演练：这条帖子是练习。它只发给中心，绝不会发给居民。",
   "typeMore": {
    "fire": "警报或疏散",
    "water": "或管道"
   },
   "required": "必填",
   "wholeLine": "全部 {n} 个楼层",
   "mineLabel": "{a} 楼至 {b} 楼",
   "mineLine": "您的巡查范围",
   "pickLabel": "选择楼层",
   "pickLine": "先点击第一个楼层，再点击最后一个",
   "pickNone": "还没有选择楼层",
   "pickOne": "{a} 楼",
   "pickRange": "{a} 楼至 {b} 楼",
   "floorAria": "{n} 楼",
   "more": "如果愿意，可以添加更多内容",
   "photoAdded": "已添加照片（示例）",
   "remove": "删除",
   "lineAdded": "您的一句话",
   "ownLine": "或者自己写一句话",
   "sampleBn": "孟加拉语示例句子",
   "sampleTag": "原型",
   "mtNote": "用其他语言阅读的居民会看到它带有“机器翻译”标签。",
   "phrases": ["已通知楼宇工作人员。", "走楼梯时请小心。", "请去看看可能需要帮助的邻居。"],
   "otherPhrases": ["前门锁不上。", "走廊的灯不亮了。", "垃圾槽堵住了。"],
   "otherFirst": "如有人身处危险，请先拨打 911。然后在这里说明发生了什么。",
   "someWait": "其中有一种类型总是要等中心核查，所以这条更新也要等待。",
   "offlineBar": "现在没有信号。内容已保存在您的手机上，有信号时会发出。",
   "postTo": "发布更新：{floors}",
   "wholeWord": "整栋楼",
   "errTypes": "请选择发生了什么。",
   "errFloors": "请点击楼层，或选择“整栋楼”。",
   "errLine": "选择“其他”需要写一句话：说明发生了什么。"
  },
  "A03": {
   "liveTitle": "已发布",
   "live": "现已在所有渠道上发布，包括短信。中心核查之前，它会显示为“尚未核实”。",
   "waitingTitle": "等待中心",
   "waiting": "中心正在核查。获批后会立即发出。",
   "approved": "已于{t}批准并发送。",
   "declined": "中心没有发送这条更新。原因：{reason}",
   "verified": "中心已于{t}核实您的更新。",
   "corrected": "中心更正了您的更新。原因：{reason}",
   "withdrawn": "中心撤回了您的更新。原因：{reason}",
   "slow": "仍在发送。这里信号较弱。信号好转后会完成发送。",
   "where": "发送到：{channels}",
   "when": "{t}发布",
   "states": {
    "queued": "已保存在您的手机上。有信号时发出",
    "live": "已发布。尚未核实",
    "waiting": "等待中心",
    "approved": "已批准并发送",
    "declined": "中心未发送",
    "verified": "已由中心核实",
    "withdrawn": "已由中心撤回",
    "corrected": "已由中心更正",
    "exercise": "演练。未发送给居民"
   },
   "queuedTitle": "已保存在您的手机上",
   "queued": "已保存在您的手机上。有信号时会发出。",
   "writtenAt": "写于{t}。您不需要再做任何事。",
   "approvedTitle": "已批准并发送",
   "declinedTitle": "未发送",
   "verifiedTitle": "已由中心核实",
   "correctedTitle": "已由中心更正",
   "withdrawnTitle": "已由中心撤回",
   "exerciseTitle": "练习帖子已保存",
   "exercise": "这是演练。没有向居民发送任何内容。",
   "approvedLine": "它现在显示为已由中心核实。",
   "verifiedLine": "居民现在会在您的更新上看到“已由中心核实”。没有发送第二条消息。",
   "correctedLine": "中心修改了您的更新：{text}",
   "correctedWhen": "已于{t}更正。",
   "yourUpdate": "您的更新",
   "floorsAll": "整栋楼",
   "floorsOne": "{a} 楼",
   "floorsRange": "{a} 楼至 {b} 楼",
   "photoYes": "附有照片",
   "whereWhen": "发到了哪里，什么时候发的",
   "chText": "短信",
   "chWeb": "CVH 应用和网站",
   "sentTo": "已于{t}发送给 {building} 的居民，{floors}",
   "liveOn": "自{t}起为 {building} 显示，{floors}",
   "notYet": "尚未发送",
   "notSent": "未发送",
   "takenDown": "已于{t}撤下",
   "waitAfter": "中心批准后，会立即在所有渠道上发出。",
   "howSeen": "居民看到的样子",
   "willSeen": "获批后，居民会看到",
   "seeIt": "以居民的视角查看",
   "toHome": "返回我的楼宇",
   "another": "再发布一条更新",
   "notFound": "在这部手机上找不到这条更新。",
   "reasonLabel": "原因：{reason}"
  },
  "A04": {
   "title": "我的巡查",
   "checkins": "您负责楼层上申请的探望",
   "unreachable": "您负责楼层上无法通过电话或应用联系到的住户",
   "carry": "要告诉他们的警报",
   "floorDoor": "{floor} 楼，{door} 号门",
   "floorPhone": "{floor} 楼，{method} {phone}",
   "method": {
    "call": "打电话",
    "text": "发短信",
    "knock": "敲门"
   },
   "done": "已完成",
   "notReached": "未联系上",
   "needsHelp": "需要帮助",
   "connected": "已转介到服务",
   "passed": "已转交中心",
   "offline": "没有信号。您的操作已保存，有信号时会发送。",
   "deleted": "这次突发情况结束后，这些记录会被删除。只保留数量统计。",
   "addDoor": "应住户要求添加一户",
   "addConfirm": "住户在我的屏幕上同意被添加。",
   "addedByRequest": "应住户要求添加",
   "addNote": "突发情况结束后，这一户会被删除。如果他们希望每次都有人探望，可以在 CVH 中选择。",
   "exercise": "这是练习巡查。",
   "forAlert": "针对：{headline}",
   "practiceFor": "练习巡查。不会有任何内容发给居民。",
   "floorN": "{n} 楼",
   "doorN": "{door} 号门",
   "methodWord": {
    "call": "打电话",
    "text": "发短信",
    "knock": "敲门"
   },
   "tally": "待完成 {todo} · 已完成 {done} · 未联系上 {nr} · 需要帮助 {help}",
   "connectedCat": "已转介到服务：{category}",
   "queued": "已保存在您的手机上。有信号时会发送。",
   "taken": "已由中心接手",
   "change": "更改",
   "connect": "转介到服务",
   "tellInPerson": "敲门并告诉他们这条警报",
   "whereLabel": "地点",
   "doLabel": "现在该怎么做",
   "noRound": "目前没有探望巡查。当中心为您的楼宇发出高温或停电警报时，您负责楼层的探望会显示在这里。",
   "addTitle": "添加一户",
   "addFloor": "楼层",
   "addDoorLabel": "门牌号",
   "addMethod": "他们希望用什么方式被联系",
   "addPhone": "电话号码",
   "addBtn": "添加到我的巡查",
   "cancel": "取消",
   "added": "已添加到您的巡查。",
   "errDoor": "请添加门牌号。",
   "errPhone": "选择打电话或发短信，请添加电话号码。",
   "errMethod": "请选择他们希望用什么方式被联系。",
   "errAgree": "请先问过对方。对方同意后，请在您的屏幕上勾选方框。",
   "practiceNoAlert": "练习：没有需要转达的警报。"
  },
  "A05": {
   "title": "转介到服务",
   "urgent": "任何紧急或危险情况：请立即拨打 911。",
   "list": "现在开放，使用住户的语言",
   "choose": "告诉他们这个服务",
   "chosen": "告诉住户如何联系 {service}，或者帮他们写下来。",
   "neverText": "我们不会通过短信发送这些内容。",
   "recorded": "已记录为：{category}。不会保存其他任何内容。",
   "exNote": "演练：这是练习。您的选择只保存在演练记录中。",
   "forWho": "对象：{who}",
   "theirLang": "他们的语言",
   "all": "全部",
   "openNowIn": "现在开放并使用{lang}，或开放时间不详",
   "hoursUnknown": "开放时间不详。请先打电话。",
   "speaks": "说{lang}",
   "none": "现在没有使用{lang}提供这项帮助的开放地点。以下地点现在开放，使用其他语言：",
   "noneAtAll": "这里现在都没有开放。中心可以帮忙：{phone}。",
   "tellTitle": "告诉他们",
   "sayOr": "说给他们听，或者帮他们写下来。您也可以让他们看这个屏幕。",
   "again": "选择其他服务",
   "backRound": "返回我的巡查",
   "already": "已转介到服务：{category}。",
   "queued": "已保存在您的手机上。有信号时会发给中心。",
   "callLabel": "电话",
   "whereLabel": "地点",
   "hoursLabel": "今天"
  },
  "building": {
   "registerTitle": "来自市政府登记册",
   "updated": "最后更新于{date}",
   "registerLead": "多伦多市政府保存着一份公寓楼登记册。这些信息就来自这份登记册。",
   "checking": "中心正在核查这栋楼的信息。您在这里看到的内容可能会改变。",
   "facts": {
    "storeys": "层数",
    "elevators": "电梯",
    "emergencyPower": "应急电源",
    "coolingRoom": "降温室",
    "airConditioning": "空调",
    "barrierFree": "无障碍入口"
   },
   "airNone": "没有",
   "airIndividual": "各单元自备",
   "roles": {
    "superintendent": "大楼管理员",
    "buildingManagement": "楼宇管理处",
    "propertyOffice": "物业办公室"
   },
   "contactTitle": "楼宇联系人",
   "providedByHub": "由中心提供，最后更新于{date}"
  },
  "guides": {
   "reviewed": "已由中心审核，最后更新于{date}"
  }
 });
  /* AD-11 pilot change (2026-10-03): the label of a directory description a model translated and no person has reviewed. AI-generated (Claude), not yet checked by native readers. */
  m(t, { "x04": { "unreviewed": "机器翻译，未经人工审核" } });
  /* The resident map (S02.07): the "map" strings. AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "map": {
    "lead": "Thorncliffe Park 和 Flemingdon Park 的服务、机构和公寓楼。点击标记，查看它是什么。",
    "service": "服务或机构",
    "building": "公寓楼",
    "pinName": "{name}：{kind}",
    "noSignal": "没有信号时无法使用地图",
    "noSignalBody": "列表中有地图上的所有地点。",
    "notSaved": "地图的这一部分没有保存在您的手机上",
    "notSavedBody": "您在有信号时看过的地图部分会保留在手机上。标记和列表仍可使用。",
    "listTitle": "地图这一部分的地点",
    "listLead": "与地图显示的地点相同。移动或缩放地图即可改变此列表。",
    "listEmpty": "地图的这一部分没有内容。请移动或缩放地图，或显示整个区域。",
    "wholeArea": "显示整个区域",
    "buildings": "公寓楼",
    "buildingsCount": "{n} 栋楼",
    "buildingsCountOne": "1 栋楼",
    "filtered": "只显示与您在目录中所选筛选条件相符的地点。"
   }
  });
  /* S07.02: the web sign-up for text alerts and the confirmation text. YES, STOP, START and CVH stay in English. AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "signup": {
    "termsAgree": "我已阅读条款和隐私页面，并且同意。",
    "termsLink": "阅读条款和隐私页面",
    "termsVersion": "条款版本 {version}",
    "age": "我年满 16 岁，或有父母或监护人在帮我。",
    "missingTerms": "您对条款的同意",
    "missingAge": "年龄声明",
    "sending": "正在发送……",
    "onItsWay": "如果这个号码可以接收短信，一条短信正在发出。",
    "expect": "请在 48 小时内对这条短信回复 YES，即可开始接收警报。回复 YES 之前，您不会收到任何短信警报。",
    "howChange": "以后如要更改楼宇、楼层或语言，请对中心的任何一条短信回复 1 或 2。",
    "startHelp": "5 分钟内没有收到短信？请发送 START 到 {number}，然后重新登记。",
    "startHelpNoNumber": "5 分钟内没有收到短信？请向我们发短信的号码发送 START，然后重新登记。",
    "error": {
     "invalid_request": "表格中的某些内容无法读取。请重新加载页面后再试。",
     "phone_not_canadian": "请使用 10 位数字的加拿大电话号码，例如 416 555 0123。",
     "neighbourhood_missing": "请选择您的社区。",
     "terms_not_agreed": "如要登记，请同意条款。",
     "age_not_confirmed": "如要登记，请确认年龄声明。",
     "terms_changed": "在此页面打开期间，条款已更改。请重新阅读，然后同意。",
     "place_unknown": "您的某个楼宇或楼层已不在列表中。请检查您的楼宇后再试。",
     "rate_limited": "来自此连接的登记太多。请一小时后再试。",
     "signup_unavailable": "短信登记暂时无法使用。请稍后再试。",
     "network": "无法连接到 CVH。请检查网络连接后再试。"
    }
   }
  });
  m(t, {"smsTexts": {"confirmation": "回复 YES 接收 CVH 警报。回复 STOP 停止。"}});
  /* S07.04: the welcome, the replies of the inbound router and the words for yes (YES, STOP and CVH stay in English). */
  m(t, {"smsTexts": {"welcome": "您已订阅 CVH 警报。Hub 工作人员会审核每条消息，因此夜间可能不会发送警报。回复 1 更改楼宇或楼层，回复 2 更改语言，回复 3 撤回探望申请，回复 0 停止并删除订阅。回复 STOP 停止。", "alreadySignedUp": "您已订阅 CVH 警报。", "deletePrompt": "请在 10 分钟内再次回复 0 以删除订阅。之后您将不再收到短信。", "signupInfo": "如需通过短信接收 CVH 警报，请在此订阅：{link} 回复 STOP 停止。"}, "smsKeywords": {"yes": "是, 是的, 好"}});
  /* S07.05: the numbered text menus and their replies (see the English file for what each is and the one-text rule; 0, 1, 8, 9, 10, 5
     and {placeholders} stay as written). AI-generated (Claude), not yet checked by native readers. */
  m(t, {"smsTexts": {"menuStreet": "街道：", "menuBuilding": "楼宇：", "menuFloor": "楼层：", "menuWholeBuilding": "整栋楼", "menuLanguage": "语言：", "menuNav": "0 返回 9 Hub", "menuNavMore": "0 返回 8 更多 9 Hub", "menuWarn": "这将替换您已保存的 {n} 栋楼宇。1 继续，0 返回", "menuHub": "请致电 Hub：{hub}", "menuClosed": "菜单已关闭，未作任何更改。", "menuReset": "您的菜单因 10 分钟未回复已关闭，未作任何更改。", "menuLimit": "您今天的 5 次菜单已用完。请明天再试，或致电 Hub：{hub}", "menuLimitLink": "您今天的 5 次菜单已用完。回复 1 获取在线修改链接，或致电 Hub：{hub}", "buildingSaved": "已保存。您的楼宇现为 {building}，{floor} 层。", "buildingSavedWhole": "已保存。您的楼宇现为 {building}。", "languageSaved": "已保存。今后您将收到中文短信。", "noCheckinRequest": "您没有探望申请。", "checkinWithdrawn": "您的探望申请已撤回。"}});
  /* S07.06: the one-time web link's texts and its page (see the English file for what each is; menuClosedLink must fit one text; 0, 1, 30
     and {placeholders} stay as written; the error lines other than edit_unavailable are the sign-up's own). AI-generated (Claude), not yet
     checked by native readers. */
  m(t, {"smsTexts":{"menuClosedLink":"菜单已关闭，未作任何更改。回复 1 获取在线修改链接。","editLink":"在此更改或删除您的 CVH 短信警报： {link} 此链接仅可使用一次，有效期 30 分钟。","editSaved":"您的 CVH 警报选择已在网页上更改。不是您本人？请致电 Hub：{hub}"},"subscriptionEdit":{"title":"更改您的短信警报","loading":"正在打开您的选择……","forNumber":"尾号为 {digits} 的电话号码。","lead":"更改任何选择，然后保存。如要停止所有短信，请在本页末尾删除您的订阅。","topicsTitle":"您不想收到短信的主题","topicsLead":"勾选某个主题即可停止该主题的警报。有关火灾或疏散的警报始终会发送。","save":"保存我的更改","saving":"正在保存……","savedTitle":"您的更改已保存","savedBody":"确认短信正在发送。此链接现已使用：如需更改其他内容，请通过短信索取新链接。","deleteTitle":"删除我的订阅","deleteLead":"您将不再收到 CVH 的短信，与您号码有关的所有信息都会被删除。此操作无法撤销。","deleteSure":"现在删除您的订阅吗？您将不再收到 CVH 的短信。","deleteYes":"是，删除","deleteNo":"不，保留","deleting":"正在删除……","deletedTitle":"您的订阅已删除","deletedBody":"您将不再收到 CVH 的短信，系统不会保留与您号码有关的任何信息。不会发送短信确认此操作。","signUpAgain":"重新订阅","expiredTitle":"此链接已过期","expiredBody":"每个链接只能使用一次，发送后 30 分钟内有效。","expiredHow":"如需通过短信获取新链接，请向 CVH 的任意短信回复 1。如果回复的是菜单，请回复 0 关闭菜单。当回复提供链接时，请回复 1。","callHub":"或致电 Hub：{hub}","error":{"invalid_request":"表格中的某些内容无法读取。请重新加载页面后再试。","neighbourhood_missing":"请选择您的社区。","place_unknown":"您的某个楼宇或楼层已不在列表中。请检查您的楼宇后再试。","edit_unavailable":"现在无法更改，请稍后再试。","network":"无法连接到 CVH。请检查网络连接后再试。"}}});
  /* S08.05: the check-in request's texts and wording (see the English file for what each is; checkinMoved and checkinUncoveredNow must fit one
     text; 1, YES, CVH, Hub and {placeholders} stay as written). AI-generated (Claude), not yet checked by native readers. */
  m(t, {"smsTexts":{"checkinMoved":"您的楼层已更改，探望申请已撤回。回复 1 获取链接重新申请。","checkinUncoveredNow":"您的楼层目前没有楼层联络员。请致电 Hub：{hub}"},"signup":{"error":{"checkin_consent_missing":"如需申请探望，请勾选同意框。"}},"subscriptionEdit":{"error":{"checkin_consent_missing":"如需申请探望，请勾选同意框。"}},"checkin":{"consentMissing":"如需申请探望，请勾选同意框。","sees":"您所在楼层的联络员会看到您的电话号码和楼层，以便给您打电话或发短信。","isNot":"探望是一通电话或一条短信，问问您是否安好。它不是医疗护理，也不保证有人会立刻来。","howTitle":"如何申请","howNew":"您需要先订阅 CVH 短信提醒。订阅时在同一张表上申请探望。","howHelp":"在 CVH 活动或 Hub，工作人员或楼宇联络员可以帮您订阅。","howSubscribed":"已经收到 CVH 短信？请在更改选择的页面上申请探望。","noCoverage":"如果您的楼层还没有联络员，我们会立刻告诉您。您也可以致电 Hub：{hub}。","ask":"请我所在楼层的联络员来探望我","whereHint":"从上面的楼宇和楼层中选择您居住的地方。","agree":"我同意我所在楼层的联络员看到我的电话号码和楼层，并来探望我。","untilYes":"您回复我们的短信 YES 后，探望申请才开始。","uncovered":"您的楼层还没有联络员。请致电 Hub：{hub}。","withdraw":"撤回我的探望申请","withdrawNote":"保存后即撤回。您仍会收到提醒。","moved":"您的住处已更改，所以您的探望申请将被撤回。如要为新楼层重新申请，请选择该楼层并再次同意。","savedRequested":"您的探望申请已保存。","savedMethod":"探望方式已更改。"}});
  /* The last resident wording that showed in English: the home's alert list and its failures (R03, status.none), the ask screen's waiting and
     failure states (R09, R10.shownIn) and the directory (S02.06). AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "status": {
    "none": "没有当前问题"
   },
   "R03": {
    "currentAlerts": "当前警报",
    "noCurrentAlerts": "目前没有警报",
    "myBuildings": "您的楼宇",
    "checking": "正在检查警报",
    "feedFailed": "我们暂时无法检查警报。显示“不详”的地点可能仍有警报。我们会再试一次。",
    "feedFailedOld": "我们无法检查新警报。显示的是{t}最后加载的内容。"
   },
   "R09": {
    "searching": "正在搜索",
    "needsSignal": "搜索需要信号",
    "needsSignalBody": "您仍可以在下方选择一个主题，或打电话给中心。",
    "busy": "搜索繁忙，请几分钟后再试",
    "busyBody": "您可以在下方选择一个主题，或打电话给中心。",
    "updating": "搜索结果正在更新，请再试一次",
    "updatingBody": "更新期间，您可以在下方选择一个主题，或打电话给中心。",
    "browseAll": "查看所有服务和机构",
    "loading": "正在加载主题"
   },
   "R10": {
    "shownIn": "以{lang}显示"
   },
   "directory": {
    "title": "服务和机构",
    "lead": "中心在 Thorncliffe Park 和 Flemingdon Park 确认过的服务和机构。选择一个主题或社区来缩小列表范围。",
    "count": "{n} 项服务",
    "countOne": "1 项服务",
    "topic": "主题",
    "emergency": "在紧急情况下提供帮助",
    "emergencyRole": "紧急情况中的作用",
    "lastConfirmed": "中心最后确认于{date}",
    "lastUpdated": "最后更新于{time}",
    "loading": "正在加载目录",
    "couldNotLoad": "目录无法加载",
    "couldNotLoadBody": "中心可以通过电话帮您找到服务。",
    "couldNotLoadNumbers": "号码页面列出了您可能需要的其他号码。",
    "numbersLink": "查看重要电话号码",
    "backToList": "所有服务和机构",
    "suggestApply": "只显示{place}"
   }
  });
  /* Reading without signal (S02.12): the offline page and R-34's note. AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "offline": {
    "title": "此页面未保存在您的手机上",
    "body": "此页面还没有在这部手机上有信号时打开过，所以需要信号。电话号码始终保存在您的手机上。",
    "available": "以下内容没有信号时也能阅读",
    "none": "这部手机上还没有保存其他内容。有信号时打开的页面会保存下来，供以后阅读。"
   },
   "R34": {
    "offlineTitle": "没有信号时阅读",
    "offlineHelp": "有信号时打开的页面会保存在这部手机上，以后没有信号也能再次阅读。电话号码始终会保存。第一次打开 CVH 需要信号。",
    "offlineNote": "这部手机可能无法保存页面供离线使用"
   }
  });
  /* S08.02: an ambassador's post (A-02): the one screen's new words (an unsent post is held only in the open page's memory), and A03.states.ended. AI-generated, not yet checked by native readers. */
  m(t, {
   "A02": {
    "building": "哪栋楼？",
    "allFloorsLine": "全部 {n} 个楼层",
    "listLabel": "部分楼层",
    "listLine": "勾选每个楼层",
    "rangeLabel": "连续的几个楼层",
    "rangeLine": "从一个楼层到另一个楼层",
    "fromFloor": "从",
    "toFloor": "到",
    "chooseFloor": "选择",
    "phaseTitle": "目前情况",
    "phaseProblem": "出现了问题",
    "phaseProgress": "正在处理",
    "validTitle": "持续到什么时候？",
    "validResolved": "直到解决（从现在起 24 小时）",
    "validAt": "到某个日期和时间",
    "dateLabel": "日期",
    "timeLabel": "时间（多伦多时间）",
    "validHint": "最多 7 天之内。",
    "textLabel": "发生了什么（用英文写）",
    "textHint": "最多 {max} 个字符。居民会用自己的语言阅读；中心会先核查。",
    "inAlert": "这条更新会加入这条警报：{headline}",
    "typesFixed": "发生了什么：{types}",
    "unsent": "还没有发出。请保持此页面打开；有信号时会发出。",
    "unsentClose": "如果关闭此页面，这条更新就会丢失。",
    "sending": "正在发送给中心……",
    "errPhase": "请选择目前情况。",
    "errText": "请用英文说明发生了什么。",
    "errTextLong": "内容太长。最多使用 {max} 个字符。",
    "errValid": "请输入日期和时间。",
    "errValidPast": "这个时间已经过去。请选择更晚的时间。",
    "errValidFar": "请选择 7 天之内的时间。",
    "errValidSkipped": "那天晚上要调整时钟，所以这个时间不明确。请选择其他时间。",
    "errRange": "第一个楼层比最后一个楼层高。请把较低的楼层放在前面。",
    "errNotAssigned": "您现在没有被分配到这栋楼，所以不能为它发布。",
    "errClosed": "这条警报已经结束。请改为发布一条新的更新。",
    "errSignedOut": "您已被登出，所以这条没有发出。请重新登录，然后再发布一次。",
    "errFailed": "这条没有发出。请再试一次。如果一直这样，请打电话给中心。"
   },
   "A03": {
    "states": {
     "ended": "未发送：中心核查前警报已结束"
    }
   }
  });
  /* S09.07: the end-of-pilot re-consent texts (the campaign text with {date}, the confirmation after YES, the answer after the deadline, the answer
     while sign-ups are paused) and the sign-up form's refusal while sign-ups are paused. YES and CVH stay in English. Each text fits one text message
     with the longest date. smsDate is how a text writes the deadline (the month names, the order of day and month, the numerals), fixed here
     from CLDR 47 so the frozen text is the same on every runtime. AI-generated (Claude), not yet checked by native readers: the texts and the
     date words are reviewed before launch (Launch Readiness). */
  m(t, {"smsDate": {"months":["1","2","3","4","5","6","7","8","9","10","11","12"],"dayMonth":"{month}月{day}日","digits":"0123456789"}, "smsTexts": {"reconsent": "CVH试点即将结束。如需继续接收提醒，请回复YES。如在{date}前未回复，您的号码将被删除。", "reconsentKept": "谢谢。您将继续收到CVH提醒。", "pilotEnded": "CVH试点已结束；您的号码未被保留。", "signupsPaused": "试点结束期间，CVH短信登记已暂停。"}, "signup": {"error": {"signups_paused": "试点结束期间，登记已暂停。"}}});
})();
