/* Gujarati string table. Phase 1: shell and shared components. AI-generated; to be checked by native readers. */
window.CVH_STRINGS = window.CVH_STRINGS || {};
window.CVH_STRINGS.gu = {
 meta: { code: 'gu', name: 'ગુજરાતી', aiNote: 'આ પ્રોટોટાઇપનું બધું લખાણ AI થી બનેલું છે. CVH શરૂ થાય તે પહેલાં લોકો તેને તપાસશે.' },
 time: { justNow: 'હમણાં જ', ago: '{t} પહેલાં', join: ' ', second: '1 સેકન્ડ', seconds: '{n} સેકન્ડ', minute: '1 મિનિટ', minutes: '{n} મિનિટ', hour: '1 કલાક', hours: '{n} કલાક', day: '1 દિવસ', days: '{n} દિવસ', today: 'આજે', tomorrow: 'આવતીકાલે', until: '{t} સુધી', closed: 'બંધ',
   days7: { mon: 'સોમવાર', tue: 'મંગળવાર', wed: 'બુધવાર', thu: 'ગુરુવાર', fri: 'શુક્રવાર', sat: 'શનિવાર', sun: 'રવિવાર' } },
 shell: { cvhName: 'કોમ્યુનિટી વર્ચ્યુઅલ હબ', prototype: 'પ્રોટોટાઇપ', prototypeNote: 'આ સાચી સેવા નથી. બધી સામગ્રી AI થી બનેલી છે.',
   language: 'ભાષા', changeLanguage: 'ભાષા બદલો', languageTitle: 'તમારી ભાષા પસંદ કરો', languageCurrent: 'હમણાં બતાવાય છે', languageReturn: 'તમે જ્યાં હતા ત્યાં જ સ્ક્રીન રહેશે.',
   choices: 'મેં CVH ને શું કહ્યું છે', choicesShort: 'મારી પસંદગીઓ', nav: { now: 'ચેતવણીઓ', help: 'મદદ શોધો', map: 'નકશો', ready: 'તૈયાર રહો' }, navLabel: 'મુખ્ય',
   close: 'બંધ કરો', back: 'પાછા', next: 'આગળ વધો', skip: 'છોડી દો', done: 'થઈ ગયું', cancel: 'રદ કરો', more: 'વધુ',
   notInPrototype: 'આ પ્રોટોટાઇપમાં નથી', notInPrototypeBody: 'આ ભાગ પ્રોટોટાઇપમાં બન્યો નથી. કંઈ બદલાયું નથી.', ok: 'બરાબર',
   about: 'CVH વિશે', aboutBody: 'કોમ્યુનિટી વર્ચ્યુઅલ હબ Thorncliffe Park Community Hub, થોર્નક્લિફ પાર્ક અને ફ્લેમિંગ્ડન પાર્ક માટે ચલાવે છે.', builtBy: 'Sprout Climate સાથે બનાવેલું',
   rules: 'આ જગ્યાના નિયમો', ambassador: 'એમ્બેસેડર', offline: 'તમે ઑફલાઇન છો. {t} લોડ થયેલી સામગ્રી બતાવાય છે.', aiLabel: 'પ્રોટોટાઇપ માટે AI થી બનેલું', illustrative: 'માત્ર ઉદાહરણ' },
 x01: { text: 'CVH કટોકટી સેવા નથી.', call: 'જો કોઈ જોખમમાં હોય, તો 911 પર ફોન કરો.', short: 'કટોકટી સેવા નથી. જોખમ? 911 પર ફોન કરો.',
   sms: 'હબ કટોકટી સેવા નથી. જો કોઈ જોખમમાં હોય, તો 911 પર ફોન કરો.', print: 'આ કટોકટી સેવા નથી. જો કોઈ જોખમમાં હોય, તો 911 પર ફોન કરો.' },
 x02: { official: '{source} તરફથી સત્તાવાર ચેતવણી', community: '{author} તરફથી સમુદાય ચેતવણી', verifiedBy: '{org} એ ચકાસ્યું', notYetVerified: 'હજી ચકાસાયું નથી',
   corrected: '{t} સુધાર્યું', whatMeans: 'આનો અર્થ', hub: 'હબ', theHub: 'હબ', ambassador: 'બિલ્ડિંગ એમ્બેસેડર, {building}', postedBy: '{author} એ પોસ્ટ કર્યું',
   levelOfficial: 'સત્તાવાર ચેતવણી', levelCommunity: 'સમુદાય ચેતવણી', sources: { ECCC: 'એન્વાયર્નમેન્ટ એન્ડ ક્લાઇમેટ ચેન્જ કેનેડા', CITY: 'ટોરોન્ટો શહેર', ALERTREADY: 'એલર્ટ રેડી' } },
 x03: { title: 'આ જગ્યાના નિયમો', intro: 'CVH પડોશીઓ એકબીજાને મદદ કરે તે માટે છે. કંઈ ઉમેરતા પહેલાં આ વાંચો.',
   rules: ['મફત કે ઓછી કિંમતની અને સૌ માટે ખુલ્લી જગ્યાઓ અને મદદ શેર કરો.', 'જગ્યા વિશે લખો, વ્યક્તિ વિશે નહીં. કોઈનું નામ, યુનિટ નંબર કે ફોન નંબર ન આપો.',
     'દયાળુ રહો. કોઈ જૂથનું અપમાન કે નિશાન બનાવવું નહીં.', 'તમે સાચું જાણો છો એ જ શેર કરો. ખાતરી ન હોય તો "ખાતરી નથી" પસંદ કરો.'],
   market: 'CVH બજાર નથી. ન વેચાણ, ન જાહેરાત.', review: 'નકશા પર આવે તે પહેલાં હબની કોઈ વ્યક્તિ બધું વાંચે છે.', agree: 'હું સમજી ગયો', readMore: 'નિયમો વાંચો' },
 x04: { label: 'મશીન અનુવાદ', from: '{lang} માંથી', report: 'અનુવાદની સમસ્યા જણાવો', reportTitle: 'આ અનુવાદમાં શું ખોટું છે?',
   reasons: { meaning: 'અર્થ ખોટો છે', words: 'કેટલાક શબ્દો ખોટા છે', unclear: 'સમજવું મુશ્કેલ છે' }, send: 'મોકલો', reported: 'આભાર. હબની કોઈ વ્યક્તિ આ અનુવાદ તપાસશે.',
   unavailable: 'આ ભાષામાં હજી ઉપલબ્ધ નથી', unavailableBody: 'આનો હજી {lang} માં અનુવાદ થયો નથી.', showSource: '{lang} માં વાંચો', original: 'મૂળ ({lang})' },
 x07: { label: 'મોટા અક્ષર, ઓછી વસ્તુઓ', on: 'ચાલુ', off: 'બંધ', setByHelper: 'તમને મદદ કરનારે ચાલુ કર્યું', remembered: 'આ ઉપકરણ પર યાદ રખાયું', turnOn: 'ચાલુ કરો', turnOff: 'બંધ કરો' },
 x08: { idle: 'સાંભળો · {t}', loading: 'ઑડિયો લોડ થાય છે', playing: 'ચાલે છે', paused: 'થોભાવ્યું', left: '{t} બાકી',
   failed: 'આ કનેક્શન પર ઑડિયો લોડ ન થયો. તેમાં જે છે તે બધું અહીં લખેલું છે.', retry: 'ફરી પ્રયત્ન કરો', play: 'ચલાવો', pause: 'થોભાવો', section: 'આ ભાગ સાંભળો · {t}' },
 x09: { open: 'ખુલ્લું', full: 'ભરેલું', closed: 'બંધ', unconfirmed: 'પુષ્ટિ નથી',
   purpose: { cooling: 'ઠંડક માટે', cleanAir: 'સ્વચ્છ હવા માટે', warming: 'ગરમી માટે', charging: 'ફોન ચાર્જ કરવા' },
   confirmed: '{t} પુષ્ટિ થઈ', unconfirmedNote: '{t} થી પુષ્ટિ નથી. કદાચ ખુલ્લું ન હોય. જતાં પહેલાં ફોન કરો.', hoursToday: 'આજે {from} થી {to}', closedToday: 'આજે બંધ',
   water: 'પીવાનું પાણી', seating: 'બેસવાની જગ્યા', charging: 'ફોન ચાર્જિંગ', washrooms: 'શૌચાલય', stepFree: 'પગથિયાં વગર', notStepFree: 'પગથિયાં છે', noId: 'ઓળખપત્ર માંગતા નથી', idAsked: 'ઓળખપત્ર માંગે છે',
   runBy: '{org} ચલાવે છે', yes: 'હા', no: 'ના', unknown: 'ખબર નથી' },
 x10: { word: 'કવાયત', running: 'કવાયત. આ માત્ર પ્રેક્ટિસ છે.', runningSub: 'અહીંથી રહેવાસીઓને કંઈ મોકલાતું નથી.', ended: 'કવાયત પૂરી', sms: 'કવાયત. માત્ર પ્રેક્ટિસ.' },
 x11: { title: 'ફિલ્ટર ચાલુ છે', remove: 'ફિલ્ટર દૂર કરો: {f}', hiding: 'આ ફિલ્ટરથી {n} જગ્યાઓ છુપાયેલી છે', hidingOne: 'આ ફિલ્ટરથી 1 જગ્યા છુપાયેલી છે',
   fromChoices: 'કેટલાક ફિલ્ટર તમારી પસંદગીઓમાંથી છે', clear: 'બધા ફિલ્ટર દૂર કરો', none: 'કોઈ ફિલ્ટર નથી' },
 x12: { title: 'તમારા માટે આનો અર્થ', fromHub: 'હબની સલાહ', tailoredLink: 'તમારી પસંદગી મુજબ', standard: 'બધાને મળે તે સંસ્કરણ બતાવો',
   standardShown: 'તમે બધાને મળે તે સંસ્કરણ જુઓ છો.', showMine: 'મારા માટે આનો અર્થ બતાવો', checkin: 'તમારા માળના એમ્બેસેડર આજે તમારી ખબર પૂછશે.',
   noCheckin: 'તમારા માળ પર હજી એમ્બેસેડર નથી, તેથી અમે ખબર પૂછી શકતા નથી. હબને {phone} પર ફોન કરો. અમે {hours} ખુલ્લા છીએ.',
   hubHours: 'સોમથી ગુરુ સવારે 9 થી રાતે 8, શુક્ર સવારે 9 થી સાંજે 5, શનિ સવારે 10 થી બપોરે 2', listen: 'સાંભળો · {t}' },
 x13: { fire: 'આગ', power: 'વીજળી', water: 'પાણી', elevator: 'લિફ્ટ', flood: 'પૂર અથવા લીકેજ', heat: 'ગરમી', smoke: 'ધુમાડો', winter: 'બરફનું તોફાન', other: 'અન્ય', fireAlarm: 'ફાયર એલાર્મ અથવા સ્થળાંતર', waterPlumbing: 'પાણી અથવા પ્લમ્બિંગ' },
 x14: { label: 'તેઓ કેવી રીતે મદદ કરી શકે' },
 status: { active: 'સક્રિય સમસ્યા', progress: 'કામ ચાલુ છે', resolved: 'ઉકેલાયું', unknown: 'ખબર નથી' },
 R02: { title: 'તમારી ભાષા પસંદ કરો', changed: 'હવે {lang} માં બતાવાય છે.' }
};
