/* Mandarin (Simplified Chinese) string table. Written form open (brief O3). Phase 1: shell and shared components. AI-generated; to be checked by native readers. */
window.CVH_STRINGS = window.CVH_STRINGS || {};
window.CVH_STRINGS.zh = {
 meta: { code: 'zh', name: '中文（普通话）', aiNote: '本原型的所有文字均由人工智能生成。CVH 上线前将由人工审核。' },
 time: { justNow: '刚刚', ago: '{t}前', join: '', second: '1秒', seconds: '{n}秒', minute: '1分钟', minutes: '{n}分钟', hour: '1小时', hours: '{n}小时', day: '1天', days: '{n}天', today: '今天', tomorrow: '明天', until: '到{t}', closed: '关闭',
   days7: { mon: '星期一', tue: '星期二', wed: '星期三', thu: '星期四', fri: '星期五', sat: '星期六', sun: '星期日' } },
 shell: { cvhName: '社区虚拟中心', prototype: '原型', prototypeNote: '这不是正式服务。所有内容均由人工智能生成。',
   language: '语言', changeLanguage: '更改语言', languageTitle: '选择您的语言', languageCurrent: '当前显示', languageReturn: '屏幕会停留在您原来的位置。',
   choices: '我告诉过 CVH 的信息', choicesShort: '我的选择', nav: { now: '警报', help: '寻求帮助', map: '地图', ready: '做好准备' }, navLabel: '主菜单',
   close: '关闭', back: '返回', next: '继续', skip: '跳过', done: '完成', cancel: '取消', more: '更多',
   notInPrototype: '本原型中没有', notInPrototypeBody: '这一部分尚未在原型中制作。没有任何更改。', ok: '好的',
   about: '关于 CVH', aboutBody: '社区虚拟中心由 Thorncliffe Park Community Hub 为 Thorncliffe Park 和 Flemingdon Park 运营。', builtBy: '与 Sprout Climate 合作打造',
   rules: '本空间的规则', ambassador: '楼层联络员', offline: '您已离线。显示{t}加载的内容。', aiLabel: '为原型由人工智能生成', illustrative: '示例' },
 x01: { text: 'CVH 不是紧急服务。', call: '如有人身处危险，请拨打 911。', short: '不是紧急服务。遇到危险？请拨打 911。',
   sms: '本中心不是紧急服务。如有人身处危险，请拨打 911。', print: '这不是紧急服务。如有人身处危险，请拨打 911。' },
 x02: { official: '来自{source}的官方警报', community: '来自{author}的社区警报', verifiedBy: '已由{org}核实', notYetVerified: '尚未核实',
   corrected: '{t}已更正', whatMeans: '这是什么意思', hub: '中心', theHub: '中心', ambassador: '楼宇联络员，{building}', postedBy: '由{author}发布',
   levelOfficial: '官方警报', levelCommunity: '社区警报', sources: { ECCC: '加拿大环境与气候变化部', CITY: '多伦多市政府', ALERTREADY: 'Alert Ready' } },
 x03: { title: '本空间的规则', intro: 'CVH 是邻居互相帮助的地方。添加内容前请先阅读。',
   rules: ['分享免费或低价、向社区开放的地点和帮助。', '写地点，不写个人。不要分享任何人的姓名、单元号或电话号码。',
     '友善待人。不得侮辱或针对任何群体。', '只分享您确定真实的信息。不确定时，请选择"不确定"。'],
   market: 'CVH 不是市场。禁止买卖，禁止广告。', review: '内容上地图之前，中心的工作人员会先阅读。', agree: '我明白了', readMore: '阅读规则' },
 x04: { label: '机器翻译', from: '译自{lang}', report: '报告翻译问题', reportTitle: '这段翻译有什么问题？',
   reasons: { meaning: '意思不对', words: '有些词不对', unclear: '很难理解' }, send: '发送', reported: '谢谢。中心的工作人员会检查这段翻译。',
   unavailable: '暂无此语言版本', unavailableBody: '此内容尚未翻译成{lang}。', showSource: '用{lang}阅读', original: '原文（{lang}）' },
 x07: { label: '字体更大，内容更少', on: '开', off: '关', setByHelper: '由帮助您的人开启', remembered: '已在此设备上记住', turnOn: '开启', turnOff: '关闭' },
 x08: { idle: '收听 · {t}', loading: '正在加载音频', playing: '正在播放', paused: '已暂停', left: '剩余{t}',
   failed: '在当前网络下音频无法加载。音频内容已全部写在这里。', retry: '重试', play: '播放', pause: '暂停', section: '收听本节 · {t}' },
 x09: { open: '开放', full: '已满', closed: '关闭', unconfirmed: '未确认',
   purpose: { cooling: '用于避暑降温', cleanAir: '用于清洁空气', warming: '用于取暖', charging: '用于设备充电' },
   confirmed: '{t}已确认', unconfirmedNote: '已有{t}未确认。可能没有开放。去之前请先打电话。', hoursToday: '今天 {from} 至 {to}', closedToday: '今天关闭',
   water: '饮用水', seating: '座位', charging: '手机充电', washrooms: '洗手间', stepFree: '无台阶', notStepFree: '有台阶', noId: '不要求身份证件', idAsked: '要求身份证件',
   runBy: '由{org}运营', yes: '是', no: '否', unknown: '不详' },
 x10: { word: '演练', running: '演练。这只是练习。', runningSub: '不会向居民发送任何内容。', ended: '演练结束', sms: '演练。仅为练习。' },
 x11: { title: '已应用筛选', remove: '移除筛选：{f}', hiding: '这些筛选隐藏了 {n} 个地点', hidingOne: '这些筛选隐藏了 1 个地点',
   fromChoices: '部分筛选来自您的选择', clear: '移除所有筛选', none: '没有筛选' },
 x12: { title: '这对您意味着什么', fromHub: '中心的建议', tailoredLink: '根据您的选择定制', standard: '显示所有人收到的版本',
   standardShown: '您正在查看所有人收到的版本。', showMine: '显示对我意味着什么', checkin: '您所在楼层的联络员今天会来探望您。',
   noCheckin: '您的楼层还没有联络员，所以我们无法探望您。请拨打 {phone} 联系中心。我们的开放时间是{hours}。',
   hubHours: '周一至周四上午9点至晚上8点，周五上午9点至下午5点，周六上午10点至下午2点', listen: '收听 · {t}' },
 x13: { fire: '火灾', power: '停电', water: '停水', elevator: '电梯', flood: '水浸或漏水', heat: '高温', smoke: '烟雾', winter: '冬季风暴', other: '其他', fireAlarm: '火警或疏散', waterPlumbing: '水或管道' },
 x14: { label: '他们能提供的帮助' },
 status: { active: '当前问题', progress: '正在处理', resolved: '已解决', unknown: '不详' },
 R02: { title: '选择您的语言', changed: '现在显示：{lang}。' }
};
