/* Spanish strings for the resident and ambassador screens, merged into the Spanish table by
   screen ID. AI-generated (Claude), not yet checked by native readers. Staff screens stay in English. */
(function () {
  var t = window.CVH_STRINGS.es;
  function m(t, s) { for (var k in s) { if (!Object.prototype.hasOwnProperty.call(s, k) || k === "__proto__" || k === "constructor" || k === "prototype") continue; if (s[k] && typeof s[k] === "object" && !Array.isArray(s[k]) && t[k] && typeof t[k] === "object" && !Array.isArray(t[k])) m(t[k], s[k]); else t[k] = s[k]; } }
  /* Production UAT (2026-10-08): the display settings (Aa), the alert-state words (an alert or entry the Hub withdrew, the note on
     an alert read from a kept copy whose time has passed, the archive's older alerts), the share screen's copy and WhatsApp words, and
     the footer's two links. AI-generated (Claude), not yet checked by native readers. The alert-state words (R07, R08) tell a resident
     not to act on an alert: they wait for native review on the launch checklist (Launch Readiness). */
  m(t, {
    "display": {"title": "Ajustes de pantalla", "close": "Listo", "textSize": "Tamaño del texto", "standard": "Normal", "large": "Grande", "simpler": "Vista más sencilla", "help": "Muestra menos detalles y usa listas en lugar del mapa. El tamaño del texto no cambia.", "saved": "Guardado en este dispositivo.", "sessionOnly": "Su navegador no puede guardar este ajuste. Solo durará esta visita."},
    "R07": {"withdrawn": "Retirada", "mayHaveEnded": "Es posible que esta alerta haya terminado. Vuelva a revisar cuando tenga señal"},
    "R08": {"withdrawn": "Retirada {t}", "more": "Mostrar alertas anteriores", "moreFailed": "No pudimos cargar las alertas anteriores. Revise que tenga señal e inténtelo de nuevo."},
    "R29": {"copy": "Copiar el mensaje", "copied": "Copiado. Puede pegarlo en cualquier aplicación.", "copyFailed": "Su teléfono no lo copió. Mantenga presionado el mensaje de arriba para copiarlo.", "whatsapp": "Enviar por WhatsApp", "noSheet": "Su teléfono no ofrece opciones para compartir aquí. Copie el mensaje o envíelo por WhatsApp."},
    "shell": {"staffSignIn": "Acceso del personal", "termsLink": "Términos y privacidad"}
  });
  m(t, {
  "terms": {
   "version": "Versión",
   "owner": "Responsable",
   "updated": "Última actualización",
   "privacyContact": "Contacto de privacidad",
   "draftTitle": "Borrador: aún no publicado",
   "draftBody": "Este texto aún no se ha aprobado. No son los términos finales. No se inscriba basándose en él.",
   "draftWhy": "No se publicó porque:",
   "translationNote": "Parte de esta página aún no se ha traducido al {lang}. Esas partes se muestran en inglés.",
   /* S09.08: the day the pilot's resident data was deleted, shown once the end-of-pilot purge has completed. AI-generated (Claude), not yet checked by native readers. */
   "dataDeleted": "Datos de residentes borrados",
   "dataDeletedNote": "El proyecto piloto CVH terminó. En esa fecha borramos el número de teléfono y las opciones de todas las personas que no respondieron YES para seguir recibiendo alertas."
  },
  "shell": {
   "hubName": "Thorncliffe Park Community Hub",
   "hubLogoAlt": "Thorncliffe Park Community Hub",
   "pageNotFound": "No se encontró esta página.",
   "pageNotFoundBody": "Puede que el enlace sea antiguo o esté mal escrito. Use el menú de abajo para seguir."
  },
  "x01": {
   "partner": "Este espacio no llama al 911 por nadie. Si alguien está en peligro, llame usted al 911. No suponga que otra organización ya lo hizo."
  },
  "x05": {
   "title": "Reciba alertas y ayuda en su idioma",
   "lead": "El Centro Virtual Comunitario le avisa cuando pasa algo en su edificio y le ayuda a encontrar servicios cerca de usted.",
   "steps": ["Abra el enlace o escanee el código con su teléfono.", "Elija su idioma.", "No necesita una cuenta ni una aplicación."],
   "link": "Enlace corto",
   "scan": "Escanee con la cámara de su teléfono",
   "building": "Edificio",
   "floor": "Piso",
   "writeIn": "Lo escribe a mano su embajador",
   "text": "¿No tiene teléfono inteligente? Pida al embajador de su piso que le ayude a recibir alertas por mensaje de texto.",
   "from": "De Thorncliffe Park Community Hub",
   "sampleLink": "Enlace de ejemplo, no está activo"
  },
  "x06": {
   "doing": "Nosotros hacemos esto",
   "canTake": "Podemos encargarnos de esto",
   "cannotCover": "No podemos cubrir esto",
   "need": "Necesitamos esto",
   "claimed": "Se encarga {org}",
   "supply": "Suministro: {item}",
   "recordDecision": "Registrar como decisión"
  },
  "groups": {
   "seniors": {
    "label": "Personas mayores",
    "line": "Avisos de calor y servicios para residentes mayores, y consejos para usted en cada alerta."
   },
   "newcomers": {
    "label": "Recién llegados",
    "line": "Servicios que no preguntan por su estatus migratorio, y consejos para usted en cada alerta."
   },
   "families": {
    "label": "Familias con niños pequeños",
    "line": "Alertas y consejos sobre bebés y niños pequeños, y servicios para familias."
   },
   "checkin": {
    "label": "Quiero un chequeo de bienestar durante el calor y los cortes",
    "line": "El embajador de su piso pasa a ver cómo está cuando hay un aviso de calor o un corte de luz."
   }
  },
  "categories": {
   "food": "Alimentos",
   "housing": "Vivienda y alquiler",
   "health": "Salud",
   "money": "Dinero y beneficios",
   "settlement": "Inmigración y asentamiento",
   "jobs": "Empleo y capacitación",
   "children": "Niños y jóvenes",
   "seniors": "Personas mayores",
   "legal": "Ayuda legal",
   "mentalHealth": "Salud mental"
  },
  "filters": {
   "openNow": "¿Está abierto ahora mismo?",
   "nbhd": "¿Qué barrio?",
   "language": "¿Hablan mi idioma?",
   "cost": "¿Cuánto cuesta?",
   "noId": "¿Piden identificación o estatus migratorio?",
   "stepFree": "¿Puedo entrar sin escalones?",
   "noAppointment": "¿Necesito una cita?",
   "short": {
    "openNow": "Abierto ahora",
    "nbhdTP": "Thorncliffe Park",
    "nbhdFP": "Flemingdon Park",
    "language": "Hablan {lang}",
    "free": "Gratis",
    "lowCost": "Gratis o de bajo costo",
    "noId": "No pide identificación",
    "stepFree": "Sin escalones",
    "noAppointment": "No necesita cita"
   },
   "answers": {
    "yes": "Sí",
    "no": "No",
    "any": "Cualquiera",
    "free": "Solo gratis",
    "lowCost": "Gratis o de bajo costo",
    "noIdOnly": "Solo lugares que no piden",
    "stepFreeOnly": "Solo lugares sin escalones",
    "walkIn": "Solo sin cita"
   }
  },
  "utilities": {
   "ac": "Aire acondicionado",
   "wifi": "Wi-Fi",
   "charging": "Carga de dispositivos",
   "washrooms": "Baños",
   "water": "Agua potable",
   "food": "Alimentos",
   "kit": "Hay kits de preparación aquí",
   "space": "Abierto ahora como espacio"
  },
  "orgKinds": {
   "grassroots": "Grupo de base",
   "nonprofit": "Sin fines de lucro",
   "faith": "Organización religiosa",
   "public": "Servicio público",
   "business": "Negocio",
   "communityOffer": "Oferta comunitaria"
  },
  "neighbourhoods": {
   "TP": "Thorncliffe Park",
   "FP": "Flemingdon Park"
  },
  "subcats": {
   "Police Station": "Estación de policía",
   "Fire Station": "Estación de bomberos",
   "Food Collaboratives": "Bancos de alimentos y programas de alimentos",
   "Shelter": "Refugios",
   "Faith-Based Organizations": "Comunidades religiosas",
   "Legal Services": "Servicios legales",
   "Government Documentation": "Documentos del gobierno",
   "Schools": "Escuelas",
   "Childminding & EarlyON": "Cuidado de niños y EarlyON",
   "Dental Clinics": "Clínicas dentales",
   "Midwives Clinic": "Parteras",
   "Health Clinics": "Clínicas de salud",
   "Non-Profits": "Organizaciones comunitarias",
   "Community Centres": "Centros comunitarios",
   "Public Washrooms": "Baños públicos",
   "Libraries": "Bibliotecas",
   "Water Fountains": "Agua potable",
   "Museums": "Museos",
   "Cooling Spaces": "Espacios para refrescarse",
   "Multi-Service Agencies": "Agencias de servicios múltiples",
   "Food Security & Climate Resilience": "Grupos de alimentos y clima",
   "Employment & Skills Training": "Empleo y habilidades",
   "Family & Parenting Support": "Familia y crianza",
   "Social & Cultural Organizations": "Grupos sociales y culturales",
   "Newcomer Supports": "Apoyo a recién llegados",
   "Housing & Tenant Supports": "Vivienda e inquilinos",
   "Neighbourhood & Individual Empowerment": "Grupos del barrio"
  },
  "hazards": {
   "power": "Corte de luz",
   "flood": "Inundación o falla de plomería",
   "elevator": "Falla del ascensor",
   "heat": "Calor extremo",
   "smoke": "Humo de incendios forestales",
   "fire": "Incendio y evacuación"
  },
  "stages": {
   "before": "Antes",
   "during": "Durante",
   "after": "Después"
  },
  "R01": {
   "title": "Elija su idioma",
   "preselected": "Elegido según su aviso",
   "selected": "Seleccionado",
   "continue": "Continuar",
   "helperBasic": "¿Ayuda a alguien? Active letra más grande, menos cosas para esa persona.",
   "forwardedNote": "Alguien compartió una alerta con usted. Primero elija su idioma.",
   "fromPhone": "Según el idioma de su teléfono",
   "chooseFirst": "Toque un idioma para continuar.",
   "youChose": "Su idioma:",
   "helperOn": "Letra más grande, menos cosas está activado. Se queda activado para esa persona."
  },
  "R02": {
   "current": "Se muestra ahora",
   "unavailable": "Aún no disponible en este idioma",
   "unavailableBody": "Algunas cosas de esta pantalla aún no se han traducido al {lang}. Lo diremos en cada lugar donde pase.",
   "continueIn": "Continuar en {lang}",
   "chooseOther": "Elegir otro idioma"
  },
  "R03": {
   "getTextAlerts": "Recibir alertas por mensaje de texto",
   "getTextAlertsLine": "Alertas para su edificio por mensaje de texto. Sin aplicación, sin cuenta.",
   "signedUp": "Alertas por texto activadas",
   "sent": "Responda YES en su teléfono para empezar a recibir alertas por texto",
   "alertsNow": "Alertas ahora",
   "myBuilding": "Su edificio",
   "myFloor": "Su piso",
   "nothingActive": "No está pasando nada ahora mismo.",
   "nothingActiveBody": "Cuando algo afecte a su edificio o a su barrio, aparecerá aquí primero.",
   "noBuildingChosen": "Elija su edificio para ver primero sus alertas",
   "ongoing": "En curso",
   "updated": "Actualizado {t}",
   "posted": "Publicado {t}",
   "everyday": "Todos los días",
   "findHelp": "Buscar ayuda",
   "map": "Mapa",
   "beReady": "Prepararse",
   "findHelpLine": "Servicios y apoyo cerca de usted",
   "mapLine": "Lugares cerca de usted y qué está abierto ahora",
   "beReadyLine": "Guías, números y chequeos de bienestar",
   "archive": "Alertas que terminaron",
   "basicTurnOn": "Letra más grande, menos cosas",
   "headsUpTitle": "Antes del calor",
   "headsUpFrom": "Un aviso previo que usted eligió",
   "headsUpGuide": "Leer la guía sobre el calor",
   "headsUpEvent": "Taller cerca de usted",
   "ongoingDay": "En curso: día {n} de {total}",
   "readAlert": "Leer la alerta",
   "neighbourhoods": "Thorncliffe Park y Flemingdon Park",
   "headsUpAction": "Una cosa que hacer ahora",
   "ambassadorHome": "Embajador: mi edificio",
   "ambassadorLine": "Publique una novedad o haga su ronda en {building}",
   "noBuildingLine": "Aquí aparecen las alertas de su barrio. Añada su edificio para ver primero sus alertas."
  },
  "R04": {
   "deviceLabel": "Mensaje de texto en un teléfono básico",
   "from": "Thorncliffe Hub",
   "fromNumber": "Alertas del CVH",
   "lockScreen": "Pantalla de bloqueo",
   "now": "ahora",
   "levelOfficial": "Alerta oficial de {source}.",
   "levelCommunity": "Alerta comunitaria del Hub. Verificada por el Hub.",
   "fromHub": "Alerta comunitaria del Hub",
   "levelAmbassador": "Alerta comunitaria de un embajador del edificio. Aún no verificada.",
   "stop": "Para dejar de recibir todos los mensajes del Hub, responda STOP.",
   "verifiedKeyword": "Para saber qué significa verificado, responda INFO.",
   "ackMore": "Pronto habrá más información.",
   "update": "Novedad sobre la alerta \"{headline}\":",
   "correction": "Corrección de la alerta \"{headline}\": {changed}",
   "resolved": "Resuelto: \"{headline}\". {final}",
   "nearestSpace": "Espacio abierto más cercano: {space}, {hours}.",
   "confirmRequest": "Thorncliffe Park Community Hub: alguien pidió alertas por texto para este teléfono, en {lang}, para {where}. Para aceptar, responda YES. Para dejar de recibir todos los mensajes del Hub, responda STOP.",
   "keywordChange": "Responda GROUPS para cambiar los grupos que eligió.",
   "checkinWithdraw": "Responda NOCHECK para dejar de recibir chequeos de bienestar.",
   "link": "Más: {url}",
   "sampleLabel": "Mensaje de ejemplo. No se envía nada.",
   "tapOpen": "Toque el mensaje para abrirlo",
   "back": "Volver a la aplicación",
   "annotOn": "Qué líneas están traducidas",
   "annotOff": "Ocultar notas de traducción",
   "bigOn": "Letra lo más grande posible",
   "bigOff": "Letra normal",
   "tagTemplate": "Plantilla revisada",
   "tagAlert": "Escrito para esta alerta",
   "annotNote": "La fase 2 está dibujada en inglés. Las líneas marcadas \"Plantilla revisada\" existen en los quince idiomas del lanzamiento, revisadas por personas. Las líneas marcadas \"Escrito para esta alerta\" se traducen para cada alerta; las versiones en urdu y griego aún no están en este prototipo.",
   "officialNote": "Las alertas oficiales salen de una plantilla revisada por personas en cada idioma. La alerta comunitaria que sigue dice lo que añade aquí.",
   "notKnownPrefix": "Aún no se sabe: {what}.",
   "you": "Usted",
   "exNote": "Simulacro. Solo las personas inscritas en el simulacro reciben este mensaje. Los residentes no reciben nada."
  },
  "R05": {
   "title": "Recibir alertas por mensaje de texto",
   "lead": "Enviamos un mensaje de texto cuando pasa algo en su edificio o su barrio. Sin aplicación, sin cuenta, sin correo electrónico.",
   "required": "Obligatorio",
   "optional": "Opcional",
   "phone": "Número de teléfono",
   "phoneHelp": "Puede escribirlo como quiera.",
   "phoneShown": "Enviaremos mensajes al {phone}",
   "phoneError": "Este número necesita 10 dígitos, como 416 555 0123.",
   "nbhd": "Barrio",
   "building": "Edificio",
   "floor": "Piso",
   "buildingSearch": "Busque su edificio",
   "notListed": "Mi edificio no está en la lista",
   "notListedResult": "Recibirá todas las alertas de {nbhd}. Avisamos al Hub que su edificio falta en la lista.",
   "language": "Idioma",
   "languageFrom": "Según su primera elección",
   "groupsTitle": "¿A qué grupos pertenece?",
   "groupsSkip": "Omitir esto",
   "send": "Envíenme un mensaje para confirmar",
   "formError": "Aún no pudimos enviar esto. Por favor, añada: {missing}.",
   "whatYouGet": "Los mensajes de texto son solo para alertas. Nunca enviamos noticias diarias ni publicidad por texto.",
   "sentTitle": "Revise su teléfono",
   "sentBody": "Enviamos un mensaje al {phone}. Responda YES para empezar a recibir alertas.",
   "resend": "Enviarlo de nuevo",
   "fix": "Corregir el número",
   "signedUpTitle": "Inscrito",
   "signedUpBody": "El {phone} recibirá alertas en {lang}.",
   "noAccount": "No necesita una cuenta.",
   "missingPhone": "un número de teléfono de 10 dígitos",
   "missingNbhd": "su barrio",
   "and": " y ",
   "nbhdError": "Elija su barrio.",
   "change": "Cambiar",
   "noFloor": "Sin piso, solo el edificio",
   "floorN": "Piso {n}",
   "step1": "Paso 1 de 2",
   "step2": "Paso 2 de 2",
   "continue": "Continuar",
   "groupsLead": "Esto es opcional. Si elige un grupo, recibirá alertas y consejos para ese grupo.",
   "consent": "La persona con este teléfono acepta al responder YES, incluidos los grupos elegidos aquí.",
   "resent": "Lo enviamos de nuevo al {phone}.",
   "protoSee": "Ver cómo llega el mensaje al teléfono",
   "protoTag": "Prototipo",
   "howStop": "Para dejar de recibir todos los mensajes del Hub, responda STOP a cualquier mensaje.",
   "howChange": "Para cambiar sus grupos, responda GROUPS.",
   "toHome": "Ir a Alertas",
   "sample": "Edificio de ejemplo",
   "moreBuildings": "{n} más. Escriba parte de la dirección."
  },
  "R06": {
   "thanks": "Gracias. Recibirá alertas del Hub para {where}, en {lang}.",
   "howStop": "Para dejar de recibir todos los mensajes, responda STOP.",
   "howChange": "Para cambiar sus grupos, responda GROUPS.",
   "groupsChanged": "Listo. Ya no recibirá alertas para: {group}.",
   "checkinWithdrawn": "Listo. Se canceló su pedido de chequeos de bienestar. Seguirá recibiendo alertas.",
   "stopped": "No recibirá más mensajes del Hub. Para empezar de nuevo, responda START.",
   "deviceLabel": "Mensajes de texto en un teléfono básico",
   "back": "Volver a la aplicación",
   "replyHint": "Toque una respuesta para enviarla",
   "you": "Usted",
   "groupsMenu": "Responda con un número para dejar de recibir alertas de ese grupo: {list}.",
   "noGroups": "No ha elegido ningún grupo. Recibe todas las alertas para {where}.",
   "started": "Bienvenido de nuevo. Recibirá alertas del Hub para {where}, en {lang}.",
   "now": "ahora",
   "exNote": "Simulacro. Esta conversación es práctica, en el teléfono de alguien inscrito en el simulacro. No se inscribió ni se cambió a ningún residente."
  },
  "R07": {
   "moreComing": "Pronto habrá más información",
   "moreComingLine": "Actualizaremos esto en cuanto sepamos más.",
   "notYetKnown": "Aún no se sabe",
   "where": "Dónde",
   "whatToDo": "Qué hacer",
   "validUntil": "Válida {until}",
   "untilResolved": "hasta que se resuelva",
   "posted": "Publicado {t}",
   "updated": "Actualizado {t}",
   "latest": "Lo más reciente",
   "thread": "Novedades, las más recientes primero",
   "earlier": "Novedades anteriores",
   "update": "Novedad",
   "correction": "Corrección",
   "corrected": "Corregido {t}",
   "whatChanged": "Qué cambió: {changed}",
   "earlierWording": "Texto anterior",
   "final": "Novedad final",
   "resolvedTitle": "Resuelto {t}",
   "expiredTitle": "Venció {t}",
   "expiredNote": "Esta alerta llegó a su hora de fin sin una novedad final.",
   "fromArchive": "Esta alerta terminó. Se queda aquí para que pueda leerla.",
   "ongoingDays": "En curso: día {n} de {total}",
   "supportOffer": "Ayuda con esto",
   "openNear": "Abierto cerca de usted",
   "openNearAll": "Ver todos los espacios abiertos",
   "officialLink": "Alerta oficial sobre el mismo evento",
   "officialFrom": "De {source}",
   "adds": "Este mensaje añade lo que pasa en su edificio.",
   "officialText": "Texto oficial",
   "officialTemplate": "Traducido de una plantilla revisada",
   "guide": "Qué hacer: la guía sobre {hazard}",
   "services": "Servicios que pueden ayudar con esto",
   "share": "Compartir",
   "amberNote": "Contenido ficticio de ejemplo. Solo muestra el diseño.",
   "ambLine": "Mensaje del embajador",
   "readingOrder": "Orden del lector de pantalla: origen y verificación, hora de publicación, la alerta, el aviso de que no es el 911 y luego las acciones.",
   "kinds": {
    "ack": "Primer mensaje",
    "alert": "Alerta",
    "issued": "Emitida",
    "update": "Novedad",
    "correction": "Corrección",
    "final": "Novedad final",
    "ambassador": "Mensaje del embajador"
   },
   "whereLabel": "Dónde",
   "actionLabel": "Qué hacer ahora",
   "notYetKnownLabel": "Aún no se sabe",
   "latestTag": "Lo más reciente",
   "ambassadorOriginal": "Original, en {lang}",
   "officialCard": "Alerta oficial sobre el mismo evento",
   "openOfficial": "Leer la alerta oficial",
   "fromCommunity": "Esto transmite una alerta oficial. El Hub añade lo que pasa aquí.",
   "spacesFiltered": "Se muestran espacios que no piden identificación, según sus opciones.",
   "supportSee": "Ver el lugar",
   "amberBody": "Las alertas Amber son alertas oficiales sobre un niño desaparecido. El texto real siempre viene de Alert Ready.",
   "endedResolved": "Esta alerta terminó. Se resolvió {t}.",
   "endedWithdrawn": "El Hub retiró esta alerta. {reason}",
   "endedExpired": "Esta alerta terminó. Venció {t} sin una novedad final.",
   "validLine": "Válida {until}",
   "timeLine": "Publicado {posted} · Actualizado {updated}",
   "timeLineOne": "Publicado {posted}",
   "basicMore": "Novedades anteriores: {n}"
  },
  "R08": {
   "title": "Alertas que terminaron",
   "resolved": "Resuelta {t}",
   "expired": "Venció {t}",
   "empty": "Todavía no ha terminado ninguna alerta.",
   "emptyBody": "Cuando una alerta termina, pasa aquí y se puede seguir leyendo.",
   "lead": "Cada alerta se puede seguir leyendo aquí después de terminar.",
   "endedOn": "Publicado {posted}",
   "backHome": "Volver a Alertas"
  },
  "R09": {
   "title": "Buscar ayuda",
   "prompt": "Por ejemplo: el dueño de mi casa quiere que me mude",
   "promptAlt": ["Por ejemplo: necesito comida para mi familia esta semana", "Por ejemplo: alguien con quien hablar sobre el estrés"],
   "searchLabel": "Díganos lo que necesita, con sus propias palabras",
   "search": "Buscar",
   "orChoose": "O elija un tema",
   "within": "Buscar dentro de {cat}",
   "clearCat": "Todos los temas",
   "lead": "Diga qué pasa, como se lo contaría a un amigo. No necesita saber el nombre de un servicio.",
   "focusHint": "Otras cosas que escribe la gente",
   "topic": "Tema: {cat}",
   "seeAll": "Ver todo en {cat}",
   "moreTopics": "Mostrar los {n} temas",
   "clear": "Borrar lo que escribí",
   "testTitle": "Búsquedas de prueba",
   "testNote": "Para facilitadores: toque una para hacer una búsqueda preparada del documento de instrucciones. Los residentes no ven esto.",
   "testGloss": "(Dari: {gloss})"
  },
  "R10": {
   "title": "Resultados",
   "resultsFor": "{n} resultados para \"{q}\"",
   "matched": "Coincide con: {reason}",
   "crossLanguage": "Escrito en {lang}, se muestra traducido",
   "contributed": "Lo añadió un vecino",
   "filters": "Filtros",
   "helpListTitle": "Servicios que pueden ayudar con: {hazard}",
   "helpListNote": "Solo se muestran los servicios que dicen cómo pueden ayudar con esto. Ordenados según qué tan bien encajan, si están abiertos ahora, la distancia y cuándo se confirmaron por última vez.",
   "noMatch": "Ahora mismo no hay nada abierto que sea gratis y no pida identificación.",
   "noMatchSuggest": "Si quita \"{f}\", coinciden {n} lugares. El más cercano abre {when}.",
   "applySuggestion": "Quitar \"{f}\"",
   "emergency": "Si alguien está herido ahora mismo, llame al 911.",
   "openNow": "Abierto ahora",
   "closedNow": "Cerrado ahora",
   "opensAt": "Abre {t}",
   "distance": "{d} km",
   "resultsForOne": "1 resultado para \"{q}\"",
   "catTitle": "{cat}: {n} servicios",
   "catTitleOne": "{cat}: 1 servicio",
   "changeSearch": "Cambiar lo que busqué",
   "filtersCount": "Filtros ({n})",
   "crossQuery": "Coincide en otro idioma. Usted escribió en {qlang}; esto está escrito en {lang}.",
   "noMatchAny": "Nada coincide con todos estos filtros.",
   "noMatchSuggestShort": "Si quita \"{f}\", coinciden {n} lugares.",
   "removeAll": "Quitar todos los filtros",
   "noneTitle": "Todavía no pudimos encontrar eso",
   "noneBody": "Una persona del Hub puede ayudarle a encontrar el servicio adecuado.",
   "toPerson": "Hablar con una persona del Hub",
   "showMore": "Mostrar {n} más",
   "hoursUnknown": "No se sabe el horario",
   "communityOffer": "Oferta comunitaria",
   "inCat": "Tema: {cat}",
   "helpEmpty": "Ningún servicio que pueda ayudar con esto coincide con estos filtros."
  },
  "R11": {
   "title": "Todavía no pudimos encontrar eso",
   "body": "Una persona del Hub puede ayudarle a encontrar el servicio adecuado.",
   "person": "Hable con la orientadora comunitaria del Hub",
   "call": "Llamar al {phone}",
   "hours": "Abierto {hours}",
   "visit": "O visite 45 Overlea Boulevard",
   "tryAgain": "Pruebe con otras palabras",
   "categories": "Mejor elija un tema",
   "searched": "Usted preguntó por \"{q}\".",
   "navigatorName": "Samira",
   "navigatorRole": "Orientadora comunitaria del Hub",
   "navigatorLine": "Conoce los servicios de la zona y puede encontrar con usted el adecuado, por teléfono o en persona.",
   "sampleName": "Nombre de ejemplo",
   "openNow": "Abierto ahora, hasta {t}",
   "closedNow": "Cerrado ahora. Abre {t}",
   "callConfirm": "En el CVH real, esto llamaría al {phone}.",
   "directionsConfirm": "En el CVH real, esto abriría las indicaciones para llegar a 45 Overlea Boulevard.",
   "directions": "Cómo llegar",
   "hoursFull": "De lunes a jueves de 9 a. m. a 8 p. m., viernes de 9 a. m. a 5 p. m., sábado de 10 a. m. a 2 p. m."
  },
  "R12": {
   "status": "Ahora mismo",
   "openNow": "Abierto ahora, hasta {t}",
   "closed": "Cerrado ahora",
   "opens": "Abre {t}",
   "address": "Dirección y cómo llegar",
   "directions": "Cómo llegar",
   "hours": "Horario",
   "languages": "Idiomas que se hablan",
   "cost": "Costo",
   "bring": "Qué llevar",
   "id": "¿Piden identificación o estatus migratorio?",
   "access": "Accesibilidad",
   "contact": "Contacto",
   "call": "Llamar",
   "email": "Correo electrónico",
   "website": "Sitio web",
   "unknown": "No se sabe",
   "languagesUnknown": "No se sabe. El Hub no sabe qué idiomas se hablan aquí.",
   "noAddress": "Sin dirección",
   "whereToFind": "Dónde encontrarlo",
   "confirmedBy": "Confirmado por {org} el {date}",
   "publicSource": "De fuentes públicas. La organización aún no lo ha confirmado.",
   "contributedBy": "Lo añadió un vecino el {date}, revisado por el Hub",
   "kind": "Tipo de organización",
   "services": "Servicios",
   "org": "Quién lo gestiona",
   "otherServices": "Ver qué más ofrece {org}",
   "onMap": "Ver en el mapa",
   "correct": "¿Algo está mal? Corríjalo",
   "communityOffer": "Oferta comunitaria",
   "communityOfferLine": "Lo ofrecen vecinos, no es un servicio oficial.",
   "callConfirm": "En el CVH real, esto llamaría al {phone}.",
   "directionsConfirm": "En el CVH real, esto abriría las indicaciones para llegar a {place}.",
   "illustrative": "Datos de ejemplo para el prototipo",
   "appointment": "¿Necesito una cita?",
   "apptYes": "Sí. Llame antes para pedir cita.",
   "apptNo": "No. Puede ir sin cita.",
   "apptSometimes": "A veces. Llame para confirmar.",
   "unknownCall": "Llame para preguntar antes de ir.",
   "unknownAsk": "Pregunte en el Hub antes de ir.",
   "stepFreeYes": "Sin escalones.",
   "stepFreeNo": "Tiene escalones.",
   "idNo": "No.",
   "idYes": "Sí.",
   "emailConfirm": "En el CVH real, esto escribiría un correo electrónico a {email}.",
   "webConfirm": "En el CVH real, esto abriría {web}.",
   "noContact": "No hay teléfono ni correo electrónico.",
   "todayTag": "Hoy",
   "hoursUnknown": "No se sabe el horario",
   "seeAll": "Mostrar todos los detalles",
   "source": "De dónde viene esta información",
   "derivedNote": "Por ahora el Hub solo tiene el nombre, el lugar y el tipo de esta entrada.",
   "addedRecently": "hace poco",
   "notFound": "No se encontró este lugar.",
   "spaceHours": "Abierto hoy como espacio, de {from} a {to}. No se sabe el resto del horario.",
   "someUnknown": "Todavía no se saben algunos detalles. {ask}"
  },
  "R13": {
   "services": "Servicios",
   "about": "Acerca de",
   "servicesCount": "Servicios aquí: {n}",
   "contact": "Contacto",
   "call": "Llamar al {phone}",
   "website": "Sitio web",
   "illustrative": "Descripción de ejemplo para el prototipo",
   "webConfirm": "En el CVH real, esto abriría {web}.",
   "callConfirm": "En el CVH real, esto llamaría al {phone}.",
   "showAll": "Mostrar los {n} servicios",
   "notFound": "No se encontró esta organización.",
   "aboutLines": {
    "TNO": "Una agencia comunitaria de Thorncliffe Park que tiene programas de alimentos, asentamiento, empleo, jóvenes y familias para el barrio.",
    "HUB": "El centro comunitario de 45 Overlea Boulevard, donde muchos servicios y grupos locales comparten un mismo edificio.",
    "TPL": "La biblioteca pública, con libros, computadoras, Wi-Fi y programas gratis para todas las edades.",
    "CITY": "Centros comunitarios y programas de la Ciudad de Toronto en Thorncliffe Park y Flemingdon Park."
   }
  },
  "R14": {
   "title": "Mapa",
   "list": "Lista",
   "mapView": "Mapa",
   "loading": "Cargando el mapa",
   "unavailable": "No se pudo cargar el mapa. La lista tiene todo.",
   "showList": "Mostrar la lista",
   "noneInView": "No hay nada aquí. Pruebe a alejar el mapa.",
   "places": "{n} lugares",
   "place": "1 lugar",
   "add": "Añadir un lugar",
   "rules": "Las reglas de este espacio",
   "filters": "¿Qué necesita?",
   "disruptionView": "Se muestran lugares que pueden ayudar con: {hazard}",
   "legend": "Tipos de lugar",
   "newlyAdded": "Nuevo",
   "tapForHours": "Toque un lugar para ver su horario",
   "legendFormal": "Un servicio o lugar público",
   "legendInformal": "Un grupo comunitario o comunidad religiosa",
   "legendOffer": "Una oferta comunitaria de vecinos",
   "legendSpace": "Abierto ahora como espacio",
   "legendCluster": "Lugares muy cerca unos de otros. Toque para acercar.",
   "legendTitle": "Qué significan las formas",
   "zoomIn": "Acercar",
   "zoomOut": "Alejar",
   "here": "{n} lugares aquí",
   "mapLabel": "Mapa de Thorncliffe Park y Flemingdon Park",
   "allPlaces": "Mostrar todos los lugares",
   "subAll": "Todo tipo de lugar",
   "subLabel": "¿Qué tipo de lugar?",
   "spaceFor": "Abierto ahora como espacio {purpose}",
   "basicList": "Con letra más grande, los lugares se muestran en una lista, los más cercanos primero.",
   "noneMatch": "Ningún lugar coincide con estos filtros.",
   "addShort": "Añadir un lugar",
   "missing": "¿Falta algo o algo está mal?"
  },
  "R15": {
   "title": "Lugares cerca de usted",
   "byDistance": "Los más cercanos primero",
   "empty": "Ningún lugar coincide con estos filtros.",
   "emptyBody": "Quite un filtro para ver más.",
   "add": "Añadir un lugar",
   "count": "{n} lugares",
   "countOne": "1 lugar",
   "more": "Mostrar {n} más",
   "distanceHome": "{d} km",
   "clearAll": "Quitar todos los filtros",
   "missing": "¿Falta algo o algo está mal aquí?",
   "suggest": "Si quita \"{f}\", coinciden {n} lugares. El más cercano está a {d}.",
   "suggestOne": "Si quita \"{f}\", coincide 1 lugar. Está a {d}.",
   "suggestButton": "Quitar \"{f}\""
  },
  "R16": {
   "open": "Ver detalles",
   "hoursToday": "Hoy: {hours}",
   "close": "Cerrar",
   "less": "Menos",
   "wrong": "¿Algo está mal en este lugar?",
   "distance": "A {d} km de su zona",
   "contributed": "Lo añadió un vecino"
  },
  "R17": {
   "title": "Añadir o corregir un lugar",
   "add": "Añadir un lugar que falta",
   "correct": "Corregir un lugar que parece estar mal",
   "fromEntry": "Corregir este lugar",
   "addLine": "Algo que ayuda a los vecinos y aún no está en el mapa. Dos pasos cortos.",
   "correctLine": "El horario, el lugar o un detalle no está al día.",
   "fromEntryLine": "Cambie solo lo que está mal. Todo lo demás se queda igual.",
   "lookingAt": "Estaba viendo",
   "pickTitle": "¿Qué lugar parece estar mal?",
   "pickHint": "Los más cercanos a usted primero. Cada lugar también tiene \"¿Algo está mal? Corríjalo\" en su página.",
   "addDifferent": "Añadir otro lugar que falta"
  },
  "R18": {
   "title": "Antes de añadir un lugar",
   "continue": "Entiendo, continuar",
   "step": "Paso 1 de 2: las reglas",
   "readIn": "Leer las reglas en",
   "readInHint": "Las reglas están escritas en todos los idiomas que ofrece el CVH.",
   "after": "Después, nos cuenta sobre el lugar. Casi todo es elegir, no escribir."
  },
  "R19": {
   "title": "Añadir un lugar",
   "name": "¿Cómo se llama?",
   "what": "Qué se hace allí, en una frase",
   "whatHint": "Hasta 140 caracteres",
   "category": "¿Qué tipo de ayuda es?",
   "type": "¿Es un servicio oficial o una oferta comunitaria?",
   "official": "Un servicio oficial",
   "offer": "Una oferta comunitaria de vecinos",
   "hours": "¿Cuándo está abierto?",
   "sameWeekdays": "Igual todos los días entre semana",
   "notSure": "No estoy seguro",
   "from": "Desde",
   "to": "Hasta",
   "closedDay": "Cerrado",
   "cost": "¿Cuánto cuesta?",
   "idQ": "¿Piden identificación o estatus migratorio?",
   "stepFreeQ": "¿Se puede entrar sin escalones?",
   "languagesQ": "¿Qué idiomas se hablan?",
   "location": "¿Dónde está?",
   "submit": "Enviar al Hub",
   "optional": "Opcional",
   "ready": "Listo para enviar",
   "saved": "Guardado en este teléfono",
   "step": "Paso 2 de 2: el lugar",
   "choose": "Elija una opción",
   "catNotSure": "No estoy seguro",
   "offerLine": "Lo ofrecen vecinos, no es un servicio oficial. Aparece en el mapa con un borde de líneas cortadas.",
   "officialLine": "Lo gestiona una organización, una agencia o la Ciudad.",
   "whereBtn": "Mostrar dónde está",
   "whereChange": "Cambiar",
   "whereNone": "Aún no se eligió",
   "costFree": "Gratis",
   "costLow": "De bajo costo",
   "costFee": "Cuesta dinero",
   "yes": "Sí",
   "no": "No",
   "weekdays": "De lunes a viernes",
   "langsHint": "Elija todos los que correspondan.",
   "count": "{n} de 140",
   "missingTitle": "Añada esto y luego envíe:",
   "resubmitNote": "El Hub le devolvió esto. {change}",
   "closedOpt": "Cerrado",
   "notSureOpt": "No estoy seguro",
   "toOpt": "Hasta",
   "fromOpt": "Abre",
   "hoursNotSureLine": "No hay problema. El Hub le preguntará al lugar.",
   "whatPh": "Por ejemplo: comestibles gratis los jueves por la tarde, para cualquier persona",
   "namePh": "Por ejemplo: banco de alimentos de los jueves"
  },
  "R20": {
   "title": "¿Dónde está?",
   "pin": "Poner un marcador en el mapa",
   "building": "En un edificio",
   "described": "Describa en qué parte del edificio",
   "describedHint": "Por ejemplo: la sala comunitaria detrás de la mezquita",
   "landmark": "Cerca de un punto de referencia",
   "landmarkHint": "Por ejemplo: junto a los chorros de agua del R.V. Burgess Park",
   "address": "Dirección",
   "noAddress": "No necesita una dirección.",
   "howTitle": "¿Cómo puede encontrarlo la gente?",
   "use": "Usar este lugar",
   "pinHint": "Mueva el mapa hasta que el marcador quede sobre el lugar.",
   "pinNear": "Un marcador en el mapa, cerca de {place}",
   "nearLandmark": "Cerca de {place}",
   "buildingChoose": "Elija un edificio",
   "landmarkChoose": "Elija un punto de referencia",
   "landmarkMore": "Cualquier otra cosa que ayude a encontrarlo",
   "addressHint": "Solo si la sabe.",
   "needOne": "Elija una de las opciones de arriba.",
   "needBuilding": "Primero elija el edificio.",
   "needLandmark": "Primero elija el punto de referencia.",
   "needAddress": "Primero escriba la dirección.",
   "pinWhere": "El marcador está cerca de {place}.",
   "mapLabel": "Mapa para poner el marcador"
  },
  "R21": {
   "title": "Enviado al Hub",
   "general": "Alguien del Hub lo leerá en una semana, más o menos. Le avisaremos cuando esté en el mapa.",
   "ambassador": "Usted es embajador, así que esto se revisa primero. Normalmente está en el mapa en un día.",
   "lane": "Tipo de revisión: {lane}",
   "laneGeneral": "Revisión comunitaria",
   "laneAmbassador": "Revisión de embajador, más rápida",
   "youSent": "Usted envió: {name}",
   "next": "Qué pasa después",
   "n1": "Alguien del Hub lo lee.",
   "n2": "Si cumple las reglas, aparece en el mapa y en las búsquedas.",
   "n3": "Si hay que cambiar algo, le decimos qué, y puede enviarlo de nuevo.",
   "n1Amb": "Alguien del Hub lo lee antes que la fila general.",
   "howLong": "Cuánto tarda",
   "weekLine": "Una semana, más o menos",
   "dayLine": "Normalmente en un día",
   "toMap": "Volver al mapa",
   "another": "Añadir otro lugar",
   "protoLabel": "Solo prototipo",
   "protoDecline": "Ver un lugar que el Hub devolvió",
   "protoAccepted": "Ver en el mapa un lugar que añadió un vecino"
  },
  "R22": {
   "title": "Corregir este lugar",
   "changeOne": "Cambie lo que está mal. Todo lo demás se queda igual.",
   "submit": "Enviar la corrección",
   "sent": "Gracias. El Hub revisará el cambio.",
   "change": "Cambiar",
   "changedTag": "Cambiado",
   "was": "Antes: {v}",
   "undo": "Deshacer",
   "nothingYet": "Cambie al menos una cosa y luego envíe.",
   "doneEditing": "Listo",
   "onlyThis": "Solo se envía lo que usted cambia. El Hub lo revisa antes de actualizar el lugar.",
   "toPlace": "Volver al lugar",
   "toMap": "Volver al mapa",
   "sentTitle": "Corrección enviada",
   "whatChanged": "Lo que usted cambió",
   "whereLabel": "Dónde está",
   "namePlace": "Nombre"
  },
  "R23": {
   "title": "Su lugar todavía no se añadió",
   "reason": "Por qué",
   "whatToChange": "Qué cambiar",
   "resubmit": "Cambiarlo y enviarlo de nuevo",
   "kept": "Todo lo que escribió se guarda.",
   "sentAgo": "Usted envió esto {t}.",
   "youWrote": "Lo que escribió",
   "whereNone": "No se indicó un lugar",
   "toMap": "Volver al mapa",
   "reasons": {
    "advert": {
     "why": "Vende algo o pide dinero. El CVH no es un mercado.",
     "change": "Si hay una parte gratuita que cualquiera puede usar, describa solo esa parte. No incluya precios ni pagos."
    },
    "noLocation": {
     "why": "No pudimos saber dónde está.",
     "change": "Añada un edificio, un punto de referencia cercano o un marcador en el mapa. No necesita una dirección."
    },
    "duplicate": {
     "why": "Este lugar ya está en el mapa.",
     "change": "Si algo está mal, ábralo y elija \"Corríjalo\"."
    },
    "unclear": {
     "why": "No pudimos saber qué lugar es o qué se hace allí.",
     "change": "Escriba su nombre y diga en una frase qué puede conseguir la gente allí."
    },
    "outOfArea": {
     "why": "Está fuera de Thorncliffe Park y Flemingdon Park.",
     "change": "El CVH solo muestra lugares dentro de estos dos barrios o cerca de ellos."
    },
    "notCommunity": {
     "why": "No está abierto a todas las personas del barrio.",
     "change": "Envíelo de nuevo si cualquier persona del barrio puede usarlo."
    }
   }
  },
  "R24": {
   "title": "Prepararse",
   "lead": "Qué hacer antes, durante y después de los seis problemas que pasan aquí.",
   "numbers": "Números que podría necesitar",
   "headsUp": "Un aviso previo antes de cada temporada",
   "checkin": "Pedir un chequeo de bienestar durante el calor y los cortes",
   "readTime": "Lectura de {n} minutos",
   "guides": "Guías: qué hacer antes, durante y después",
   "more": "Más formas de estar listo",
   "checkinLine": "El embajador de su piso pasa a ver cómo está. No es un servicio de emergencia.",
   "numbersLine": "911, 211, 311, Toronto Hydro y el Hub",
   "headsUpLine": "Solo en el CVH, nunca por mensaje de texto",
   "none": "No se pudieron cargar las guías en este momento. Si alguien está en peligro, llame al 911."
  },
  "R25": {
   "stagesNav": "Ir a",
   "aiLabel": "Escrito con IA para el prototipo. Personas lo revisarán antes de lanzar el CVH.",
   "kit": "Esta guía coincide con el Local Preparedness Kit (kit local de preparación) impreso.",
   "numbers": "Números que podría necesitar",
   "services": "Servicios que pueden ayudar",
   "spaces": "Espacios abiertos {purpose}",
   "forYou": "Primero, para usted",
   "fullGuide": "La guía completa",
   "next": "Siguiente: {stage}",
   "stageNow": "Está leyendo: {stage}",
   "unavailable": "Esta guía aún no está disponible en {lang}.",
   "guideWord": "Guía",
   "readTime": "Lectura de {n} minutos",
   "helpTitle": "Ayuda con esto",
   "tailoredLink": "Adaptado a sus opciones",
   "allSteps": "Mostrar los {n} pasos",
   "purposeWords": {
    "cooling": "para refrescarse",
    "cleanAir": "para aire limpio",
    "charging": "para cargar dispositivos"
   },
   "endLine": "Esa es la última parte de esta guía. Si necesita más ayuda:",
   "numbersLine": "911, 211, 311, Toronto Hydro y el Hub",
   "openedDuring": "Se abrió en \"Durante\" porque esto está pasando ahora."
  },
  "R26": {
   "title": "¿A qué grupos pertenece?",
   "lead": "Elija los que correspondan a usted. Esto cambia las alertas que recibe y los consejos que ve. Nunca preguntamos por qué.",
   "skipLine": "Si omite esto, no cambia nada en las alertas que recibe.",
   "helperConfirm": "Estoy ayudando a alguien. Esa persona aceptó estas opciones.",
   "helperNote": "Por favor, pregúntele primero.",
   "step": "Paso 1 de 2",
   "checkinNext": "Después elige su edificio y su piso, y luego cómo quiere que vean cómo está.",
   "helperNeeded": "Por favor, pregúntele primero. Marque la casilla cuando haya aceptado, u omita esta pregunta.",
   "save": "Guardar",
   "saved": "Guardado. Esto se aplica ahora.",
   "choose": "Elija los que correspondan a usted",
   "helping": "¿Ayuda a alguien con esto?"
  },
  "R27": {
   "title": "Filtros",
   "apply": "Mostrar {n} resultados",
   "clear": "Borrar todo",
   "lead": "Responda solo las preguntas que le importan. Todo lo demás queda abierto.",
   "openNowOnly": "Solo lugares abiertos ahora",
   "anyLang": "Cualquier idioma",
   "langHint": "Muestra lugares donde alguien lo habla. Se dejan fuera los lugares que no nos lo han dicho.",
   "noIdHint": "Muestra solo los lugares que le dijeron al Hub que no pedirán identificación, papeles ni estatus migratorio para ayudarle. Se dejan fuera los lugares que no nos lo han dicho, para que no llegue y le pregunten.",
   "private": "Sus respuestas se quedan en este teléfono. No se guardan ni se envían a nadie.",
   "fromChoices": "Según sus opciones",
   "cancel": "Volver sin cambios",
   "applyOne": "Mostrar 1 resultado",
   "moreQuestions": "Más preguntas ({n})",
   "applyNone": "Aplicar (todavía no coincide nada)"
  },
  "R28": {
   "title": "Qué significa \"verificado\"",
   "body": "Verificado significa que alguien del Hub, o de una organización aliada con la que trabaja el Hub, revisó esta alerta con las personas que están en el lugar antes de enviarla.",
   "who": "{org} verificó esta alerta {t}.",
   "notYet": "Aún no verificado significa que la alerta vino de un embajador del edificio, que muchas veces es el primero en saberlo. El Hub la revisa en cuanto puede.",
   "official": "Las alertas oficiales vienen de {source} y se transmiten sin cambiar sus palabras.",
   "notFalse": "Aún no verificado no significa que esté mal.",
   "thisAlert": "Esta alerta",
   "ambFirst": "La publicó primero {t} un embajador del edificio en {building}.",
   "ambPosted": "La publicó {t} un embajador del edificio en {building}.",
   "notYetAct": "Puede actuar según ella ahora. Cuando el Hub la haya revisado, dirá \"Verificado por el Hub\".",
   "correctedLine": "Se corrigió {t}. La alerta muestra qué cambió, y el texto anterior se puede seguir leyendo.",
   "officialAdds": "El Hub nunca cambia las palabras de una alerta oficial. Puede añadir lo que pasa en su edificio en una alerta comunitaria propia.",
   "legendTitle": "Las palabras que verá en las alertas",
   "thisOne": "Esta alerta",
   "legendVerified": "Alguien del Hub o de una organización aliada la revisó antes de enviarla.",
   "legendUnverified": "La publicó un embajador del edificio. El Hub todavía no la ha revisado.",
   "legendOfficial": "De una fuente del gobierno, transmitida palabra por palabra.",
   "backToAlert": "Volver a la alerta"
  },
  "R29": {
   "title": "Compartir esta alerta",
   "preview": "Esto es lo que recibirán sus vecinos",
   "everyone": "Todos reciben esta versión. No se comparte nada adaptado a usted.",
   "notRecorded": "El CVH no registra quién comparte alertas ni a quién se las envía.",
   "send": "Compartir",
   "handed": "Aquí se abrirían las opciones para compartir de su teléfono.",
   "lead": "Sus vecinos reciben la alerta tal como la escribió el Hub, con su origen y un enlace a la versión más reciente.",
   "postedAt": "Publicado {t}",
   "updatedAt": "Actualizado {t}",
   "todayAt": "hoy a las {time}",
   "dayAt": "{day} a las {time}",
   "linkLine": "Novedades más recientes y correcciones: {url}",
   "sendLine": "Su teléfono le preguntará con qué aplicación enviarlo.",
   "placeMore": "y {n} más"
  },
  "R30": {
   "deviceLabel": "La alerta en un grupo de WhatsApp",
   "group": "Vecinos del piso 4",
   "openedLater": "Abierto más tarde: muestra la novedad más reciente y una corrección.",
   "groupBuilding": "Vecinos de {building}",
   "members": "{name}, Maria, usted y 9 más",
   "membersOut": "Maria, Farhan y 10 más",
   "today": "Hoy",
   "forwarded": "Reenviado",
   "you": "Usted",
   "askLine": "¿A alguien más se le fue la luz?",
   "askLineOther": "¿Alguien sabe qué pasa con el ascensor?",
   "proto": "Prototipo",
   "backToApp": "Volver a la aplicación",
   "removeLink": "Quitar el enlace",
   "restoreLink": "Volver a poner el enlace",
   "openLater": "Abrir el enlace, horas después",
   "senderLang": "{name} lee el CVH en {lang}. El enlace se abre en el idioma de quien lo abre, no en el de quien lo envía.",
   "linkRemovedNote": "Se quitó el enlace. El mensaje sigue diciendo qué pasó, dónde, de quién viene, si está verificado, cuándo y qué hacer.",
   "sinceSent": "Desde que {name} envió esto:",
   "showSince": "Mostrar qué cambió",
   "noChange": "Abierto más tarde: no se ha publicado nada nuevo desde que se envió.",
   "nowVerified": "Abierto más tarde: el Hub ya revisó esta publicación, así que ahora la alerta dice \"Verificado por el Hub\".",
   "exNote": "Simulacro. Si se reenvía un mensaje de práctica, la palabra del simulacro va con él como primera línea, para que nadie lo confunda con una alerta real."
  },
  "R31": {
   "title": "Números que podría necesitar",
   "emergency": "Emergencia",
   "emergencyWhen": "Llame al 911 si la vida o la seguridad de alguien está en peligro ahora mismo: un incendio, una emergencia médica o un delito que está pasando.",
   "p211": "Ayuda para encontrar servicios comunitarios, sociales y del gobierno",
   "p311": "Servicios de la Ciudad de Toronto y problemas que no son emergencias",
   "hydro": "Reportar un corte de luz a Toronto Hydro",
   "hub": "Hablar con alguien del Hub",
   "building": "El {role} de su edificio",
   "noBuilding": "Todavía no tenemos un contacto para su edificio. El embajador de su piso puede ayudarle.",
   "call": "Llamar",
   "callConfirm": "En el CVH real, esto llamaría al {number}.",
   "lead": "Cada número aparece según para qué sirve.",
   "others": "Para todo lo demás",
   "call911": "Llamar al 911",
   "buildingTitle": "Su edificio",
   "noBuildingNoAmb": "Todavía no tenemos un contacto para su edificio. El Hub puede ayudarle a comunicarse con la administración de su edificio.",
   "noBuildingChosen": "Elija su edificio y le mostraremos aquí su contacto cuando lo tengamos. Mientras tanto, el Hub puede ayudarle.",
   "chooseBuilding": "Elija su edificio",
   "ambRoute": "Vive en su edificio y puede pasarle cosas a la administración del edificio.",
   "hubHours": "Abierto de lunes a jueves de 9 a. m. a 8 p. m., viernes de 9 a. m. a 5 p. m., sábado de 10 a. m. a 2 p. m.",
   "calling": "Llamar a {what}",
   "roles": {
    "superintendent": "encargado"
   },
   "checked": "Revisado por el Hub, última actualización el {date}",
   "noOthers": "No se pudieron cargar los otros números en este momento. Inténtelo de nuevo en unos minutos."
  },
  "R32": {
   "title": "Un aviso previo antes de cada temporada",
   "lead": "Un recordatorio corto en el CVH antes del calor, el humo y los cortes de invierno, con una o dos cosas que hacer.",
   "never": "Los avisos previos aparecen solo en el CVH. Nunca llegan como mensaje de texto.",
   "on": "Avisos previos activados",
   "off": "Avisos previos desactivados",
   "season": "Cuándo: {season}",
   "switchLabel": "Mostrarme un aviso previo antes de cada temporada",
   "what": "Lo que vería",
   "whatOn": "Lo que verá",
   "titles": {
    "heat": "Antes del calor",
    "smoke": "Antes de la temporada de humo de incendios forestales",
    "winter": "Antes de las tormentas de invierno"
   },
   "readGuide": "Leer la guía sobre {hazard}",
   "turnedOn": "Avisos previos activados. Los verá en Alertas, solo en el CVH.",
   "turnedOff": "Avisos previos desactivados. No cambió nada más.",
   "offLine": "Los avisos previos están desactivados hasta que usted los active.",
   "whereLine": "Aparecen en la pantalla Alertas, unas semanas antes de cada temporada."
  },
  "R33": {
   "title": "Pedir un chequeo de bienestar",
   "what": "Cuando haya un aviso de calor o un corte de luz en su edificio, el embajador de su piso verá cómo está y puede ayudarle a comunicarse con los servicios que necesite.",
   "notEmergency": "Un chequeo de bienestar no es un servicio de emergencia.",
   "how": "¿Cómo quiere que vean cómo está?",
   "call": "Una llamada",
   "text": "Un mensaje de texto",
   "knock": "Que toquen a su puerta",
   "unit": "Número de apartamento",
   "unitWhy": "Solo pedimos su número de apartamento para que su embajador sepa a qué puerta tocar.",
   "building": "Su edificio y piso",
   "noAmbassador": "Todavía no hay embajador en el piso {floor}, así que no podemos prometerle un chequeo de bienestar.",
   "hubInstead": "Mejor llame al Hub al {phone}. Abrimos {hours}.",
   "request": "Pedir chequeos de bienestar",
   "requested": "Chequeos de bienestar pedidos",
   "requestedBody": "Cuando haya un aviso de calor o un corte de luz en {building}, el embajador de su piso verá cómo está por {method}.",
   "withdraw": "Dejar los chequeos de bienestar",
   "withdrawn": "Se dejaron los chequeos de bienestar. Seguirá recibiendo alertas.",
   "helper": "Estoy ayudando a alguien. Esa persona aceptó pedir chequeos de bienestar.",
   "whatTitle": "Qué es un chequeo de bienestar",
   "askPlace": "Necesitamos su edificio y su piso para saber si un embajador de piso puede ver cómo está.",
   "chooseBuilding": "Elija su edificio",
   "chooseFloor": "Elija su piso",
   "floorN": "Piso {n}",
   "change": "Cambiar",
   "placeLine": "{building}, piso {floor}",
   "covered": "Un embajador de piso cubre el piso {floor}.",
   "callHub": "Llamar al Hub",
   "stillAlerts": "Seguirá recibiendo todas las alertas de su edificio.",
   "needMethod": "Elija cómo quiere que vean cómo está.",
   "needUnit": "Añada su número de apartamento para que toquen a su puerta, o elija una llamada o un mensaje de texto.",
   "needHelper": "Por favor, pregúntele primero. Marque la casilla cuando haya aceptado.",
   "needPlace": "Primero elija su edificio y su piso.",
   "howWithdraw": "Puede dejar los chequeos de bienestar cuando quiera: aquí, en Mis opciones, o respondiendo NOCHECK a un mensaje de texto del Hub.",
   "changeHow": "Cambiar cómo",
   "again": "Pedir chequeos de bienestar de nuevo",
   "unitShown": "Apartamento {unit}",
   "continue": "Continuar",
   "skip": "Ahora no",
   "helping": "¿Ayuda a alguien con esto?"
  },
  "R34": {
   "title": "Lo que le he dicho al CVH",
   "lead": "Solo lo que usted eligió. Cambie o quite cualquier cosa aquí. Los cambios se aplican enseguida.",
   "language": "Idioma",
   "building": "Edificio y piso",
   "basic": "Letra más grande, menos cosas",
   "groups": "Grupos",
   "checkin": "Chequeos de bienestar",
   "headsUp": "Avisos previos de temporada",
   "change": "Cambiar",
   "remove": "Quitar",
   "removed": "Quitado. Esto se aplica ahora.",
   "nothing": "Todavía no le ha dicho nada al CVH.",
   "onDevice": "Estas opciones se guardan solo en este dispositivo.",
   "invite": "Para recibir en su teléfono alertas para su edificio y sus grupos, active las alertas por mensaje de texto. Toma un minuto y no necesita una cuenta.",
   "inviteYes": "Activar alertas por texto",
   "inviteNo": "Ahora no",
   "fromTailored": "Los consejos de \"Qué significa para usted\" vienen solo de las opciones de esta página. Cámbielas aquí y los consejos también cambian.",
   "neighbourhoodOnly": "Todas las alertas de {nbhd}",
   "floorOf": "{building}, piso {floor}",
   "on": "Activado",
   "setByHelper": "Lo activó alguien que le ayuda",
   "checkinNone": "No pedido",
   "checkinAsk": "Pedir un chequeo de bienestar",
   "checkinBy": "Por {method}",
   "checkinNoAmb": "Todavía no hay embajador en su piso. El Hub puede ayudarle.",
   "unitLine": "Apartamento {unit}, solo para tocar a la puerta",
   "textAlerts": "Alertas por mensaje de texto",
   "textOn": "Activadas, al {phone}",
   "textPending": "Esperando que responda YES desde el {phone}",
   "howStop": "Para dejar de recibirlas, responda STOP a cualquier mensaje de texto del Hub.",
   "removedItem": "Quitado: {item}",
   "tellUs": "Puede decirle al CVH:",
   "whereLive": "Dónde vive",
   "whichGroups": "A qué grupos pertenece",
   "turnOff": "Desactivar",
   "changeGroups": "Cambiar grupos",
   "groupsNone": "Ninguno elegido",
   "chooseGroups": "Elegir grupos",
   "langNote": "El idioma en que lee el CVH.",
   "removedBuildingOne": "1 edificio que guardó ya no está en la lista de edificios, así que se quitó.",
   "removedBuildingMany": "{n} edificios que guardó ya no están en la lista de edificios, así que se quitaron.",
   "removedFloorOne": "1 piso que guardó ya no existe, así que se quitó.",
   "removedFloorMany": "{n} pisos que guardó ya no existen, así que se quitaron.",
   "removedRest": "Todo lo demás que eligió sigue igual.",
   "clearAll": "Borrar todo",
   "clearTitle": "¿Borrar todo de este teléfono?",
   "clearBody": "Esto quita su idioma, sus grupos, sus edificios y sus pisos de este teléfono. Empezará de nuevo eligiendo un idioma.",
   "clearYes": "Sí, borrar todo",
   "loading": "Cargando sus edificios...",
   "listFailed": "No se pudo cargar la lista de edificios en este momento. Sus opciones siguen guardadas.",
   "buildingByRsn": "Edificio {rsn}",
   "floorsOne": "1 piso elegido",
   "floorsMany": "{n} pisos elegidos",
   "buildingsNone": "Ninguno elegido",
   "removeItem": "Quitar: {item}"
  },
  "R35": {
   "title": "Recibir alertas para su edificio",
   "lead": "Elija dónde vive para ver primero las alertas de su edificio. Todos los pasos son opcionales.",
   "nbhd": "Barrio",
   "building": "Edificio",
   "floor": "Piso",
   "nbhdOnly": "Solo el barrio completo",
   "floorLine": "Si elige un piso, también recibe alertas solo para su piso, como una falla del ascensor o un corte de agua.",
   "noUnit": "Aquí nunca le pedimos su número de apartamento.",
   "preselected": "Según su aviso",
   "skipLine": "Si omite esto, igual verá todas las alertas de su barrio.",
   "finishedTitle": "Usted eligió",
   "invite": "Para recibir en su teléfono alertas para su edificio, su piso y sus grupos, active las alertas por mensaje de texto. Toma un minuto y no necesita una cuenta.",
   "inviteYes": "Activar alertas por texto",
   "inviteNo": "Ahora no",
   "helper": "Estoy ayudando a alguien. Esa persona aceptó esta opción.",
   "step": "Paso 2 de 2",
   "buildingSearch": "Busque su edificio",
   "more": "{n} más. Escriba parte de la dirección para encontrar el suyo.",
   "noMatch": "Ningún edificio coincide con \"{q}\".",
   "change": "Cambiar",
   "noFloor": "Sin piso, solo el edificio",
   "floorN": "Piso {n}",
   "sample": "Edificio de ejemplo",
   "nextCheckin": "Siguiente: cómo quiere que vean cómo está.",
   "helperNeeded": "Por favor, pregúntele primero. Marque la casilla cuando haya aceptado, u omita esta pregunta.",
   "save": "Guardar",
   "saved": "Guardado. Esto se aplica ahora.",
   "both": "Thorncliffe Park y Flemingdon Park",
   "nothingSummary": "Todavía nada. Verá todas las alertas de Thorncliffe Park y Flemingdon Park.",
   "everyAlert": "Todas las alertas de {nbhd}",
   "floorOf": "{building}, piso {floor}",
   "checkinBy": "Chequeos de bienestar por {method}",
   "changeAll": "Cambiar lo que eligió",
   "toHome": "Ir a Alertas",
   "manyLine": "Elija su propio edificio o el de un familiar. Puede elegir todos los que quiera.",
   "chosenNone": "Todavía no eligió ningún edificio",
   "chosenOne": "1 edificio elegido",
   "chosenMany": "{n} edificios elegidos",
   "floorsIn": "Pisos de {building}. Opcional.",
   "noFloorsListed": "Todavía no hay pisos en la lista para este edificio.",
   "loading": "Cargando la lista de edificios...",
   "loadFailed": "No se pudo cargar la lista de edificios. Revise su conexión e inténtelo de nuevo, u omita este paso.",
   "retry": "Intentar de nuevo"
  },
  "A01": {
   "title": "Mi edificio",
   "assigned": "Usted es el embajador de {building}, pisos {floors}.",
   "canPost": "Puede publicar novedades para cualquier piso de {building}.",
   "post": "Publicar una novedad del edificio",
   "active": "Lo que pasa en su edificio",
   "nothing": "No hay nada activo en su edificio.",
   "round": "Ronda de chequeos de bienestar: {n} en sus pisos",
   "openRound": "Abrir mi ronda",
   "role": "Embajador del edificio",
   "roundFloors": "Su ronda: pisos {a} a {b}.",
   "offline": "Sin señal. Lo que haga se guarda en su teléfono y se envía cuando tenga señal.",
   "noRound": "No hay ronda de chequeos de bienestar en este momento. Empieza cuando el Hub envía una alerta de calor o de corte de luz para su edificio.",
   "toDo": "Faltan {n}",
   "tellInPerson": "{n} hogares a los que hay que avisar en persona",
   "practice": "Ronda de práctica",
   "myRound": "Mi ronda",
   "myPosts": "Sus novedades",
   "postedAgo": "Publicado {t}",
   "fromHub": "Del Hub",
   "fromAmb": "De un embajador del edificio",
   "fromOfficial": "Alerta oficial",
   "fromPartner": "De una organización aliada",
   "verifiedWord": "Verificado",
   "notVerifiedWord": "Aún no verificado"
  },
  "A02": {
   "title": "Publicar una novedad del edificio",
   "types": "¿Qué está pasando? Elija todo lo que corresponda",
   "floors": "¿Qué pisos?",
   "wholeBuilding": "Todo el edificio",
   "range": "Del piso {a} al {b}",
   "pick": "Elegir pisos",
   "photo": "Añadir una foto",
   "line": "Añadir una línea",
   "lineRequired": "Diga qué está pasando, en una línea",
   "optional": "Opcional",
   "other911": "Si alguien está en peligro, llame primero al 911.",
   "appearsAs": "Aparecerá como: Embajador del edificio, {building}",
   "goesNow": "Esto se enviará ahora.",
   "waits": "El Hub revisará esto antes de enviarlo.",
   "post": "Publicar novedad",
   "notOffered": "Los avisos de calor y humo los envía el Hub para todo el barrio.",
   "exOutcome": "Práctica: esto va solo al Hub. No se envía nada a los residentes.",
   "exNote": "Simulacro: esta publicación es práctica. Va solo al Hub, nunca a los residentes.",
   "typeMore": {
    "fire": "alarma o evacuación",
    "water": "o plomería"
   },
   "required": "Obligatorio",
   "wholeLine": "Los {n} pisos",
   "mineLabel": "Pisos {a} a {b}",
   "mineLine": "Su ronda",
   "pickLabel": "Elegir pisos",
   "pickLine": "Toque el primer piso y luego el último",
   "pickNone": "Todavía no eligió pisos",
   "pickOne": "Piso {a}",
   "pickRange": "Pisos {a} a {b}",
   "floorAria": "Piso {n}",
   "more": "Añada más si quiere",
   "photoAdded": "Foto añadida (ejemplo)",
   "remove": "Quitar",
   "lineAdded": "Su línea",
   "ownLine": "O escriba su propia línea",
   "sampleBn": "Línea de ejemplo en bengalí",
   "sampleTag": "Prototipo",
   "mtNote": "Los residentes que leen en otro idioma la ven con una etiqueta de traducción automática.",
   "phrases": ["Ya se avisó al personal del edificio.", "Use las escaleras con cuidado.", "Por favor, vea cómo están los vecinos que puedan necesitar ayuda."],
   "otherPhrases": ["La puerta de entrada no cierra con llave.", "Las luces del pasillo no funcionan.", "El ducto de basura está tapado."],
   "otherFirst": "Si alguien está en peligro, llame primero al 911. Luego diga aquí qué está pasando.",
   "someWait": "Uno de estos tipos siempre espera al Hub, así que esta novedad también espera.",
   "offlineBar": "Ahora no hay señal. Se guarda en su teléfono y se envía cuando tenga señal.",
   "postTo": "Publicar novedad: {floors}",
   "wholeWord": "todo el edificio",
   "errTypes": "Elija qué está pasando.",
   "errFloors": "Toque los pisos o elija Todo el edificio.",
   "errLine": "Otro necesita una línea: diga qué está pasando."
  },
  "A03": {
   "liveTitle": "Publicado",
   "live": "Ya está publicado en todos los canales, incluidos los mensajes de texto. Aparece como \"Aún no verificado\" hasta que el Hub lo revise.",
   "waitingTitle": "Esperando al Hub",
   "waiting": "El Hub está revisando esto ahora. Se enviará en cuanto se apruebe.",
   "approved": "Aprobado y enviado {t}.",
   "declined": "El Hub no envió esto. Motivo: {reason}",
   "verified": "El Hub verificó su novedad {t}.",
   "corrected": "El Hub corrigió su novedad. Motivo: {reason}",
   "withdrawn": "El Hub retiró su novedad. Motivo: {reason}",
   "slow": "Todavía se está enviando. La señal aquí es débil. Terminará cuando tenga mejor señal.",
   "where": "Enviado a: {channels}",
   "when": "Publicado {t}",
   "states": {
    "queued": "Guardado en su teléfono. Se envía cuando tenga señal",
    "live": "Publicado. Aún no verificado",
    "waiting": "Esperando al Hub",
    "approved": "Aprobado y enviado",
    "declined": "El Hub no lo envió",
    "verified": "Verificado por el Hub",
    "withdrawn": "Retirado por el Hub",
    "corrected": "Corregido por el Hub",
    "exercise": "Simulacro. No se envió a los residentes"
   },
   "queuedTitle": "Guardado en su teléfono",
   "queued": "Guardado en su teléfono. Se enviará cuando tenga señal.",
   "writtenAt": "Escrito {t}. No necesita hacer nada más.",
   "approvedTitle": "Aprobado y enviado",
   "declinedTitle": "No enviado",
   "verifiedTitle": "Verificado por el Hub",
   "correctedTitle": "Corregido por el Hub",
   "withdrawnTitle": "Retirado por el Hub",
   "exerciseTitle": "Publicación de práctica guardada",
   "exercise": "Esto es un simulacro. No se envió nada a los residentes.",
   "approvedLine": "Ahora aparece como verificado por el Hub.",
   "verifiedLine": "Ahora los residentes ven \"Verificado por el Hub\" en su novedad. No se envió un segundo mensaje.",
   "correctedLine": "El Hub cambió su novedad: {text}",
   "correctedWhen": "Corregido {t}.",
   "yourUpdate": "Su novedad",
   "floorsAll": "Todo el edificio",
   "floorsOne": "Piso {a}",
   "floorsRange": "Pisos {a} a {b}",
   "photoYes": "Con una foto",
   "whereWhen": "Qué se envió, a dónde y cuándo",
   "chText": "Mensajes de texto",
   "chWeb": "La aplicación y el sitio web del CVH",
   "sentTo": "Enviado {t} a los residentes de {building}, {floors}",
   "liveOn": "Se muestra desde {t} para {building}, {floors}",
   "notYet": "Todavía no se envió",
   "notSent": "No enviado",
   "takenDown": "Retirado {t}",
   "waitAfter": "Se envía por todos los canales en cuanto el Hub lo apruebe.",
   "howSeen": "Cómo lo ven los residentes",
   "willSeen": "Cuando se apruebe, los residentes verán",
   "seeIt": "Verlo como lo ven los residentes",
   "toHome": "Volver a mi edificio",
   "another": "Publicar otra novedad",
   "notFound": "No se encontró esta novedad en este teléfono.",
   "reasonLabel": "Motivo: {reason}"
  },
  "A04": {
   "title": "Mi ronda",
   "checkins": "Chequeos de bienestar pedidos en sus pisos",
   "unreachable": "Hogares de sus pisos a los que no se puede llegar por teléfono ni por la aplicación",
   "carry": "Alerta que hay que darles",
   "floorDoor": "Piso {floor}, puerta {door}",
   "floorPhone": "Piso {floor}, {method}: {phone}",
   "method": {
    "call": "llamada",
    "text": "mensaje de texto",
    "knock": "tocar la puerta"
   },
   "done": "Hecho",
   "notReached": "No se pudo contactar",
   "needsHelp": "Necesita ayuda",
   "connected": "Conectado con un servicio",
   "passed": "Pasado al Hub",
   "offline": "Sin señal. Lo que toque se guarda y se enviará cuando tenga señal.",
   "deleted": "Cuando se cierre este problema, estos registros se borran. Solo se guardan los totales.",
   "addDoor": "Añadir una puerta a pedido de un residente",
   "addConfirm": "El residente aceptó que lo añadan, aquí en mi pantalla.",
   "addedByRequest": "Añadido a pedido del residente",
   "addNote": "Esta puerta se borra cuando se cierre el problema. Para que vean cómo está cada vez, puede elegirlo en el CVH.",
   "exercise": "Esta es una ronda de práctica.",
   "forAlert": "Para: {headline}",
   "practiceFor": "Ronda de práctica. No le llega nada a los residentes.",
   "floorN": "Piso {n}",
   "doorN": "Puerta {door}",
   "methodWord": {
    "call": "Llamada",
    "text": "Mensaje de texto",
    "knock": "Tocar la puerta"
   },
   "tally": "{todo} por hacer · {done} hechos · {nr} sin contactar · {help} necesitan ayuda",
   "connectedCat": "Conectado con un servicio: {category}",
   "queued": "Guardado en su teléfono. Se enviará cuando tenga señal.",
   "taken": "Lo tomó el Hub",
   "change": "Cambiar",
   "connect": "Conectar con un servicio",
   "tellInPerson": "Toque la puerta y deles esta alerta",
   "whereLabel": "Dónde",
   "doLabel": "Qué hacer ahora",
   "noRound": "No hay ronda de chequeos de bienestar en este momento. Cuando el Hub envíe una alerta de calor o de corte de luz para su edificio, aquí aparecerán los chequeos de bienestar de sus pisos.",
   "addTitle": "Añadir una puerta",
   "addFloor": "Piso",
   "addDoorLabel": "Número de puerta",
   "addMethod": "Cómo quiere que lo contacten",
   "addPhone": "Número de teléfono",
   "addBtn": "Añadir a mi ronda",
   "cancel": "Cancelar",
   "added": "Añadido a su ronda.",
   "errDoor": "Añada el número de puerta.",
   "errPhone": "Añada un número de teléfono para una llamada o un mensaje de texto.",
   "errMethod": "Elija cómo quiere que lo contacten.",
   "errAgree": "Pregúntele primero. Marque la casilla cuando haya aceptado, aquí en su pantalla.",
   "practiceNoAlert": "Práctica: no hay ninguna alerta que dar."
  },
  "A05": {
   "title": "Conectar con un servicio",
   "urgent": "Cualquier cosa urgente o peligrosa: llame al 911 ahora.",
   "list": "Abierto ahora, en el idioma del residente",
   "choose": "Háblele de esto",
   "chosen": "Dígale al residente cómo comunicarse con {service}, o escríbaselo.",
   "neverText": "No enviamos esto por mensaje de texto.",
   "recorded": "Registrado como: {category}. No se guarda nada más.",
   "exNote": "Simulacro: esto es práctica. Lo que elija se guarda solo en el registro del simulacro.",
   "forWho": "Para: {who}",
   "theirLang": "Su idioma",
   "all": "Todos",
   "openNowIn": "Abierto ahora en {lang}, o no se sabe el horario",
   "hoursUnknown": "No se sabe el horario. Llame antes.",
   "speaks": "Hablan {lang}",
   "none": "No hay nada abierto ahora en {lang} para esto. Estos están abiertos ahora en otros idiomas:",
   "noneAtAll": "No hay nada abierto ahora aquí. El Hub puede ayudar: {phone}.",
   "tellTitle": "Dígale",
   "sayOr": "Dígaselo o escríbaselo. También puede mostrarle esta pantalla.",
   "again": "Elegir otro servicio",
   "backRound": "Volver a mi ronda",
   "already": "Ya está conectado con un servicio: {category}.",
   "queued": "Guardado en su teléfono. Se envía al Hub cuando tenga señal.",
   "callLabel": "Teléfono",
   "whereLabel": "Dónde",
   "hoursLabel": "Hoy"
  },
  "building": {
   "registerTitle": "Del registro de la Ciudad",
   "updated": "Última actualización: {date}",
   "registerLead": "La Ciudad de Toronto tiene un registro de edificios de apartamentos. Estos datos vienen de allí.",
   "checking": "El Hub está revisando los datos de este edificio. Lo que ve aquí puede cambiar.",
   "facts": {
    "storeys": "Pisos",
    "elevators": "Ascensores",
    "emergencyPower": "Electricidad de emergencia",
    "coolingRoom": "Sala para refrescarse",
    "airConditioning": "Aire acondicionado",
    "barrierFree": "Entrada sin barreras"
   },
   "airNone": "No tiene",
   "airIndividual": "En cada apartamento",
   "roles": {
    "superintendent": "Encargado",
    "buildingManagement": "Administración del edificio",
    "propertyOffice": "Oficina de administración"
   },
   "contactTitle": "Contacto del edificio",
   "providedByHub": "Lo proporciona el Hub, última actualización el {date}"
  },
  "guides": {
   "reviewed": "Revisado por el Hub, última actualización el {date}"
  }
 });
  /* AD-11 pilot change (2026-10-03): the label of a directory description a model translated and no person has reviewed. AI-generated (Claude), not yet checked by native readers. */
  m(t, { "x04": { "unreviewed": "Traducción automática; no revisada por una persona" } });
  /* The resident map (S02.07): the "map" strings. AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "map": {
    "lead": "Servicios, organizaciones y edificios de apartamentos en Thorncliffe Park y Flemingdon Park. Toque un marcador para ver qué es.",
    "service": "Servicio u organización",
    "building": "Edificio de apartamentos",
    "pinName": "{name}: {kind}",
    "noSignal": "El mapa no está disponible sin señal",
    "noSignalBody": "La lista tiene todos los lugares del mapa.",
    "notSaved": "Esta parte del mapa no está guardada en su teléfono",
    "notSavedBody": "Las partes del mapa que vio con señal se quedan en su teléfono. Los marcadores y la lista siguen funcionando.",
    "listTitle": "Lugares en esta parte del mapa",
    "listLead": "Los mismos lugares que muestra el mapa. Mueva el mapa o haga zoom para cambiar esta lista.",
    "listEmpty": "No hay nada en esta parte del mapa. Mueva el mapa o haga zoom, o muestre toda la zona.",
    "wholeArea": "Mostrar toda la zona",
    "buildings": "Edificios de apartamentos",
    "buildingsCount": "{n} edificios",
    "buildingsCountOne": "1 edificio",
    "filtered": "Solo se muestran los lugares que coinciden con los filtros que eligió en el directorio."
   }
  });
  /* S07.02: the web sign-up for text alerts and the confirmation text. YES, STOP, START and CVH stay in English. AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "signup": {
    "termsAgree": "He leído la página de términos y privacidad, y estoy de acuerdo.",
    "termsLink": "Leer la página de términos y privacidad",
    "termsVersion": "Versión de los términos {version}",
    "age": "Tengo 16 años o más, o me ayuda mi madre, mi padre o mi tutor.",
    "missingTerms": "su acuerdo con los términos",
    "missingAge": "la declaración de edad",
    "sending": "Enviando...",
    "onItsWay": "Si este número puede recibir mensajes de texto, hay un mensaje en camino.",
    "expect": "Responda YES a ese mensaje en un plazo de 48 horas para empezar a recibir alertas. Hasta que responda YES, no recibirá alertas por mensaje de texto.",
    "howChange": "Para cambiar más adelante su edificio, piso o idioma, responda 1 o 2 a cualquier mensaje del Hub.",
    "startHelp": "¿No le llegó un mensaje en 5 minutos? Envíe START al {number} y luego vuelva a inscribirse.",
    "startHelpNoNumber": "¿No le llegó un mensaje en 5 minutos? Envíe START al número desde el que llegan nuestros mensajes y luego vuelva a inscribirse.",
    "error": {
     "invalid_request": "No se pudo leer algo del formulario. Vuelva a cargar la página e inténtelo de nuevo.",
     "phone_not_canadian": "Use un número de teléfono canadiense de 10 dígitos, como 416 555 0123.",
     "neighbourhood_missing": "Elija su barrio.",
     "terms_not_agreed": "Para inscribirse, acepte los términos.",
     "age_not_confirmed": "Para inscribirse, confirme la declaración de edad.",
     "terms_changed": "Los términos cambiaron mientras esta página estaba abierta. Vuelva a leerlos y luego acéptelos.",
     "place_unknown": "Uno de sus edificios o pisos ya no está en la lista. Revise sus edificios e inténtelo de nuevo.",
     "rate_limited": "Llegaron demasiadas inscripciones desde esta conexión. Inténtelo de nuevo dentro de una hora.",
     "signup_unavailable": "La inscripción por mensaje de texto no está disponible ahora. Inténtelo más tarde.",
     "network": "No pudimos conectar con el CVH. Revise su conexión e inténtelo de nuevo."
    }
   }
  });
  m(t, {"smsTexts": {"confirmation": "Alertas CVH del Thorncliffe Park Community Hub: responde YES para confirmar. Frecuencia de mensajes variable. Pueden aplicarse tarifas de mensajes y datos. HELP: ayuda. STOP: parar."}});
  /* S07.04: the welcome, the replies of the inbound router and the words for yes (YES, STOP and CVH stay in English). */
  m(t, {"smsTexts": {"welcome": "Ya está suscrito a las alertas del CVH. El personal del Hub revisa cada mensaje, así que es posible que las alertas no se envíen de noche. Responda 1 para cambiar su edificio o piso, 2 para cambiar su idioma, 3 para retirar su pedido de chequeo de bienestar y 0 para dejar de recibir mensajes y borrar su suscripción. Responda STOP para dejar de recibirlas.", "alreadySignedUp": "Ya está suscrito a las alertas del CVH.", "deletePrompt": "Envíe 0 otra vez en 10 minutos para borrarse. No recibirá más textos.", "signupInfo": "Para recibir alertas del CVH por mensaje de texto, suscríbase aquí: {link} Responda STOP para dejar de recibirlas."}, "smsKeywords": {"yes": "sí, si"}});
  /* S07.05: the numbered text menus and their replies (see the English file for what each is and the one-text rule; 0, 1, 8, 9, 10, 5
     and {placeholders} stay as written). AI-generated (Claude), not yet checked by native readers. */
  m(t, {"smsTexts": {"menuStreet": "Calle:", "menuBuilding": "Edificio:", "menuFloor": "Piso:", "menuWholeBuilding": "Todo el edificio", "menuLanguage": "Idioma:", "menuNav": "0 Volver 9 Hub", "menuNavMore": "0 Volver 8 Siguiente 9 Hub", "menuWarn": "Esto reemplaza sus {n} edificios guardados. 1 Continuar, 0 Volver", "menuHub": "Llame al Hub al {hub}.", "menuClosed": "Menú cerrado. No se cambió nada.", "menuReset": "Su menú se cerró tras 10 minutos sin respuesta. No se cambió nada.", "menuLimit": "Usó los 5 menús de hoy. Intente mañana o llame al Hub: {hub}", "menuLimitLink": "Usó los 5 menús de hoy. Envíe 1 para un enlace. Hub: {hub}", "buildingSaved": "Guardado. Su edificio es {building}, piso {floor}.", "buildingSavedWhole": "Guardado. Su edificio es {building}.", "languageSaved": "Guardado. Recibirá los mensajes en español.", "noCheckinRequest": "No tiene ningún pedido de chequeo de bienestar.", "checkinWithdrawn": "Se retiró su pedido de chequeo de bienestar."}});
  /* S07.06: the one-time web link's texts and its page (see the English file for what each is; menuClosedLink must fit one text; 0, 1, 30
     and {placeholders} stay as written; the error lines other than edit_unavailable are the sign-up's own). AI-generated (Claude), not yet
     checked by native readers. */
  m(t, {"smsTexts":{"menuClosedLink":"Menú cerrado. No se cambió nada. Envíe 1 para un enlace web.","editLink":"Cambie o borre sus alertas del CVH aquí: {link} El enlace funciona una vez, durante 30 minutos.","editSaved":"Sus opciones de alertas del CVH se cambiaron en la página web. ¿No fue usted? Llame al Hub al {hub}."},"subscriptionEdit":{"title":"Cambie sus alertas por mensaje de texto","loading":"Abriendo sus opciones...","forNumber":"Para el número de teléfono que termina en {digits}.","lead":"Cambie lo que quiera y luego guarde. Para dejar de recibir todos los mensajes, borre su suscripción al final de esta página.","topicsTitle":"Temas sobre los que no quiere mensajes","topicsLead":"Marque un tema para dejar de recibir sus alertas. Las alertas de incendio o evacuación siempre llegan.","save":"Guardar mis cambios","saving":"Guardando...","savedTitle":"Sus cambios se guardaron","savedBody":"Le llegará un mensaje para confirmarlos. Este enlace ya se usó: para cambiar otra cosa, pida un enlace nuevo por mensaje de texto.","deleteTitle":"Borrar mi suscripción","deleteLead":"No recibirá más mensajes del CVH y se borrará todo lo que se guarda sobre su número. Esto no se puede deshacer.","deleteSure":"¿Borrar su suscripción ahora? No recibirá más mensajes del CVH.","deleteYes":"Sí, borrarla","deleteNo":"No, mantenerla","deleting":"Borrando...","deletedTitle":"Su suscripción se borró","deletedBody":"No recibirá más mensajes del CVH y no se guarda nada sobre su número. No se envía ningún mensaje para confirmarlo.","signUpAgain":"Suscribirse de nuevo","expiredTitle":"Este enlace caducó","expiredBody":"Un enlace funciona una vez, durante 30 minutos después de enviarse.","expiredHow":"Para recibir un enlace nuevo por mensaje de texto, responda 1 a un mensaje del CVH. Si la respuesta es un menú, envíe 0 para cerrarlo. Cuando la respuesta le ofrezca un enlace, envíe 1.","callHub":"O llame al Hub al {hub}.","error":{"invalid_request":"No se pudo leer algo del formulario. Vuelva a cargar la página e inténtelo de nuevo.","neighbourhood_missing":"Elija su barrio.","place_unknown":"Uno de sus edificios o pisos ya no está en la lista. Revise sus edificios e inténtelo de nuevo.","edit_unavailable":"No se pueden hacer cambios ahora. Inténtelo más tarde.","network":"No pudimos conectar con el CVH. Revise su conexión e inténtelo de nuevo."}}});
  /* S08.05: the check-in request's texts and wording (see the English file for what each is; checkinMoved and checkinUncoveredNow must fit one
     text; 1, YES, CVH, Hub and {placeholders} stay as written). AI-generated (Claude), not yet checked by native readers. */
  m(t, {"smsTexts":{"checkinMoved":"Su piso cambió: pedido de chequeo retirado. Envíe 1 para un enlace.","checkinUncoveredNow":"Ahora ningún embajador cubre su piso. Llame al Hub: {hub}"},"signup":{"error":{"checkin_consent_missing":"Para pedir un chequeo de bienestar, marque la casilla para aceptar."}},"subscriptionEdit":{"error":{"checkin_consent_missing":"Para pedir un chequeo de bienestar, marque la casilla para aceptar."}},"checkin":{"consentMissing":"Para pedir un chequeo de bienestar, marque la casilla para aceptar.","sees":"Un embajador de su piso verá su número de teléfono y su piso, para poder llamarle o enviarle un mensaje.","isNot":"Un chequeo de bienestar es una llamada o un mensaje para preguntar si usted está bien. No es atención médica, ni una promesa de que alguien vendrá enseguida.","howTitle":"Cómo pedirlo","howNew":"Necesita las alertas de texto del CVH. Suscríbase y pida el chequeo en el mismo formulario.","howHelp":"En un evento del CVH o en el Hub, el personal o un embajador del edificio pueden ayudarle a suscribirse.","howSubscribed":"¿Ya recibe textos del CVH? Pida el chequeo en la página donde cambia sus opciones.","noCoverage":"Si ningún embajador cubre su piso todavía, se lo diremos enseguida. En su lugar, puede llamar al Hub al {hub}.","ask":"Que un embajador de mi piso me haga un chequeo de bienestar","whereHint":"Elija el edificio y el piso donde vive, de los de arriba.","agree":"Acepto que un embajador de mi piso vea mi número de teléfono y mi piso, y me haga un chequeo de bienestar.","untilYes":"Su pedido de chequeo empieza cuando responda YES a nuestro mensaje.","uncovered":"Ningún embajador cubre su piso todavía. Llame al Hub al {hub}.","withdraw":"Retirar mi pedido de chequeo","withdrawNote":"Se retira al guardar. Seguirá recibiendo alertas.","moved":"Cambió el lugar donde vive, así que su pedido de chequeo se retirará. Para pedirlo otra vez para su nuevo piso, elíjalo y acepte de nuevo.","savedRequested":"Su pedido de chequeo está guardado.","savedMethod":"Cambió la forma de su chequeo."}});
  /* The last resident wording that showed in English: the home's alert list and its failures (R03, status.none), the ask screen's waiting and
     failure states (R09, R10.shownIn) and the directory (S02.06). AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "status": {
    "none": "Nada activo"
   },
   "R03": {
    "currentAlerts": "Alertas actuales",
    "noCurrentAlerts": "No hay alertas actuales",
    "myBuildings": "Sus edificios",
    "checking": "Buscando alertas",
    "feedFailed": "No pudimos comprobar las alertas en este momento. Un lugar que dice \"No se sabe\" puede tener una alerta igualmente. Volveremos a intentarlo.",
    "feedFailedOld": "No pudimos comprobar si hay alertas nuevas. Se muestra lo último que se cargó {t}."
   },
   "R09": {
    "searching": "Buscando",
    "needsSignal": "La búsqueda necesita señal",
    "needsSignalBody": "Todavía puede elegir un tema abajo, o llamar al Hub.",
    "busy": "La búsqueda está ocupada, inténtelo de nuevo en unos minutos",
    "busyBody": "Puede elegir un tema abajo, o llamar al Hub.",
    "updating": "Los resultados de búsqueda se están actualizando, inténtelo de nuevo",
    "updatingBody": "Puede elegir un tema abajo mientras se actualizan, o llamar al Hub.",
    "browseAll": "Ver todos los servicios y organizaciones",
    "loading": "Cargando los temas"
   },
   "R10": {
    "shownIn": "Se muestra en {lang}"
   },
   "directory": {
    "title": "Servicios y organizaciones",
    "lead": "Lo que el Hub ha confirmado en Thorncliffe Park y Flemingdon Park. Elija un tema o un barrio para acotar la lista.",
    "count": "{n} servicios",
    "countOne": "1 servicio",
    "topic": "Tema",
    "emergency": "Ayuda en una emergencia",
    "emergencyRole": "Función en una emergencia",
    /* The verified badge's line on a provider (it replaces the earlier last-confirmed line). AI-generated (Claude), not yet checked by native readers. */
    "checkedByHub": "Verificado por el Hub · {date}",
    "lastUpdated": "Última actualización: {time}",
    "loading": "Cargando el directorio",
    "couldNotLoad": "No se pudo cargar el directorio",
    "couldNotLoadBody": "El Hub puede ayudarle a encontrar un servicio por teléfono.",
    "couldNotLoadNumbers": "La página de números tiene los otros números que podría necesitar.",
    "numbersLink": "Ver los números esenciales",
    "backToList": "Todos los servicios y organizaciones",
    "suggestApply": "Mostrar solo {place}"
   }
  });
  /* Reading without signal (S02.12): the offline page and R-34's note. AI-generated (Claude), not yet checked by native readers. */
  m(t, {
   "offline": {
    "title": "Esta página no está guardada en su teléfono",
    "body": "Todavía no se ha abierto en este teléfono con señal, así que necesita señal. Los números siempre están guardados en su teléfono.",
    "available": "Puede leer esto sin señal",
    "none": "Todavía no hay nada más guardado en este teléfono. Las páginas que abre con señal se guardan para después."
   },
   "R34": {
    "offlineTitle": "Leer sin señal",
    "offlineHelp": "Las páginas que abre con señal se guardan en este teléfono, para que pueda volver a leerlas sin señal. Los números siempre están guardados. La primera vez, el CVH necesita señal para abrirse.",
    "offlineNote": "Es posible que este teléfono no guarde páginas para usarlas sin conexión"
   }
  });
  /* S08.02: an ambassador's post (A-02): the one screen's new words (an unsent post is held only in the open page's memory), and A03.states.ended. AI-generated, not yet checked by native readers. */
  m(t, {
   "A02": {
    "building": "¿Qué edificio?",
    "allFloorsLine": "Los {n} pisos",
    "listLabel": "Algunos pisos",
    "listLine": "Marque cada piso",
    "rangeLabel": "Varios pisos seguidos",
    "rangeLine": "De un piso a otro",
    "fromFloor": "Desde el piso",
    "toFloor": "Hasta el piso",
    "chooseFloor": "Elegir",
    "phaseTitle": "Cómo están las cosas",
    "phaseProblem": "Hay un problema",
    "phaseProgress": "Se está trabajando en ello",
    "validTitle": "¿Hasta cuándo?",
    "validResolved": "Hasta que se arregle (24 horas desde ahora)",
    "validAt": "Hasta una fecha y hora",
    "dateLabel": "Fecha",
    "timeLabel": "Hora (hora de Toronto)",
    "validHint": "Como máximo 7 días a partir de ahora.",
    "textLabel": "Qué está pasando, en inglés",
    "textHint": "Como máximo {max} caracteres. Los residentes lo leen en su idioma; el Hub lo revisa primero.",
    "inAlert": "Esta novedad va en la alerta: {headline}",
    "typesFixed": "Qué está pasando: {types}",
    "unsent": "Todavía no se ha enviado. Mantenga esta página abierta; se enviará cuando tenga señal.",
    "unsentClose": "Si cierra esta página, esta novedad se pierde.",
    "sending": "Enviando al Hub...",
    "errPhase": "Elija cómo están las cosas.",
    "errText": "Diga qué está pasando, en inglés.",
    "errTextLong": "Es demasiado largo. Use como máximo {max} caracteres.",
    "errValid": "Escriba una fecha y una hora.",
    "errValidPast": "Esa hora ya pasó. Elija una hora posterior.",
    "errValidFar": "Elija una hora dentro de los próximos 7 días como máximo.",
    "errValidSkipped": "Esa noche cambia la hora, así que esa hora no está clara. Elija otra hora.",
    "errRange": "El primer piso está por encima del último. Ponga primero el piso más bajo.",
    "errNotAssigned": "Ahora no está asignado a este edificio, así que no puede publicar para él.",
    "errClosed": "Esta alerta terminó. Mejor publique una novedad nueva.",
    "errSignedOut": "Se cerró su sesión, así que esto no se envió. Vuelva a iniciar sesión y publíquelo otra vez.",
    "errFailed": "Esto no se envió. Inténtelo de nuevo. Si sigue pasando, llame al Hub."
   },
   "A03": {
    "states": {
     "ended": "No enviado: la alerta terminó antes de que el Hub la revisara"
    }
   }
  });
  /* S09.07: the end-of-pilot re-consent texts (the campaign text with {date}, the confirmation after YES, the answer after the deadline, the answer
     while sign-ups are paused) and the sign-up form's refusal while sign-ups are paused. YES and CVH stay in English. Each text fits one text message
     with the longest date. smsDate is how a text writes the deadline (the month names, the order of day and month, the numerals), fixed here
     from CLDR 47 so the frozen text is the same on every runtime. AI-generated (Claude), not yet checked by native readers: the texts and the
     date words are reviewed before launch (Launch Readiness). */
  m(t, {"smsDate": {"months":["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"],"dayMonth":"{day} de {month}","digits":"0123456789"}, "smsTexts": {"reconsent": "El proyecto piloto CVH termina. Responda YES para seguir recibiendo alertas. Si no responde hasta el final del {date}, borraremos sus datos.", "reconsentKept": "Gracias. Seguirá recibiendo las alertas de CVH.", "pilotEnded": "El proyecto piloto CVH terminó; no se guardó su número.", "signupsPaused": "Las inscripciones a CVH están en pausa mientras termina el piloto."}, "signup": {"error": {"signups_paused": "Las inscripciones están en pausa mientras termina el proyecto piloto."}}});
  /* The opt-in disclosures carriers ask for (program, frequency, rates, HELP and STOP) under the sign-up form. AI-generated (Claude), not yet checked by native readers. */
  m(t, {"signup": {"smsTerms": "Alertas CVH por texto del Thorncliffe Park Community Hub. La frecuencia de los mensajes varía. Pueden aplicarse tarifas de mensajes y datos. Responde HELP para recibir ayuda o STOP para dejar de recibirlas."}});
  /* The per-group advice lines of the tailored block (X-12) and the simpler-view switch (X-07, retranslated from the current English
     "Simpler view"). AI-generated (Claude) on 2026-10-09 under the product owner's pilot decision that everything is translated;
     not yet checked by native readers (launch checklist, section 8). */
  m(t, {"tailored": {"power": {"seniors": ["Si usa un aparato médico que necesita electricidad, vaya ahora a un lugar donde pueda cargarlo.", "Use las escaleras solo si se siente capaz. El embajador de su piso puede llevarle cosas."], "newcomers": ["Los espacios para cargar dispositivos no piden identificación ni estatus migratorio.", "Toronto Hydro y la Ciudad nunca le pedirán dinero ni papeles por teléfono durante un corte de luz."], "families": ["Si el refrigerador se ha calentado, guarde la fórmula para bebés y la leche en una hielera con hielo.", "Cerca de los niños, use linternas, no velas."]}, "flood": {"seniors": ["Ponga ahora sus medicamentos y papeles en un estante alto.", "Si tiene que salir, pida ayuda a un vecino o al embajador de su piso."], "newcomers": ["Puede avisar de una fuga al dueño de su casa sin que eso afecte su estatus migratorio.", "La ayuda legal gratuita puede explicarle, en su idioma, las reparaciones y el alquiler después de una inundación."], "families": ["Mantenga a los niños lejos de las zonas mojadas y de los enchufes.", "Tire los juguetes y la comida que tocaron el agua de la inundación."]}, "elevator": {"seniors": ["El embajador de su piso puede organizar que le suban comestibles o medicamentos.", "Mientras el ascensor no funcione, se puede organizar transporte a sus citas médicas."], "newcomers": ["La ayuda con comestibles y transporte no pide identificación ni estatus migratorio.", "Tiene derecho a preguntar al dueño de su casa cuándo van a arreglar el ascensor."], "families": ["Los vecinos pueden ayudar a subir por las escaleras los cochecitos y los comestibles.", "Si un niño tiene una cita médica, pregunte por la ayuda con el transporte."]}, "heat": {"seniors": ["Algunos medicamentos hacen que el calor afecte más al cuerpo. Consulte a su farmacéutico.", "Vaya a un espacio para refrescarse a primera hora de la tarde, antes de la parte más calurosa del día."], "newcomers": ["Los espacios para refrescarse son gratis y no piden identificación ni estatus migratorio.", "La ayuda con las facturas de electricidad es gratis. Pregunte en el Hub."], "families": ["Los bebés y los niños pequeños se calientan más rápido que los adultos. Deles agua a menudo.", "Nunca deje a un niño en un auto estacionado, ni siquiera por un minuto."]}, "smoke": {"seniors": ["Si tiene asma o un problema del corazón, tenga sus medicamentos cerca.", "Hay espacios con aire filtrado abiertos. Pida a un vecino que vaya con usted."], "newcomers": ["Los espacios con aire filtrado son gratis y no piden identificación ni estatus migratorio.", "Hay mascarillas gratis en el Hub hasta que se acaben."], "families": ["Mantenga a los niños dentro de casa y limite que corran y jueguen.", "Un ventilador de caja con filtro en el cuarto de los niños les ayuda a dormir."]}, "fire": {"seniors": ["Si no puede usar las escaleras, quédese en su apartamento con la puerta cerrada y llame al 911.", "El embajador de su piso sabe qué residentes pueden necesitar ayuda para salir."], "newcomers": ["Los puntos de recepción y el apoyo después de un incendio no piden estatus migratorio.", "Los trabajadores de asentamiento pueden ayudarle a reemplazar documentos perdidos."], "families": ["Practique con sus hijos cómo llegar a la escalera y dónde reunirse afuera.", "Tenga junto a la puerta una bolsa con los medicamentos y los papeles de los niños."]}, "winter": {"seniors": ["Cargue su teléfono y tenga mantas cerca por si se va la luz."], "newcomers": ["Los espacios para calentarse son gratis y no piden identificación ni estatus migratorio."], "families": ["Si se apaga la calefacción, vista a los niños con varias capas de ropa dentro de casa."]}}, "x07": {"label": "Vista más sencilla", "turnOn": "Activar la vista más sencilla", "turnOff": "Desactivar la vista más sencilla"}});
})();
