// GENERATED by scripts/gen-hub-number.mjs from data/catalogue/numbers.json (the number with id "hub"). Do not edit; run `npm run gen:hub-number`.

/** The Hub's number in E.164, the form a tel: link takes. Show it with displayPhone (phone.ts). */
export const HUB_PHONE_E164 = "+14164218997";
