// Writes src/app/[lang]/fonts.generated.css: the @font-face rules of the fonts the resident surface uses (AD-16),
// and src/app/staff/fonts.generated.css: the Public Sans faces alone, which are all the English staff screens use.
// Both are taken from the version-pinned @fontsource-variable packages in node_modules, so no font is fetched from
// a font CDN at build or run time.
//
//   node scripts/gen-fonts.mjs           writes the files
//   node scripts/gen-fonts.mjs --check   fails if a file differs from what the packages give
//
// Each rule keeps the package's unicode-range slice, so a page downloads only the slices its text needs; the
// family is renamed from "Noto Sans Tamil Variable" to "Noto Sans Tamil" (the name the stack and the tests use).
// Only the slices a launch language needs are kept: Latin text is Public Sans's, so a Noto face has its own script.
import { existsSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const OUTPUT = "src/app/[lang]/fonts.generated.css";
export const STAFF_OUTPUT = "src/app/staff/fonts.generated.css";
// Both outputs are three folders below the repository root.
const NODE_MODULES_FROM_OUTPUT = "../../../node_modules";

// Package (under @fontsource-variable/), family name, and the slices to keep ("sc" keeps the numbered ones).
export const FONTS = [
  { pkg: "public-sans", family: "Public Sans", slices: ["latin", "latin-ext"] },
  { pkg: "noto-naskh-arabic", family: "Noto Naskh Arabic", slices: ["arabic"] },
  { pkg: "noto-sans-gujarati", family: "Noto Sans Gujarati", slices: ["gujarati"] },
  { pkg: "noto-sans-tamil", family: "Noto Sans Tamil", slices: ["tamil"] },
  { pkg: "noto-sans", family: "Noto Sans", slices: ["greek", "greek-ext"] },
  { pkg: "noto-sans-bengali", family: "Noto Sans Bengali", slices: ["bengali"] },
  { pkg: "noto-sans-devanagari", family: "Noto Sans Devanagari", slices: ["devanagari"] },
  { pkg: "noto-sans-gurmukhi", family: "Noto Sans Gurmukhi", slices: ["gurmukhi"] },
  { pkg: "noto-sans-sc", family: "Noto Sans SC", slices: ["sc"] },
];

// The staff surface is English: Public Sans's Latin slices, and no Noto face or script.
export const STAFF_FONTS = FONTS.filter(({ pkg }) => pkg === "public-sans");

const HEADER = "/* GENERATED by scripts/gen-fonts.mjs from the @fontsource-variable packages. Do not edit; run `npm run gen:fonts`. */";

function facesOf(root, { pkg, family, slices }) {
  const css = readFileSync(path.join(root, "node_modules/@fontsource-variable", pkg, "wght.css"), "utf8");
  const faces = [];
  for (const match of css.matchAll(/\/\*\s*(\S+)-wght-normal\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)) {
    const [, tag, rule] = match;
    const slice = tag.slice(pkg.length + 1);
    const wanted = slices.includes("sc") ? /^\[\d+\]$/.test(slice) : slices.includes(slice);
    if (!wanted) continue;
    const renamed = rule
      .replace(/font-family:\s*'[^']*'/, `font-family: '${family}'`)
      .replace(/url\(\.\/files\//, `url(${NODE_MODULES_FROM_OUTPUT}/@fontsource-variable/${pkg}/files/`);
    faces.push(`/* ${tag} */\n${renamed}`);
  }
  if (faces.length === 0) throw new Error(`No @font-face for ${family} (${slices.join(", ")}) in @fontsource-variable/${pkg}`);
  return faces;
}

const fileOf = (root, fonts) => `${HEADER}\n\n${fonts.flatMap((font) => facesOf(root, font)).join("\n\n")}\n`;

/** The content of the resident surface's generated file. */
export function generate(root) {
  return fileOf(root, FONTS);
}

/** The content of the staff surface's generated file. */
export function generateStaff(root) {
  return fileOf(root, STAFF_FONTS);
}

function main(argv) {
  const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
  const outputs = [
    [OUTPUT, generate(root)],
    [STAFF_OUTPUT, generateStaff(root)],
  ];
  if (argv.includes("--check")) {
    const stale = outputs.filter(([output, content]) => !existsSync(path.join(root, output)) || readFileSync(path.join(root, output), "utf8") !== content);
    for (const [output] of stale) console.error(`${output} is stale; run "npm run gen:fonts" and commit the result`);
    if (stale.length > 0) return 1;
    for (const [output] of outputs) console.log(`${output} is up to date.`);
    return 0;
  }
  for (const [output, content] of outputs) {
    writeFileSync(path.join(root, output), content);
    console.log(`Wrote ${output}`);
  }
  return 0;
}

// Run directly, not imported. Node runs the entry point by its real path (import.meta.url), while argv[1] keeps any
// symlink in the path it was given (macOS's /var is /private/var), so the two are compared as real paths.
if (process.argv[1] && import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href) process.exitCode = main(process.argv.slice(2));
