// Generates the app's design tokens from design/prototype/ds/cvrh/tokens.json, the only token
// source (AD-16; docs/design-framework/spacing-container/token-architecture.md sections 2 and 9).
//
//   node scripts/gen-tokens.mjs           writes the generated files
//   node scripts/gen-tokens.mjs --check   fails if a generated file differs from what tokens.json gives
//
// It never writes a default: a token that tokens.json lacks fails the run and is named.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import postcss from "postcss";

export const TOKENS_FILE = "design/prototype/ds/cvrh/tokens.json";
export const SEMANTIC_FILE = "src/ui/tokens/semantic.css";
export const LAYOUT_DIR = "src/ui/layout";
export const PRIMITIVES_FILE = "src/ui/tokens/tokens.generated.css";
export const THEME_FILE = "src/ui/tokens/theme.generated.css";
export const TOKENS_VERSION = 3;

const HEADER = `/* GENERATED by scripts/gen-tokens.mjs from ${TOKENS_FILE}. Do not edit; run \`npm run gen:tokens\`. */`;

// The "Screens" type groups (G7). Each style is named screen-{prefix}{role}; every group has the same roles.
const TYPE_GROUPS = [
  { name: "Screens: resident", prefix: "" },
  { name: "Screens: basic mode", prefix: "basic-" },
  { name: "Screens: staff", prefix: "staff-" },
];

// Basic mode is data-basic="true" on <html> (token-architecture.md section 8). The staff type set
// applies on the staff surface: the element carrying data-surface="staff", which is Screen's staff
// root and, from S01.09, the Hub shell's root.
const BASIC_SELECTOR = '[data-basic="true"]';
const STAFF_SELECTOR = '[data-surface="staff"]';

// Build-time tokens written as literals into Tailwind's @theme only (section 2.5).
const BUILD_TIME = [
  { group: "breakpoint", token: "app-breakpoint-hub", theme: "--breakpoint-hub", note: "variant hub:, the Hub shell only (viewport)" },
  {
    group: "container",
    token: "app-container-hub-two-column-min",
    theme: "--container-hub-two-column",
    note: "variant @hub-two-column:, two-column Hub pages only (hub-page container)",
  },
];

// Tokens a primitive or the tap rule needs even before semantic.css names them.
const REQUIRED = ["app-tap", "app-tap-basic"];

// Semantic spacing tokens exposed as Tailwind spacing utilities: the role word is dropped
// (--gap-icon gives gap-icon, --inset-card gives p-card); the resident gutter is `gutter` (section 9).
const SPACING_ROLES = [/^gap-/, /^inset-/, /^offset-/];
const SPACING_ALIASES = { "gutter-resident": "gutter", tap: "tap", "tap-basic": "tap-basic" };

/** The design owner's decision (token-architecture.md section 11) behind a tokens.json name. */
export function decisionFor(name) {
  if (/^app-space-/.test(name)) return "G1";
  if (/^app-tap/.test(name)) return "G3";
  if (/^app-(breakpoint|container)-/.test(name)) return "G4";
  if (/^app-(page|side-nav|aside)/.test(name)) return "G5";
  if (/^(app-icon|app-fs-|screen-)/.test(name)) return "G7";
  if (/^app-min-/.test(name)) return "G8";
  if (/^(lh-|app-lh-)/.test(name)) return "G10";
  return undefined;
}

export class TokenError extends Error {}

function missing(token, neededBy) {
  const decision = decisionFor(token);
  return new TokenError(
    `tokens.json does not define "${token}"${decision ? ` (decision ${decision})` : ""}, needed by ${neededBy}. ` +
      "gen:tokens writes no default value; add the token to tokens.json.",
  );
}

function list(tokens, pathName) {
  const value = pathName.split(".").reduce((node, key) => node?.[key], tokens);
  if (!Array.isArray(value)) throw new TokenError(`tokens.json has no "${pathName}" list`);
  return value;
}

const declarations = (entries) => entries.map(([name, value]) => `  --${name}: ${value};`).join("\n");
const block = (selector, comment, entries) => `${selector} {\n  /* ${comment} */\n${declarations(entries)}\n}`;

// {tpch-blue} in tokens.json is a reference to another colour token.
function colourValue(value, colours) {
  const reference = /^\{([\w-]+)\}$/.exec(value);
  if (!reference) return value;
  if (!colours.has(reference[1])) throw missing(reference[1], "a colour reference in tokens.json");
  return `var(--${reference[1]})`;
}

function typeSets(tokens) {
  const groups = list(tokens, "type.groups");
  const lineHeights = new Set(list(tokens, "type.lineHeights").map((token) => token.name));
  const sets = TYPE_GROUPS.map(({ name, prefix }) => {
    const group = groups.find((candidate) => candidate.name === name);
    if (!group) throw new TokenError(`tokens.json has no type group "${name}" (decision G7); gen:tokens writes no default value`);
    return group.styles.map((style) => {
      const role = style.name.replace(new RegExp(`^screen-${prefix}`), "");
      if (role === style.name) throw new TokenError(`Type style "${style.name}" in "${name}" is not named screen-${prefix}{role}`);
      if (!lineHeights.has(style.lineHeight)) throw missing(style.lineHeight, `type style "${style.name}"`);
      return { role, fontSize: style.fontSize, lineHeight: style.lineHeight };
    });
  });
  const roles = sets[0].map((style) => style.role).join(",");
  sets.forEach((set, index) => {
    if (set.map((style) => style.role).join(",") !== roles) {
      throw new TokenError(`"${TYPE_GROUPS[index].name}" does not have the same roles as "${TYPE_GROUPS[0].name}" (${roles})`);
    }
  });
  return sets.map((set) =>
    set.flatMap(({ role, fontSize, lineHeight }) => [
      [`app-fs-${role}`, fontSize],
      [`app-lh-${role}`, `var(--${lineHeight})`],
    ]),
  );
}

// Line heights by script: a token with `languages` overrides the token whose name it extends
// (lh-body-arabic -> lh-body) for those languages (G10).
function lineHeightBlocks(tokens) {
  const all = list(tokens, "type.lineHeights");
  const base = all.filter((token) => !token.languages);
  const byLanguages = new Map();
  for (const token of all.filter((candidate) => candidate.languages)) {
    const target = base
      .filter((candidate) => token.name.startsWith(`${candidate.name}-`))
      .sort((a, b) => b.name.length - a.name.length)[0];
    if (!target) throw new TokenError(`Line height "${token.name}" extends no line height without languages`);
    const key = token.languages.join(",");
    if (!byLanguages.has(key)) byLanguages.set(key, { languages: token.languages, entries: [] });
    byLanguages.get(key).entries.push([target.name, String(token.value), token.name]);
  }
  return {
    root: base.map((token) => [token.name, String(token.value)]),
    languages: [...byLanguages.values()].map(({ languages, entries }) =>
      block(
        languages.map((language) => `:lang(${language})`).join(", "),
        `type.lineHeights: ${entries.map(([, , name]) => name).join(", ")}`,
        entries.map(([name, value]) => [name, value]),
      ),
    ),
  };
}

function themes(tokens) {
  const ids = list(tokens, "color.themes").map((theme) => theme.id);
  const launch = tokens.color?.launch?.theme;
  if (!ids.includes(launch)) throw new TokenError(`tokens.json's color.launch.theme "${launch}" is not one of its themes (decision G9)`);
  return { launch, others: ids.filter((id) => id !== launch) };
}

/**
 * Layer 1 (tokens.generated.css): spacing, size and radius once on :root; colour per theme;
 * the screen type sets switched by basic mode and the staff surface; line heights per language.
 */
export function buildPrimitives(tokens) {
  if (tokens.version !== TOKENS_VERSION) {
    throw new TokenError(`tokens.json is version ${tokens.version}; gen:tokens reads version ${TOKENS_VERSION}`);
  }
  const spacing = list(tokens, "spacing.app").map((token) => [token.name, token.value]);
  const sizes = list(tokens, "size.tokens").map((token) => [token.name, token.value]);
  const radius = list(tokens, "radius.tokens").map((token) => [token.name, token.value]);
  const defined = new Set([...spacing, ...sizes].map(([name]) => name));
  for (const name of REQUIRED) if (!defined.has(name)) throw missing(name, "the tap rule (touch-target.md)");

  const colours = list(tokens, "color.tokens");
  const colourNames = new Set(colours.map((token) => token.name));
  const { launch, others } = themes(tokens);
  const themed = (token, theme) => {
    if (typeof token.value === "string") return token.value;
    if (!(theme in token.value)) throw new TokenError(`tokens.json gives "${token.name}" no ${theme} value (decision G9); gen:tokens writes no default value`);
    return token.value[theme];
  };
  const [resident, basic, staff] = typeSets(tokens);
  const lineHeights = lineHeightBlocks(tokens);

  const root = [
    "  /* spacing.app (G1) */",
    declarations(spacing),
    "  /* size (G3, G5, G7, G8) */",
    declarations(sizes),
    "  /* radius */",
    declarations(radius),
    `  /* color, ${launch} theme */`,
    declarations(colours.map((token) => [token.name, colourValue(themed(token, launch), colourNames)])),
    "  /* type: Screens: resident (G7) */",
    declarations(resident),
    "  /* type.lineHeights (G10) */",
    declarations(lineHeights.root),
  ].join("\n");

  return [
    HEADER,
    `:root {\n${root}\n}`,
    ...others.map((theme) =>
      block(
        `[data-theme="${theme}"]`,
        `color, ${theme} theme: only the tokens whose value changes`,
        colours
          .filter((token) => typeof token.value !== "string")
          .map((token) => [token.name, colourValue(themed(token, theme), colourNames)]),
      ),
    ),
    block(BASIC_SELECTOR, "type: Screens: basic mode (G7)", basic),
    block(STAFF_SELECTOR, "type: Screens: staff (G7)", staff),
    ...lineHeights.languages,
  ].join("\n\n") + "\n";
}

/** Custom properties declared in a stylesheet, with the var() names each one references. */
export function customProperties(css, from) {
  const found = [];
  postcss.parse(css, { from }).walkDecls(/^--/, (decl) => {
    found.push({ name: decl.prop.slice(2), value: decl.value, line: decl.source?.start?.line });
  });
  return found;
}

const varReferences = (css) => [...css.matchAll(/var\(\s*--([\w-]+)/g)].map((match) => match[1]);

/**
 * Fails, naming the token, when semantic.css or a layout primitive references an --app-* primitive
 * that the generated layer does not define.
 */
export function checkReferences(primitivesCss, sources) {
  const defined = new Set(customProperties(primitivesCss).map((property) => property.name));
  for (const { file, css } of sources) {
    for (const name of varReferences(css)) {
      if (name.startsWith("app-") && !defined.has(name)) throw missing(name, file);
    }
  }
}

/** Tailwind @theme (theme.generated.css): resets, the two build-time literals and the token mappings. */
export function buildTheme(tokens, semanticCss) {
  const buildTime = BUILD_TIME.map(({ group, token, theme, note }) => {
    const entry = list(tokens, `${group}.tokens`).find((candidate) => candidate.name === token);
    if (!entry) throw missing(token, `Tailwind's ${theme}`);
    return `  /* ${token}: ${note} */\n  ${theme}: ${entry.value};`;
  });

  const spacing = new Map();
  for (const { name } of customProperties(semanticCss, SEMANTIC_FILE)) {
    const utility = SPACING_ALIASES[name] ?? (SPACING_ROLES.some((role) => role.test(name)) ? name.replace(/^[a-z]+-/, "") : null);
    if (!utility) continue;
    if (spacing.has(utility)) throw new TokenError(`--${spacing.get(utility)} and --${name} would both be the spacing utility "${utility}"`);
    spacing.set(utility, name);
  }

  const lines = [
    "  /* Tailwind's default spacing scale, breakpoints, container sizes and radii are removed. */",
    "  --spacing-*: initial;",
    "  --breakpoint-*: initial;",
    "  --container-*: initial;",
    "  --radius-*: initial;",
    "",
    ...buildTime,
    "",
    "  /* Spacing utilities (gap-icon, p-card, ps-gutter): semantic tokens only, never primitives. */",
    ...[...spacing].map(([utility, name]) => `  --spacing-${utility}: var(--${name});`),
    "",
    "  /* Radius (rounded-card). `reference` keeps Tailwind from emitting these as variables, so",
    "     --radius-card: var(--radius-card) is never declared and cannot be circular. */",
    ...list(tokens, "radius.tokens").map(({ name }) => `  --radius-${name.replace(/^radius-/, "")}: var(--${name});`),
    "",
    "  /* Colour (bg-surface, text-ink): follows [data-theme] through the generated variables. */",
    ...list(tokens, "color.tokens").map(({ name }) => `  --color-${name}: var(--${name});`),
  ];

  return `${HEADER}\n@theme inline reference {\n${lines.join("\n")}\n}\n`;
}

/** Every generated file, keyed by its path from the repository root. */
export function generate({ tokens, semanticCss, layoutSources }) {
  const primitives = buildPrimitives(tokens);
  checkReferences(primitives, [{ file: SEMANTIC_FILE, css: semanticCss }, ...layoutSources]);
  return {
    [PRIMITIVES_FILE]: primitives,
    [THEME_FILE]: buildTheme(tokens, semanticCss),
  };
}

export function readInputs(root) {
  const read = (file) => readFileSync(path.join(root, file), "utf8");
  const layoutDir = path.join(root, LAYOUT_DIR);
  const layoutSources = existsSync(layoutDir)
    ? readdirSync(layoutDir)
        .filter((name) => name.endsWith(".css"))
        .sort()
        .map((name) => ({ file: `${LAYOUT_DIR}/${name}`, css: read(`${LAYOUT_DIR}/${name}`) }))
    : [];
  return { tokens: JSON.parse(read(TOKENS_FILE)), semanticCss: read(SEMANTIC_FILE), layoutSources };
}

/** @returns {number} the process exit code */
export function main(argv, root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..")) {
  const check = argv.includes("--check");
  let files;
  try {
    files = generate(readInputs(root));
  } catch (error) {
    if (!(error instanceof TokenError)) throw error;
    console.error(`gen:tokens failed: ${error.message}`);
    return 1;
  }
  const stale = [];
  for (const [file, content] of Object.entries(files)) {
    const target = path.join(root, file);
    const current = existsSync(target) ? readFileSync(target, "utf8") : null;
    if (current === content) continue;
    if (check) stale.push(file);
    else writeFileSync(target, content);
  }
  if (stale.length > 0) {
    console.error(`Generated tokens are stale: ${stale.join(", ")}. Run \`npm run gen:tokens\` and commit the result.`);
    return 1;
  }
  console.log(check ? "Generated tokens match tokens.json." : `Wrote ${Object.keys(files).join(", ")}.`);
  return 0;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const rootFlag = process.argv.indexOf("--root");
  process.exitCode = main(process.argv.slice(2), rootFlag > 0 ? path.resolve(process.argv[rootFlag + 1]) : undefined);
}
